# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmPreprocessingGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmPreprocess(object):
    def setupUi(self, frmPreprocess):
        frmPreprocess.setObjectName("frmPreprocess")
        frmPreprocess.resize(551, 529)
        frmPreprocess.setAcceptDrops(False)
        frmPreprocess.setModal(False)
        self.tabWidget = QtWidgets.QTabWidget(frmPreprocess)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 521, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 8, 481, 80))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 39, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(169, 35, 60, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(329, 39, 60, 16))
        self.label_4.setObjectName("label_4")
        self.txtSubNum = QtWidgets.QLineEdit(self.groupBox)
        self.txtSubNum.setGeometry(QtCore.QRect(73, 37, 91, 21))
        self.txtSubNum.setObjectName("txtSubNum")
        self.txtSubPer = QtWidgets.QLineEdit(self.groupBox)
        self.txtSubPer.setGeometry(QtCore.QRect(379, 37, 91, 21))
        self.txtSubPer.setObjectName("txtSubPer")
        self.txtSubLen = QtWidgets.QLineEdit(self.groupBox)
        self.txtSubLen.setGeometry(QtCore.QRect(229, 37, 91, 21))
        self.txtSubLen.setInputMask("")
        self.txtSubLen.setObjectName("txtSubLen")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 198, 481, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.txtBOLD = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtBOLD.setGeometry(QtCore.QRect(134, 114, 91, 21))
        self.txtBOLD.setObjectName("txtBOLD")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(240, 115, 121, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(6, 115, 121, 16))
        self.label_12.setObjectName("label_12")
        self.txtOnset = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtOnset.setGeometry(QtCore.QRect(374, 114, 91, 21))
        self.txtOnset.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtOnset.setObjectName("txtOnset")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(11, 77, 81, 16))
        self.label_5.setObjectName("label_5")
        self.txtTask = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtTask.setGeometry(QtCore.QRect(101, 74, 361, 21))
        self.txtTask.setObjectName("txtTask")
        self.btnDIR = QtWidgets.QPushButton(self.groupBox_4)
        self.btnDIR.setGeometry(QtCore.QRect(410, 30, 51, 32))
        self.btnDIR.setObjectName("btnDIR")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 38, 111, 16))
        self.label.setToolTip("")
        self.label.setStatusTip("")
        self.label.setProperty("toolTipDuration", -1)
        self.label.setObjectName("label")
        self.txtDIR = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtDIR.setGeometry(QtCore.QRect(129, 35, 271, 21))
        self.txtDIR.setToolTip("")
        self.txtDIR.setStatusTip("")
        self.txtDIR.setProperty("toolTipDuration", -1)
        self.txtDIR.setObjectName("txtDIR")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 98, 481, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 38, 60, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(170, 35, 60, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(329, 38, 60, 16))
        self.label_10.setObjectName("label_10")
        self.txtRunNum = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtRunNum.setGeometry(QtCore.QRect(74, 37, 91, 21))
        self.txtRunNum.setObjectName("txtRunNum")
        self.txtRunPer = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtRunPer.setGeometry(QtCore.QRect(379, 37, 91, 21))
        self.txtRunPer.setObjectName("txtRunPer")
        self.txtRunLen = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtRunLen.setGeometry(QtCore.QRect(229, 37, 91, 21))
        self.txtRunLen.setObjectName("txtRunLen")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 23, 71, 16))
        self.label_13.setObjectName("label_13")
        self.txtTR = QtWidgets.QLineEdit(self.tab_2)
        self.txtTR.setGeometry(QtCore.QRect(90, 20, 91, 21))
        self.txtTR.setText("")
        self.txtTR.setObjectName("txtTR")
        self.txtFWHM = QtWidgets.QLineEdit(self.tab_2)
        self.txtFWHM.setGeometry(QtCore.QRect(240, 58, 91, 21))
        self.txtFWHM.setText("")
        self.txtFWHM.setObjectName("txtFWHM")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(10, 60, 231, 16))
        self.label_16.setObjectName("label_16")
        self.txtTotalVol = QtWidgets.QLineEdit(self.tab_2)
        self.txtTotalVol.setGeometry(QtCore.QRect(360, 20, 91, 21))
        self.txtTotalVol.setObjectName("txtTotalVol")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(240, 22, 110, 16))
        self.label_15.setObjectName("label_15")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(10, 93, 231, 16))
        self.label_20.setObjectName("label_20")
        self.txtHighPass = QtWidgets.QLineEdit(self.tab_2)
        self.txtHighPass.setGeometry(QtCore.QRect(240, 90, 91, 21))
        self.txtHighPass.setObjectName("txtHighPass")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(10, 130, 231, 16))
        self.label_21.setObjectName("label_21")
        self.cbSliceTime = QtWidgets.QComboBox(self.tab_2)
        self.cbSliceTime.setGeometry(QtCore.QRect(180, 126, 251, 26))
        self.cbSliceTime.setObjectName("cbSliceTime")
        self.txtVoxel = QtWidgets.QLabel(self.tab_2)
        self.txtVoxel.setGeometry(QtCore.QRect(10, 330, 491, 16))
        self.txtVoxel.setObjectName("txtVoxel")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(10, 22, 110, 16))
        self.label_14.setObjectName("label_14")
        self.txtDeleteVol = QtWidgets.QLineEdit(self.tab_3)
        self.txtDeleteVol.setGeometry(QtCore.QRect(140, 20, 91, 21))
        self.txtDeleteVol.setObjectName("txtDeleteVol")
        self.cbMotionCorrection = QtWidgets.QCheckBox(self.tab_3)
        self.cbMotionCorrection.setGeometry(QtCore.QRect(10, 60, 160, 20))
        self.cbMotionCorrection.setChecked(True)
        self.cbMotionCorrection.setObjectName("cbMotionCorrection")
        self.cbRegAnat = QtWidgets.QCheckBox(self.tab_3)
        self.cbRegAnat.setEnabled(True)
        self.cbRegAnat.setGeometry(QtCore.QRect(10, 90, 271, 20))
        self.cbRegAnat.setChecked(False)
        self.cbRegAnat.setObjectName("cbRegAnat")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 130, 481, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 111, 17))
        self.label_7.setObjectName("label_7")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(21, 72, 131, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(22, 115, 141, 17))
        self.label_18.setObjectName("label_18")
        self.txtOnsetRID = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtOnsetRID.setGeometry(QtCore.QRect(156, 26, 113, 29))
        self.txtOnsetRID.setObjectName("txtOnsetRID")
        self.txtConditionRID = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtConditionRID.setGeometry(QtCore.QRect(157, 110, 113, 29))
        self.txtConditionRID.setObjectName("txtConditionRID")
        self.txtDurationRID = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtDurationRID.setGeometry(QtCore.QRect(157, 68, 113, 29))
        self.txtDurationRID.setObjectName("txtDurationRID")
        self.txtRowStart = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtRowStart.setGeometry(QtCore.QRect(156, 151, 113, 29))
        self.txtRowStart.setObjectName("txtRowStart")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(21, 156, 141, 17))
        self.label_19.setObjectName("label_19")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.btnEvent = QtWidgets.QPushButton(self.tab_4)
        self.btnEvent.setEnabled(True)
        self.btnEvent.setGeometry(QtCore.QRect(80, 30, 320, 40))
        self.btnEvent.setObjectName("btnEvent")
        self.btnExtractor = QtWidgets.QPushButton(self.tab_4)
        self.btnExtractor.setEnabled(False)
        self.btnExtractor.setGeometry(QtCore.QRect(80, 80, 320, 40))
        self.btnExtractor.setObjectName("btnExtractor")
        self.btnPreprocessScripts = QtWidgets.QPushButton(self.tab_4)
        self.btnPreprocessScripts.setEnabled(True)
        self.btnPreprocessScripts.setGeometry(QtCore.QRect(80, 130, 320, 40))
        self.btnPreprocessScripts.setObjectName("btnPreprocessScripts")
        self.cbShowResult = QtWidgets.QCheckBox(self.tab_4)
        self.cbShowResult.setEnabled(False)
        self.cbShowResult.setGeometry(QtCore.QRect(406, 90, 131, 22))
        self.cbShowResult.setChecked(True)
        self.cbShowResult.setObjectName("cbShowResult")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 180, 491, 171))
        self.groupBox_5.setObjectName("groupBox_5")
        self.cbJustRun = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbJustRun.setGeometry(QtCore.QRect(20, 30, 171, 20))
        self.cbJustRun.setObjectName("cbJustRun")
        self.cbRemoveOlds = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbRemoveOlds.setGeometry(QtCore.QRect(20, 60, 161, 20))
        self.cbRemoveOlds.setChecked(True)
        self.cbRemoveOlds.setObjectName("cbRemoveOlds")
        self.btnPreprocess = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPreprocess.setEnabled(True)
        self.btnPreprocess.setGeometry(QtCore.QRect(72, 110, 321, 40))
        self.btnPreprocess.setObjectName("btnPreprocess")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.btnLoadHistory = QtWidgets.QPushButton(self.tab_5)
        self.btnLoadHistory.setGeometry(QtCore.QRect(10, 320, 131, 29))
        self.btnLoadHistory.setObjectName("btnLoadHistory")
        self.lwHistory = QtWidgets.QListWidget(self.tab_5)
        self.lwHistory.setGeometry(QtCore.QRect(10, 10, 501, 301))
        self.lwHistory.setObjectName("lwHistory")
        self.btnRemoveHistory = QtWidgets.QPushButton(self.tab_5)
        self.btnRemoveHistory.setGeometry(QtCore.QRect(160, 320, 131, 29))
        self.btnRemoveHistory.setObjectName("btnRemoveHistory")
        self.btnClearAllHistory = QtWidgets.QPushButton(self.tab_5)
        self.btnClearAllHistory.setGeometry(QtCore.QRect(410, 320, 101, 29))
        self.btnClearAllHistory.setObjectName("btnClearAllHistory")
        self.tabWidget.addTab(self.tab_5, "")
        self.btnTest = QtWidgets.QPushButton(frmPreprocess)
        self.btnTest.setGeometry(QtCore.QRect(270, 470, 113, 32))
        self.btnTest.setObjectName("btnTest")
        self.btnClose = QtWidgets.QPushButton(frmPreprocess)
        self.btnClose.setGeometry(QtCore.QRect(420, 470, 113, 32))
        self.btnClose.setObjectName("btnClose")
        self.btnSave = QtWidgets.QPushButton(frmPreprocess)
        self.btnSave.setGeometry(QtCore.QRect(140, 470, 113, 32))
        self.btnSave.setObjectName("btnSave")
        self.btnLoad = QtWidgets.QPushButton(frmPreprocess)
        self.btnLoad.setGeometry(QtCore.QRect(10, 470, 113, 32))
        self.btnLoad.setObjectName("btnLoad")
        self.label_6 = QtWidgets.QLabel(frmPreprocess)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 68, 21))
        self.label_6.setObjectName("label_6")
        self.txtSetting = QtWidgets.QLineEdit(frmPreprocess)
        self.txtSetting.setGeometry(QtCore.QRect(80, 7, 461, 29))
        self.txtSetting.setReadOnly(True)
        self.txtSetting.setObjectName("txtSetting")

        self.retranslateUi(frmPreprocess)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmPreprocess)
        frmPreprocess.setTabOrder(self.tabWidget, self.txtSubNum)
        frmPreprocess.setTabOrder(self.txtSubNum, self.txtSubLen)
        frmPreprocess.setTabOrder(self.txtSubLen, self.txtSubPer)
        frmPreprocess.setTabOrder(self.txtSubPer, self.txtRunNum)
        frmPreprocess.setTabOrder(self.txtRunNum, self.txtRunLen)
        frmPreprocess.setTabOrder(self.txtRunLen, self.txtRunPer)
        frmPreprocess.setTabOrder(self.txtRunPer, self.txtDIR)
        frmPreprocess.setTabOrder(self.txtDIR, self.btnDIR)
        frmPreprocess.setTabOrder(self.btnDIR, self.txtTask)
        frmPreprocess.setTabOrder(self.txtTask, self.txtBOLD)
        frmPreprocess.setTabOrder(self.txtBOLD, self.txtOnset)
        frmPreprocess.setTabOrder(self.txtOnset, self.btnLoad)
        frmPreprocess.setTabOrder(self.btnLoad, self.btnSave)
        frmPreprocess.setTabOrder(self.btnSave, self.btnTest)
        frmPreprocess.setTabOrder(self.btnTest, self.btnClose)
        frmPreprocess.setTabOrder(self.btnClose, self.txtTR)
        frmPreprocess.setTabOrder(self.txtTR, self.txtTotalVol)
        frmPreprocess.setTabOrder(self.txtTotalVol, self.txtFWHM)
        frmPreprocess.setTabOrder(self.txtFWHM, self.txtHighPass)
        frmPreprocess.setTabOrder(self.txtHighPass, self.cbSliceTime)
        frmPreprocess.setTabOrder(self.cbSliceTime, self.txtDeleteVol)
        frmPreprocess.setTabOrder(self.txtDeleteVol, self.cbMotionCorrection)
        frmPreprocess.setTabOrder(self.cbMotionCorrection, self.cbRegAnat)
        frmPreprocess.setTabOrder(self.cbRegAnat, self.txtSetting)
        frmPreprocess.setTabOrder(self.txtSetting, self.txtOnsetRID)
        frmPreprocess.setTabOrder(self.txtOnsetRID, self.txtDurationRID)
        frmPreprocess.setTabOrder(self.txtDurationRID, self.txtConditionRID)
        frmPreprocess.setTabOrder(self.txtConditionRID, self.txtRowStart)
        frmPreprocess.setTabOrder(self.txtRowStart, self.btnEvent)
        frmPreprocess.setTabOrder(self.btnEvent, self.btnExtractor)
        frmPreprocess.setTabOrder(self.btnExtractor, self.btnPreprocessScripts)
        frmPreprocess.setTabOrder(self.btnPreprocessScripts, self.btnPreprocess)
        frmPreprocess.setTabOrder(self.btnPreprocess, self.cbShowResult)
        frmPreprocess.setTabOrder(self.cbShowResult, self.btnLoadHistory)
        frmPreprocess.setTabOrder(self.btnLoadHistory, self.lwHistory)
        frmPreprocess.setTabOrder(self.lwHistory, self.btnRemoveHistory)
        frmPreprocess.setTabOrder(self.btnRemoveHistory, self.btnClearAllHistory)

    def retranslateUi(self, frmPreprocess):
        _translate = QtCore.QCoreApplication.translate
        frmPreprocess.setWindowTitle(_translate("frmPreprocess", "easy fMRI: Preprosessing (0.0.1)"))
        self.groupBox.setTitle(_translate("frmPreprocess", "<Subjects>"))
        self.label_2.setText(_translate("frmPreprocess", "Number:"))
        self.label_3.setText(_translate("frmPreprocess", "Length:"))
        self.label_4.setText(_translate("frmPreprocess", "Perfix:"))
        self.txtSubNum.setText(_translate("frmPreprocess", "1"))
        self.txtSubPer.setText(_translate("frmPreprocess", "0"))
        self.txtSubLen.setText(_translate("frmPreprocess", "2"))
        self.groupBox_4.setTitle(_translate("frmPreprocess", "<General>"))
        self.txtBOLD.setText(_translate("frmPreprocess", "nii.gz"))
        self.label_11.setText(_translate("frmPreprocess", "Event Extension:"))
        self.label_12.setText(_translate("frmPreprocess", "BOLD Extension:"))
        self.txtOnset.setText(_translate("frmPreprocess", "tsv"))
        self.label_5.setText(_translate("frmPreprocess", "Task Perfix:"))
        self.btnDIR.setText(_translate("frmPreprocess", "..."))
        self.label.setText(_translate("frmPreprocess", "Main Directory:"))
        self.label.setProperty("setToolTip", _translate("frmPreprocess", "Please enter the main directory of the fMRI dataset. Format of directory must be based on BIDS structure."))
        self.groupBox_3.setTitle(_translate("frmPreprocess", "<Runs>"))
        self.label_8.setText(_translate("frmPreprocess", "Number:"))
        self.label_9.setText(_translate("frmPreprocess", "Length:"))
        self.label_10.setText(_translate("frmPreprocess", "Perfix:"))
        self.txtRunNum.setText(_translate("frmPreprocess", "1"))
        self.txtRunPer.setText(_translate("frmPreprocess", "0"))
        self.txtRunLen.setText(_translate("frmPreprocess", "2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmPreprocess", "Directory"))
        self.label_13.setText(_translate("frmPreprocess", "TR (sec):"))
        self.label_16.setText(_translate("frmPreprocess", "Spatial Smoothing FWHM (mm):"))
        self.txtTotalVol.setText(_translate("frmPreprocess", "0"))
        self.label_15.setText(_translate("frmPreprocess", "Total Volumes: "))
        self.label_20.setText(_translate("frmPreprocess", "High pass filter cutoff (sec):"))
        self.txtHighPass.setText(_translate("frmPreprocess", "100"))
        self.label_21.setText(_translate("frmPreprocess", "Slice timing correction:"))
        self.txtVoxel.setText(_translate("frmPreprocess", "Voxel Size: None"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmPreprocess", "fMRI Images"))
        self.label_14.setText(_translate("frmPreprocess", "Delete Volumes: "))
        self.txtDeleteVol.setText(_translate("frmPreprocess", "0"))
        self.cbMotionCorrection.setText(_translate("frmPreprocess", "Motion Correction"))
        self.cbRegAnat.setText(_translate("frmPreprocess", "Register to Anatomical Image"))
        self.groupBox_2.setTitle(_translate("frmPreprocess", "<Event Setting>"))
        self.label_7.setText(_translate("frmPreprocess", "Onset Row ID:"))
        self.label_17.setText(_translate("frmPreprocess", "Duration Row ID:"))
        self.label_18.setText(_translate("frmPreprocess", "Condition Row ID:"))
        self.txtOnsetRID.setText(_translate("frmPreprocess", "1"))
        self.txtConditionRID.setText(_translate("frmPreprocess", "3"))
        self.txtDurationRID.setText(_translate("frmPreprocess", "2"))
        self.txtRowStart.setText(_translate("frmPreprocess", "2"))
        self.label_19.setText(_translate("frmPreprocess", "Start from Row:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmPreprocess", "Advance"))
        self.btnEvent.setText(_translate("frmPreprocess", "Generate Event Files"))
        self.btnExtractor.setText(_translate("frmPreprocess", "Brain Extractor"))
        self.btnPreprocessScripts.setText(_translate("frmPreprocess", "Generate Preprocessing Scripts"))
        self.cbShowResult.setText(_translate("frmPreprocess", "Show Result"))
        self.groupBox_5.setTitle(_translate("frmPreprocess", "<Preprocessing>"))
        self.cbJustRun.setText(_translate("frmPreprocess", "Just Run One for test"))
        self.cbRemoveOlds.setText(_translate("frmPreprocess", "Remove Old Results"))
        self.btnPreprocess.setText(_translate("frmPreprocess", "Preprocessing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmPreprocess", "Run"))
        self.btnLoadHistory.setText(_translate("frmPreprocess", "Load Selected"))
        self.btnRemoveHistory.setText(_translate("frmPreprocess", "Remove Selected"))
        self.btnClearAllHistory.setText(_translate("frmPreprocess", "Clear All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmPreprocess", "History"))
        self.btnTest.setText(_translate("frmPreprocess", "Test"))
        self.btnClose.setText(_translate("frmPreprocess", "Close"))
        self.btnSave.setText(_translate("frmPreprocess", "Save"))
        self.btnLoad.setText(_translate("frmPreprocess", "Load"))
        self.label_6.setText(_translate("frmPreprocess", "Setting:"))

