# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmAAVoxelGUI.ui'
#
# Created by: PyQt6 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_frmAAVoxel(object):
    def setupUi(self, frmAAVoxel):
        frmAAVoxel.setObjectName("frmAAVoxel")
        frmAAVoxel.resize(757, 425)
        self.btnInFile = QtWidgets.QPushButton(frmAAVoxel)
        self.btnInFile.setGeometry(QtCore.QRect(690, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmAAVoxel)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 131, 16))
        self.label_33.setObjectName("label_33")
        self.btnOutFile = QtWidgets.QPushButton(frmAAVoxel)
        self.btnOutFile.setGeometry(QtCore.QRect(690, 70, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.txtInFile = QtWidgets.QLineEdit(frmAAVoxel)
        self.txtInFile.setGeometry(QtCore.QRect(160, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmAAVoxel)
        self.btnConvert.setGeometry(QtCore.QRect(640, 380, 91, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label_35 = QtWidgets.QLabel(frmAAVoxel)
        self.label_35.setGeometry(QtCore.QRect(30, 70, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmAAVoxel)
        self.txtOutFile.setGeometry(QtCore.QRect(160, 70, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnClose = QtWidgets.QPushButton(frmAAVoxel)
        self.btnClose.setGeometry(QtCore.QRect(30, 380, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmAAVoxel)
        self.tabWidget.setGeometry(QtCore.QRect(30, 110, 701, 251))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(140, 90, 60, 16))
        self.label_3.setObjectName("label_3")
        self.txtCol = QtWidgets.QComboBox(self.tab)
        self.txtCol.setGeometry(QtCore.QRect(260, 130, 121, 26))
        self.txtCol.setEditable(True)
        self.txtCol.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCol.setObjectName("txtCol")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(300, 20, 61, 16))
        self.label.setObjectName("label")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(260, 90, 121, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(260, 50, 121, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(140, 130, 101, 16))
        self.label_6.setObjectName("label_6")
        self.txtTeLabel = QtWidgets.QComboBox(self.tab)
        self.txtTeLabel.setGeometry(QtCore.QRect(420, 90, 121, 26))
        self.txtTeLabel.setEditable(True)
        self.txtTeLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTeLabel.setObjectName("txtTeLabel")
        self.txtTeData = QtWidgets.QComboBox(self.tab)
        self.txtTeData.setGeometry(QtCore.QRect(420, 50, 121, 26))
        self.txtTeData.setEditable(True)
        self.txtTeData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTeData.setObjectName("txtTeData")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(460, 20, 61, 16))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.cbScale = QtWidgets.QCheckBox(self.tab_4)
        self.cbScale.setGeometry(QtCore.QRect(30, 30, 191, 20))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(30, 80, 171, 16))
        self.label_5.setObjectName("label_5")
        self.txtJob = QtWidgets.QSpinBox(self.tab_4)
        self.txtJob.setGeometry(QtCore.QRect(190, 80, 161, 24))
        self.txtJob.setMaximum(999999999)
        self.txtJob.setObjectName("txtJob")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(30, 30, 60, 16))
        self.label_17.setObjectName("label_17")
        self.txtFoldTo = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldTo.setGeometry(QtCore.QRect(260, 30, 80, 24))
        self.txtFoldTo.setMaximum(100000)
        self.txtFoldTo.setProperty("value", 1)
        self.txtFoldTo.setObjectName("txtFoldTo")
        self.txtFoldFrom = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldFrom.setGeometry(QtCore.QRect(90, 30, 80, 24))
        self.txtFoldFrom.setMaximum(100000)
        self.txtFoldFrom.setProperty("value", 1)
        self.txtFoldFrom.setObjectName("txtFoldFrom")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(200, 30, 60, 16))
        self.label_44.setObjectName("label_44")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_12 = QtWidgets.QLabel(frmAAVoxel)
        self.label_12.setGeometry(QtCore.QRect(190, 380, 391, 20))
        self.label_12.setObjectName("label_12")
        self.btnSelection = QtWidgets.QPushButton(frmAAVoxel)
        self.btnSelection.setGeometry(QtCore.QRect(480, 380, 151, 32))
        self.btnSelection.setObjectName("btnSelection")

        self.retranslateUi(frmAAVoxel)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmAAVoxel)
        frmAAVoxel.setTabOrder(self.txtInFile, self.btnInFile)
        frmAAVoxel.setTabOrder(self.btnInFile, self.txtOutFile)
        frmAAVoxel.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmAAVoxel.setTabOrder(self.btnOutFile, self.tabWidget)
        frmAAVoxel.setTabOrder(self.tabWidget, self.txtData)
        frmAAVoxel.setTabOrder(self.txtData, self.txtLabel)
        frmAAVoxel.setTabOrder(self.txtLabel, self.txtCol)
        frmAAVoxel.setTabOrder(self.txtCol, self.btnConvert)
        frmAAVoxel.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmAAVoxel):
        _translate = QtCore.QCoreApplication.translate
        frmAAVoxel.setWindowTitle(_translate("frmAAVoxel", "Incremental Principal Component Analysis (PCA)"))
        self.btnInFile.setText(_translate("frmAAVoxel", "..."))
        self.label_33.setText(_translate("frmAAVoxel", "Input Data"))
        self.btnOutFile.setText(_translate("frmAAVoxel", "..."))
        self.btnConvert.setText(_translate("frmAAVoxel", "Report"))
        self.label_35.setText(_translate("frmAAVoxel", "Output"))
        self.btnClose.setText(_translate("frmAAVoxel", "Close"))
        self.label_2.setText(_translate("frmAAVoxel", "Data"))
        self.label_3.setText(_translate("frmAAVoxel", "Label"))
        self.label.setText(_translate("frmAAVoxel", "Train"))
        self.label_6.setText(_translate("frmAAVoxel", "Coordinate"))
        self.label_4.setText(_translate("frmAAVoxel", "Test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmAAVoxel", "Data"))
        self.cbScale.setText(_translate("frmAAVoxel", "Scale Data X~N(0,1)"))
        self.label_5.setText(_translate("frmAAVoxel", "Number of Job (Auto=0)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmAAVoxel", "Parameters"))
        self.label_17.setText(_translate("frmAAVoxel", "From:"))
        self.label_44.setText(_translate("frmAAVoxel", "To:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmAAVoxel", "Fold"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmAAVoxel", "Model"))
        self.label_12.setText(_translate("frmAAVoxel", "$FOLD$ will be replaced by fold number."))
        self.btnSelection.setText(_translate("frmAAVoxel", "Voxel Selection"))

