# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmAtlasROIGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmAtlasROI(object):
    def setupUi(self, frmAtlasROI):
        frmAtlasROI.setObjectName("frmAtlasROI")
        frmAtlasROI.resize(715, 655)
        self.tvArea = QtWidgets.QTreeWidget(frmAtlasROI)
        self.tvArea.setGeometry(QtCore.QRect(12, 218, 691, 381))
        self.tvArea.setMinimumSize(QtCore.QSize(691, 300))
        self.tvArea.setObjectName("tvArea")
        self.tvArea.headerItem().setText(0, "1")
        self.btnRun = QtWidgets.QPushButton(frmAtlasROI)
        self.btnRun.setGeometry(QtCore.QRect(580, 610, 121, 32))
        self.btnRun.setObjectName("btnRun")
        self.btnClose = QtWidgets.QPushButton(frmAtlasROI)
        self.btnClose.setGeometry(QtCore.QRect(14, 610, 121, 32))
        self.btnClose.setObjectName("btnClose")
        self.groupBox = QtWidgets.QGroupBox(frmAtlasROI)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 691, 121))
        self.groupBox.setObjectName("groupBox")
        self.btnFile = QtWidgets.QPushButton(self.groupBox)
        self.btnFile.setGeometry(QtCore.QRect(620, 35, 54, 32))
        self.btnFile.setObjectName("btnFile")
        self.txtRangeFrom = QtWidgets.QSpinBox(self.groupBox)
        self.txtRangeFrom.setGeometry(QtCore.QRect(102, 82, 100, 24))
        self.txtRangeFrom.setMinimumSize(QtCore.QSize(100, 0))
        self.txtRangeFrom.setObjectName("txtRangeFrom")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(13, 39, 59, 16))
        self.label.setObjectName("label")
        self.txtRangeTo = QtWidgets.QSpinBox(self.groupBox)
        self.txtRangeTo.setGeometry(QtCore.QRect(250, 82, 100, 24))
        self.txtRangeTo.setMinimumSize(QtCore.QSize(100, 24))
        self.txtRangeTo.setObjectName("txtRangeTo")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(12, 82, 78, 16))
        self.label_2.setObjectName("label_2")
        self.txtFile = QtWidgets.QLineEdit(self.groupBox)
        self.txtFile.setGeometry(QtCore.QRect(80, 39, 531, 21))
        self.txtFile.setObjectName("txtFile")
        self.btnAdd = QtWidgets.QPushButton(self.groupBox)
        self.btnAdd.setGeometry(QtCore.QRect(610, 82, 71, 32))
        self.btnAdd.setObjectName("btnAdd")
        self.btnRemove = QtWidgets.QPushButton(self.groupBox)
        self.btnRemove.setGeometry(QtCore.QRect(505, 82, 91, 32))
        self.btnRemove.setObjectName("btnRemove")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(220, 82, 16, 16))
        self.label_3.setObjectName("label_3")
        self.btnAffine = QtWidgets.QPushButton(self.groupBox)
        self.btnAffine.setGeometry(QtCore.QRect(400, 82, 91, 32))
        self.btnAffine.setObjectName("btnAffine")
        self.label_4 = QtWidgets.QLabel(frmAtlasROI)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.label_4.setObjectName("label_4")
        self.txtCurrent = QtWidgets.QLineEdit(frmAtlasROI)
        self.txtCurrent.setGeometry(QtCore.QRect(100, 10, 601, 21))
        self.txtCurrent.setReadOnly(True)
        self.txtCurrent.setObjectName("txtCurrent")
        self.txtOFile = QtWidgets.QLineEdit(frmAtlasROI)
        self.txtOFile.setGeometry(QtCore.QRect(100, 45, 531, 21))
        self.txtOFile.setStatusTip("")
        self.txtOFile.setText("")
        self.txtOFile.setObjectName("txtOFile")
        self.label_5 = QtWidgets.QLabel(frmAtlasROI)
        self.label_5.setGeometry(QtCore.QRect(10, 45, 101, 17))
        self.label_5.setObjectName("label_5")
        self.btnOFile = QtWidgets.QPushButton(frmAtlasROI)
        self.btnOFile.setGeometry(QtCore.QRect(640, 40, 51, 32))
        self.btnOFile.setObjectName("btnOFile")

        self.retranslateUi(frmAtlasROI)
        QtCore.QMetaObject.connectSlotsByName(frmAtlasROI)
        frmAtlasROI.setTabOrder(self.txtOFile, self.btnOFile)
        frmAtlasROI.setTabOrder(self.btnOFile, self.txtFile)
        frmAtlasROI.setTabOrder(self.txtFile, self.btnFile)
        frmAtlasROI.setTabOrder(self.btnFile, self.txtRangeFrom)
        frmAtlasROI.setTabOrder(self.txtRangeFrom, self.txtRangeTo)
        frmAtlasROI.setTabOrder(self.txtRangeTo, self.btnAffine)
        frmAtlasROI.setTabOrder(self.btnAffine, self.btnRemove)
        frmAtlasROI.setTabOrder(self.btnRemove, self.btnAdd)
        frmAtlasROI.setTabOrder(self.btnAdd, self.tvArea)
        frmAtlasROI.setTabOrder(self.tvArea, self.btnRun)
        frmAtlasROI.setTabOrder(self.btnRun, self.btnClose)
        frmAtlasROI.setTabOrder(self.btnClose, self.txtCurrent)

    def retranslateUi(self, frmAtlasROI):
        _translate = QtCore.QCoreApplication.translate
        frmAtlasROI.setWindowTitle(_translate("frmAtlasROI", "Atlas Based ROI"))
        self.btnRun.setText(_translate("frmAtlasROI", "Run"))
        self.btnClose.setText(_translate("frmAtlasROI", "Close"))
        self.groupBox.setTitle(_translate("frmAtlasROI", "<Insert Atlas>"))
        self.btnFile.setText(_translate("frmAtlasROI", "..."))
        self.label.setText(_translate("frmAtlasROI", "Atlas File:"))
        self.label_2.setText(_translate("frmAtlasROI", "Region: from"))
        self.btnAdd.setText(_translate("frmAtlasROI", "Add"))
        self.btnRemove.setText(_translate("frmAtlasROI", "Remove"))
        self.label_3.setText(_translate("frmAtlasROI", "to"))
        self.btnAffine.setText(_translate("frmAtlasROI", "Affine"))
        self.label_4.setText(_translate("frmAtlasROI", "Current File:"))
        self.txtOFile.setToolTip(_translate("frmAtlasROI", "<html><head/><body><p><span style=\" font-size:18pt;\">mainDIR: main folder that is included all dataset files, i.e. support BIDS format: </span><a href=\"https://www.nature.com/articles/sdata201644\"><span style=\" font-size:18pt; text-decoration: underline; color:#0000ff;\">https://www.nature.com/articles/sdata201644</span></a></p></body></html>"))
        self.label_5.setText(_translate("frmAtlasROI", "Output:"))
        self.btnOFile.setText(_translate("frmAtlasROI", "..."))

