# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmDataEditorGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmDataEditor(object):
    def setupUi(self, frmDataEditor):
        frmDataEditor.setObjectName("frmDataEditor")
        frmDataEditor.resize(848, 584)
        self.centralwidget = QtWidgets.QWidget(frmDataEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnInFile = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnInFile.sizePolicy().hasHeightForWidth())
        self.btnInFile.setSizePolicy(sizePolicy)
        self.btnInFile.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons/icons8-opened-folder-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInFile.setIcon(icon)
        self.btnInFile.setIconSize(QtCore.QSize(48, 48))
        self.btnInFile.setObjectName("btnInFile")
        self.horizontalLayout.addWidget(self.btnInFile)
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        self.btnSave.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Icons/icons8-save-close-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon1)
        self.btnSave.setIconSize(QtCore.QSize(48, 48))
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnSaveAs = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveAs.sizePolicy().hasHeightForWidth())
        self.btnSaveAs.setSizePolicy(sizePolicy)
        self.btnSaveAs.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Icons/icons8-save-all-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveAs.setIcon(icon2)
        self.btnSaveAs.setIconSize(QtCore.QSize(48, 48))
        self.btnSaveAs.setObjectName("btnSaveAs")
        self.horizontalLayout.addWidget(self.btnSaveAs)
        self.btnRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefresh.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Icons/icons8-refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRefresh.setIcon(icon3)
        self.btnRefresh.setIconSize(QtCore.QSize(48, 48))
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout.addWidget(self.btnRefresh)
        self.btnValue = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnValue.sizePolicy().hasHeightForWidth())
        self.btnValue.setSizePolicy(sizePolicy)
        self.btnValue.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Icons/icons8-eye-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnValue.setIcon(icon4)
        self.btnValue.setIconSize(QtCore.QSize(48, 48))
        self.btnValue.setObjectName("btnValue")
        self.horizontalLayout.addWidget(self.btnValue)
        self.btnIn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnIn.sizePolicy().hasHeightForWidth())
        self.btnIn.setSizePolicy(sizePolicy)
        self.btnIn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Icons/icons8-forward-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIn.setIcon(icon5)
        self.btnIn.setIconSize(QtCore.QSize(48, 48))
        self.btnIn.setObjectName("btnIn")
        self.horizontalLayout.addWidget(self.btnIn)
        self.txtInside = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtInside.sizePolicy().hasHeightForWidth())
        self.txtInside.setSizePolicy(sizePolicy)
        self.txtInside.setMinimumSize(QtCore.QSize(60, 54))
        self.txtInside.setMaximumSize(QtCore.QSize(6, 54))
        self.txtInside.setMaximum(999999999)
        self.txtInside.setObjectName("txtInside")
        self.horizontalLayout.addWidget(self.txtInside)
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBack.sizePolicy().hasHeightForWidth())
        self.btnBack.setSizePolicy(sizePolicy)
        self.btnBack.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Icons/icons8-back-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon6)
        self.btnBack.setIconSize(QtCore.QSize(48, 48))
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout.addWidget(self.btnBack)
        spacerItem = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        self.btnClose.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Icons/icons8-shutdown-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon7)
        self.btnClose.setIconSize(QtCore.QSize(48, 48))
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lwData = QtWidgets.QTreeWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lwData.setFont(font)
        self.lwData.setObjectName("lwData")
        self.lwData.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.lwData)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_2.addWidget(self.label_33)
        self.txtInFile = QtWidgets.QLineEdit(self.centralwidget)
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.horizontalLayout_2.addWidget(self.txtInFile)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        frmDataEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frmDataEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 20))
        self.menubar.setObjectName("menubar")
        frmDataEditor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frmDataEditor)
        self.statusbar.setObjectName("statusbar")
        frmDataEditor.setStatusBar(self.statusbar)

        self.retranslateUi(frmDataEditor)
        QtCore.QMetaObject.connectSlotsByName(frmDataEditor)

    def retranslateUi(self, frmDataEditor):
        _translate = QtCore.QCoreApplication.translate
        frmDataEditor.setWindowTitle(_translate("frmDataEditor", "MainWindow"))
        self.btnInFile.setToolTip(_translate("frmDataEditor", "Open File"))
        self.btnSave.setToolTip(_translate("frmDataEditor", "Save File"))
        self.lwData.setSortingEnabled(True)
        self.label_33.setText(_translate("frmDataEditor", "Address"))

