# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmFAPCAGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmFAPCA(object):
    def setupUi(self, frmFAPCA):
        frmFAPCA.setObjectName("frmFAPCA")
        frmFAPCA.resize(782, 775)
        self.btnInFile = QtWidgets.QPushButton(frmFAPCA)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmFAPCA)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 131, 16))
        self.label_33.setObjectName("label_33")
        self.btnOutFile = QtWidgets.QPushButton(frmFAPCA)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.txtInFile = QtWidgets.QLineEdit(frmFAPCA)
        self.txtInFile.setGeometry(QtCore.QRect(160, 20, 541, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmFAPCA)
        self.btnConvert.setGeometry(QtCore.QRect(620, 730, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label_35 = QtWidgets.QLabel(frmFAPCA)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmFAPCA)
        self.txtOutFile.setGeometry(QtCore.QRect(160, 60, 541, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnClose = QtWidgets.QPushButton(frmFAPCA)
        self.btnClose.setGeometry(QtCore.QRect(30, 730, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmFAPCA)
        self.tabWidget.setGeometry(QtCore.QRect(30, 100, 731, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.txtOTrTask = QtWidgets.QLineEdit(self.tab)
        self.txtOTrTask.setGeometry(QtCore.QRect(450, 300, 113, 21))
        self.txtOTrTask.setObjectName("txtOTrTask")
        self.txtITrmLabel = QtWidgets.QComboBox(self.tab)
        self.txtITrmLabel.setGeometry(QtCore.QRect(140, 180, 121, 26))
        self.txtITrmLabel.setEditable(True)
        self.txtITrmLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrmLabel.setObjectName("txtITrmLabel")
        self.cbmLabel = QtWidgets.QCheckBox(self.tab)
        self.cbmLabel.setGeometry(QtCore.QRect(20, 180, 111, 20))
        self.cbmLabel.setObjectName("cbmLabel")
        self.txtITrScan = QtWidgets.QComboBox(self.tab)
        self.txtITrScan.setGeometry(QtCore.QRect(140, 460, 121, 26))
        self.txtITrScan.setEditable(True)
        self.txtITrScan.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrScan.setObjectName("txtITrScan")
        self.txtITrTask = QtWidgets.QComboBox(self.tab)
        self.txtITrTask.setGeometry(QtCore.QRect(140, 300, 121, 26))
        self.txtITrTask.setEditable(True)
        self.txtITrTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrTask.setObjectName("txtITrTask")
        self.txtITrSubject = QtWidgets.QComboBox(self.tab)
        self.txtITrSubject.setGeometry(QtCore.QRect(140, 140, 121, 26))
        self.txtITrSubject.setEditable(True)
        self.txtITrSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrSubject.setObjectName("txtITrSubject")
        self.txtOTrmLabel = QtWidgets.QLineEdit(self.tab)
        self.txtOTrmLabel.setGeometry(QtCore.QRect(450, 180, 113, 21))
        self.txtOTrmLabel.setObjectName("txtOTrmLabel")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 60, 16))
        self.label_2.setObjectName("label_2")
        self.txtOTrDM = QtWidgets.QLineEdit(self.tab)
        self.txtOTrDM.setGeometry(QtCore.QRect(450, 260, 113, 21))
        self.txtOTrDM.setObjectName("txtOTrDM")
        self.cbTask = QtWidgets.QCheckBox(self.tab)
        self.cbTask.setGeometry(QtCore.QRect(20, 300, 81, 20))
        self.cbTask.setChecked(True)
        self.cbTask.setObjectName("cbTask")
        self.txtITrDM = QtWidgets.QComboBox(self.tab)
        self.txtITrDM.setGeometry(QtCore.QRect(140, 260, 121, 26))
        self.txtITrDM.setEditable(True)
        self.txtITrDM.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrDM.setObjectName("txtITrDM")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 60, 16))
        self.label_3.setObjectName("label_3")
        self.cbNScan = QtWidgets.QCheckBox(self.tab)
        self.cbNScan.setGeometry(QtCore.QRect(20, 460, 91, 20))
        self.cbNScan.setChecked(False)
        self.cbNScan.setObjectName("cbNScan")
        self.cbCond = QtWidgets.QCheckBox(self.tab)
        self.cbCond.setGeometry(QtCore.QRect(20, 420, 101, 20))
        self.cbCond.setChecked(True)
        self.cbCond.setObjectName("cbCond")
        self.cbDM = QtWidgets.QCheckBox(self.tab)
        self.cbDM.setGeometry(QtCore.QRect(20, 260, 121, 20))
        self.cbDM.setChecked(False)
        self.cbDM.setObjectName("cbDM")
        self.txtCol = QtWidgets.QComboBox(self.tab)
        self.txtCol.setGeometry(QtCore.QRect(140, 220, 121, 26))
        self.txtCol.setEditable(True)
        self.txtCol.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCol.setObjectName("txtCol")
        self.cbCol = QtWidgets.QCheckBox(self.tab)
        self.cbCol.setGeometry(QtCore.QRect(20, 220, 111, 20))
        self.cbCol.setChecked(True)
        self.cbCol.setObjectName("cbCol")
        self.txtOCond = QtWidgets.QLineEdit(self.tab)
        self.txtOCond.setGeometry(QtCore.QRect(450, 420, 113, 21))
        self.txtOCond.setObjectName("txtOCond")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 10, 61, 16))
        self.label.setObjectName("label")
        self.txtOTrLabel = QtWidgets.QLineEdit(self.tab)
        self.txtOTrLabel.setGeometry(QtCore.QRect(450, 100, 113, 21))
        self.txtOTrLabel.setObjectName("txtOTrLabel")
        self.txtITrCounter = QtWidgets.QComboBox(self.tab)
        self.txtITrCounter.setGeometry(QtCore.QRect(140, 380, 121, 26))
        self.txtITrCounter.setEditable(True)
        self.txtITrCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrCounter.setObjectName("txtITrCounter")
        self.txtITrLabel = QtWidgets.QComboBox(self.tab)
        self.txtITrLabel.setGeometry(QtCore.QRect(140, 100, 121, 26))
        self.txtITrLabel.setEditable(True)
        self.txtITrLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrLabel.setObjectName("txtITrLabel")
        self.txtOTrScan = QtWidgets.QLineEdit(self.tab)
        self.txtOTrScan.setGeometry(QtCore.QRect(450, 460, 113, 21))
        self.txtOTrScan.setObjectName("txtOTrScan")
        self.cbCounter = QtWidgets.QCheckBox(self.tab)
        self.cbCounter.setGeometry(QtCore.QRect(20, 380, 81, 20))
        self.cbCounter.setChecked(False)
        self.cbCounter.setObjectName("cbCounter")
        self.txtOCol = QtWidgets.QLineEdit(self.tab)
        self.txtOCol.setGeometry(QtCore.QRect(450, 220, 113, 21))
        self.txtOCol.setObjectName("txtOCol")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(550, 10, 61, 16))
        self.label_5.setObjectName("label_5")
        self.txtITrData = QtWidgets.QComboBox(self.tab)
        self.txtITrData.setGeometry(QtCore.QRect(140, 60, 121, 26))
        self.txtITrData.setEditable(True)
        self.txtITrData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrData.setObjectName("txtITrData")
        self.txtITrRun = QtWidgets.QComboBox(self.tab)
        self.txtITrRun.setGeometry(QtCore.QRect(140, 340, 121, 26))
        self.txtITrRun.setEditable(True)
        self.txtITrRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrRun.setObjectName("txtITrRun")
        self.txtCond = QtWidgets.QComboBox(self.tab)
        self.txtCond.setGeometry(QtCore.QRect(140, 420, 121, 26))
        self.txtCond.setEditable(True)
        self.txtCond.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCond.setObjectName("txtCond")
        self.txtOTrCounter = QtWidgets.QLineEdit(self.tab)
        self.txtOTrCounter.setGeometry(QtCore.QRect(450, 380, 113, 21))
        self.txtOTrCounter.setObjectName("txtOTrCounter")
        self.txtOTrSubject = QtWidgets.QLineEdit(self.tab)
        self.txtOTrSubject.setGeometry(QtCore.QRect(450, 140, 113, 21))
        self.txtOTrSubject.setObjectName("txtOTrSubject")
        self.cbRun = QtWidgets.QCheckBox(self.tab)
        self.cbRun.setGeometry(QtCore.QRect(20, 340, 81, 20))
        self.cbRun.setChecked(True)
        self.cbRun.setObjectName("cbRun")
        self.txtOTrData = QtWidgets.QLineEdit(self.tab)
        self.txtOTrData.setGeometry(QtCore.QRect(450, 60, 113, 21))
        self.txtOTrData.setObjectName("txtOTrData")
        self.txtOTrRun = QtWidgets.QLineEdit(self.tab)
        self.txtOTrRun.setGeometry(QtCore.QRect(450, 340, 113, 21))
        self.txtOTrRun.setObjectName("txtOTrRun")
        self.txtITemLabel = QtWidgets.QComboBox(self.tab)
        self.txtITemLabel.setGeometry(QtCore.QRect(290, 180, 121, 26))
        self.txtITemLabel.setEditable(True)
        self.txtITemLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITemLabel.setObjectName("txtITemLabel")
        self.txtITeSubject = QtWidgets.QComboBox(self.tab)
        self.txtITeSubject.setGeometry(QtCore.QRect(290, 140, 121, 26))
        self.txtITeSubject.setEditable(True)
        self.txtITeSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeSubject.setObjectName("txtITeSubject")
        self.txtITeDM = QtWidgets.QComboBox(self.tab)
        self.txtITeDM.setGeometry(QtCore.QRect(290, 260, 121, 26))
        self.txtITeDM.setEditable(True)
        self.txtITeDM.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeDM.setObjectName("txtITeDM")
        self.txtITeCounter = QtWidgets.QComboBox(self.tab)
        self.txtITeCounter.setGeometry(QtCore.QRect(290, 380, 121, 26))
        self.txtITeCounter.setEditable(True)
        self.txtITeCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeCounter.setObjectName("txtITeCounter")
        self.txtITeLabel = QtWidgets.QComboBox(self.tab)
        self.txtITeLabel.setGeometry(QtCore.QRect(290, 100, 121, 26))
        self.txtITeLabel.setEditable(True)
        self.txtITeLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeLabel.setObjectName("txtITeLabel")
        self.txtITeData = QtWidgets.QComboBox(self.tab)
        self.txtITeData.setGeometry(QtCore.QRect(290, 60, 121, 26))
        self.txtITeData.setEditable(True)
        self.txtITeData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeData.setObjectName("txtITeData")
        self.txtITeTask = QtWidgets.QComboBox(self.tab)
        self.txtITeTask.setGeometry(QtCore.QRect(290, 300, 121, 26))
        self.txtITeTask.setEditable(True)
        self.txtITeTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeTask.setObjectName("txtITeTask")
        self.txtITeScan = QtWidgets.QComboBox(self.tab)
        self.txtITeScan.setGeometry(QtCore.QRect(290, 460, 121, 26))
        self.txtITeScan.setEditable(True)
        self.txtITeScan.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeScan.setObjectName("txtITeScan")
        self.txtITeRun = QtWidgets.QComboBox(self.tab)
        self.txtITeRun.setGeometry(QtCore.QRect(290, 340, 121, 26))
        self.txtITeRun.setEditable(True)
        self.txtITeRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeRun.setObjectName("txtITeRun")
        self.txtOTeLabel = QtWidgets.QLineEdit(self.tab)
        self.txtOTeLabel.setGeometry(QtCore.QRect(600, 100, 113, 21))
        self.txtOTeLabel.setObjectName("txtOTeLabel")
        self.txtOTeRun = QtWidgets.QLineEdit(self.tab)
        self.txtOTeRun.setGeometry(QtCore.QRect(600, 340, 113, 21))
        self.txtOTeRun.setObjectName("txtOTeRun")
        self.txtOTemLabel = QtWidgets.QLineEdit(self.tab)
        self.txtOTemLabel.setGeometry(QtCore.QRect(600, 180, 113, 21))
        self.txtOTemLabel.setObjectName("txtOTemLabel")
        self.txtOTeDM = QtWidgets.QLineEdit(self.tab)
        self.txtOTeDM.setGeometry(QtCore.QRect(600, 260, 113, 21))
        self.txtOTeDM.setObjectName("txtOTeDM")
        self.txtOTeData = QtWidgets.QLineEdit(self.tab)
        self.txtOTeData.setGeometry(QtCore.QRect(600, 60, 113, 21))
        self.txtOTeData.setObjectName("txtOTeData")
        self.txtOTeCounter = QtWidgets.QLineEdit(self.tab)
        self.txtOTeCounter.setGeometry(QtCore.QRect(600, 380, 113, 21))
        self.txtOTeCounter.setObjectName("txtOTeCounter")
        self.txtOTeSubject = QtWidgets.QLineEdit(self.tab)
        self.txtOTeSubject.setGeometry(QtCore.QRect(600, 140, 113, 21))
        self.txtOTeSubject.setObjectName("txtOTeSubject")
        self.txtOTeTask = QtWidgets.QLineEdit(self.tab)
        self.txtOTeTask.setGeometry(QtCore.QRect(600, 300, 113, 21))
        self.txtOTeTask.setObjectName("txtOTeTask")
        self.txtOTeScan = QtWidgets.QLineEdit(self.tab)
        self.txtOTeScan.setGeometry(QtCore.QRect(600, 460, 113, 21))
        self.txtOTeScan.setObjectName("txtOTeScan")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(185, 30, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(330, 30, 81, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(485, 30, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(630, 30, 81, 16))
        self.label_10.setObjectName("label_10")
        self.cbFoldID = QtWidgets.QCheckBox(self.tab)
        self.cbFoldID.setGeometry(QtCore.QRect(20, 500, 101, 20))
        self.cbFoldID.setChecked(True)
        self.cbFoldID.setObjectName("cbFoldID")
        self.txtFoldID = QtWidgets.QComboBox(self.tab)
        self.txtFoldID.setGeometry(QtCore.QRect(140, 500, 121, 26))
        self.txtFoldID.setEditable(True)
        self.txtFoldID.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFoldID.setObjectName("txtFoldID")
        self.txtOFoldID = QtWidgets.QLineEdit(self.tab)
        self.txtOFoldID.setGeometry(QtCore.QRect(450, 500, 113, 21))
        self.txtOFoldID.setObjectName("txtOFoldID")
        self.txtFoldInfo = QtWidgets.QComboBox(self.tab)
        self.txtFoldInfo.setGeometry(QtCore.QRect(140, 540, 121, 26))
        self.txtFoldInfo.setEditable(True)
        self.txtFoldInfo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFoldInfo.setObjectName("txtFoldInfo")
        self.cbFoldInfo = QtWidgets.QCheckBox(self.tab)
        self.cbFoldInfo.setGeometry(QtCore.QRect(20, 540, 101, 20))
        self.cbFoldInfo.setChecked(True)
        self.cbFoldInfo.setObjectName("cbFoldInfo")
        self.txtOFoldInfo = QtWidgets.QLineEdit(self.tab)
        self.txtOFoldInfo.setGeometry(QtCore.QRect(450, 540, 113, 21))
        self.txtOFoldInfo.setObjectName("txtOFoldInfo")
        self.lbFoldID = QtWidgets.QLabel(self.tab)
        self.lbFoldID.setGeometry(QtCore.QRect(290, 500, 121, 16))
        self.lbFoldID.setObjectName("lbFoldID")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 140, 121, 16))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 671, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 191, 20))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(30, 440, 231, 16))
        self.label_11.setObjectName("label_11")
        self.txtJobs = QtWidgets.QLineEdit(self.tab_2)
        self.txtJobs.setGeometry(QtCore.QRect(260, 480, 160, 21))
        self.txtJobs.setObjectName("txtJobs")
        self.txtMaxIter = QtWidgets.QLineEdit(self.tab_2)
        self.txtMaxIter.setGeometry(QtCore.QRect(260, 440, 160, 21))
        self.txtMaxIter.setObjectName("txtMaxIter")
        self.txtDegree = QtWidgets.QLineEdit(self.tab_2)
        self.txtDegree.setGeometry(QtCore.QRect(260, 280, 160, 21))
        self.txtDegree.setObjectName("txtDegree")
        self.lblFeaNum_6 = QtWidgets.QLabel(self.tab_2)
        self.lblFeaNum_6.setGeometry(QtCore.QRect(440, 440, 241, 16))
        self.lblFeaNum_6.setObjectName("lblFeaNum_6")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(30, 480, 231, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(30, 240, 221, 16))
        self.label_14.setObjectName("label_14")
        self.txtCoef0 = QtWidgets.QLineEdit(self.tab_2)
        self.txtCoef0.setGeometry(QtCore.QRect(260, 320, 160, 21))
        self.txtCoef0.setObjectName("txtCoef0")
        self.cbKernel = QtWidgets.QComboBox(self.tab_2)
        self.cbKernel.setGeometry(QtCore.QRect(260, 200, 161, 26))
        self.cbKernel.setObjectName("cbKernel")
        self.lblFeaNum = QtWidgets.QLabel(self.tab_2)
        self.lblFeaNum.setGeometry(QtCore.QRect(440, 160, 191, 16))
        self.lblFeaNum.setObjectName("lblFeaNum")
        self.txtGamma = QtWidgets.QLineEdit(self.tab_2)
        self.txtGamma.setGeometry(QtCore.QRect(260, 240, 160, 21))
        self.txtGamma.setObjectName("txtGamma")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 280, 231, 16))
        self.label_15.setObjectName("label_15")
        self.txtAlpha = QtWidgets.QLineEdit(self.tab_2)
        self.txtAlpha.setGeometry(QtCore.QRect(260, 360, 160, 21))
        self.txtAlpha.setObjectName("txtAlpha")
        self.lblFeaNum_2 = QtWidgets.QLabel(self.tab_2)
        self.lblFeaNum_2.setGeometry(QtCore.QRect(440, 280, 191, 16))
        self.lblFeaNum_2.setObjectName("lblFeaNum_2")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(30, 360, 231, 16))
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(30, 200, 231, 16))
        self.label_18.setObjectName("label_18")
        self.txtNumFea = QtWidgets.QSpinBox(self.tab_2)
        self.txtNumFea.setGeometry(QtCore.QRect(260, 160, 161, 24))
        self.txtNumFea.setMinimum(1)
        self.txtNumFea.setObjectName("txtNumFea")
        self.lblFeaNum_3 = QtWidgets.QLabel(self.tab_2)
        self.lblFeaNum_3.setGeometry(QtCore.QRect(440, 240, 241, 16))
        self.lblFeaNum_3.setObjectName("lblFeaNum_3")
        self.lblFeaNum_5 = QtWidgets.QLabel(self.tab_2)
        self.lblFeaNum_5.setGeometry(QtCore.QRect(440, 400, 241, 16))
        self.lblFeaNum_5.setObjectName("lblFeaNum_5")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(30, 400, 221, 16))
        self.label_19.setObjectName("label_19")
        self.lblFeaNum_4 = QtWidgets.QLabel(self.tab_2)
        self.lblFeaNum_4.setGeometry(QtCore.QRect(440, 320, 271, 16))
        self.lblFeaNum_4.setObjectName("lblFeaNum_4")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 221, 16))
        self.label_4.setObjectName("label_4")
        self.txtTole = QtWidgets.QLineEdit(self.tab_2)
        self.txtTole.setGeometry(QtCore.QRect(260, 400, 160, 21))
        self.txtTole.setObjectName("txtTole")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(30, 320, 231, 16))
        self.label_20.setObjectName("label_20")
        self.lblFeaNum_7 = QtWidgets.QLabel(self.tab_2)
        self.lblFeaNum_7.setGeometry(QtCore.QRect(440, 480, 241, 16))
        self.lblFeaNum_7.setObjectName("lblFeaNum_7")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(30, 120, 231, 16))
        self.label_21.setObjectName("label_21")
        self.cbMethod = QtWidgets.QComboBox(self.tab_2)
        self.cbMethod.setGeometry(QtCore.QRect(260, 120, 161, 26))
        self.cbMethod.setObjectName("cbMethod")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(30, 520, 171, 16))
        self.label_22.setObjectName("label_22")
        self.txtBatch = QtWidgets.QSpinBox(self.tab_2)
        self.txtBatch.setGeometry(QtCore.QRect(260, 520, 161, 24))
        self.txtBatch.setMinimum(0)
        self.txtBatch.setMaximum(999999999)
        self.txtBatch.setProperty("value", 0)
        self.txtBatch.setObjectName("txtBatch")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.txtFoldFrom = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldFrom.setGeometry(QtCore.QRect(100, 30, 80, 24))
        self.txtFoldFrom.setMaximum(100000)
        self.txtFoldFrom.setProperty("value", 1)
        self.txtFoldFrom.setObjectName("txtFoldFrom")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(40, 30, 60, 16))
        self.label_17.setObjectName("label_17")
        self.txtFoldTo = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldTo.setGeometry(QtCore.QRect(270, 30, 80, 24))
        self.txtFoldTo.setMaximum(100000)
        self.txtFoldTo.setProperty("value", 1)
        self.txtFoldTo.setObjectName("txtFoldTo")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(210, 30, 60, 16))
        self.label_44.setObjectName("label_44")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_12 = QtWidgets.QLabel(frmFAPCA)
        self.label_12.setGeometry(QtCore.QRect(185, 735, 421, 20))
        self.label_12.setObjectName("label_12")

        self.retranslateUi(frmFAPCA)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmFAPCA)
        frmFAPCA.setTabOrder(self.txtInFile, self.btnInFile)
        frmFAPCA.setTabOrder(self.btnInFile, self.txtOutFile)
        frmFAPCA.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmFAPCA.setTabOrder(self.btnOutFile, self.tabWidget)
        frmFAPCA.setTabOrder(self.tabWidget, self.cbmLabel)
        frmFAPCA.setTabOrder(self.cbmLabel, self.cbCol)
        frmFAPCA.setTabOrder(self.cbCol, self.cbDM)
        frmFAPCA.setTabOrder(self.cbDM, self.cbTask)
        frmFAPCA.setTabOrder(self.cbTask, self.cbRun)
        frmFAPCA.setTabOrder(self.cbRun, self.cbCounter)
        frmFAPCA.setTabOrder(self.cbCounter, self.cbCond)
        frmFAPCA.setTabOrder(self.cbCond, self.cbNScan)
        frmFAPCA.setTabOrder(self.cbNScan, self.txtITrData)
        frmFAPCA.setTabOrder(self.txtITrData, self.txtITrLabel)
        frmFAPCA.setTabOrder(self.txtITrLabel, self.txtITrSubject)
        frmFAPCA.setTabOrder(self.txtITrSubject, self.txtITrmLabel)
        frmFAPCA.setTabOrder(self.txtITrmLabel, self.txtCol)
        frmFAPCA.setTabOrder(self.txtCol, self.txtITrDM)
        frmFAPCA.setTabOrder(self.txtITrDM, self.txtITrTask)
        frmFAPCA.setTabOrder(self.txtITrTask, self.txtITrRun)
        frmFAPCA.setTabOrder(self.txtITrRun, self.txtITrCounter)
        frmFAPCA.setTabOrder(self.txtITrCounter, self.txtITrScan)
        frmFAPCA.setTabOrder(self.txtITrScan, self.txtOTrData)
        frmFAPCA.setTabOrder(self.txtOTrData, self.txtOTrLabel)
        frmFAPCA.setTabOrder(self.txtOTrLabel, self.txtOTrSubject)
        frmFAPCA.setTabOrder(self.txtOTrSubject, self.txtOTrmLabel)
        frmFAPCA.setTabOrder(self.txtOTrmLabel, self.txtOCol)
        frmFAPCA.setTabOrder(self.txtOCol, self.txtOTrDM)
        frmFAPCA.setTabOrder(self.txtOTrDM, self.txtOTrTask)
        frmFAPCA.setTabOrder(self.txtOTrTask, self.txtOTrRun)
        frmFAPCA.setTabOrder(self.txtOTrRun, self.txtOTrCounter)
        frmFAPCA.setTabOrder(self.txtOTrCounter, self.txtOCond)
        frmFAPCA.setTabOrder(self.txtOCond, self.txtOTrScan)
        frmFAPCA.setTabOrder(self.txtOTrScan, self.txtCond)
        frmFAPCA.setTabOrder(self.txtCond, self.btnConvert)
        frmFAPCA.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmFAPCA):
        _translate = QtCore.QCoreApplication.translate
        frmFAPCA.setWindowTitle(_translate("frmFAPCA", "PCA Functional Alignment"))
        self.btnInFile.setText(_translate("frmFAPCA", "..."))
        self.label_33.setText(_translate("frmFAPCA", "Input Data"))
        self.btnOutFile.setText(_translate("frmFAPCA", "..."))
        self.btnConvert.setText(_translate("frmFAPCA", "Alignment"))
        self.label_35.setText(_translate("frmFAPCA", "Output Data"))
        self.btnClose.setText(_translate("frmFAPCA", "Close"))
        self.txtOTrTask.setText(_translate("frmFAPCA", "train_task"))
        self.cbmLabel.setText(_translate("frmFAPCA", "Label (matrix)"))
        self.txtOTrmLabel.setText(_translate("frmFAPCA", "train_mlabel"))
        self.label_2.setText(_translate("frmFAPCA", "Data"))
        self.txtOTrDM.setText(_translate("frmFAPCA", "train_design"))
        self.cbTask.setText(_translate("frmFAPCA", "Task"))
        self.label_3.setText(_translate("frmFAPCA", "Label"))
        self.cbNScan.setText(_translate("frmFAPCA", "NScan"))
        self.cbCond.setText(_translate("frmFAPCA", "Condition"))
        self.cbDM.setText(_translate("frmFAPCA", "Design Matrix"))
        self.cbCol.setText(_translate("frmFAPCA", "Coordinate"))
        self.txtOCond.setText(_translate("frmFAPCA", "condition"))
        self.label.setText(_translate("frmFAPCA", "Input"))
        self.txtOTrLabel.setText(_translate("frmFAPCA", "train_label"))
        self.txtOTrScan.setText(_translate("frmFAPCA", "train_nscan"))
        self.cbCounter.setText(_translate("frmFAPCA", "Counter"))
        self.txtOCol.setText(_translate("frmFAPCA", "coordinate"))
        self.label_5.setText(_translate("frmFAPCA", "Output"))
        self.txtOTrCounter.setText(_translate("frmFAPCA", "train_counter"))
        self.txtOTrSubject.setText(_translate("frmFAPCA", "train_subject"))
        self.cbRun.setText(_translate("frmFAPCA", "Run"))
        self.txtOTrData.setText(_translate("frmFAPCA", "train_data"))
        self.txtOTrRun.setText(_translate("frmFAPCA", "train_run"))
        self.txtOTeLabel.setText(_translate("frmFAPCA", "test_label"))
        self.txtOTeRun.setText(_translate("frmFAPCA", "test_run"))
        self.txtOTemLabel.setText(_translate("frmFAPCA", "test_mlabel"))
        self.txtOTeDM.setText(_translate("frmFAPCA", "test_design"))
        self.txtOTeData.setText(_translate("frmFAPCA", "test_data"))
        self.txtOTeCounter.setText(_translate("frmFAPCA", "test_counter"))
        self.txtOTeSubject.setText(_translate("frmFAPCA", "test_subject"))
        self.txtOTeTask.setText(_translate("frmFAPCA", "test_task"))
        self.txtOTeScan.setText(_translate("frmFAPCA", "test_nscan"))
        self.label_7.setText(_translate("frmFAPCA", "Train"))
        self.label_8.setText(_translate("frmFAPCA", "Test"))
        self.label_9.setText(_translate("frmFAPCA", "Train"))
        self.label_10.setText(_translate("frmFAPCA", "Test"))
        self.cbFoldID.setText(_translate("frmFAPCA", "FoldID"))
        self.txtOFoldID.setText(_translate("frmFAPCA", "FoldID"))
        self.cbFoldInfo.setText(_translate("frmFAPCA", "FoldInfo"))
        self.txtOFoldInfo.setText(_translate("frmFAPCA", "FoldInfo"))
        self.lbFoldID.setText(_translate("frmFAPCA", "ID=None"))
        self.label_6.setText(_translate("frmFAPCA", "Subject"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmFAPCA", "Data"))
        self.groupBox.setTitle(_translate("frmFAPCA", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmFAPCA", "Scale Data X~N(0,1)"))
        self.label_11.setText(_translate("frmFAPCA", "Maximum Iterations (None=0)"))
        self.txtJobs.setText(_translate("frmFAPCA", "-1"))
        self.txtMaxIter.setText(_translate("frmFAPCA", "0"))
        self.txtDegree.setText(_translate("frmFAPCA", "3"))
        self.lblFeaNum_6.setText(_translate("frmFAPCA", "Related to arpack."))
        self.label_13.setText(_translate("frmFAPCA", "Number of parallel jobs"))
        self.label_14.setText(_translate("frmFAPCA", "Gamma (None=0)"))
        self.txtCoef0.setText(_translate("frmFAPCA", "1"))
        self.lblFeaNum.setText(_translate("frmFAPCA", "No Data"))
        self.txtGamma.setText(_translate("frmFAPCA", "0"))
        self.label_15.setText(_translate("frmFAPCA", "Degree"))
        self.txtAlpha.setText(_translate("frmFAPCA", "1"))
        self.lblFeaNum_2.setText(_translate("frmFAPCA", "Degree for poly kernels."))
        self.label_16.setText(_translate("frmFAPCA", "Alpha"))
        self.label_18.setText(_translate("frmFAPCA", "Kernel"))
        self.lblFeaNum_3.setText(_translate("frmFAPCA", "Coefficient for rbf, poly and sigmoid."))
        self.lblFeaNum_5.setText(_translate("frmFAPCA", "Convergence tolerance for arpack."))
        self.label_19.setText(_translate("frmFAPCA", "Tolerance"))
        self.lblFeaNum_4.setText(_translate("frmFAPCA", "Term in poly and sigmoid kernels. "))
        self.label_4.setText(_translate("frmFAPCA", "Number of features"))
        self.txtTole.setText(_translate("frmFAPCA", "0"))
        self.label_20.setText(_translate("frmFAPCA", "Coef0"))
        self.lblFeaNum_7.setText(_translate("frmFAPCA", "-1 is for auto assign."))
        self.label_21.setText(_translate("frmFAPCA", "Method"))
        self.label_22.setText(_translate("frmFAPCA", "Batch Size (0 = None) "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmFAPCA", "Parameters"))
        self.label_17.setText(_translate("frmFAPCA", "From:"))
        self.label_44.setText(_translate("frmFAPCA", "To:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmFAPCA", "Fold"))
        self.label_12.setText(_translate("frmFAPCA", "$FOLD$ will be replaced by fold number."))

