# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmFEEZCrossValidationGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmFEEZCrossValidation(object):
    def setupUi(self, frmFEEZCrossValidation):
        frmFEEZCrossValidation.setObjectName("frmFEEZCrossValidation")
        frmFEEZCrossValidation.resize(743, 479)
        self.btnInFile = QtWidgets.QPushButton(frmFEEZCrossValidation)
        self.btnInFile.setGeometry(QtCore.QRect(670, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmFEEZCrossValidation)
        self.label_33.setGeometry(QtCore.QRect(20, 20, 151, 16))
        self.label_33.setObjectName("label_33")
        self.txtInFile = QtWidgets.QLineEdit(frmFEEZCrossValidation)
        self.txtInFile.setGeometry(QtCore.QRect(160, 20, 501, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmFEEZCrossValidation)
        self.btnConvert.setGeometry(QtCore.QRect(590, 430, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.btnClose = QtWidgets.QPushButton(frmFEEZCrossValidation)
        self.btnClose.setGeometry(QtCore.QRect(20, 430, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmFEEZCrossValidation)
        self.tabWidget.setGeometry(QtCore.QRect(20, 60, 711, 351))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 221, 16))
        self.label_3.setObjectName("label_3")
        self.txtLabel = QtWidgets.QComboBox(self.tab_2)
        self.txtLabel.setGeometry(QtCore.QRect(180, 20, 151, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.lblDataStr = QtWidgets.QLabel(self.tab_2)
        self.lblDataStr.setGeometry(QtCore.QRect(350, 20, 341, 17))
        self.lblDataStr.setObjectName("lblDataStr")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 221, 16))
        self.label_5.setObjectName("label_5")
        self.txtData = QtWidgets.QComboBox(self.tab_2)
        self.txtData.setGeometry(QtCore.QRect(180, 60, 151, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.btnReload = QtWidgets.QPushButton(self.tab_2)
        self.btnReload.setGeometry(QtCore.QRect(350, 60, 141, 29))
        self.btnReload.setObjectName("btnReload")
        self.txtRun = QtWidgets.QComboBox(self.tab_2)
        self.txtRun.setGeometry(QtCore.QRect(180, 180, 151, 26))
        self.txtRun.setEditable(True)
        self.txtRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRun.setObjectName("txtRun")
        self.txtSubject = QtWidgets.QComboBox(self.tab_2)
        self.txtSubject.setGeometry(QtCore.QRect(180, 140, 151, 26))
        self.txtSubject.setEditable(True)
        self.txtSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubject.setObjectName("txtSubject")
        self.txtTask = QtWidgets.QComboBox(self.tab_2)
        self.txtTask.setGeometry(QtCore.QRect(180, 100, 151, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTask.setObjectName("txtTask")
        self.txtCounter = QtWidgets.QComboBox(self.tab_2)
        self.txtCounter.setGeometry(QtCore.QRect(180, 220, 151, 26))
        self.txtCounter.setEditable(True)
        self.txtCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounter.setObjectName("txtCounter")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(21, 260, 141, 16))
        self.label_30.setObjectName("label_30")
        self.txtDIOutDAT = QtWidgets.QLineEdit(self.tab_2)
        self.txtDIOutDAT.setGeometry(QtCore.QRect(180, 260, 511, 21))
        self.txtDIOutDAT.setObjectName("txtDIOutDAT")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(540, 140, 60, 16))
        self.label_25.setObjectName("label_25")
        self.txtDISubPer = QtWidgets.QLineEdit(self.tab_2)
        self.txtDISubPer.setGeometry(QtCore.QRect(610, 140, 80, 21))
        self.txtDISubPer.setObjectName("txtDISubPer")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(350, 140, 60, 21))
        self.label_26.setObjectName("label_26")
        self.txtDISubLen = QtWidgets.QSpinBox(self.tab_2)
        self.txtDISubLen.setGeometry(QtCore.QRect(430, 140, 80, 24))
        self.txtDISubLen.setMinimum(1)
        self.txtDISubLen.setMaximum(999999999)
        self.txtDISubLen.setSingleStep(1)
        self.txtDISubLen.setProperty("value", 2)
        self.txtDISubLen.setObjectName("txtDISubLen")
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(20, 140, 141, 16))
        self.label_32.setObjectName("label_32")
        self.txtDIRunPer = QtWidgets.QLineEdit(self.tab_2)
        self.txtDIRunPer.setGeometry(QtCore.QRect(610, 180, 80, 21))
        self.txtDIRunPer.setObjectName("txtDIRunPer")
        self.txtDIRunLen = QtWidgets.QSpinBox(self.tab_2)
        self.txtDIRunLen.setGeometry(QtCore.QRect(430, 180, 80, 24))
        self.txtDIRunLen.setMinimum(1)
        self.txtDIRunLen.setMaximum(999999999)
        self.txtDIRunLen.setProperty("value", 2)
        self.txtDIRunLen.setObjectName("txtDIRunLen")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(540, 180, 60, 16))
        self.label_28.setObjectName("label_28")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(350, 180, 60, 21))
        self.label_27.setObjectName("label_27")
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(20, 180, 141, 16))
        self.label_34.setObjectName("label_34")
        self.txtDIConLen = QtWidgets.QSpinBox(self.tab_2)
        self.txtDIConLen.setGeometry(QtCore.QRect(430, 220, 80, 24))
        self.txtDIConLen.setMaximum(100000)
        self.txtDIConLen.setSingleStep(1)
        self.txtDIConLen.setProperty("value", 2)
        self.txtDIConLen.setObjectName("txtDIConLen")
        self.label_47 = QtWidgets.QLabel(self.tab_2)
        self.label_47.setGeometry(QtCore.QRect(540, 220, 60, 16))
        self.label_47.setObjectName("label_47")
        self.label_45 = QtWidgets.QLabel(self.tab_2)
        self.label_45.setGeometry(QtCore.QRect(350, 220, 60, 21))
        self.label_45.setObjectName("label_45")
        self.txtDIConPer = QtWidgets.QLineEdit(self.tab_2)
        self.txtDIConPer.setGeometry(QtCore.QRect(610, 220, 80, 21))
        self.txtDIConPer.setObjectName("txtDIConPer")
        self.label_35 = QtWidgets.QLabel(self.tab_2)
        self.label_35.setGeometry(QtCore.QRect(20, 220, 141, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(20, 100, 141, 16))
        self.label_36.setObjectName("label_36")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 231, 16))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 100, 231, 16))
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 221, 16))
        self.label_7.setObjectName("label_7")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(20, 140, 651, 141))
        self.groupBox.setObjectName("groupBox")
        self.cbFTask = QtWidgets.QCheckBox(self.groupBox)
        self.cbFTask.setGeometry(QtCore.QRect(490, 60, 161, 20))
        self.cbFTask.setObjectName("cbFTask")
        self.cbFCounter = QtWidgets.QCheckBox(self.groupBox)
        self.cbFCounter.setGeometry(QtCore.QRect(490, 100, 161, 20))
        self.cbFCounter.setObjectName("cbFCounter")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 30, 451, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cbFSubject = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbFSubject.setGeometry(QtCore.QRect(20, 30, 130, 20))
        self.cbFSubject.setChecked(True)
        self.cbFSubject.setObjectName("cbFSubject")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(20, 60, 201, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.rbFRun = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbFRun.setGeometry(QtCore.QRect(230, 60, 221, 20))
        self.rbFRun.setObjectName("rbFRun")
        self.txtTest = QtWidgets.QLineEdit(self.tab_3)
        self.txtTest.setGeometry(QtCore.QRect(250, 60, 401, 21))
        self.txtTest.setObjectName("txtTest")
        self.txtUnit = QtWidgets.QSpinBox(self.tab_3)
        self.txtUnit.setGeometry(QtCore.QRect(250, 100, 181, 24))
        self.txtUnit.setMinimum(1)
        self.txtUnit.setMaximum(1000000000)
        self.txtUnit.setObjectName("txtUnit")
        self.txtTrain = QtWidgets.QLineEdit(self.tab_3)
        self.txtTrain.setGeometry(QtCore.QRect(250, 20, 401, 21))
        self.txtTrain.setObjectName("txtTrain")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 651, 20))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.txtDataFiles = QtWidgets.QTextBrowser(self.tab)
        self.txtDataFiles.setGeometry(QtCore.QRect(8, 10, 691, 281))
        self.txtDataFiles.setObjectName("txtDataFiles")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(frmFEEZCrossValidation)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmFEEZCrossValidation)
        frmFEEZCrossValidation.setTabOrder(self.txtInFile, self.btnInFile)
        frmFEEZCrossValidation.setTabOrder(self.btnInFile, self.tabWidget)
        frmFEEZCrossValidation.setTabOrder(self.tabWidget, self.btnConvert)
        frmFEEZCrossValidation.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmFEEZCrossValidation):
        _translate = QtCore.QCoreApplication.translate
        frmFEEZCrossValidation.setWindowTitle(_translate("frmFEEZCrossValidation", "EzData Cross Validation"))
        self.btnInFile.setText(_translate("frmFEEZCrossValidation", "..."))
        self.label_33.setText(_translate("frmFEEZCrossValidation", "EzData Header"))
        self.btnConvert.setText(_translate("frmFEEZCrossValidation", "Convert"))
        self.btnClose.setText(_translate("frmFEEZCrossValidation", "Close"))
        self.label_3.setText(_translate("frmFEEZCrossValidation", "Input Label Variable"))
        self.lblDataStr.setText(_translate("frmFEEZCrossValidation", "Data Structure: None"))
        self.label_5.setText(_translate("frmFEEZCrossValidation", "Data Files Variable"))
        self.btnReload.setText(_translate("frmFEEZCrossValidation", "Reload"))
        self.label_30.setText(_translate("frmFEEZCrossValidation", "Ouput Data:"))
        self.txtDIOutDAT.setText(_translate("frmFEEZCrossValidation", "data-$TASK$_sub-$SUB$_con-$COUNT$_run-$RUN$.ezmat"))
        self.label_25.setText(_translate("frmFEEZCrossValidation", "Perfix:"))
        self.txtDISubPer.setToolTip(_translate("frmFEEZCrossValidation", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubPer: content of subject counter, e.g. SubPer = 0 -&gt; sub-001 OR SubPer = A -&gt; sub-AA1</span></p></body></html>"))
        self.txtDISubPer.setText(_translate("frmFEEZCrossValidation", "0"))
        self.label_26.setText(_translate("frmFEEZCrossValidation", "Length:"))
        self.txtDISubLen.setToolTip(_translate("frmFEEZCrossValidation", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen: the length of subject counter, e.g. SubLen=3 -&gt; output sub-001, sub-002</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen &gt; 1</span></p></body></html>"))
        self.label_32.setText(_translate("frmFEEZCrossValidation", "Subject"))
        self.txtDIRunPer.setToolTip(_translate("frmFEEZCrossValidation", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunPer: content of subject counter, e.g. RunPer = 0 -&gt; run-001 OR RunPer = A -&gt; run-AA1</span></p></body></html>"))
        self.txtDIRunPer.setText(_translate("frmFEEZCrossValidation", "0"))
        self.txtDIRunLen.setToolTip(_translate("frmFEEZCrossValidation", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunLen: the length of run counter, e.g. RunLen=3 -&gt; output run-001, rub-002</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">RunLen &gt; 1</span></p></body></html>"))
        self.label_28.setText(_translate("frmFEEZCrossValidation", "Perfix:"))
        self.label_27.setText(_translate("frmFEEZCrossValidation", "Length:"))
        self.label_34.setText(_translate("frmFEEZCrossValidation", "Run"))
        self.label_47.setText(_translate("frmFEEZCrossValidation", "Perfix:"))
        self.label_45.setText(_translate("frmFEEZCrossValidation", "Length:"))
        self.txtDIConPer.setText(_translate("frmFEEZCrossValidation", "0"))
        self.label_35.setText(_translate("frmFEEZCrossValidation", "Counter"))
        self.label_36.setText(_translate("frmFEEZCrossValidation", "Task"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmFEEZCrossValidation", "General"))
        self.label_4.setText(_translate("frmFEEZCrossValidation", "Training Perfix"))
        self.label_8.setText(_translate("frmFEEZCrossValidation", "Unit number for test set"))
        self.label_7.setText(_translate("frmFEEZCrossValidation", "Testing Perfix"))
        self.groupBox.setTitle(_translate("frmFEEZCrossValidation", "<Fold Level>"))
        self.cbFTask.setText(_translate("frmFEEZCrossValidation", "Task"))
        self.cbFCounter.setText(_translate("frmFEEZCrossValidation", "Counter"))
        self.groupBox_2.setTitle(_translate("frmFEEZCrossValidation", "<Subject Level>"))
        self.cbFSubject.setText(_translate("frmFEEZCrossValidation", "Subject"))
        self.radioButton.setText(_translate("frmFEEZCrossValidation", "Without Run"))
        self.rbFRun.setText(_translate("frmFEEZCrossValidation", "With Run"))
        self.txtTest.setText(_translate("frmFEEZCrossValidation", "test_fold$FOLD$"))
        self.txtTrain.setText(_translate("frmFEEZCrossValidation", "train_fold$FOLD$"))
        self.label_6.setText(_translate("frmFEEZCrossValidation", "$FOLD$ will be replaced by fold number."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmFEEZCrossValidation", "Parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmFEEZCrossValidation", "Data Files"))

