# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmFeatureAnalysisGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmFeatureAnalysis(object):
    def setupUi(self, frmFeatureAnalysis):
        frmFeatureAnalysis.setObjectName("frmFeatureAnalysis")
        frmFeatureAnalysis.resize(832, 691)
        self.tabWidget = QtWidgets.QTabWidget(frmFeatureAnalysis)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 811, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 68, 21))
        self.label_6.setObjectName("label_6")
        self.btnSSSetting = QtWidgets.QPushButton(self.tab)
        self.btnSSSetting.setGeometry(QtCore.QRect(740, 20, 51, 32))
        self.btnSSSetting.setObjectName("btnSSSetting")
        self.btnSSSpace = QtWidgets.QPushButton(self.tab)
        self.btnSSSpace.setGeometry(QtCore.QRect(740, 120, 51, 32))
        self.btnSSSpace.setObjectName("btnSSSpace")
        self.txtSSSpace = QtWidgets.QComboBox(self.tab)
        self.txtSSSpace.setGeometry(QtCore.QRect(160, 120, 571, 26))
        self.txtSSSpace.setEditable(True)
        self.txtSSSpace.setObjectName("txtSSSpace")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 141, 16))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 170, 141, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(20, 516, 781, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_23.setObjectName("label_23")
        self.btnSSRUN = QtWidgets.QPushButton(self.tab)
        self.btnSSRUN.setGeometry(QtCore.QRect(20, 470, 761, 32))
        self.btnSSRUN.setObjectName("btnSSRUN")
        self.txtSSSetting = QtWidgets.QComboBox(self.tab)
        self.txtSSSetting.setGeometry(QtCore.QRect(88, 20, 551, 26))
        self.txtSSSetting.setEditable(True)
        self.txtSSSetting.setObjectName("txtSSSetting")
        self.btnSSSettingReload = QtWidgets.QPushButton(self.tab)
        self.btnSSSettingReload.setGeometry(QtCore.QRect(650, 20, 81, 32))
        self.btnSSSettingReload.setObjectName("btnSSSettingReload")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 270, 761, 181))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.txtSSDIR = QtWidgets.QLineEdit(self.tab_9)
        self.txtSSDIR.setGeometry(QtCore.QRect(142, 26, 601, 21))
        self.txtSSDIR.setStatusTip("")
        self.txtSSDIR.setText("")
        self.txtSSDIR.setObjectName("txtSSDIR")
        self.label_4 = QtWidgets.QLabel(self.tab_9)
        self.label_4.setGeometry(QtCore.QRect(10, 26, 131, 16))
        self.label_4.setToolTip("")
        self.label_4.setStatusTip("")
        self.label_4.setProperty("toolTipDuration", -1)
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.tab_9)
        self.label_9.setGeometry(QtCore.QRect(11, 60, 131, 16))
        self.label_9.setObjectName("label_9")
        self.txtSSTask = QtWidgets.QLineEdit(self.tab_9)
        self.txtSSTask.setGeometry(QtCore.QRect(140, 60, 601, 21))
        self.txtSSTask.setStatusTip("")
        self.txtSSTask.setText("")
        self.txtSSTask.setObjectName("txtSSTask")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_12 = QtWidgets.QLabel(self.tab_8)
        self.label_12.setGeometry(QtCore.QRect(550, 20, 60, 16))
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.tab_8)
        self.label_11.setGeometry(QtCore.QRect(370, 20, 60, 21))
        self.label_11.setObjectName("label_11")
        self.txtSSSubPer = QtWidgets.QLineEdit(self.tab_8)
        self.txtSSSubPer.setGeometry(QtCore.QRect(600, 20, 80, 21))
        self.txtSSSubPer.setObjectName("txtSSSubPer")
        self.txtSSSubLen = QtWidgets.QSpinBox(self.tab_8)
        self.txtSSSubLen.setGeometry(QtCore.QRect(440, 20, 80, 24))
        self.txtSSSubLen.setMinimum(1)
        self.txtSSSubLen.setMaximum(999999999)
        self.txtSSSubLen.setSingleStep(1)
        self.txtSSSubLen.setProperty("value", 2)
        self.txtSSSubLen.setObjectName("txtSSSubLen")
        self.label_10 = QtWidgets.QLabel(self.tab_8)
        self.label_10.setGeometry(QtCore.QRect(70, 20, 71, 16))
        self.label_10.setObjectName("label_10")
        self.txtSSSubRange = QtWidgets.QLineEdit(self.tab_8)
        self.txtSSSubRange.setGeometry(QtCore.QRect(140, 20, 211, 21))
        self.txtSSSubRange.setObjectName("txtSSSubRange")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.txtSSRunLen = QtWidgets.QSpinBox(self.tab_10)
        self.txtSSRunLen.setGeometry(QtCore.QRect(440, 20, 80, 24))
        self.txtSSRunLen.setMinimum(1)
        self.txtSSRunLen.setMaximum(999999999)
        self.txtSSRunLen.setProperty("value", 2)
        self.txtSSRunLen.setObjectName("txtSSRunLen")
        self.txtSSRunPer = QtWidgets.QLineEdit(self.tab_10)
        self.txtSSRunPer.setGeometry(QtCore.QRect(600, 20, 80, 21))
        self.txtSSRunPer.setObjectName("txtSSRunPer")
        self.label_18 = QtWidgets.QLabel(self.tab_10)
        self.label_18.setGeometry(QtCore.QRect(370, 20, 60, 21))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.tab_10)
        self.label_21.setGeometry(QtCore.QRect(550, 20, 60, 16))
        self.label_21.setObjectName("label_21")
        self.txtSSRunRange = QtWidgets.QLineEdit(self.tab_10)
        self.txtSSRunRange.setGeometry(QtCore.QRect(135, 20, 211, 21))
        self.txtSSRunRange.setObjectName("txtSSRunRange")
        self.label_22 = QtWidgets.QLabel(self.tab_10)
        self.label_22.setGeometry(QtCore.QRect(60, 20, 71, 16))
        self.label_22.setObjectName("label_22")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.txtSSConLen = QtWidgets.QSpinBox(self.tab_11)
        self.txtSSConLen.setGeometry(QtCore.QRect(440, 20, 80, 24))
        self.txtSSConLen.setMaximum(100000)
        self.txtSSConLen.setSingleStep(1)
        self.txtSSConLen.setProperty("value", 2)
        self.txtSSConLen.setObjectName("txtSSConLen")
        self.label_43 = QtWidgets.QLabel(self.tab_11)
        self.label_43.setGeometry(QtCore.QRect(370, 20, 60, 21))
        self.label_43.setObjectName("label_43")
        self.label_42 = QtWidgets.QLabel(self.tab_11)
        self.label_42.setGeometry(QtCore.QRect(540, 20, 60, 16))
        self.label_42.setObjectName("label_42")
        self.txtSSConPer = QtWidgets.QLineEdit(self.tab_11)
        self.txtSSConPer.setGeometry(QtCore.QRect(590, 20, 80, 21))
        self.txtSSConPer.setObjectName("txtSSConPer")
        self.label_16 = QtWidgets.QLabel(self.tab_11)
        self.label_16.setGeometry(QtCore.QRect(80, 20, 71, 16))
        self.label_16.setObjectName("label_16")
        self.txtSSConRange = QtWidgets.QLineEdit(self.tab_11)
        self.txtSSConRange.setGeometry(QtCore.QRect(150, 20, 201, 21))
        self.txtSSConRange.setObjectName("txtSSConRange")
        self.tabWidget_2.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.cbSSInter = QtWidgets.QComboBox(self.tab_12)
        self.cbSSInter.setGeometry(QtCore.QRect(330, 20, 201, 26))
        self.cbSSInter.setObjectName("cbSSInter")
        self.label_14 = QtWidgets.QLabel(self.tab_12)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 291, 16))
        self.label_14.setObjectName("label_14")
        self.tabWidget_2.addTab(self.tab_12, "")
        self.txtSSMatFile = QtWidgets.QLineEdit(self.tab)
        self.txtSSMatFile.setGeometry(QtCore.QRect(200, 70, 531, 21))
        self.txtSSMatFile.setObjectName("txtSSMatFile")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 181, 16))
        self.label_2.setObjectName("label_2")
        self.btnSSMatFile = QtWidgets.QPushButton(self.tab)
        self.btnSSMatFile.setGeometry(QtCore.QRect(740, 70, 51, 32))
        self.btnSSMatFile.setObjectName("btnSSMatFile")
        self.txtSSOutFile = QtWidgets.QComboBox(self.tab)
        self.txtSSOutFile.setGeometry(QtCore.QRect(160, 220, 621, 26))
        self.txtSSOutFile.setEditable(True)
        self.txtSSOutFile.setObjectName("txtSSOutFile")
        self.txtSSInFile = QtWidgets.QComboBox(self.tab)
        self.txtSSInFile.setGeometry(QtCore.QRect(160, 170, 621, 26))
        self.txtSSInFile.setEditable(True)
        self.txtSSInFile.setObjectName("txtSSInFile")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btnROIWholeBrain = QtWidgets.QPushButton(self.tab_2)
        self.btnROIWholeBrain.setGeometry(QtCore.QRect(20, 30, 771, 32))
        self.btnROIWholeBrain.setObjectName("btnROIWholeBrain")
        self.btnROIProbabilistic = QtWidgets.QPushButton(self.tab_2)
        self.btnROIProbabilistic.setGeometry(QtCore.QRect(20, 80, 771, 32))
        self.btnROIProbabilistic.setObjectName("btnROIProbabilistic")
        self.btnROIAtlas = QtWidgets.QPushButton(self.tab_2)
        self.btnROIAtlas.setGeometry(QtCore.QRect(20, 130, 771, 32))
        self.btnROIAtlas.setObjectName("btnROIAtlas")
        self.btnROIManuallyDesign = QtWidgets.QPushButton(self.tab_2)
        self.btnROIManuallyDesign.setGeometry(QtCore.QRect(20, 180, 771, 32))
        self.btnROIManuallyDesign.setObjectName("btnROIManuallyDesign")
        self.btnROICombine = QtWidgets.QPushButton(self.tab_2)
        self.btnROICombine.setGeometry(QtCore.QRect(20, 230, 771, 32))
        self.btnROICombine.setObjectName("btnROICombine")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_3.setGeometry(QtCore.QRect(20, 180, 771, 271))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.txtDIDIR = QtWidgets.QLineEdit(self.tab_13)
        self.txtDIDIR.setGeometry(QtCore.QRect(162, 20, 591, 21))
        self.txtDIDIR.setStatusTip("")
        self.txtDIDIR.setText("")
        self.txtDIDIR.setObjectName("txtDIDIR")
        self.label_8 = QtWidgets.QLabel(self.tab_13)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.label_8.setToolTip("")
        self.label_8.setStatusTip("")
        self.label_8.setProperty("toolTipDuration", -1)
        self.label_8.setObjectName("label_8")
        self.label_15 = QtWidgets.QLabel(self.tab_13)
        self.label_15.setGeometry(QtCore.QRect(11, 60, 131, 16))
        self.label_15.setObjectName("label_15")
        self.txtDITask = QtWidgets.QLineEdit(self.tab_13)
        self.txtDITask.setGeometry(QtCore.QRect(160, 60, 591, 21))
        self.txtDITask.setStatusTip("")
        self.txtDITask.setText("")
        self.txtDITask.setObjectName("txtDITask")
        self.label_7 = QtWidgets.QLabel(self.tab_13)
        self.label_7.setGeometry(QtCore.QRect(11, 140, 141, 16))
        self.label_7.setObjectName("label_7")
        self.label_30 = QtWidgets.QLabel(self.tab_13)
        self.label_30.setGeometry(QtCore.QRect(11, 180, 141, 16))
        self.label_30.setObjectName("label_30")
        self.txtDIOutHDR = QtWidgets.QLineEdit(self.tab_13)
        self.txtDIOutHDR.setGeometry(QtCore.QRect(160, 140, 591, 21))
        self.txtDIOutHDR.setObjectName("txtDIOutHDR")
        self.txtDIOutDIR = QtWidgets.QLineEdit(self.tab_13)
        self.txtDIOutDIR.setGeometry(QtCore.QRect(160, 100, 531, 21))
        self.txtDIOutDIR.setObjectName("txtDIOutDIR")
        self.btnDIOutFile = QtWidgets.QPushButton(self.tab_13)
        self.btnDIOutFile.setGeometry(QtCore.QRect(700, 100, 51, 32))
        self.btnDIOutFile.setObjectName("btnDIOutFile")
        self.txtDIOutDAT = QtWidgets.QLineEdit(self.tab_13)
        self.txtDIOutDAT.setGeometry(QtCore.QRect(160, 180, 591, 21))
        self.txtDIOutDAT.setObjectName("txtDIOutDAT")
        self.label_29 = QtWidgets.QLabel(self.tab_13)
        self.label_29.setGeometry(QtCore.QRect(11, 100, 141, 16))
        self.label_29.setObjectName("label_29")
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.label_25 = QtWidgets.QLabel(self.tab_14)
        self.label_25.setGeometry(QtCore.QRect(550, 20, 60, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_14)
        self.label_26.setGeometry(QtCore.QRect(370, 20, 60, 21))
        self.label_26.setObjectName("label_26")
        self.txtDISubPer = QtWidgets.QLineEdit(self.tab_14)
        self.txtDISubPer.setGeometry(QtCore.QRect(600, 20, 80, 21))
        self.txtDISubPer.setObjectName("txtDISubPer")
        self.txtDISubLen = QtWidgets.QSpinBox(self.tab_14)
        self.txtDISubLen.setGeometry(QtCore.QRect(440, 20, 80, 24))
        self.txtDISubLen.setMinimum(1)
        self.txtDISubLen.setMaximum(999999999)
        self.txtDISubLen.setSingleStep(1)
        self.txtDISubLen.setProperty("value", 2)
        self.txtDISubLen.setObjectName("txtDISubLen")
        self.label_13 = QtWidgets.QLabel(self.tab_14)
        self.label_13.setGeometry(QtCore.QRect(60, 20, 71, 16))
        self.label_13.setObjectName("label_13")
        self.txtDISubRange = QtWidgets.QLineEdit(self.tab_14)
        self.txtDISubRange.setGeometry(QtCore.QRect(140, 20, 211, 21))
        self.txtDISubRange.setObjectName("txtDISubRange")
        self.tabWidget_3.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.txtDIRunLen = QtWidgets.QSpinBox(self.tab_15)
        self.txtDIRunLen.setGeometry(QtCore.QRect(440, 20, 80, 24))
        self.txtDIRunLen.setMinimum(1)
        self.txtDIRunLen.setMaximum(999999999)
        self.txtDIRunLen.setProperty("value", 2)
        self.txtDIRunLen.setObjectName("txtDIRunLen")
        self.txtDIRunPer = QtWidgets.QLineEdit(self.tab_15)
        self.txtDIRunPer.setGeometry(QtCore.QRect(600, 20, 80, 21))
        self.txtDIRunPer.setObjectName("txtDIRunPer")
        self.label_27 = QtWidgets.QLabel(self.tab_15)
        self.label_27.setGeometry(QtCore.QRect(370, 20, 60, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_15)
        self.label_28.setGeometry(QtCore.QRect(550, 20, 60, 16))
        self.label_28.setObjectName("label_28")
        self.txtDIRunRange = QtWidgets.QLineEdit(self.tab_15)
        self.txtDIRunRange.setGeometry(QtCore.QRect(135, 20, 211, 21))
        self.txtDIRunRange.setObjectName("txtDIRunRange")
        self.label_20 = QtWidgets.QLabel(self.tab_15)
        self.label_20.setGeometry(QtCore.QRect(60, 20, 71, 16))
        self.label_20.setObjectName("label_20")
        self.tabWidget_3.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.txtDIConLen = QtWidgets.QSpinBox(self.tab_16)
        self.txtDIConLen.setGeometry(QtCore.QRect(440, 20, 80, 24))
        self.txtDIConLen.setMaximum(100000)
        self.txtDIConLen.setSingleStep(1)
        self.txtDIConLen.setProperty("value", 2)
        self.txtDIConLen.setObjectName("txtDIConLen")
        self.label_45 = QtWidgets.QLabel(self.tab_16)
        self.label_45.setGeometry(QtCore.QRect(370, 20, 60, 21))
        self.label_45.setObjectName("label_45")
        self.label_47 = QtWidgets.QLabel(self.tab_16)
        self.label_47.setGeometry(QtCore.QRect(540, 20, 60, 16))
        self.label_47.setObjectName("label_47")
        self.txtDIConPer = QtWidgets.QLineEdit(self.tab_16)
        self.txtDIConPer.setGeometry(QtCore.QRect(590, 20, 80, 21))
        self.txtDIConPer.setObjectName("txtDIConPer")
        self.txtDIConRange = QtWidgets.QLineEdit(self.tab_16)
        self.txtDIConRange.setGeometry(QtCore.QRect(140, 20, 201, 21))
        self.txtDIConRange.setObjectName("txtDIConRange")
        self.label_17 = QtWidgets.QLabel(self.tab_16)
        self.label_17.setGeometry(QtCore.QRect(70, 20, 71, 16))
        self.label_17.setObjectName("label_17")
        self.tabWidget_3.addTab(self.tab_16, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.txtDIEventDIR = QtWidgets.QLineEdit(self.tab_19)
        self.txtDIEventDIR.setGeometry(QtCore.QRect(220, 40, 511, 21))
        self.txtDIEventDIR.setObjectName("txtDIEventDIR")
        self.label_41 = QtWidgets.QLabel(self.tab_19)
        self.label_41.setGeometry(QtCore.QRect(14, 40, 221, 16))
        self.label_41.setObjectName("label_41")
        self.label_48 = QtWidgets.QLabel(self.tab_19)
        self.label_48.setGeometry(QtCore.QRect(14, 80, 201, 16))
        self.label_48.setObjectName("label_48")
        self.txtDICondPre = QtWidgets.QLineEdit(self.tab_19)
        self.txtDICondPre.setGeometry(QtCore.QRect(220, 80, 511, 21))
        self.txtDICondPre.setObjectName("txtDICondPre")
        self.tabWidget_3.addTab(self.tab_19, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.label_36 = QtWidgets.QLabel(self.tab_18)
        self.label_36.setGeometry(QtCore.QRect(20, 23, 111, 16))
        self.label_36.setObjectName("label_36")
        self.rbDIDynamic = QtWidgets.QRadioButton(self.tab_18)
        self.rbDIDynamic.setGeometry(QtCore.QRect(100, 20, 100, 20))
        self.rbDIDynamic.setChecked(True)
        self.rbDIDynamic.setObjectName("rbDIDynamic")
        self.rbDIManual = QtWidgets.QRadioButton(self.tab_18)
        self.rbDIManual.setGeometry(QtCore.QRect(200, 20, 100, 20))
        self.rbDIManual.setObjectName("rbDIManual")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_18)
        self.tabWidget_4.setGeometry(QtCore.QRect(10, 49, 741, 181))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.label_39 = QtWidgets.QLabel(self.tab_20)
        self.label_39.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_39.setObjectName("label_39")
        self.txtDIThreshold = QtWidgets.QLineEdit(self.tab_20)
        self.txtDIThreshold.setGeometry(QtCore.QRect(120, 20, 151, 21))
        self.txtDIThreshold.setObjectName("txtDIThreshold")
        self.groupBox = QtWidgets.QGroupBox(self.tab_20)
        self.groupBox.setGeometry(QtCore.QRect(300, 0, 421, 141))
        self.groupBox.setObjectName("groupBox")
        self.btnDIDraw = QtWidgets.QPushButton(self.groupBox)
        self.btnDIDraw.setGeometry(QtCore.QRect(10, 100, 401, 32))
        self.btnDIDraw.setObjectName("btnDIDraw")
        self.cbDILegend = QtWidgets.QCheckBox(self.groupBox)
        self.cbDILegend.setGeometry(QtCore.QRect(20, 30, 121, 20))
        self.cbDILegend.setObjectName("cbDILegend")
        self.cbDIDraw = QtWidgets.QCheckBox(self.groupBox)
        self.cbDIDraw.setGeometry(QtCore.QRect(150, 30, 141, 20))
        self.cbDIDraw.setChecked(True)
        self.cbDIDraw.setObjectName("cbDIDraw")
        self.cbDIColor = QtWidgets.QCheckBox(self.groupBox)
        self.cbDIColor.setGeometry(QtCore.QRect(290, 30, 121, 20))
        self.cbDIColor.setChecked(True)
        self.cbDIColor.setObjectName("cbDIColor")
        self.cbDIReal = QtWidgets.QCheckBox(self.groupBox)
        self.cbDIReal.setGeometry(QtCore.QRect(20, 60, 81, 20))
        self.cbDIReal.setObjectName("cbDIReal")
        self.cbDINorm = QtWidgets.QCheckBox(self.groupBox)
        self.cbDINorm.setGeometry(QtCore.QRect(110, 60, 121, 20))
        self.cbDINorm.setChecked(True)
        self.cbDINorm.setObjectName("cbDINorm")
        self.cbDIClass = QtWidgets.QCheckBox(self.groupBox)
        self.cbDIClass.setGeometry(QtCore.QRect(240, 60, 101, 20))
        self.cbDIClass.setChecked(True)
        self.cbDIClass.setObjectName("cbDIClass")
        self.cbDIRest = QtWidgets.QCheckBox(self.groupBox)
        self.cbDIRest.setGeometry(QtCore.QRect(340, 60, 81, 20))
        self.cbDIRest.setChecked(True)
        self.cbDIRest.setObjectName("cbDIRest")
        self.tabWidget_4.addTab(self.tab_20, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.txtDILabels = QtWidgets.QLineEdit(self.tab_21)
        self.txtDILabels.setGeometry(QtCore.QRect(100, 20, 561, 21))
        self.txtDILabels.setText("")
        self.txtDILabels.setObjectName("txtDILabels")
        self.btnDILabels = QtWidgets.QPushButton(self.tab_21)
        self.btnDILabels.setGeometry(QtCore.QRect(670, 20, 51, 32))
        self.btnDILabels.setObjectName("btnDILabels")
        self.label_37 = QtWidgets.QLabel(self.tab_21)
        self.label_37.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_21)
        self.label_38.setGeometry(QtCore.QRect(10, 90, 721, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_38.setObjectName("label_38")
        self.tabWidget_4.addTab(self.tab_21, "")
        self.cbDIRemoveRest = QtWidgets.QCheckBox(self.tab_18)
        self.cbDIRemoveRest.setGeometry(QtCore.QRect(530, 20, 221, 20))
        self.cbDIRemoveRest.setChecked(False)
        self.cbDIRemoveRest.setObjectName("cbDIRemoveRest")
        self.tabWidget_3.addTab(self.tab_18, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.cbDIDataID = QtWidgets.QCheckBox(self.tab_17)
        self.cbDIDataID.setGeometry(QtCore.QRect(20, 20, 71, 20))
        self.cbDIDataID.setChecked(True)
        self.cbDIDataID.setObjectName("cbDIDataID")
        self.cbDILabelID = QtWidgets.QCheckBox(self.tab_17)
        self.cbDILabelID.setGeometry(QtCore.QRect(20, 60, 181, 20))
        self.cbDILabelID.setChecked(True)
        self.cbDILabelID.setObjectName("cbDILabelID")
        self.cbDImLabelID = QtWidgets.QCheckBox(self.tab_17)
        self.cbDImLabelID.setGeometry(QtCore.QRect(20, 100, 161, 20))
        self.cbDImLabelID.setChecked(True)
        self.cbDImLabelID.setObjectName("cbDImLabelID")
        self.cbDICoID = QtWidgets.QCheckBox(self.tab_17)
        self.cbDICoID.setGeometry(QtCore.QRect(20, 140, 151, 20))
        self.cbDICoID.setChecked(True)
        self.cbDICoID.setObjectName("cbDICoID")
        self.cbDIDM = QtWidgets.QCheckBox(self.tab_17)
        self.cbDIDM.setGeometry(QtCore.QRect(20, 180, 151, 20))
        self.cbDIDM.setChecked(True)
        self.cbDIDM.setObjectName("cbDIDM")
        self.txtDIDataID = QtWidgets.QLineEdit(self.tab_17)
        self.txtDIDataID.setGeometry(QtCore.QRect(170, 20, 113, 21))
        self.txtDIDataID.setObjectName("txtDIDataID")
        self.txtDILabelID = QtWidgets.QLineEdit(self.tab_17)
        self.txtDILabelID.setGeometry(QtCore.QRect(170, 60, 113, 21))
        self.txtDILabelID.setObjectName("txtDILabelID")
        self.txtDICoID = QtWidgets.QLineEdit(self.tab_17)
        self.txtDICoID.setGeometry(QtCore.QRect(170, 140, 113, 21))
        self.txtDICoID.setObjectName("txtDICoID")
        self.txtDIDMID = QtWidgets.QLineEdit(self.tab_17)
        self.txtDIDMID.setGeometry(QtCore.QRect(170, 180, 113, 21))
        self.txtDIDMID.setObjectName("txtDIDMID")
        self.txtDImLabelID = QtWidgets.QLineEdit(self.tab_17)
        self.txtDImLabelID.setGeometry(QtCore.QRect(170, 100, 113, 21))
        self.txtDImLabelID.setObjectName("txtDImLabelID")
        self.txtDISubjectID = QtWidgets.QLineEdit(self.tab_17)
        self.txtDISubjectID.setGeometry(QtCore.QRect(400, 20, 113, 21))
        self.txtDISubjectID.setObjectName("txtDISubjectID")
        self.cbDISubjectID = QtWidgets.QCheckBox(self.tab_17)
        self.cbDISubjectID.setGeometry(QtCore.QRect(300, 20, 101, 20))
        self.cbDISubjectID.setChecked(True)
        self.cbDISubjectID.setObjectName("cbDISubjectID")
        self.txtDITaskID = QtWidgets.QLineEdit(self.tab_17)
        self.txtDITaskID.setGeometry(QtCore.QRect(400, 60, 113, 21))
        self.txtDITaskID.setObjectName("txtDITaskID")
        self.cbDITaskID = QtWidgets.QCheckBox(self.tab_17)
        self.cbDITaskID.setGeometry(QtCore.QRect(300, 60, 101, 20))
        self.cbDITaskID.setChecked(True)
        self.cbDITaskID.setObjectName("cbDITaskID")
        self.cbDIRunID = QtWidgets.QCheckBox(self.tab_17)
        self.cbDIRunID.setGeometry(QtCore.QRect(300, 100, 101, 20))
        self.cbDIRunID.setChecked(True)
        self.cbDIRunID.setObjectName("cbDIRunID")
        self.txtDIRunID = QtWidgets.QLineEdit(self.tab_17)
        self.txtDIRunID.setGeometry(QtCore.QRect(400, 100, 113, 21))
        self.txtDIRunID.setObjectName("txtDIRunID")
        self.cbDICounterID = QtWidgets.QCheckBox(self.tab_17)
        self.cbDICounterID.setGeometry(QtCore.QRect(300, 140, 101, 20))
        self.cbDICounterID.setChecked(True)
        self.cbDICounterID.setObjectName("cbDICounterID")
        self.txtDICounterID = QtWidgets.QLineEdit(self.tab_17)
        self.txtDICounterID.setGeometry(QtCore.QRect(400, 140, 113, 21))
        self.txtDICounterID.setObjectName("txtDICounterID")
        self.cbDICondID = QtWidgets.QCheckBox(self.tab_17)
        self.cbDICondID.setGeometry(QtCore.QRect(300, 180, 101, 20))
        self.cbDICondID.setChecked(True)
        self.cbDICondID.setObjectName("cbDICondID")
        self.txtDICoundID = QtWidgets.QLineEdit(self.tab_17)
        self.txtDICoundID.setGeometry(QtCore.QRect(400, 180, 113, 21))
        self.txtDICoundID.setObjectName("txtDICoundID")
        self.txtDINScanID = QtWidgets.QLineEdit(self.tab_17)
        self.txtDINScanID.setGeometry(QtCore.QRect(630, 20, 113, 21))
        self.txtDINScanID.setObjectName("txtDINScanID")
        self.cbDINScanID = QtWidgets.QCheckBox(self.tab_17)
        self.cbDINScanID.setGeometry(QtCore.QRect(530, 20, 101, 20))
        self.cbDINScanID.setChecked(True)
        self.cbDINScanID.setObjectName("cbDINScanID")
        self.tabWidget_3.addTab(self.tab_17, "")
        self.txtDISetting = QtWidgets.QComboBox(self.tab_3)
        self.txtDISetting.setGeometry(QtCore.QRect(88, 20, 551, 26))
        self.txtDISetting.setEditable(True)
        self.txtDISetting.setObjectName("txtDISetting")
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(20, 20, 68, 21))
        self.label_31.setObjectName("label_31")
        self.btnDISetting = QtWidgets.QPushButton(self.tab_3)
        self.btnDISetting.setGeometry(QtCore.QRect(740, 20, 51, 32))
        self.btnDISetting.setObjectName("btnDISetting")
        self.btnDISettingReload = QtWidgets.QPushButton(self.tab_3)
        self.btnDISettingReload.setGeometry(QtCore.QRect(650, 20, 81, 32))
        self.btnDISettingReload.setObjectName("btnDISettingReload")
        self.txtDIInFile = QtWidgets.QComboBox(self.tab_3)
        self.txtDIInFile.setGeometry(QtCore.QRect(160, 60, 621, 26))
        self.txtDIInFile.setEditable(True)
        self.txtDIInFile.setObjectName("txtDIInFile")
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(20, 60, 141, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(20, 140, 141, 16))
        self.label_33.setObjectName("label_33")
        self.btnDIROIFile = QtWidgets.QPushButton(self.tab_3)
        self.btnDIROIFile.setGeometry(QtCore.QRect(730, 140, 51, 32))
        self.btnDIROIFile.setObjectName("btnDIROIFile")
        self.txtDIROIFile = QtWidgets.QLineEdit(self.tab_3)
        self.txtDIROIFile.setGeometry(QtCore.QRect(160, 140, 561, 21))
        self.txtDIROIFile.setText("")
        self.txtDIROIFile.setObjectName("txtDIROIFile")
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(20, 520, 771, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_34.setObjectName("label_34")
        self.btnDIRUN = QtWidgets.QPushButton(self.tab_3)
        self.btnDIRUN.setGeometry(QtCore.QRect(20, 470, 771, 32))
        self.btnDIRUN.setObjectName("btnDIRUN")
        self.txtDIDM = QtWidgets.QComboBox(self.tab_3)
        self.txtDIDM.setGeometry(QtCore.QRect(160, 100, 621, 26))
        self.txtDIDM.setEditable(True)
        self.txtDIDM.setObjectName("txtDIDM")
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setGeometry(QtCore.QRect(20, 100, 141, 16))
        self.label_35.setObjectName("label_35")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_40 = QtWidgets.QLabel(self.tab_7)
        self.label_40.setGeometry(QtCore.QRect(20, 20, 181, 16))
        self.label_40.setObjectName("label_40")
        self.cbFEU = QtWidgets.QComboBox(self.tab_7)
        self.cbFEU.setGeometry(QtCore.QRect(210, 20, 581, 26))
        self.cbFEU.setObjectName("cbFEU")
        self.btnFEURun = QtWidgets.QPushButton(self.tab_7)
        self.btnFEURun.setGeometry(QtCore.QRect(12, 70, 781, 32))
        self.btnFEURun.setObjectName("btnFEURun")
        self.btnFECross = QtWidgets.QPushButton(self.tab_7)
        self.btnFECross.setGeometry(QtCore.QRect(12, 170, 781, 32))
        self.btnFECross.setObjectName("btnFECross")
        self.label_50 = QtWidgets.QLabel(self.tab_7)
        self.label_50.setGeometry(QtCore.QRect(20, 220, 181, 16))
        self.label_50.setObjectName("label_50")
        self.cbFES = QtWidgets.QComboBox(self.tab_7)
        self.cbFES.setGeometry(QtCore.QRect(210, 220, 581, 26))
        self.cbFES.setObjectName("cbFES")
        self.btnFESRun = QtWidgets.QPushButton(self.tab_7)
        self.btnFESRun.setGeometry(QtCore.QRect(12, 270, 781, 32))
        self.btnFESRun.setObjectName("btnFESRun")
        self.btnFECrossEzData = QtWidgets.QPushButton(self.tab_7)
        self.btnFECrossEzData.setGeometry(QtCore.QRect(12, 120, 781, 32))
        self.btnFECrossEzData.setObjectName("btnFECrossEzData")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_49 = QtWidgets.QLabel(self.tab_4)
        self.label_49.setGeometry(QtCore.QRect(18, 20, 91, 16))
        self.label_49.setObjectName("label_49")
        self.cbFA = QtWidgets.QComboBox(self.tab_4)
        self.cbFA.setGeometry(QtCore.QRect(108, 20, 681, 26))
        self.cbFA.setObjectName("cbFA")
        self.btnFARun = QtWidgets.QPushButton(self.tab_4)
        self.btnFARun.setGeometry(QtCore.QRect(10, 80, 781, 32))
        self.btnFARun.setObjectName("btnFARun")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.label_19.setObjectName("label_19")
        self.label_24 = QtWidgets.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(19, 80, 121, 16))
        self.label_24.setObjectName("label_24")
        self.txtFSLDIR = QtWidgets.QLineEdit(self.tab_5)
        self.txtFSLDIR.setGeometry(QtCore.QRect(139, 30, 651, 21))
        self.txtFSLDIR.setToolTip("")
        self.txtFSLDIR.setStatusTip("")
        self.txtFSLDIR.setProperty("toolTipDuration", -1)
        self.txtFSLDIR.setObjectName("txtFSLDIR")
        self.txtFlirt = QtWidgets.QLineEdit(self.tab_5)
        self.txtFlirt.setGeometry(QtCore.QRect(139, 80, 651, 21))
        self.txtFlirt.setToolTip("")
        self.txtFlirt.setStatusTip("")
        self.txtFlirt.setProperty("toolTipDuration", -1)
        self.txtFlirt.setObjectName("txtFlirt")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.btnDICombineData = QtWidgets.QPushButton(self.tab_6)
        self.btnDICombineData.setGeometry(QtCore.QRect(20, 170, 761, 32))
        self.btnDICombineData.setObjectName("btnDICombineData")
        self.btnDIRemoveRest = QtWidgets.QPushButton(self.tab_6)
        self.btnDIRemoveRest.setGeometry(QtCore.QRect(20, 220, 761, 32))
        self.btnDIRemoveRest.setObjectName("btnDIRemoveRest")
        self.btnDIRemoveRest2 = QtWidgets.QPushButton(self.tab_6)
        self.btnDIRemoveRest2.setGeometry(QtCore.QRect(20, 270, 761, 32))
        self.btnDIRemoveRest2.setObjectName("btnDIRemoveRest2")
        self.btnSSMatCreator = QtWidgets.QPushButton(self.tab_6)
        self.btnSSMatCreator.setGeometry(QtCore.QRect(20, 70, 761, 32))
        self.btnSSMatCreator.setObjectName("btnSSMatCreator")
        self.btnImageInfo = QtWidgets.QPushButton(self.tab_6)
        self.btnImageInfo.setGeometry(QtCore.QRect(20, 20, 761, 32))
        self.btnImageInfo.setObjectName("btnImageInfo")
        self.btnDIConvertEzData = QtWidgets.QPushButton(self.tab_6)
        self.btnDIConvertEzData.setGeometry(QtCore.QRect(20, 120, 761, 32))
        self.btnDIConvertEzData.setObjectName("btnDIConvertEzData")
        self.tabWidget.addTab(self.tab_6, "")
        self.btnClose = QtWidgets.QPushButton(frmFeatureAnalysis)
        self.btnClose.setGeometry(QtCore.QRect(10, 640, 811, 32))
        self.btnClose.setObjectName("btnClose")

        self.retranslateUi(frmFeatureAnalysis)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(frmFeatureAnalysis)
        frmFeatureAnalysis.setTabOrder(self.tabWidget, self.txtSSSetting)
        frmFeatureAnalysis.setTabOrder(self.txtSSSetting, self.btnSSSettingReload)
        frmFeatureAnalysis.setTabOrder(self.btnSSSettingReload, self.btnSSSetting)
        frmFeatureAnalysis.setTabOrder(self.btnSSSetting, self.txtSSMatFile)
        frmFeatureAnalysis.setTabOrder(self.txtSSMatFile, self.btnSSMatFile)
        frmFeatureAnalysis.setTabOrder(self.btnSSMatFile, self.txtSSSpace)
        frmFeatureAnalysis.setTabOrder(self.txtSSSpace, self.btnSSSpace)
        frmFeatureAnalysis.setTabOrder(self.btnSSSpace, self.tabWidget_2)
        frmFeatureAnalysis.setTabOrder(self.tabWidget_2, self.txtSSDIR)
        frmFeatureAnalysis.setTabOrder(self.txtSSDIR, self.txtSSTask)
        frmFeatureAnalysis.setTabOrder(self.txtSSTask, self.txtSSSubLen)
        frmFeatureAnalysis.setTabOrder(self.txtSSSubLen, self.txtSSSubPer)
        frmFeatureAnalysis.setTabOrder(self.txtSSSubPer, self.txtSSRunLen)
        frmFeatureAnalysis.setTabOrder(self.txtSSRunLen, self.txtSSRunPer)
        frmFeatureAnalysis.setTabOrder(self.txtSSRunPer, self.txtSSConLen)
        frmFeatureAnalysis.setTabOrder(self.txtSSConLen, self.txtSSConPer)
        frmFeatureAnalysis.setTabOrder(self.txtSSConPer, self.btnSSRUN)
        frmFeatureAnalysis.setTabOrder(self.btnSSRUN, self.txtFSLDIR)
        frmFeatureAnalysis.setTabOrder(self.txtFSLDIR, self.txtFlirt)
        frmFeatureAnalysis.setTabOrder(self.txtFlirt, self.btnClose)
        frmFeatureAnalysis.setTabOrder(self.btnClose, self.btnROIWholeBrain)
        frmFeatureAnalysis.setTabOrder(self.btnROIWholeBrain, self.btnROIProbabilistic)
        frmFeatureAnalysis.setTabOrder(self.btnROIProbabilistic, self.btnROIAtlas)
        frmFeatureAnalysis.setTabOrder(self.btnROIAtlas, self.btnROIManuallyDesign)

    def retranslateUi(self, frmFeatureAnalysis):
        _translate = QtCore.QCoreApplication.translate
        frmFeatureAnalysis.setWindowTitle(_translate("frmFeatureAnalysis", "Feature Analysis"))
        self.label_6.setText(_translate("frmFeatureAnalysis", "Setting:"))
        self.btnSSSetting.setText(_translate("frmFeatureAnalysis", "..."))
        self.btnSSSpace.setText(_translate("frmFeatureAnalysis", "..."))
        self.label_5.setText(_translate("frmFeatureAnalysis", "Standard Space"))
        self.label.setText(_translate("frmFeatureAnalysis", "Input File Name"))
        self.label_3.setText(_translate("frmFeatureAnalysis", "Ouput File Name"))
        self.label_23.setText(_translate("frmFeatureAnalysis", "$MAINDIR$, $SUB$, $TASK$, $RUN$, $COUNT$ will be replaced by the preprocessing parameters.\n"
"It\'s case sensitive."))
        self.btnSSRUN.setText(_translate("frmFeatureAnalysis", "Registration"))
        self.btnSSSettingReload.setText(_translate("frmFeatureAnalysis", "Reload"))
        self.txtSSDIR.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt;\">mainDIR: main folder that is included all dataset files, i.e. support BIDS format: </span><a href=\"https://www.nature.com/articles/sdata201644\"><span style=\" font-size:18pt; text-decoration: underline; color:#0000ff;\">https://www.nature.com/articles/sdata201644</span></a></p></body></html>"))
        self.label_4.setText(_translate("frmFeatureAnalysis", "Main Directory:"))
        self.label_4.setProperty("setToolTip", _translate("frmFeatureAnalysis", "Please enter the main directory of the fMRI dataset. Format of directory must be based on BIDS structure."))
        self.label_9.setText(_translate("frmFeatureAnalysis", "Task Name:"))
        self.txtSSTask.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt;\">mainDIR: main folder that is included all dataset files, i.e. support BIDS format: </span><a href=\"https://www.nature.com/articles/sdata201644\"><span style=\" font-size:18pt; text-decoration: underline; color:#0000ff;\">https://www.nature.com/articles/sdata201644</span></a></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("frmFeatureAnalysis", "General"))
        self.label_12.setText(_translate("frmFeatureAnalysis", "Perfix:"))
        self.label_11.setText(_translate("frmFeatureAnalysis", "Length:"))
        self.txtSSSubPer.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubPer: content of subject counter, e.g. SubPer = 0 -&gt; sub-001 OR SubPer = A -&gt; sub-AA1</span></p></body></html>"))
        self.txtSSSubPer.setText(_translate("frmFeatureAnalysis", "0"))
        self.txtSSSubLen.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen: the length of subject counter, e.g. SubLen=3 -&gt; output sub-001, sub-002</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen &gt; 1</span></p></body></html>"))
        self.label_10.setText(_translate("frmFeatureAnalysis", "Range:"))
        self.txtSSSubRange.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubRange: a unique range of integers, i.e. Range=[1, 4-8, 10, 12-14]</span></p></body></html>"))
        self.txtSSSubRange.setText(_translate("frmFeatureAnalysis", "[1-1]"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("frmFeatureAnalysis", "Subjects"))
        self.txtSSRunLen.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunLen: the length of run counter, e.g. RunLen=3 -&gt; output run-001, rub-002</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">RunLen &gt; 1</span></p></body></html>"))
        self.txtSSRunPer.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunPer: content of subject counter, e.g. RunPer = 0 -&gt; run-001 OR RunPer = A -&gt; run-AA1</span></p></body></html>"))
        self.txtSSRunPer.setText(_translate("frmFeatureAnalysis", "0"))
        self.label_18.setText(_translate("frmFeatureAnalysis", "Length:"))
        self.label_21.setText(_translate("frmFeatureAnalysis", "Perfix:"))
        self.txtSSRunRange.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunRange: sequence of ranges, i.e. If all 12 subjects have runs from 2 to 5 then Range=[12*2-5]; If 3 subjects have runs from 1 to 4 and 2 subjects have runs from 5 to 7 then Range=[3*1-4, 2*5-7]</span></p></body></html>"))
        self.txtSSRunRange.setText(_translate("frmFeatureAnalysis", "[1*1-1]"))
        self.label_22.setText(_translate("frmFeatureAnalysis", "Ranges:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("frmFeatureAnalysis", "Run"))
        self.label_43.setText(_translate("frmFeatureAnalysis", "Length:"))
        self.label_42.setText(_translate("frmFeatureAnalysis", "Perfix:"))
        self.txtSSConPer.setText(_translate("frmFeatureAnalysis", "0"))
        self.label_16.setText(_translate("frmFeatureAnalysis", "Ranges:"))
        self.txtSSConRange.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">CounterRange: sequence of ranges, i.e. If all 12 subjects have runs from 2 to 5 then Range=[12*2-5]; If 3 subjects have runs from 1 to 4 and 2 subjects have runs from 5 to 7 then Range=[3*1-4, 2*5-7]</span></p></body></html>"))
        self.txtSSConRange.setText(_translate("frmFeatureAnalysis", "[1*1-1]"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("frmFeatureAnalysis", "Counter"))
        self.label_14.setText(_translate("frmFeatureAnalysis", "Final Interpolation Method (Reslice Only)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_12), _translate("frmFeatureAnalysis", "Interpolation"))
        self.txtSSMatFile.setText(_translate("frmFeatureAnalysis", "$MAINDIR$/sub-$SUB$/func/sub-$SUB$_task-$TASK$_run-$RUN$_analyze.feat/reg/example_func2standard.mat"))
        self.label_2.setText(_translate("frmFeatureAnalysis", "Tranformation (mat) File"))
        self.btnSSMatFile.setText(_translate("frmFeatureAnalysis", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmFeatureAnalysis", "Standard Space"))
        self.btnROIWholeBrain.setText(_translate("frmFeatureAnalysis", "Whole Brain"))
        self.btnROIProbabilistic.setText(_translate("frmFeatureAnalysis", "Probabilistic ROI"))
        self.btnROIAtlas.setText(_translate("frmFeatureAnalysis", "Atlas Based ROI"))
        self.btnROIManuallyDesign.setText(_translate("frmFeatureAnalysis", "Design ROI Manually"))
        self.btnROICombine.setText(_translate("frmFeatureAnalysis", "Combine ROIs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmFeatureAnalysis", "ROI"))
        self.txtDIDIR.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt;\">mainDIR: main folder that is included all dataset files, i.e. support BIDS format: </span><a href=\"https://www.nature.com/articles/sdata201644\"><span style=\" font-size:18pt; text-decoration: underline; color:#0000ff;\">https://www.nature.com/articles/sdata201644</span></a></p></body></html>"))
        self.label_8.setText(_translate("frmFeatureAnalysis", "Main Directory:"))
        self.label_8.setProperty("setToolTip", _translate("frmFeatureAnalysis", "Please enter the main directory of the fMRI dataset. Format of directory must be based on BIDS structure."))
        self.label_15.setText(_translate("frmFeatureAnalysis", "Task Name:"))
        self.txtDITask.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt;\">mainDIR: main folder that is included all dataset files, i.e. support BIDS format: </span><a href=\"https://www.nature.com/articles/sdata201644\"><span style=\" font-size:18pt; text-decoration: underline; color:#0000ff;\">https://www.nature.com/articles/sdata201644</span></a></p></body></html>"))
        self.label_7.setText(_translate("frmFeatureAnalysis", "Ouput Header:"))
        self.label_30.setText(_translate("frmFeatureAnalysis", "Ouput Data:"))
        self.txtDIOutHDR.setText(_translate("frmFeatureAnalysis", "data-$TASK$.ezdata"))
        self.txtDIOutDIR.setText(_translate("frmFeatureAnalysis", "$MAINDIR$/Integration"))
        self.btnDIOutFile.setText(_translate("frmFeatureAnalysis", "..."))
        self.txtDIOutDAT.setText(_translate("frmFeatureAnalysis", "data-$TASK$_sub-$SUB$_con-$COUNT$_run-$RUN$.ezmat"))
        self.label_29.setText(_translate("frmFeatureAnalysis", "Ouput Directory:"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("frmFeatureAnalysis", "General"))
        self.label_25.setText(_translate("frmFeatureAnalysis", "Perfix:"))
        self.label_26.setText(_translate("frmFeatureAnalysis", "Length:"))
        self.txtDISubPer.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubPer: content of subject counter, e.g. SubPer = 0 -&gt; sub-001 OR SubPer = A -&gt; sub-AA1</span></p></body></html>"))
        self.txtDISubPer.setText(_translate("frmFeatureAnalysis", "0"))
        self.txtDISubLen.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen: the length of subject counter, e.g. SubLen=3 -&gt; output sub-001, sub-002</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen &gt; 1</span></p></body></html>"))
        self.label_13.setText(_translate("frmFeatureAnalysis", "Range:"))
        self.txtDISubRange.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubRange: a unique range of integers, i.e. Range=[1, 4-8, 10, 12-14]</span></p></body></html>"))
        self.txtDISubRange.setText(_translate("frmFeatureAnalysis", "[1-1]"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), _translate("frmFeatureAnalysis", "Subjects"))
        self.txtDIRunLen.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunLen: the length of run counter, e.g. RunLen=3 -&gt; output run-001, rub-002</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">RunLen &gt; 1</span></p></body></html>"))
        self.txtDIRunPer.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunPer: content of subject counter, e.g. RunPer = 0 -&gt; run-001 OR RunPer = A -&gt; run-AA1</span></p></body></html>"))
        self.txtDIRunPer.setText(_translate("frmFeatureAnalysis", "0"))
        self.label_27.setText(_translate("frmFeatureAnalysis", "Length:"))
        self.label_28.setText(_translate("frmFeatureAnalysis", "Perfix:"))
        self.txtDIRunRange.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunRange: sequence of ranges, i.e. If all 12 subjects have runs from 2 to 5 then Range=[12*2-5]; If 3 subjects have runs from 1 to 4 and 2 subjects have runs from 5 to 7 then Range=[3*1-4, 2*5-7]</span></p></body></html>"))
        self.txtDIRunRange.setText(_translate("frmFeatureAnalysis", "[1*1-1]"))
        self.label_20.setText(_translate("frmFeatureAnalysis", "Ranges:"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_15), _translate("frmFeatureAnalysis", "Run"))
        self.label_45.setText(_translate("frmFeatureAnalysis", "Length:"))
        self.label_47.setText(_translate("frmFeatureAnalysis", "Perfix:"))
        self.txtDIConPer.setText(_translate("frmFeatureAnalysis", "0"))
        self.txtDIConRange.setToolTip(_translate("frmFeatureAnalysis", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">CounterRange: sequence of ranges, i.e. If all 12 subjects have runs from 2 to 5 then Range=[12*2-5]; If 3 subjects have runs from 1 to 4 and 2 subjects have runs from 5 to 7 then Range=[3*1-4, 2*5-7]</span></p></body></html>"))
        self.txtDIConRange.setText(_translate("frmFeatureAnalysis", "[1*1-1]"))
        self.label_17.setText(_translate("frmFeatureAnalysis", "Ranges:"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_16), _translate("frmFeatureAnalysis", "Counter"))
        self.txtDIEventDIR.setText(_translate("frmFeatureAnalysis", "$MAINDIR$/sub-$SUB$/func/sub-$SUB$_task-$TASK$_run-$RUN$_events/"))
        self.label_41.setText(_translate("frmFeatureAnalysis", "Generated Event Folders:"))
        self.label_48.setText(_translate("frmFeatureAnalysis", "Condition Prefix:"))
        self.txtDICondPre.setText(_translate("frmFeatureAnalysis", "cond"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_19), _translate("frmFeatureAnalysis", "Condition"))
        self.label_36.setText(_translate("frmFeatureAnalysis", "Method"))
        self.rbDIDynamic.setText(_translate("frmFeatureAnalysis", "Dynamic"))
        self.rbDIManual.setText(_translate("frmFeatureAnalysis", "Manual"))
        self.label_39.setText(_translate("frmFeatureAnalysis", "Threshold"))
        self.txtDIThreshold.setText(_translate("frmFeatureAnalysis", "0.1"))
        self.groupBox.setTitle(_translate("frmFeatureAnalysis", "<Draw Timing>"))
        self.btnDIDraw.setText(_translate("frmFeatureAnalysis", "Draw"))
        self.cbDILegend.setText(_translate("frmFeatureAnalysis", "Legend"))
        self.cbDIDraw.setText(_translate("frmFeatureAnalysis", "Multi-Figure"))
        self.cbDIColor.setText(_translate("frmFeatureAnalysis", "Multi-Color"))
        self.cbDIReal.setText(_translate("frmFeatureAnalysis", "Real"))
        self.cbDINorm.setText(_translate("frmFeatureAnalysis", "Normalized"))
        self.cbDIClass.setText(_translate("frmFeatureAnalysis", "Class"))
        self.cbDIRest.setText(_translate("frmFeatureAnalysis", "Rest "))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_20), _translate("frmFeatureAnalysis", "Dynamic"))
        self.btnDILabels.setText(_translate("frmFeatureAnalysis", "..."))
        self.label_37.setText(_translate("frmFeatureAnalysis", "Labels"))
        self.label_38.setText(_translate("frmFeatureAnalysis", "$MAINDIR$, $SUB$, $TASK$, $RUN$, $COUNT$ will be replaced by the preprocessing parameters. It\'s case sensitive.\n"
"Labels must be a text file for each fMRI image, i.e. each line is the class label of its corresponding timepoint:\n"
"E.g. Line 1 represents the class label of the first timepoint. "))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_21), _translate("frmFeatureAnalysis", "Manual"))
        self.cbDIRemoveRest.setText(_translate("frmFeatureAnalysis", "Remove Rest Scans (Class = 0)"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_18), _translate("frmFeatureAnalysis", "Labels"))
        self.cbDIDataID.setText(_translate("frmFeatureAnalysis", "Data"))
        self.cbDILabelID.setText(_translate("frmFeatureAnalysis", "Label"))
        self.cbDImLabelID.setText(_translate("frmFeatureAnalysis", "Label (matrix)"))
        self.cbDICoID.setText(_translate("frmFeatureAnalysis", "Coordinate"))
        self.cbDIDM.setText(_translate("frmFeatureAnalysis", "Design Matrix"))
        self.txtDIDataID.setText(_translate("frmFeatureAnalysis", "data"))
        self.txtDILabelID.setText(_translate("frmFeatureAnalysis", "label"))
        self.txtDICoID.setText(_translate("frmFeatureAnalysis", "coordinate"))
        self.txtDIDMID.setText(_translate("frmFeatureAnalysis", "design"))
        self.txtDImLabelID.setText(_translate("frmFeatureAnalysis", "mlabel"))
        self.txtDISubjectID.setText(_translate("frmFeatureAnalysis", "subject"))
        self.cbDISubjectID.setText(_translate("frmFeatureAnalysis", "Subject"))
        self.txtDITaskID.setText(_translate("frmFeatureAnalysis", "task"))
        self.cbDITaskID.setText(_translate("frmFeatureAnalysis", "Task"))
        self.cbDIRunID.setText(_translate("frmFeatureAnalysis", "Run"))
        self.txtDIRunID.setText(_translate("frmFeatureAnalysis", "run"))
        self.cbDICounterID.setText(_translate("frmFeatureAnalysis", "Counter"))
        self.txtDICounterID.setText(_translate("frmFeatureAnalysis", "counter"))
        self.cbDICondID.setText(_translate("frmFeatureAnalysis", "Condition"))
        self.txtDICoundID.setText(_translate("frmFeatureAnalysis", "condition"))
        self.txtDINScanID.setText(_translate("frmFeatureAnalysis", "nscan"))
        self.cbDINScanID.setText(_translate("frmFeatureAnalysis", "NScan"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_17), _translate("frmFeatureAnalysis", "Options"))
        self.label_31.setText(_translate("frmFeatureAnalysis", "Setting:"))
        self.btnDISetting.setText(_translate("frmFeatureAnalysis", "..."))
        self.btnDISettingReload.setText(_translate("frmFeatureAnalysis", "Reload"))
        self.label_32.setText(_translate("frmFeatureAnalysis", "Data File Name"))
        self.label_33.setText(_translate("frmFeatureAnalysis", "ROI File Name"))
        self.btnDIROIFile.setText(_translate("frmFeatureAnalysis", "..."))
        self.label_34.setText(_translate("frmFeatureAnalysis", "$MAINDIR$, $SUB$, $TASK$, $RUN$, $COUNT$ will be replaced by the preprocessing parameters.\n"
"It\'s case sensitive."))
        self.btnDIRUN.setText(_translate("frmFeatureAnalysis", "Integration"))
        self.label_35.setText(_translate("frmFeatureAnalysis", "Design Matrix"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmFeatureAnalysis", "Integration"))
        self.label_40.setText(_translate("frmFeatureAnalysis", "Unsupervised Method"))
        self.btnFEURun.setText(_translate("frmFeatureAnalysis", "Run"))
        self.btnFECross.setText(_translate("frmFeatureAnalysis", "MatLab: Cross Validation"))
        self.label_50.setText(_translate("frmFeatureAnalysis", "Supervised Method"))
        self.btnFESRun.setText(_translate("frmFeatureAnalysis", "Run"))
        self.btnFECrossEzData.setText(_translate("frmFeatureAnalysis", "EasyData: Cross Validation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("frmFeatureAnalysis", "Feature Engineering"))
        self.label_49.setText(_translate("frmFeatureAnalysis", "Method"))
        self.btnFARun.setText(_translate("frmFeatureAnalysis", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmFeatureAnalysis", "Functional Alignment"))
        self.label_19.setText(_translate("frmFeatureAnalysis", "$FSLDIR:"))
        self.label_24.setText(_translate("frmFeatureAnalysis", "flirt cmd:"))
        self.txtFlirt.setText(_translate("frmFeatureAnalysis", "/bin/flirt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmFeatureAnalysis", "System"))
        self.btnDICombineData.setText(_translate("frmFeatureAnalysis", "MatLab: Combine Datasets"))
        self.btnDIRemoveRest.setText(_translate("frmFeatureAnalysis", "MatLab: Remove Rest Scans (before cross validation)"))
        self.btnDIRemoveRest2.setText(_translate("frmFeatureAnalysis", "MatLab: Remove Rest Scans (after cross validation)"))
        self.btnSSMatCreator.setText(_translate("frmFeatureAnalysis", "Create Transformation Matrix"))
        self.btnImageInfo.setText(_translate("frmFeatureAnalysis", "Image Information"))
        self.btnDIConvertEzData.setText(_translate("frmFeatureAnalysis", "Convert EasyData to MatLab"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("frmFeatureAnalysis", "Tools"))
        self.btnClose.setText(_translate("frmFeatureAnalysis", "Close"))

