# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmFECNNGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmFECNN(object):
    def setupUi(self, frmFECNN):
        frmFECNN.setObjectName("frmFECNN")
        frmFECNN.resize(758, 691)
        self.btnInFile = QtWidgets.QPushButton(frmFECNN)
        self.btnInFile.setGeometry(QtCore.QRect(690, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmFECNN)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 131, 16))
        self.label_33.setObjectName("label_33")
        self.btnOutFile = QtWidgets.QPushButton(frmFECNN)
        self.btnOutFile.setGeometry(QtCore.QRect(690, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.txtInFile = QtWidgets.QLineEdit(frmFECNN)
        self.txtInFile.setGeometry(QtCore.QRect(160, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmFECNN)
        self.btnConvert.setGeometry(QtCore.QRect(590, 640, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label_35 = QtWidgets.QLabel(frmFECNN)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmFECNN)
        self.txtOutFile.setGeometry(QtCore.QRect(160, 60, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnClose = QtWidgets.QPushButton(frmFECNN)
        self.btnClose.setGeometry(QtCore.QRect(30, 640, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmFECNN)
        self.tabWidget.setGeometry(QtCore.QRect(30, 100, 701, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.txtOTask = QtWidgets.QLineEdit(self.tab)
        self.txtOTask.setGeometry(QtCore.QRect(420, 290, 113, 21))
        self.txtOTask.setObjectName("txtOTask")
        self.txtmLabel = QtWidgets.QComboBox(self.tab)
        self.txtmLabel.setGeometry(QtCore.QRect(260, 170, 121, 26))
        self.txtmLabel.setEditable(True)
        self.txtmLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtmLabel.setObjectName("txtmLabel")
        self.cbmLabel = QtWidgets.QCheckBox(self.tab)
        self.cbmLabel.setGeometry(QtCore.QRect(140, 170, 111, 20))
        self.cbmLabel.setObjectName("cbmLabel")
        self.txtScan = QtWidgets.QComboBox(self.tab)
        self.txtScan.setGeometry(QtCore.QRect(260, 450, 121, 26))
        self.txtScan.setEditable(True)
        self.txtScan.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtScan.setObjectName("txtScan")
        self.txtTask = QtWidgets.QComboBox(self.tab)
        self.txtTask.setGeometry(QtCore.QRect(260, 290, 121, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTask.setObjectName("txtTask")
        self.txtSubject = QtWidgets.QComboBox(self.tab)
        self.txtSubject.setGeometry(QtCore.QRect(260, 130, 121, 26))
        self.txtSubject.setEditable(True)
        self.txtSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubject.setObjectName("txtSubject")
        self.txtOmLabel = QtWidgets.QLineEdit(self.tab)
        self.txtOmLabel.setGeometry(QtCore.QRect(420, 170, 113, 21))
        self.txtOmLabel.setObjectName("txtOmLabel")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 60, 16))
        self.label_2.setObjectName("label_2")
        self.txtODM = QtWidgets.QLineEdit(self.tab)
        self.txtODM.setGeometry(QtCore.QRect(420, 250, 113, 21))
        self.txtODM.setObjectName("txtODM")
        self.cbTask = QtWidgets.QCheckBox(self.tab)
        self.cbTask.setGeometry(QtCore.QRect(140, 290, 81, 20))
        self.cbTask.setChecked(True)
        self.cbTask.setObjectName("cbTask")
        self.txtDM = QtWidgets.QComboBox(self.tab)
        self.txtDM.setGeometry(QtCore.QRect(260, 250, 121, 26))
        self.txtDM.setEditable(True)
        self.txtDM.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtDM.setObjectName("txtDM")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(140, 90, 60, 16))
        self.label_3.setObjectName("label_3")
        self.cbNScan = QtWidgets.QCheckBox(self.tab)
        self.cbNScan.setGeometry(QtCore.QRect(140, 450, 91, 20))
        self.cbNScan.setChecked(False)
        self.cbNScan.setObjectName("cbNScan")
        self.cbCond = QtWidgets.QCheckBox(self.tab)
        self.cbCond.setGeometry(QtCore.QRect(140, 410, 101, 20))
        self.cbCond.setChecked(True)
        self.cbCond.setObjectName("cbCond")
        self.cbDM = QtWidgets.QCheckBox(self.tab)
        self.cbDM.setGeometry(QtCore.QRect(140, 250, 121, 20))
        self.cbDM.setChecked(False)
        self.cbDM.setObjectName("cbDM")
        self.txtCol = QtWidgets.QComboBox(self.tab)
        self.txtCol.setGeometry(QtCore.QRect(260, 210, 121, 26))
        self.txtCol.setEditable(True)
        self.txtCol.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCol.setObjectName("txtCol")
        self.cbCol = QtWidgets.QCheckBox(self.tab)
        self.cbCol.setGeometry(QtCore.QRect(140, 210, 111, 20))
        self.cbCol.setChecked(True)
        self.cbCol.setObjectName("cbCol")
        self.txtOCond = QtWidgets.QLineEdit(self.tab)
        self.txtOCond.setGeometry(QtCore.QRect(420, 410, 113, 21))
        self.txtOCond.setObjectName("txtOCond")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(300, 20, 61, 16))
        self.label.setObjectName("label")
        self.txtOLabel = QtWidgets.QLineEdit(self.tab)
        self.txtOLabel.setGeometry(QtCore.QRect(420, 90, 113, 21))
        self.txtOLabel.setObjectName("txtOLabel")
        self.txtCounter = QtWidgets.QComboBox(self.tab)
        self.txtCounter.setGeometry(QtCore.QRect(260, 370, 121, 26))
        self.txtCounter.setEditable(True)
        self.txtCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounter.setObjectName("txtCounter")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(260, 90, 121, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtOScan = QtWidgets.QLineEdit(self.tab)
        self.txtOScan.setGeometry(QtCore.QRect(420, 450, 113, 21))
        self.txtOScan.setObjectName("txtOScan")
        self.cbCounter = QtWidgets.QCheckBox(self.tab)
        self.cbCounter.setGeometry(QtCore.QRect(140, 370, 81, 20))
        self.cbCounter.setChecked(False)
        self.cbCounter.setObjectName("cbCounter")
        self.txtOCol = QtWidgets.QLineEdit(self.tab)
        self.txtOCol.setGeometry(QtCore.QRect(420, 210, 113, 21))
        self.txtOCol.setObjectName("txtOCol")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(450, 20, 61, 16))
        self.label_5.setObjectName("label_5")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(260, 50, 121, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.txtRun = QtWidgets.QComboBox(self.tab)
        self.txtRun.setGeometry(QtCore.QRect(260, 330, 121, 26))
        self.txtRun.setEditable(True)
        self.txtRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRun.setObjectName("txtRun")
        self.txtCond = QtWidgets.QComboBox(self.tab)
        self.txtCond.setGeometry(QtCore.QRect(260, 410, 121, 26))
        self.txtCond.setEditable(True)
        self.txtCond.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCond.setObjectName("txtCond")
        self.txtOCounter = QtWidgets.QLineEdit(self.tab)
        self.txtOCounter.setGeometry(QtCore.QRect(420, 370, 113, 21))
        self.txtOCounter.setObjectName("txtOCounter")
        self.txtOSubject = QtWidgets.QLineEdit(self.tab)
        self.txtOSubject.setGeometry(QtCore.QRect(420, 130, 113, 21))
        self.txtOSubject.setObjectName("txtOSubject")
        self.cbRun = QtWidgets.QCheckBox(self.tab)
        self.cbRun.setGeometry(QtCore.QRect(140, 330, 81, 20))
        self.cbRun.setChecked(True)
        self.cbRun.setObjectName("cbRun")
        self.txtOData = QtWidgets.QLineEdit(self.tab)
        self.txtOData.setGeometry(QtCore.QRect(420, 50, 113, 21))
        self.txtOData.setObjectName("txtOData")
        self.txtORun = QtWidgets.QLineEdit(self.tab)
        self.txtORun.setGeometry(QtCore.QRect(420, 330, 113, 21))
        self.txtORun.setObjectName("txtORun")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(140, 130, 60, 16))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 641, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 191, 20))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.rbScale = QtWidgets.QRadioButton(self.groupBox)
        self.rbScale.setGeometry(QtCore.QRect(210, 40, 161, 20))
        self.rbScale.setChecked(True)
        self.rbScale.setObjectName("rbScale")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(370, 40, 131, 20))
        self.radioButton.setObjectName("radioButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 110, 641, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(190, 40, 131, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.rbALScale = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbALScale.setGeometry(QtCore.QRect(30, 40, 161, 20))
        self.rbALScale.setChecked(True)
        self.rbALScale.setObjectName("rbALScale")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 210, 641, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setGeometry(QtCore.QRect(410, 40, 131, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.rbMat = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbMat.setGeometry(QtCore.QRect(30, 40, 161, 20))
        self.rbMat.setChecked(True)
        self.rbMat.setObjectName("rbMat")
        self.cbOutNormal = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbOutNormal.setGeometry(QtCore.QRect(150, 40, 231, 21))
        self.cbOutNormal.setChecked(True)
        self.cbOutNormal.setObjectName("cbOutNormal")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 310, 641, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.cbThreshold = QtWidgets.QCheckBox(self.groupBox_4)
        self.cbThreshold.setGeometry(QtCore.QRect(20, 40, 601, 21))
        self.cbThreshold.setChecked(True)
        self.cbThreshold.setObjectName("cbThreshold")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 131, 16))
        self.label_4.setObjectName("label_4")
        self.txtThreshold = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtThreshold.setGeometry(QtCore.QRect(110, 80, 231, 23))
        self.txtThreshold.setObjectName("txtThreshold")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tbModel = QtWidgets.QTableWidget(self.tab_3)
        self.tbModel.setGeometry(QtCore.QRect(9, 60, 681, 371))
        self.tbModel.setObjectName("tbModel")
        self.tbModel.setColumnCount(0)
        self.tbModel.setRowCount(0)
        self.btnAddConv = QtWidgets.QPushButton(self.tab_3)
        self.btnAddConv.setGeometry(QtCore.QRect(10, 450, 101, 32))
        self.btnAddConv.setObjectName("btnAddConv")
        self.btnAddPool = QtWidgets.QPushButton(self.tab_3)
        self.btnAddPool.setGeometry(QtCore.QRect(340, 450, 91, 32))
        self.btnAddPool.setObjectName("btnAddPool")
        self.btnAddAF = QtWidgets.QPushButton(self.tab_3)
        self.btnAddAF.setGeometry(QtCore.QRect(130, 450, 191, 32))
        self.btnAddAF.setObjectName("btnAddAF")
        self.btnUp = QtWidgets.QPushButton(self.tab_3)
        self.btnUp.setGeometry(QtCore.QRect(10, 14, 111, 32))
        self.btnUp.setObjectName("btnUp")
        self.btnDown = QtWidgets.QPushButton(self.tab_3)
        self.btnDown.setGeometry(QtCore.QRect(140, 14, 111, 32))
        self.btnDown.setObjectName("btnDown")
        self.btnDelete = QtWidgets.QPushButton(self.tab_3)
        self.btnDelete.setGeometry(QtCore.QRect(600, 450, 91, 32))
        self.btnDelete.setObjectName("btnDelete")
        self.btnLoadNet = QtWidgets.QPushButton(self.tab_3)
        self.btnLoadNet.setGeometry(QtCore.QRect(450, 14, 111, 32))
        self.btnLoadNet.setObjectName("btnLoadNet")
        self.btnSaveNet = QtWidgets.QPushButton(self.tab_3)
        self.btnSaveNet.setGeometry(QtCore.QRect(580, 14, 111, 32))
        self.btnSaveNet.setObjectName("btnSaveNet")
        self.btnClearNet = QtWidgets.QPushButton(self.tab_3)
        self.btnClearNet.setGeometry(QtCore.QRect(490, 450, 91, 32))
        self.btnClearNet.setObjectName("btnClearNet")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(frmFECNN)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmFECNN)
        frmFECNN.setTabOrder(self.txtInFile, self.btnInFile)
        frmFECNN.setTabOrder(self.btnInFile, self.txtOutFile)
        frmFECNN.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmFECNN.setTabOrder(self.btnOutFile, self.tabWidget)
        frmFECNN.setTabOrder(self.tabWidget, self.cbmLabel)
        frmFECNN.setTabOrder(self.cbmLabel, self.cbCol)
        frmFECNN.setTabOrder(self.cbCol, self.cbDM)
        frmFECNN.setTabOrder(self.cbDM, self.cbTask)
        frmFECNN.setTabOrder(self.cbTask, self.cbRun)
        frmFECNN.setTabOrder(self.cbRun, self.cbCounter)
        frmFECNN.setTabOrder(self.cbCounter, self.cbCond)
        frmFECNN.setTabOrder(self.cbCond, self.cbNScan)
        frmFECNN.setTabOrder(self.cbNScan, self.txtData)
        frmFECNN.setTabOrder(self.txtData, self.txtLabel)
        frmFECNN.setTabOrder(self.txtLabel, self.txtSubject)
        frmFECNN.setTabOrder(self.txtSubject, self.txtmLabel)
        frmFECNN.setTabOrder(self.txtmLabel, self.txtCol)
        frmFECNN.setTabOrder(self.txtCol, self.txtDM)
        frmFECNN.setTabOrder(self.txtDM, self.txtTask)
        frmFECNN.setTabOrder(self.txtTask, self.txtRun)
        frmFECNN.setTabOrder(self.txtRun, self.txtCounter)
        frmFECNN.setTabOrder(self.txtCounter, self.txtScan)
        frmFECNN.setTabOrder(self.txtScan, self.txtOData)
        frmFECNN.setTabOrder(self.txtOData, self.txtOLabel)
        frmFECNN.setTabOrder(self.txtOLabel, self.txtOSubject)
        frmFECNN.setTabOrder(self.txtOSubject, self.txtOmLabel)
        frmFECNN.setTabOrder(self.txtOmLabel, self.txtOCol)
        frmFECNN.setTabOrder(self.txtOCol, self.txtODM)
        frmFECNN.setTabOrder(self.txtODM, self.txtOTask)
        frmFECNN.setTabOrder(self.txtOTask, self.txtORun)
        frmFECNN.setTabOrder(self.txtORun, self.txtOCounter)
        frmFECNN.setTabOrder(self.txtOCounter, self.txtOCond)
        frmFECNN.setTabOrder(self.txtOCond, self.txtOScan)
        frmFECNN.setTabOrder(self.txtOScan, self.txtCond)
        frmFECNN.setTabOrder(self.txtCond, self.cbScale)
        frmFECNN.setTabOrder(self.cbScale, self.rbScale)
        frmFECNN.setTabOrder(self.rbScale, self.radioButton)
        frmFECNN.setTabOrder(self.radioButton, self.btnConvert)
        frmFECNN.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmFECNN):
        _translate = QtCore.QCoreApplication.translate
        frmFECNN.setWindowTitle(_translate("frmFECNN", "Convolutional Neural Network"))
        self.btnInFile.setText(_translate("frmFECNN", "..."))
        self.label_33.setText(_translate("frmFECNN", "Input Data"))
        self.btnOutFile.setText(_translate("frmFECNN", "..."))
        self.btnConvert.setText(_translate("frmFECNN", "Convert"))
        self.label_35.setText(_translate("frmFECNN", "Output Data"))
        self.btnClose.setText(_translate("frmFECNN", "Close"))
        self.txtOTask.setText(_translate("frmFECNN", "task"))
        self.cbmLabel.setText(_translate("frmFECNN", "Label (matrix)"))
        self.txtOmLabel.setText(_translate("frmFECNN", "mlabel"))
        self.label_2.setText(_translate("frmFECNN", "Data"))
        self.txtODM.setText(_translate("frmFECNN", "design"))
        self.cbTask.setText(_translate("frmFECNN", "Task"))
        self.label_3.setText(_translate("frmFECNN", "Label"))
        self.cbNScan.setText(_translate("frmFECNN", "NScan"))
        self.cbCond.setText(_translate("frmFECNN", "Condition"))
        self.cbDM.setText(_translate("frmFECNN", "Design Matrix"))
        self.cbCol.setText(_translate("frmFECNN", "Coordinate"))
        self.txtOCond.setText(_translate("frmFECNN", "condition"))
        self.label.setText(_translate("frmFECNN", "Input"))
        self.txtOLabel.setText(_translate("frmFECNN", "label"))
        self.txtOScan.setText(_translate("frmFECNN", "nscan"))
        self.cbCounter.setText(_translate("frmFECNN", "Counter"))
        self.txtOCol.setText(_translate("frmFECNN", "coordinate"))
        self.label_5.setText(_translate("frmFECNN", "Output"))
        self.txtOCounter.setText(_translate("frmFECNN", "counter"))
        self.txtOSubject.setText(_translate("frmFECNN", "subject"))
        self.cbRun.setText(_translate("frmFECNN", "Run"))
        self.txtOData.setText(_translate("frmFECNN", "data"))
        self.txtORun.setText(_translate("frmFECNN", "run"))
        self.label_6.setText(_translate("frmFECNN", "Subject"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmFECNN", "Data"))
        self.groupBox.setTitle(_translate("frmFECNN", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmFECNN", "Scale Data X~N(0,1)"))
        self.rbScale.setText(_translate("frmFECNN", "Subject Level"))
        self.radioButton.setText(_translate("frmFECNN", "Whole Data"))
        self.groupBox_2.setTitle(_translate("frmFECNN", "<Analysis Level>"))
        self.radioButton_2.setText(_translate("frmFECNN", "Whole Data"))
        self.rbALScale.setText(_translate("frmFECNN", "Subject Level"))
        self.groupBox_3.setTitle(_translate("frmFECNN", "<Output Model>"))
        self.radioButton_3.setText(_translate("frmFECNN", "4D (Tensor)"))
        self.rbMat.setText(_translate("frmFECNN", "2D (Matrix)"))
        self.cbOutNormal.setText(_translate("frmFECNN", "Normalize 2D data"))
        self.groupBox_4.setTitle(_translate("frmFECNN", "<STD Thresholding>"))
        self.cbThreshold.setText(_translate("frmFECNN", "For 2D matrix, remove features with standard deviation thresholding"))
        self.label_4.setText(_translate("frmFECNN", "Threshold"))
        self.txtThreshold.setText(_translate("frmFECNN", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmFECNN", "Parameters"))
        self.btnAddConv.setText(_translate("frmFECNN", "Add Conv"))
        self.btnAddPool.setText(_translate("frmFECNN", "Add Pool"))
        self.btnAddAF.setText(_translate("frmFECNN", "Add Activation Function"))
        self.btnUp.setText(_translate("frmFECNN", "Move Up"))
        self.btnDown.setText(_translate("frmFECNN", "Move Down"))
        self.btnDelete.setText(_translate("frmFECNN", "Delete"))
        self.btnLoadNet.setText(_translate("frmFECNN", "Load"))
        self.btnSaveNet.setText(_translate("frmFECNN", "Save"))
        self.btnClearNet.setText(_translate("frmFECNN", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmFECNN", "Network"))

