# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmFETempAlignGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmFETempAlign(object):
    def setupUi(self, frmFETempAlign):
        frmFETempAlign.setObjectName("frmFETempAlign")
        frmFETempAlign.resize(758, 451)
        self.btnInFile = QtWidgets.QPushButton(frmFETempAlign)
        self.btnInFile.setGeometry(QtCore.QRect(690, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmFETempAlign)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 131, 16))
        self.label_33.setObjectName("label_33")
        self.txtInFile = QtWidgets.QLineEdit(frmFETempAlign)
        self.txtInFile.setGeometry(QtCore.QRect(160, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnClose = QtWidgets.QPushButton(frmFETempAlign)
        self.btnClose.setGeometry(QtCore.QRect(30, 400, 151, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmFETempAlign)
        self.tabWidget.setGeometry(QtCore.QRect(30, 60, 701, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.txtTask = QtWidgets.QComboBox(self.tab)
        self.txtTask.setGeometry(QtCore.QRect(300, 250, 121, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTask.setObjectName("txtTask")
        self.txtSubject = QtWidgets.QComboBox(self.tab)
        self.txtSubject.setGeometry(QtCore.QRect(300, 130, 121, 26))
        self.txtSubject.setEditable(True)
        self.txtSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubject.setObjectName("txtSubject")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(140, 90, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(340, 20, 61, 16))
        self.label.setObjectName("label")
        self.txtCounter = QtWidgets.QComboBox(self.tab)
        self.txtCounter.setGeometry(QtCore.QRect(300, 210, 121, 26))
        self.txtCounter.setEditable(True)
        self.txtCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounter.setObjectName("txtCounter")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(300, 90, 121, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(300, 50, 121, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.txtRun = QtWidgets.QComboBox(self.tab)
        self.txtRun.setGeometry(QtCore.QRect(300, 170, 121, 26))
        self.txtRun.setEditable(True)
        self.txtRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRun.setObjectName("txtRun")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(140, 130, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(140, 170, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(140, 210, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(140, 250, 101, 16))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cbFCounter = QtWidgets.QCheckBox(self.tab_2)
        self.cbFCounter.setGeometry(QtCore.QRect(510, 90, 161, 20))
        self.cbFCounter.setObjectName("cbFCounter")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 20, 451, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cbFSubject = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbFSubject.setGeometry(QtCore.QRect(20, 30, 130, 20))
        self.cbFSubject.setChecked(True)
        self.cbFSubject.setObjectName("cbFSubject")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(20, 60, 201, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.rbFRun = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbFRun.setGeometry(QtCore.QRect(230, 60, 221, 20))
        self.rbFRun.setObjectName("rbFRun")
        self.cbFTask = QtWidgets.QCheckBox(self.tab_2)
        self.cbFTask.setGeometry(QtCore.QRect(510, 50, 161, 20))
        self.cbFTask.setObjectName("cbFTask")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.txtReport = QtWidgets.QTextEdit(self.tab_3)
        self.txtReport.setGeometry(QtCore.QRect(12, 10, 671, 270))
        self.txtReport.setReadOnly(True)
        self.txtReport.setObjectName("txtReport")
        self.tabWidget.addTab(self.tab_3, "")
        self.btnReport = QtWidgets.QPushButton(frmFETempAlign)
        self.btnReport.setGeometry(QtCore.QRect(570, 400, 150, 32))
        self.btnReport.setObjectName("btnReport")

        self.retranslateUi(frmFETempAlign)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmFETempAlign)
        frmFETempAlign.setTabOrder(self.txtInFile, self.btnInFile)
        frmFETempAlign.setTabOrder(self.btnInFile, self.tabWidget)
        frmFETempAlign.setTabOrder(self.tabWidget, self.txtData)
        frmFETempAlign.setTabOrder(self.txtData, self.txtLabel)
        frmFETempAlign.setTabOrder(self.txtLabel, self.txtSubject)
        frmFETempAlign.setTabOrder(self.txtSubject, self.txtTask)
        frmFETempAlign.setTabOrder(self.txtTask, self.txtRun)
        frmFETempAlign.setTabOrder(self.txtRun, self.txtCounter)
        frmFETempAlign.setTabOrder(self.txtCounter, self.btnClose)

    def retranslateUi(self, frmFETempAlign):
        _translate = QtCore.QCoreApplication.translate
        frmFETempAlign.setWindowTitle(_translate("frmFETempAlign", "Temporal Alignment Report"))
        self.btnInFile.setText(_translate("frmFETempAlign", "..."))
        self.label_33.setText(_translate("frmFETempAlign", "Input Data"))
        self.btnClose.setText(_translate("frmFETempAlign", "Close"))
        self.label_2.setText(_translate("frmFETempAlign", "Data"))
        self.label_3.setText(_translate("frmFETempAlign", "Label"))
        self.label.setText(_translate("frmFETempAlign", "Input"))
        self.label_6.setText(_translate("frmFETempAlign", "Subject"))
        self.label_7.setText(_translate("frmFETempAlign", "Run"))
        self.label_8.setText(_translate("frmFETempAlign", "Counter"))
        self.label_9.setText(_translate("frmFETempAlign", "Task"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmFETempAlign", "Data"))
        self.cbFCounter.setText(_translate("frmFETempAlign", "Counter"))
        self.groupBox_2.setTitle(_translate("frmFETempAlign", "<Subject Level>"))
        self.cbFSubject.setText(_translate("frmFETempAlign", "Subject"))
        self.radioButton.setText(_translate("frmFETempAlign", "Without Run"))
        self.rbFRun.setText(_translate("frmFETempAlign", "With Run"))
        self.cbFTask.setText(_translate("frmFETempAlign", "Task"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmFETempAlign", "Level"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmFETempAlign", "Report"))
        self.btnReport.setText(_translate("frmFETempAlign", "Report"))

