# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmFELabelAlignGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmFELabelAlign(object):
    def setupUi(self, frmFELabelAlign):
        frmFELabelAlign.setObjectName("frmFELabelAlign")
        frmFELabelAlign.resize(758, 722)
        self.btnInFile = QtWidgets.QPushButton(frmFELabelAlign)
        self.btnInFile.setGeometry(QtCore.QRect(690, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmFELabelAlign)
        self.label_33.setGeometry(QtCore.QRect(20, 20, 131, 16))
        self.label_33.setObjectName("label_33")
        self.txtInFile = QtWidgets.QLineEdit(frmFELabelAlign)
        self.txtInFile.setGeometry(QtCore.QRect(130, 20, 551, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnClose = QtWidgets.QPushButton(frmFELabelAlign)
        self.btnClose.setGeometry(QtCore.QRect(10, 670, 151, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmFELabelAlign)
        self.tabWidget.setGeometry(QtCore.QRect(10, 100, 731, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.txtTask = QtWidgets.QComboBox(self.tab)
        self.txtTask.setGeometry(QtCore.QRect(300, 220, 121, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTask.setObjectName("txtTask")
        self.txtSubject = QtWidgets.QComboBox(self.tab)
        self.txtSubject.setGeometry(QtCore.QRect(300, 100, 121, 26))
        self.txtSubject.setEditable(True)
        self.txtSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubject.setObjectName("txtSubject")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(140, 60, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(340, 20, 61, 16))
        self.label.setObjectName("label")
        self.txtCounter = QtWidgets.QComboBox(self.tab)
        self.txtCounter.setGeometry(QtCore.QRect(300, 180, 121, 26))
        self.txtCounter.setEditable(True)
        self.txtCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounter.setObjectName("txtCounter")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(300, 60, 121, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtRun = QtWidgets.QComboBox(self.tab)
        self.txtRun.setGeometry(QtCore.QRect(300, 140, 121, 26))
        self.txtRun.setEditable(True)
        self.txtRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRun.setObjectName("txtRun")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(140, 100, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(140, 140, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(140, 180, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(140, 220, 101, 16))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cbFCounter = QtWidgets.QCheckBox(self.tab_2)
        self.cbFCounter.setGeometry(QtCore.QRect(510, 90, 161, 20))
        self.cbFCounter.setObjectName("cbFCounter")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 20, 451, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cbFSubject = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbFSubject.setGeometry(QtCore.QRect(20, 30, 130, 20))
        self.cbFSubject.setChecked(True)
        self.cbFSubject.setObjectName("cbFSubject")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(20, 60, 201, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.rbFRun = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbFRun.setGeometry(QtCore.QRect(230, 60, 221, 20))
        self.rbFRun.setObjectName("rbFRun")
        self.cbFTask = QtWidgets.QCheckBox(self.tab_2)
        self.cbFTask.setGeometry(QtCore.QRect(510, 50, 161, 20))
        self.cbFTask.setObjectName("cbFTask")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tbReport = QtWidgets.QTableWidget(self.tab_3)
        self.tbReport.setGeometry(QtCore.QRect(8, 10, 711, 501))
        self.tbReport.setObjectName("tbReport")
        self.tbReport.setColumnCount(0)
        self.tbReport.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.btnReport = QtWidgets.QPushButton(frmFELabelAlign)
        self.btnReport.setGeometry(QtCore.QRect(590, 670, 150, 32))
        self.btnReport.setObjectName("btnReport")
        self.txtColor = QtWidgets.QComboBox(frmFELabelAlign)
        self.txtColor.setGeometry(QtCore.QRect(130, 55, 271, 26))
        self.txtColor.setEditable(False)
        self.txtColor.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtColor.setObjectName("txtColor")
        self.label_10 = QtWidgets.QLabel(frmFELabelAlign)
        self.label_10.setGeometry(QtCore.QRect(20, 55, 101, 16))
        self.label_10.setObjectName("label_10")

        self.retranslateUi(frmFELabelAlign)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmFELabelAlign)
        frmFELabelAlign.setTabOrder(self.txtInFile, self.btnInFile)
        frmFELabelAlign.setTabOrder(self.btnInFile, self.tabWidget)
        frmFELabelAlign.setTabOrder(self.tabWidget, self.txtLabel)
        frmFELabelAlign.setTabOrder(self.txtLabel, self.txtSubject)
        frmFELabelAlign.setTabOrder(self.txtSubject, self.txtTask)
        frmFELabelAlign.setTabOrder(self.txtTask, self.txtRun)
        frmFELabelAlign.setTabOrder(self.txtRun, self.txtCounter)
        frmFELabelAlign.setTabOrder(self.txtCounter, self.btnClose)

    def retranslateUi(self, frmFELabelAlign):
        _translate = QtCore.QCoreApplication.translate
        frmFELabelAlign.setWindowTitle(_translate("frmFELabelAlign", "Label Alignment Report"))
        self.btnInFile.setText(_translate("frmFELabelAlign", "..."))
        self.label_33.setText(_translate("frmFELabelAlign", "Input Data"))
        self.btnClose.setText(_translate("frmFELabelAlign", "Close"))
        self.label_3.setText(_translate("frmFELabelAlign", "Label"))
        self.label.setText(_translate("frmFELabelAlign", "Input"))
        self.label_6.setText(_translate("frmFELabelAlign", "Subject"))
        self.label_7.setText(_translate("frmFELabelAlign", "Run"))
        self.label_8.setText(_translate("frmFELabelAlign", "Counter"))
        self.label_9.setText(_translate("frmFELabelAlign", "Task"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmFELabelAlign", "Data"))
        self.cbFCounter.setText(_translate("frmFELabelAlign", "Counter"))
        self.groupBox_2.setTitle(_translate("frmFELabelAlign", "<Subject Level>"))
        self.cbFSubject.setText(_translate("frmFELabelAlign", "Subject"))
        self.radioButton.setText(_translate("frmFELabelAlign", "Without Run"))
        self.rbFRun.setText(_translate("frmFELabelAlign", "With Run"))
        self.cbFTask.setText(_translate("frmFELabelAlign", "Task"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmFELabelAlign", "Level"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmFELabelAlign", "Report"))
        self.btnReport.setText(_translate("frmFELabelAlign", "Report"))
        self.label_10.setText(_translate("frmFELabelAlign", "Color Palette"))

