# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmFADHAGUI.ui'
#
# Created by: PyQt6 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_frmFADHA(object):
    def setupUi(self, frmFADHA):
        frmFADHA.setObjectName("frmFADHA")
        frmFADHA.resize(782, 809)
        self.btnInFile = QtWidgets.QPushButton(frmFADHA)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmFADHA)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 131, 16))
        self.label_33.setObjectName("label_33")
        self.btnOutFile = QtWidgets.QPushButton(frmFADHA)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.txtInFile = QtWidgets.QLineEdit(frmFADHA)
        self.txtInFile.setGeometry(QtCore.QRect(160, 20, 541, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmFADHA)
        self.btnConvert.setGeometry(QtCore.QRect(620, 760, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label_35 = QtWidgets.QLabel(frmFADHA)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmFADHA)
        self.txtOutFile.setGeometry(QtCore.QRect(160, 60, 541, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnClose = QtWidgets.QPushButton(frmFADHA)
        self.btnClose.setGeometry(QtCore.QRect(30, 760, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmFADHA)
        self.tabWidget.setGeometry(QtCore.QRect(30, 130, 731, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.txtOTrTask = QtWidgets.QLineEdit(self.tab)
        self.txtOTrTask.setGeometry(QtCore.QRect(450, 300, 113, 21))
        self.txtOTrTask.setObjectName("txtOTrTask")
        self.txtITrmLabel = QtWidgets.QComboBox(self.tab)
        self.txtITrmLabel.setGeometry(QtCore.QRect(140, 180, 121, 26))
        self.txtITrmLabel.setEditable(True)
        self.txtITrmLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrmLabel.setObjectName("txtITrmLabel")
        self.cbmLabel = QtWidgets.QCheckBox(self.tab)
        self.cbmLabel.setGeometry(QtCore.QRect(20, 180, 111, 20))
        self.cbmLabel.setObjectName("cbmLabel")
        self.txtITrScan = QtWidgets.QComboBox(self.tab)
        self.txtITrScan.setGeometry(QtCore.QRect(140, 460, 121, 26))
        self.txtITrScan.setEditable(True)
        self.txtITrScan.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrScan.setObjectName("txtITrScan")
        self.txtITrTask = QtWidgets.QComboBox(self.tab)
        self.txtITrTask.setGeometry(QtCore.QRect(140, 300, 121, 26))
        self.txtITrTask.setEditable(True)
        self.txtITrTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrTask.setObjectName("txtITrTask")
        self.txtITrSubject = QtWidgets.QComboBox(self.tab)
        self.txtITrSubject.setGeometry(QtCore.QRect(140, 140, 121, 26))
        self.txtITrSubject.setEditable(True)
        self.txtITrSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrSubject.setObjectName("txtITrSubject")
        self.txtOTrmLabel = QtWidgets.QLineEdit(self.tab)
        self.txtOTrmLabel.setGeometry(QtCore.QRect(450, 180, 113, 21))
        self.txtOTrmLabel.setObjectName("txtOTrmLabel")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 60, 16))
        self.label_2.setObjectName("label_2")
        self.txtOTrDM = QtWidgets.QLineEdit(self.tab)
        self.txtOTrDM.setGeometry(QtCore.QRect(450, 260, 113, 21))
        self.txtOTrDM.setObjectName("txtOTrDM")
        self.cbTask = QtWidgets.QCheckBox(self.tab)
        self.cbTask.setGeometry(QtCore.QRect(20, 300, 81, 20))
        self.cbTask.setChecked(True)
        self.cbTask.setObjectName("cbTask")
        self.txtITrDM = QtWidgets.QComboBox(self.tab)
        self.txtITrDM.setGeometry(QtCore.QRect(140, 260, 121, 26))
        self.txtITrDM.setEditable(True)
        self.txtITrDM.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrDM.setObjectName("txtITrDM")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 60, 16))
        self.label_3.setObjectName("label_3")
        self.cbNScan = QtWidgets.QCheckBox(self.tab)
        self.cbNScan.setGeometry(QtCore.QRect(20, 460, 91, 20))
        self.cbNScan.setChecked(False)
        self.cbNScan.setObjectName("cbNScan")
        self.cbCond = QtWidgets.QCheckBox(self.tab)
        self.cbCond.setGeometry(QtCore.QRect(20, 420, 101, 20))
        self.cbCond.setChecked(True)
        self.cbCond.setObjectName("cbCond")
        self.cbDM = QtWidgets.QCheckBox(self.tab)
        self.cbDM.setGeometry(QtCore.QRect(20, 260, 121, 20))
        self.cbDM.setChecked(False)
        self.cbDM.setObjectName("cbDM")
        self.txtCol = QtWidgets.QComboBox(self.tab)
        self.txtCol.setGeometry(QtCore.QRect(140, 220, 121, 26))
        self.txtCol.setEditable(True)
        self.txtCol.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCol.setObjectName("txtCol")
        self.cbCol = QtWidgets.QCheckBox(self.tab)
        self.cbCol.setGeometry(QtCore.QRect(20, 220, 111, 20))
        self.cbCol.setChecked(True)
        self.cbCol.setObjectName("cbCol")
        self.txtOCond = QtWidgets.QLineEdit(self.tab)
        self.txtOCond.setGeometry(QtCore.QRect(450, 420, 113, 21))
        self.txtOCond.setObjectName("txtOCond")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 10, 61, 16))
        self.label.setObjectName("label")
        self.txtOTrLabel = QtWidgets.QLineEdit(self.tab)
        self.txtOTrLabel.setGeometry(QtCore.QRect(450, 100, 113, 21))
        self.txtOTrLabel.setObjectName("txtOTrLabel")
        self.txtITrCounter = QtWidgets.QComboBox(self.tab)
        self.txtITrCounter.setGeometry(QtCore.QRect(140, 380, 121, 26))
        self.txtITrCounter.setEditable(True)
        self.txtITrCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrCounter.setObjectName("txtITrCounter")
        self.txtITrLabel = QtWidgets.QComboBox(self.tab)
        self.txtITrLabel.setGeometry(QtCore.QRect(140, 100, 121, 26))
        self.txtITrLabel.setEditable(True)
        self.txtITrLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrLabel.setObjectName("txtITrLabel")
        self.txtOTrScan = QtWidgets.QLineEdit(self.tab)
        self.txtOTrScan.setGeometry(QtCore.QRect(450, 460, 113, 21))
        self.txtOTrScan.setObjectName("txtOTrScan")
        self.cbCounter = QtWidgets.QCheckBox(self.tab)
        self.cbCounter.setGeometry(QtCore.QRect(20, 380, 81, 20))
        self.cbCounter.setChecked(False)
        self.cbCounter.setObjectName("cbCounter")
        self.txtOCol = QtWidgets.QLineEdit(self.tab)
        self.txtOCol.setGeometry(QtCore.QRect(450, 220, 113, 21))
        self.txtOCol.setObjectName("txtOCol")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(550, 10, 61, 16))
        self.label_5.setObjectName("label_5")
        self.txtITrData = QtWidgets.QComboBox(self.tab)
        self.txtITrData.setGeometry(QtCore.QRect(140, 60, 121, 26))
        self.txtITrData.setEditable(True)
        self.txtITrData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrData.setObjectName("txtITrData")
        self.txtITrRun = QtWidgets.QComboBox(self.tab)
        self.txtITrRun.setGeometry(QtCore.QRect(140, 340, 121, 26))
        self.txtITrRun.setEditable(True)
        self.txtITrRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrRun.setObjectName("txtITrRun")
        self.txtCond = QtWidgets.QComboBox(self.tab)
        self.txtCond.setGeometry(QtCore.QRect(140, 420, 121, 26))
        self.txtCond.setEditable(True)
        self.txtCond.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCond.setObjectName("txtCond")
        self.txtOTrCounter = QtWidgets.QLineEdit(self.tab)
        self.txtOTrCounter.setGeometry(QtCore.QRect(450, 380, 113, 21))
        self.txtOTrCounter.setObjectName("txtOTrCounter")
        self.txtOTrSubject = QtWidgets.QLineEdit(self.tab)
        self.txtOTrSubject.setGeometry(QtCore.QRect(450, 140, 113, 21))
        self.txtOTrSubject.setObjectName("txtOTrSubject")
        self.cbRun = QtWidgets.QCheckBox(self.tab)
        self.cbRun.setGeometry(QtCore.QRect(20, 340, 81, 20))
        self.cbRun.setChecked(True)
        self.cbRun.setObjectName("cbRun")
        self.txtOTrData = QtWidgets.QLineEdit(self.tab)
        self.txtOTrData.setGeometry(QtCore.QRect(450, 60, 113, 21))
        self.txtOTrData.setObjectName("txtOTrData")
        self.txtOTrRun = QtWidgets.QLineEdit(self.tab)
        self.txtOTrRun.setGeometry(QtCore.QRect(450, 340, 113, 21))
        self.txtOTrRun.setObjectName("txtOTrRun")
        self.txtITemLabel = QtWidgets.QComboBox(self.tab)
        self.txtITemLabel.setGeometry(QtCore.QRect(290, 180, 121, 26))
        self.txtITemLabel.setEditable(True)
        self.txtITemLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITemLabel.setObjectName("txtITemLabel")
        self.txtITeSubject = QtWidgets.QComboBox(self.tab)
        self.txtITeSubject.setGeometry(QtCore.QRect(290, 140, 121, 26))
        self.txtITeSubject.setEditable(True)
        self.txtITeSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeSubject.setObjectName("txtITeSubject")
        self.txtITeDM = QtWidgets.QComboBox(self.tab)
        self.txtITeDM.setGeometry(QtCore.QRect(290, 260, 121, 26))
        self.txtITeDM.setEditable(True)
        self.txtITeDM.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeDM.setObjectName("txtITeDM")
        self.txtITeCounter = QtWidgets.QComboBox(self.tab)
        self.txtITeCounter.setGeometry(QtCore.QRect(290, 380, 121, 26))
        self.txtITeCounter.setEditable(True)
        self.txtITeCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeCounter.setObjectName("txtITeCounter")
        self.txtITeLabel = QtWidgets.QComboBox(self.tab)
        self.txtITeLabel.setGeometry(QtCore.QRect(290, 100, 121, 26))
        self.txtITeLabel.setEditable(True)
        self.txtITeLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeLabel.setObjectName("txtITeLabel")
        self.txtITeData = QtWidgets.QComboBox(self.tab)
        self.txtITeData.setGeometry(QtCore.QRect(290, 60, 121, 26))
        self.txtITeData.setEditable(True)
        self.txtITeData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeData.setObjectName("txtITeData")
        self.txtITeTask = QtWidgets.QComboBox(self.tab)
        self.txtITeTask.setGeometry(QtCore.QRect(290, 300, 121, 26))
        self.txtITeTask.setEditable(True)
        self.txtITeTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeTask.setObjectName("txtITeTask")
        self.txtITeScan = QtWidgets.QComboBox(self.tab)
        self.txtITeScan.setGeometry(QtCore.QRect(290, 460, 121, 26))
        self.txtITeScan.setEditable(True)
        self.txtITeScan.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeScan.setObjectName("txtITeScan")
        self.txtITeRun = QtWidgets.QComboBox(self.tab)
        self.txtITeRun.setGeometry(QtCore.QRect(290, 340, 121, 26))
        self.txtITeRun.setEditable(True)
        self.txtITeRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeRun.setObjectName("txtITeRun")
        self.txtOTeLabel = QtWidgets.QLineEdit(self.tab)
        self.txtOTeLabel.setGeometry(QtCore.QRect(600, 100, 113, 21))
        self.txtOTeLabel.setObjectName("txtOTeLabel")
        self.txtOTeRun = QtWidgets.QLineEdit(self.tab)
        self.txtOTeRun.setGeometry(QtCore.QRect(600, 340, 113, 21))
        self.txtOTeRun.setObjectName("txtOTeRun")
        self.txtOTemLabel = QtWidgets.QLineEdit(self.tab)
        self.txtOTemLabel.setGeometry(QtCore.QRect(600, 180, 113, 21))
        self.txtOTemLabel.setObjectName("txtOTemLabel")
        self.txtOTeDM = QtWidgets.QLineEdit(self.tab)
        self.txtOTeDM.setGeometry(QtCore.QRect(600, 260, 113, 21))
        self.txtOTeDM.setObjectName("txtOTeDM")
        self.txtOTeData = QtWidgets.QLineEdit(self.tab)
        self.txtOTeData.setGeometry(QtCore.QRect(600, 60, 113, 21))
        self.txtOTeData.setObjectName("txtOTeData")
        self.txtOTeCounter = QtWidgets.QLineEdit(self.tab)
        self.txtOTeCounter.setGeometry(QtCore.QRect(600, 380, 113, 21))
        self.txtOTeCounter.setObjectName("txtOTeCounter")
        self.txtOTeSubject = QtWidgets.QLineEdit(self.tab)
        self.txtOTeSubject.setGeometry(QtCore.QRect(600, 140, 113, 21))
        self.txtOTeSubject.setObjectName("txtOTeSubject")
        self.txtOTeTask = QtWidgets.QLineEdit(self.tab)
        self.txtOTeTask.setGeometry(QtCore.QRect(600, 300, 113, 21))
        self.txtOTeTask.setObjectName("txtOTeTask")
        self.txtOTeScan = QtWidgets.QLineEdit(self.tab)
        self.txtOTeScan.setGeometry(QtCore.QRect(600, 460, 113, 21))
        self.txtOTeScan.setObjectName("txtOTeScan")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(185, 30, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(330, 30, 81, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(485, 30, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(630, 30, 81, 16))
        self.label_10.setObjectName("label_10")
        self.cbFoldID = QtWidgets.QCheckBox(self.tab)
        self.cbFoldID.setGeometry(QtCore.QRect(20, 500, 101, 20))
        self.cbFoldID.setChecked(True)
        self.cbFoldID.setObjectName("cbFoldID")
        self.txtFoldID = QtWidgets.QComboBox(self.tab)
        self.txtFoldID.setGeometry(QtCore.QRect(140, 500, 121, 26))
        self.txtFoldID.setEditable(True)
        self.txtFoldID.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFoldID.setObjectName("txtFoldID")
        self.txtOFoldID = QtWidgets.QLineEdit(self.tab)
        self.txtOFoldID.setGeometry(QtCore.QRect(450, 500, 113, 21))
        self.txtOFoldID.setObjectName("txtOFoldID")
        self.txtFoldInfo = QtWidgets.QComboBox(self.tab)
        self.txtFoldInfo.setGeometry(QtCore.QRect(140, 540, 121, 26))
        self.txtFoldInfo.setEditable(True)
        self.txtFoldInfo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFoldInfo.setObjectName("txtFoldInfo")
        self.cbFoldInfo = QtWidgets.QCheckBox(self.tab)
        self.cbFoldInfo.setGeometry(QtCore.QRect(20, 540, 101, 20))
        self.cbFoldInfo.setChecked(True)
        self.cbFoldInfo.setObjectName("cbFoldInfo")
        self.txtOFoldInfo = QtWidgets.QLineEdit(self.tab)
        self.txtOFoldInfo.setGeometry(QtCore.QRect(450, 540, 113, 21))
        self.txtOFoldInfo.setObjectName("txtOFoldInfo")
        self.lbFoldID = QtWidgets.QLabel(self.tab)
        self.lbFoldID.setGeometry(QtCore.QRect(290, 500, 121, 16))
        self.lbFoldID.setObjectName("lbFoldID")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 140, 121, 16))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 671, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 191, 20))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.rbScale = QtWidgets.QRadioButton(self.groupBox)
        self.rbScale.setGeometry(QtCore.QRect(210, 40, 161, 20))
        self.rbScale.setChecked(True)
        self.rbScale.setObjectName("rbScale")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(370, 40, 131, 20))
        self.radioButton.setObjectName("radioButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 120, 671, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cbFTask = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbFTask.setGeometry(QtCore.QRect(490, 60, 161, 20))
        self.cbFTask.setObjectName("cbFTask")
        self.cbFCounter = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbFCounter.setGeometry(QtCore.QRect(490, 100, 161, 20))
        self.cbFCounter.setObjectName("cbFCounter")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 30, 451, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cbFSubject = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbFSubject.setGeometry(QtCore.QRect(10, 30, 130, 20))
        self.cbFSubject.setChecked(True)
        self.cbFSubject.setObjectName("cbFSubject")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 60, 201, 20))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.rbFRun = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbFRun.setGeometry(QtCore.QRect(220, 60, 221, 20))
        self.rbFRun.setObjectName("rbFRun")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(30, 290, 221, 16))
        self.label_11.setObjectName("label_11")
        self.txtRegularization = QtWidgets.QLineEdit(self.tab_2)
        self.txtRegularization.setGeometry(QtCore.QRect(260, 290, 160, 21))
        self.txtRegularization.setObjectName("txtRegularization")
        self.cbOptim = QtWidgets.QComboBox(self.tab_2)
        self.cbOptim.setGeometry(QtCore.QRect(260, 370, 161, 26))
        self.cbOptim.setObjectName("cbOptim")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 330, 201, 16))
        self.label_15.setObjectName("label_15")
        self.txtRate = QtWidgets.QLineEdit(self.tab_2)
        self.txtRate.setGeometry(QtCore.QRect(260, 490, 160, 21))
        self.txtRate.setObjectName("txtRate")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(30, 450, 201, 16))
        self.label_16.setObjectName("label_16")
        self.txtEpoch = QtWidgets.QLineEdit(self.tab_2)
        self.txtEpoch.setGeometry(QtCore.QRect(260, 450, 160, 21))
        self.txtEpoch.setObjectName("txtEpoch")
        self.cbLossType = QtWidgets.QComboBox(self.tab_2)
        self.cbLossType.setGeometry(QtCore.QRect(260, 330, 161, 26))
        self.cbLossType.setObjectName("cbLossType")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(30, 490, 201, 16))
        self.label_19.setObjectName("label_19")
        self.cbVerbose = QtWidgets.QCheckBox(self.tab_2)
        self.cbVerbose.setGeometry(QtCore.QRect(440, 330, 371, 20))
        self.cbVerbose.setChecked(True)
        self.cbVerbose.setObjectName("cbVerbose")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(30, 370, 201, 16))
        self.label_20.setObjectName("label_20")
        self.cbBest = QtWidgets.QCheckBox(self.tab_2)
        self.cbBest.setGeometry(QtCore.QRect(440, 290, 280, 20))
        self.cbBest.setChecked(True)
        self.cbBest.setObjectName("cbBest")
        self.txtIter = QtWidgets.QLineEdit(self.tab_2)
        self.txtIter.setGeometry(QtCore.QRect(260, 410, 160, 21))
        self.txtIter.setObjectName("txtIter")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(30, 410, 221, 16))
        self.label_21.setObjectName("label_21")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.txtFoldFrom = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldFrom.setGeometry(QtCore.QRect(100, 30, 80, 24))
        self.txtFoldFrom.setMaximum(100000)
        self.txtFoldFrom.setProperty("value", 1)
        self.txtFoldFrom.setObjectName("txtFoldFrom")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(40, 30, 60, 16))
        self.label_17.setObjectName("label_17")
        self.txtFoldTo = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldTo.setGeometry(QtCore.QRect(270, 30, 80, 24))
        self.txtFoldTo.setMaximum(100000)
        self.txtFoldTo.setProperty("value", 1)
        self.txtFoldTo.setObjectName("txtFoldTo")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(210, 30, 60, 16))
        self.label_44.setObjectName("label_44")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.btnDown = QtWidgets.QPushButton(self.tab_4)
        self.btnDown.setGeometry(QtCore.QRect(551, 85, 161, 32))
        self.btnDown.setObjectName("btnDown")
        self.tbModel = QtWidgets.QTableWidget(self.tab_4)
        self.tbModel.setGeometry(QtCore.QRect(16, 36, 521, 371))
        self.tbModel.setObjectName("tbModel")
        self.tbModel.setColumnCount(0)
        self.tbModel.setRowCount(0)
        self.btnAdd = QtWidgets.QPushButton(self.tab_4)
        self.btnAdd.setGeometry(QtCore.QRect(551, 130, 161, 32))
        self.btnAdd.setObjectName("btnAdd")
        self.btnClearNet = QtWidgets.QPushButton(self.tab_4)
        self.btnClearNet.setGeometry(QtCore.QRect(551, 220, 161, 32))
        self.btnClearNet.setObjectName("btnClearNet")
        self.btnSaveNet = QtWidgets.QPushButton(self.tab_4)
        self.btnSaveNet.setGeometry(QtCore.QRect(552, 370, 160, 32))
        self.btnSaveNet.setObjectName("btnSaveNet")
        self.btnLoadNet = QtWidgets.QPushButton(self.tab_4)
        self.btnLoadNet.setGeometry(QtCore.QRect(551, 325, 161, 32))
        self.btnLoadNet.setObjectName("btnLoadNet")
        self.btnDelete = QtWidgets.QPushButton(self.tab_4)
        self.btnDelete.setGeometry(QtCore.QRect(551, 175, 161, 32))
        self.btnDelete.setObjectName("btnDelete")
        self.btnUp = QtWidgets.QPushButton(self.tab_4)
        self.btnUp.setGeometry(QtCore.QRect(551, 40, 161, 32))
        self.btnUp.setObjectName("btnUp")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 430, 691, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.cbOutAF = QtWidgets.QComboBox(self.groupBox_4)
        self.cbOutAF.setGeometry(QtCore.QRect(180, 40, 251, 23))
        self.cbOutAF.setObjectName("cbOutAF")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 151, 20))
        self.label_13.setObjectName("label_13")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.label_4.setObjectName("label_4")
        self.lblFeaNum = QtWidgets.QLabel(self.groupBox_4)
        self.lblFeaNum.setGeometry(QtCore.QRect(360, 80, 191, 16))
        self.lblFeaNum.setObjectName("lblFeaNum")
        self.txtNumFea = QtWidgets.QSpinBox(self.groupBox_4)
        self.txtNumFea.setGeometry(QtCore.QRect(180, 80, 161, 24))
        self.txtNumFea.setMinimum(0)
        self.txtNumFea.setMaximum(10000000)
        self.txtNumFea.setObjectName("txtNumFea")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 281, 16))
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_4, "")
        self.label_12 = QtWidgets.QLabel(frmFADHA)
        self.label_12.setGeometry(QtCore.QRect(185, 765, 421, 20))
        self.label_12.setObjectName("label_12")
        self.label_26 = QtWidgets.QLabel(frmFADHA)
        self.label_26.setGeometry(QtCore.QRect(510, 102, 81, 16))
        self.label_26.setObjectName("label_26")
        self.cbDevice = QtWidgets.QComboBox(frmFADHA)
        self.cbDevice.setGeometry(QtCore.QRect(590, 102, 171, 26))
        self.cbDevice.setObjectName("cbDevice")

        self.retranslateUi(frmFADHA)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmFADHA)
        frmFADHA.setTabOrder(self.txtInFile, self.btnInFile)
        frmFADHA.setTabOrder(self.btnInFile, self.txtOutFile)
        frmFADHA.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmFADHA.setTabOrder(self.btnOutFile, self.tabWidget)
        frmFADHA.setTabOrder(self.tabWidget, self.cbmLabel)
        frmFADHA.setTabOrder(self.cbmLabel, self.cbCol)
        frmFADHA.setTabOrder(self.cbCol, self.cbDM)
        frmFADHA.setTabOrder(self.cbDM, self.cbTask)
        frmFADHA.setTabOrder(self.cbTask, self.cbRun)
        frmFADHA.setTabOrder(self.cbRun, self.cbCounter)
        frmFADHA.setTabOrder(self.cbCounter, self.cbCond)
        frmFADHA.setTabOrder(self.cbCond, self.cbNScan)
        frmFADHA.setTabOrder(self.cbNScan, self.txtITrData)
        frmFADHA.setTabOrder(self.txtITrData, self.txtITrLabel)
        frmFADHA.setTabOrder(self.txtITrLabel, self.txtITrSubject)
        frmFADHA.setTabOrder(self.txtITrSubject, self.txtITrmLabel)
        frmFADHA.setTabOrder(self.txtITrmLabel, self.txtCol)
        frmFADHA.setTabOrder(self.txtCol, self.txtITrDM)
        frmFADHA.setTabOrder(self.txtITrDM, self.txtITrTask)
        frmFADHA.setTabOrder(self.txtITrTask, self.txtITrRun)
        frmFADHA.setTabOrder(self.txtITrRun, self.txtITrCounter)
        frmFADHA.setTabOrder(self.txtITrCounter, self.txtITrScan)
        frmFADHA.setTabOrder(self.txtITrScan, self.txtOTrData)
        frmFADHA.setTabOrder(self.txtOTrData, self.txtOTrLabel)
        frmFADHA.setTabOrder(self.txtOTrLabel, self.txtOTrSubject)
        frmFADHA.setTabOrder(self.txtOTrSubject, self.txtOTrmLabel)
        frmFADHA.setTabOrder(self.txtOTrmLabel, self.txtOCol)
        frmFADHA.setTabOrder(self.txtOCol, self.txtOTrDM)
        frmFADHA.setTabOrder(self.txtOTrDM, self.txtOTrTask)
        frmFADHA.setTabOrder(self.txtOTrTask, self.txtOTrRun)
        frmFADHA.setTabOrder(self.txtOTrRun, self.txtOTrCounter)
        frmFADHA.setTabOrder(self.txtOTrCounter, self.txtOCond)
        frmFADHA.setTabOrder(self.txtOCond, self.txtOTrScan)
        frmFADHA.setTabOrder(self.txtOTrScan, self.txtCond)
        frmFADHA.setTabOrder(self.txtCond, self.btnConvert)
        frmFADHA.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmFADHA):
        _translate = QtCore.QCoreApplication.translate
        frmFADHA.setWindowTitle(_translate("frmFADHA", "Deep Hyperalignment"))
        self.btnInFile.setText(_translate("frmFADHA", "..."))
        self.label_33.setText(_translate("frmFADHA", "Input Data"))
        self.btnOutFile.setText(_translate("frmFADHA", "..."))
        self.btnConvert.setText(_translate("frmFADHA", "Alignment"))
        self.label_35.setText(_translate("frmFADHA", "Output Data"))
        self.btnClose.setText(_translate("frmFADHA", "Close"))
        self.txtOTrTask.setText(_translate("frmFADHA", "train_task"))
        self.cbmLabel.setText(_translate("frmFADHA", "Label (matrix)"))
        self.txtOTrmLabel.setText(_translate("frmFADHA", "train_mlabel"))
        self.label_2.setText(_translate("frmFADHA", "Data"))
        self.txtOTrDM.setText(_translate("frmFADHA", "train_design"))
        self.cbTask.setText(_translate("frmFADHA", "Task"))
        self.label_3.setText(_translate("frmFADHA", "Label"))
        self.cbNScan.setText(_translate("frmFADHA", "NScan"))
        self.cbCond.setText(_translate("frmFADHA", "Condition"))
        self.cbDM.setText(_translate("frmFADHA", "Design Matrix"))
        self.cbCol.setText(_translate("frmFADHA", "Coordinate"))
        self.txtOCond.setText(_translate("frmFADHA", "condition"))
        self.label.setText(_translate("frmFADHA", "Input"))
        self.txtOTrLabel.setText(_translate("frmFADHA", "train_label"))
        self.txtOTrScan.setText(_translate("frmFADHA", "train_nscan"))
        self.cbCounter.setText(_translate("frmFADHA", "Counter"))
        self.txtOCol.setText(_translate("frmFADHA", "coordinate"))
        self.label_5.setText(_translate("frmFADHA", "Output"))
        self.txtOTrCounter.setText(_translate("frmFADHA", "train_counter"))
        self.txtOTrSubject.setText(_translate("frmFADHA", "train_subject"))
        self.cbRun.setText(_translate("frmFADHA", "Run"))
        self.txtOTrData.setText(_translate("frmFADHA", "train_data"))
        self.txtOTrRun.setText(_translate("frmFADHA", "train_run"))
        self.txtOTeLabel.setText(_translate("frmFADHA", "test_label"))
        self.txtOTeRun.setText(_translate("frmFADHA", "test_run"))
        self.txtOTemLabel.setText(_translate("frmFADHA", "test_mlabel"))
        self.txtOTeDM.setText(_translate("frmFADHA", "test_design"))
        self.txtOTeData.setText(_translate("frmFADHA", "test_data"))
        self.txtOTeCounter.setText(_translate("frmFADHA", "test_counter"))
        self.txtOTeSubject.setText(_translate("frmFADHA", "test_subject"))
        self.txtOTeTask.setText(_translate("frmFADHA", "test_task"))
        self.txtOTeScan.setText(_translate("frmFADHA", "test_nscan"))
        self.label_7.setText(_translate("frmFADHA", "Train"))
        self.label_8.setText(_translate("frmFADHA", "Test"))
        self.label_9.setText(_translate("frmFADHA", "Train"))
        self.label_10.setText(_translate("frmFADHA", "Test"))
        self.cbFoldID.setText(_translate("frmFADHA", "FoldID"))
        self.txtOFoldID.setText(_translate("frmFADHA", "FoldID"))
        self.cbFoldInfo.setText(_translate("frmFADHA", "FoldInfo"))
        self.txtOFoldInfo.setText(_translate("frmFADHA", "FoldInfo"))
        self.lbFoldID.setText(_translate("frmFADHA", "ID=None"))
        self.label_6.setText(_translate("frmFADHA", "Subject"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmFADHA", "Data"))
        self.groupBox.setTitle(_translate("frmFADHA", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmFADHA", "Scale Data X~N(0,1)"))
        self.rbScale.setText(_translate("frmFADHA", "Subject Level"))
        self.radioButton.setText(_translate("frmFADHA", "Whole Data"))
        self.groupBox_2.setTitle(_translate("frmFADHA", "<Alignment Level>"))
        self.cbFTask.setText(_translate("frmFADHA", "Task"))
        self.cbFCounter.setText(_translate("frmFADHA", "Counter"))
        self.groupBox_3.setTitle(_translate("frmFADHA", "<Subject Level>"))
        self.cbFSubject.setText(_translate("frmFADHA", "Subject"))
        self.radioButton_2.setText(_translate("frmFADHA", "Without Run"))
        self.rbFRun.setText(_translate("frmFADHA", "With Run"))
        self.label_11.setText(_translate("frmFADHA", "Regularization"))
        self.txtRegularization.setText(_translate("frmFADHA", "0.0001"))
        self.label_15.setText(_translate("frmFADHA", "Loss Type"))
        self.txtRate.setText(_translate("frmFADHA", "0.1"))
        self.label_16.setText(_translate("frmFADHA", "Epoch"))
        self.txtEpoch.setText(_translate("frmFADHA", "10"))
        self.label_19.setText(_translate("frmFADHA", "Learning Rate"))
        self.cbVerbose.setText(_translate("frmFADHA", "Verbose"))
        self.label_20.setText(_translate("frmFADHA", "Optimization"))
        self.cbBest.setText(_translate("frmFADHA", "Choose Best Result Automatically"))
        self.txtIter.setText(_translate("frmFADHA", "10"))
        self.label_21.setText(_translate("frmFADHA", "Iterations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmFADHA", "Parameters"))
        self.label_17.setText(_translate("frmFADHA", "From:"))
        self.label_44.setText(_translate("frmFADHA", "To:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmFADHA", "Fold"))
        self.btnDown.setText(_translate("frmFADHA", "Move Down"))
        self.btnAdd.setText(_translate("frmFADHA", "Add"))
        self.btnClearNet.setText(_translate("frmFADHA", "Clear"))
        self.btnSaveNet.setText(_translate("frmFADHA", "Save"))
        self.btnLoadNet.setText(_translate("frmFADHA", "Load"))
        self.btnDelete.setText(_translate("frmFADHA", "Delete"))
        self.btnUp.setText(_translate("frmFADHA", "Move Up"))
        self.groupBox_4.setTitle(_translate("frmFADHA", "<Output Layer>"))
        self.label_13.setText(_translate("frmFADHA", "Activation Function:"))
        self.label_4.setText(_translate("frmFADHA", "Number of features:"))
        self.lblFeaNum.setText(_translate("frmFADHA", "No Data"))
        self.label_14.setText(_translate("frmFADHA", "Hidden Layers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmFADHA", "Network"))
        self.label_12.setText(_translate("frmFADHA", "$FOLD$ will be replaced by fold number."))
        self.label_26.setText(_translate("frmFADHA", "Device"))

