# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMAGPUSVMGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMAGPUSVM(object):
    def setupUi(self, frmMAGPUSVM):
        frmMAGPUSVM.setObjectName("frmMAGPUSVM")
        frmMAGPUSVM.resize(782, 764)
        self.btnInFile = QtWidgets.QPushButton(frmMAGPUSVM)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMAGPUSVM)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.btnOutFile = QtWidgets.QPushButton(frmMAGPUSVM)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.txtInFile = QtWidgets.QLineEdit(frmMAGPUSVM)
        self.txtInFile.setGeometry(QtCore.QRect(210, 20, 491, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMAGPUSVM)
        self.btnConvert.setGeometry(QtCore.QRect(620, 715, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label_35 = QtWidgets.QLabel(frmMAGPUSVM)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 211, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMAGPUSVM)
        self.txtOutFile.setGeometry(QtCore.QRect(210, 60, 491, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnClose = QtWidgets.QPushButton(frmMAGPUSVM)
        self.btnClose.setGeometry(QtCore.QRect(30, 715, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMAGPUSVM)
        self.tabWidget.setGeometry(QtCore.QRect(30, 150, 731, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(310, 10, 61, 16))
        self.label.setObjectName("label")
        self.txtITrLabel = QtWidgets.QComboBox(self.tab)
        self.txtITrLabel.setGeometry(QtCore.QRect(190, 110, 121, 26))
        self.txtITrLabel.setEditable(True)
        self.txtITrLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrLabel.setObjectName("txtITrLabel")
        self.txtITrData = QtWidgets.QComboBox(self.tab)
        self.txtITrData.setGeometry(QtCore.QRect(190, 70, 121, 26))
        self.txtITrData.setEditable(True)
        self.txtITrData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrData.setObjectName("txtITrData")
        self.txtITeLabel = QtWidgets.QComboBox(self.tab)
        self.txtITeLabel.setGeometry(QtCore.QRect(340, 110, 121, 26))
        self.txtITeLabel.setEditable(True)
        self.txtITeLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeLabel.setObjectName("txtITeLabel")
        self.txtITeData = QtWidgets.QComboBox(self.tab)
        self.txtITeData.setGeometry(QtCore.QRect(340, 70, 121, 26))
        self.txtITeData.setEditable(True)
        self.txtITeData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeData.setObjectName("txtITeData")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(235, 40, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(380, 40, 81, 16))
        self.label_8.setObjectName("label_8")
        self.txtFoldID = QtWidgets.QComboBox(self.tab)
        self.txtFoldID.setGeometry(QtCore.QRect(190, 190, 270, 26))
        self.txtFoldID.setEditable(True)
        self.txtFoldID.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFoldID.setObjectName("txtFoldID")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 190, 121, 16))
        self.label_9.setObjectName("label_9")
        self.lbFoldID = QtWidgets.QLabel(self.tab)
        self.lbFoldID.setGeometry(QtCore.QRect(500, 190, 210, 16))
        self.lbFoldID.setObjectName("lbFoldID")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(20, 150, 131, 16))
        self.label_31.setObjectName("label_31")
        self.txtCond = QtWidgets.QComboBox(self.tab)
        self.txtCond.setGeometry(QtCore.QRect(190, 150, 271, 26))
        self.txtCond.setEditable(True)
        self.txtCond.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCond.setObjectName("txtCond")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 671, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 641, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.txtRate = QtWidgets.QLineEdit(self.tab_2)
        self.txtRate.setGeometry(QtCore.QRect(260, 400, 160, 21))
        self.txtRate.setObjectName("txtRate")
        self.txtPer = QtWidgets.QLineEdit(self.tab_2)
        self.txtPer.setGeometry(QtCore.QRect(260, 440, 160, 21))
        self.txtPer.setObjectName("txtPer")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(30, 440, 221, 16))
        self.label_14.setObjectName("label_14")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(30, 400, 221, 16))
        self.label_11.setObjectName("label_11")
        self.lblFeaNum_5 = QtWidgets.QLabel(self.tab_2)
        self.lblFeaNum_5.setGeometry(QtCore.QRect(440, 440, 281, 16))
        self.lblFeaNum_5.setObjectName("lblFeaNum_5")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(30, 360, 221, 16))
        self.label_20.setObjectName("label_20")
        self.txtC = QtWidgets.QLineEdit(self.tab_2)
        self.txtC.setGeometry(QtCore.QRect(260, 360, 160, 21))
        self.txtC.setObjectName("txtC")
        self.cbVerbose = QtWidgets.QCheckBox(self.tab_2)
        self.cbVerbose.setGeometry(QtCore.QRect(30, 480, 131, 20))
        self.cbVerbose.setChecked(True)
        self.cbVerbose.setObjectName("cbVerbose")
        self.cbNorm2 = QtWidgets.QCheckBox(self.tab_2)
        self.cbNorm2.setGeometry(QtCore.QRect(180, 480, 231, 20))
        self.cbNorm2.setChecked(True)
        self.cbNorm2.setObjectName("cbNorm2")
        self.txtEpoch = QtWidgets.QLineEdit(self.tab_2)
        self.txtEpoch.setGeometry(QtCore.QRect(260, 280, 160, 21))
        self.txtEpoch.setObjectName("txtEpoch")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(30, 280, 221, 16))
        self.label_21.setObjectName("label_21")
        self.txtBatch = QtWidgets.QLineEdit(self.tab_2)
        self.txtBatch.setGeometry(QtCore.QRect(260, 320, 160, 21))
        self.txtBatch.setObjectName("txtBatch")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(30, 320, 221, 16))
        self.label_22.setObjectName("label_22")
        self.cbOptim = QtWidgets.QComboBox(self.tab_2)
        self.cbOptim.setGeometry(QtCore.QRect(260, 120, 161, 26))
        self.cbOptim.setObjectName("cbOptim")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 120, 201, 16))
        self.label_15.setObjectName("label_15")
        self.cbKernel = QtWidgets.QComboBox(self.tab_2)
        self.cbKernel.setGeometry(QtCore.QRect(260, 160, 161, 26))
        self.cbKernel.setObjectName("cbKernel")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(30, 160, 201, 16))
        self.label_16.setObjectName("label_16")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(30, 200, 221, 16))
        self.label_23.setObjectName("label_23")
        self.txtGamma = QtWidgets.QLineEdit(self.tab_2)
        self.txtGamma.setGeometry(QtCore.QRect(260, 200, 160, 21))
        self.txtGamma.setObjectName("txtGamma")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(30, 240, 221, 16))
        self.label_24.setObjectName("label_24")
        self.txtDegree = QtWidgets.QLineEdit(self.tab_2)
        self.txtDegree.setGeometry(QtCore.QRect(260, 240, 160, 21))
        self.txtDegree.setObjectName("txtDegree")
        self.cbNorm1 = QtWidgets.QCheckBox(self.tab_2)
        self.cbNorm1.setGeometry(QtCore.QRect(390, 480, 231, 20))
        self.cbNorm1.setChecked(False)
        self.cbNorm1.setObjectName("cbNorm1")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.txtFoldFrom = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldFrom.setGeometry(QtCore.QRect(100, 30, 80, 24))
        self.txtFoldFrom.setMaximum(100000)
        self.txtFoldFrom.setProperty("value", 1)
        self.txtFoldFrom.setObjectName("txtFoldFrom")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(40, 30, 60, 16))
        self.label_17.setObjectName("label_17")
        self.txtFoldTo = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldTo.setGeometry(QtCore.QRect(270, 30, 80, 24))
        self.txtFoldTo.setMaximum(100000)
        self.txtFoldTo.setProperty("value", 1)
        self.txtFoldTo.setObjectName("txtFoldTo")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(210, 30, 60, 16))
        self.label_44.setObjectName("label_44")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 431))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbAverage = QtWidgets.QCheckBox(self.tab_5)
        self.cbAverage.setGeometry(QtCore.QRect(20, 30, 181, 20))
        self.cbAverage.setChecked(True)
        self.cbAverage.setObjectName("cbAverage")
        self.cbPrecision = QtWidgets.QCheckBox(self.tab_5)
        self.cbPrecision.setGeometry(QtCore.QRect(20, 70, 181, 20))
        self.cbPrecision.setChecked(True)
        self.cbPrecision.setObjectName("cbPrecision")
        self.cbPrecisionAvg = QtWidgets.QComboBox(self.tab_5)
        self.cbPrecisionAvg.setGeometry(QtCore.QRect(240, 70, 321, 26))
        self.cbPrecisionAvg.setObjectName("cbPrecisionAvg")
        self.cbAPrecisionAvg = QtWidgets.QComboBox(self.tab_5)
        self.cbAPrecisionAvg.setGeometry(QtCore.QRect(240, 110, 321, 26))
        self.cbAPrecisionAvg.setObjectName("cbAPrecisionAvg")
        self.cbAPrecision = QtWidgets.QCheckBox(self.tab_5)
        self.cbAPrecision.setGeometry(QtCore.QRect(20, 110, 231, 20))
        self.cbAPrecision.setChecked(False)
        self.cbAPrecision.setObjectName("cbAPrecision")
        self.cbRecallAvg = QtWidgets.QComboBox(self.tab_5)
        self.cbRecallAvg.setGeometry(QtCore.QRect(240, 150, 321, 26))
        self.cbRecallAvg.setObjectName("cbRecallAvg")
        self.cbRecall = QtWidgets.QCheckBox(self.tab_5)
        self.cbRecall.setGeometry(QtCore.QRect(20, 150, 181, 20))
        self.cbRecall.setChecked(True)
        self.cbRecall.setObjectName("cbRecall")
        self.cbF1 = QtWidgets.QCheckBox(self.tab_5)
        self.cbF1.setGeometry(QtCore.QRect(20, 190, 181, 20))
        self.cbF1.setChecked(True)
        self.cbF1.setObjectName("cbF1")
        self.cbF1Avg = QtWidgets.QComboBox(self.tab_5)
        self.cbF1Avg.setGeometry(QtCore.QRect(240, 190, 321, 26))
        self.cbF1Avg.setObjectName("cbF1Avg")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_37 = QtWidgets.QLabel(self.tab_6)
        self.label_37.setGeometry(QtCore.QRect(20, 50, 131, 16))
        self.label_37.setObjectName("label_37")
        self.btnOutSim = QtWidgets.QPushButton(self.tab_6)
        self.btnOutSim.setGeometry(QtCore.QRect(660, 50, 51, 32))
        self.btnOutSim.setObjectName("btnOutSim")
        self.txtOutSim = QtWidgets.QLineEdit(self.tab_6)
        self.txtOutSim.setGeometry(QtCore.QRect(148, 50, 491, 21))
        self.txtOutSim.setText("")
        self.txtOutSim.setObjectName("txtOutSim")
        self.cbSimDend = QtWidgets.QCheckBox(self.tab_6)
        self.cbSimDend.setGeometry(QtCore.QRect(20, 100, 321, 21))
        self.cbSimDend.setChecked(True)
        self.cbSimDend.setObjectName("cbSimDend")
        self.cbSimMatrix = QtWidgets.QCheckBox(self.tab_6)
        self.cbSimMatrix.setGeometry(QtCore.QRect(20, 140, 321, 21))
        self.cbSimMatrix.setChecked(False)
        self.cbSimMatrix.setObjectName("cbSimMatrix")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.label_27 = QtWidgets.QLabel(self.tab_13)
        self.label_27.setGeometry(QtCore.QRect(20, 38, 71, 16))
        self.label_27.setObjectName("label_27")
        self.txtTitleDen = QtWidgets.QLineEdit(self.tab_13)
        self.txtTitleDen.setGeometry(QtCore.QRect(260, 144, 450, 35))
        self.txtTitleDen.setObjectName("txtTitleDen")
        self.txtFontSize = QtWidgets.QSpinBox(self.tab_13)
        self.txtFontSize.setGeometry(QtCore.QRect(260, 32, 171, 35))
        self.txtFontSize.setMinimum(1)
        self.txtFontSize.setMaximum(1000)
        self.txtFontSize.setProperty("value", 14)
        self.txtFontSize.setObjectName("txtFontSize")
        self.txtTitleCorr = QtWidgets.QLineEdit(self.tab_13)
        self.txtTitleCorr.setGeometry(QtCore.QRect(260, 89, 450, 35))
        self.txtTitleCorr.setObjectName("txtTitleCorr")
        self.label_28 = QtWidgets.QLabel(self.tab_13)
        self.label_28.setGeometry(QtCore.QRect(20, 89, 221, 20))
        self.label_28.setObjectName("label_28")
        self.label_30 = QtWidgets.QLabel(self.tab_13)
        self.label_30.setGeometry(QtCore.QRect(20, 150, 221, 20))
        self.label_30.setObjectName("label_30")
        self.tabWidget.addTab(self.tab_13, "")
        self.label_12 = QtWidgets.QLabel(frmMAGPUSVM)
        self.label_12.setGeometry(QtCore.QRect(185, 720, 421, 20))
        self.label_12.setObjectName("label_12")
        self.btnOutModel = QtWidgets.QPushButton(frmMAGPUSVM)
        self.btnOutModel.setGeometry(QtCore.QRect(710, 100, 51, 32))
        self.btnOutModel.setObjectName("btnOutModel")
        self.label_36 = QtWidgets.QLabel(frmMAGPUSVM)
        self.label_36.setGeometry(QtCore.QRect(30, 100, 231, 16))
        self.label_36.setObjectName("label_36")
        self.txtOutModel = QtWidgets.QLineEdit(frmMAGPUSVM)
        self.txtOutModel.setGeometry(QtCore.QRect(210, 100, 491, 21))
        self.txtOutModel.setText("")
        self.txtOutModel.setObjectName("txtOutModel")
        self.btnRedraw = QtWidgets.QPushButton(frmMAGPUSVM)
        self.btnRedraw.setGeometry(QtCore.QRect(460, 715, 141, 32))
        self.btnRedraw.setObjectName("btnRedraw")

        self.retranslateUi(frmMAGPUSVM)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMAGPUSVM)
        frmMAGPUSVM.setTabOrder(self.txtInFile, self.btnInFile)
        frmMAGPUSVM.setTabOrder(self.btnInFile, self.txtOutFile)
        frmMAGPUSVM.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmMAGPUSVM.setTabOrder(self.btnOutFile, self.tabWidget)
        frmMAGPUSVM.setTabOrder(self.tabWidget, self.txtITrData)
        frmMAGPUSVM.setTabOrder(self.txtITrData, self.txtITrLabel)
        frmMAGPUSVM.setTabOrder(self.txtITrLabel, self.btnConvert)
        frmMAGPUSVM.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMAGPUSVM):
        _translate = QtCore.QCoreApplication.translate
        frmMAGPUSVM.setWindowTitle(_translate("frmMAGPUSVM", "GPU Support Vector Classification"))
        self.btnInFile.setText(_translate("frmMAGPUSVM", "..."))
        self.label_33.setText(_translate("frmMAGPUSVM", "Input Data (per fold)"))
        self.btnOutFile.setText(_translate("frmMAGPUSVM", "..."))
        self.btnConvert.setText(_translate("frmMAGPUSVM", "Analyze"))
        self.label_35.setText(_translate("frmMAGPUSVM", "Analysis Results"))
        self.btnClose.setText(_translate("frmMAGPUSVM", "Close"))
        self.label_2.setText(_translate("frmMAGPUSVM", "Data"))
        self.label_3.setText(_translate("frmMAGPUSVM", "Label"))
        self.label.setText(_translate("frmMAGPUSVM", "Input"))
        self.label_7.setText(_translate("frmMAGPUSVM", "Train"))
        self.label_8.setText(_translate("frmMAGPUSVM", "Test"))
        self.label_9.setText(_translate("frmMAGPUSVM", "FoldID"))
        self.lbFoldID.setText(_translate("frmMAGPUSVM", "ID=None"))
        self.label_31.setText(_translate("frmMAGPUSVM", "Condition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMAGPUSVM", "Data"))
        self.groupBox.setTitle(_translate("frmMAGPUSVM", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMAGPUSVM", "Scale Data Train~N(0,1) and Test~N(0,1)"))
        self.txtRate.setText(_translate("frmMAGPUSVM", "0.1"))
        self.txtPer.setText(_translate("frmMAGPUSVM", "0.5"))
        self.label_14.setText(_translate("frmMAGPUSVM", "Percentage of iteration per batch"))
        self.label_11.setText(_translate("frmMAGPUSVM", "Learning Rate"))
        self.lblFeaNum_5.setText(_translate("frmMAGPUSVM", "between 0 and 1"))
        self.label_20.setText(_translate("frmMAGPUSVM", "C"))
        self.txtC.setText(_translate("frmMAGPUSVM", "0.1"))
        self.cbVerbose.setText(_translate("frmMAGPUSVM", "Verbose"))
        self.cbNorm2.setText(_translate("frmMAGPUSVM", "Apply norm 2 penalty"))
        self.txtEpoch.setText(_translate("frmMAGPUSVM", "10"))
        self.label_21.setText(_translate("frmMAGPUSVM", "Epoch"))
        self.txtBatch.setText(_translate("frmMAGPUSVM", "10"))
        self.label_22.setText(_translate("frmMAGPUSVM", "Batch Size"))
        self.label_15.setText(_translate("frmMAGPUSVM", "Optimization"))
        self.label_16.setText(_translate("frmMAGPUSVM", "Kernel"))
        self.label_23.setText(_translate("frmMAGPUSVM", "Gamma (for rbf kernel, 0 = auto)"))
        self.txtGamma.setText(_translate("frmMAGPUSVM", "0"))
        self.label_24.setText(_translate("frmMAGPUSVM", "Degree"))
        self.txtDegree.setText(_translate("frmMAGPUSVM", "3"))
        self.cbNorm1.setText(_translate("frmMAGPUSVM", "Apply norm 1 penalty"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMAGPUSVM", "Parameters"))
        self.label_17.setText(_translate("frmMAGPUSVM", "From:"))
        self.label_44.setText(_translate("frmMAGPUSVM", "To:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmMAGPUSVM", "Fold"))
        self.label_4.setText(_translate("frmMAGPUSVM", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMAGPUSVM", "0"))
        self.label_5.setText(_translate("frmMAGPUSVM", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMAGPUSVM", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMAGPUSVM", "Filter Class ID"))
        self.cbAverage.setText(_translate("frmMAGPUSVM", "Average"))
        self.cbPrecision.setText(_translate("frmMAGPUSVM", "Precision"))
        self.cbAPrecision.setText(_translate("frmMAGPUSVM", "Average of Precision"))
        self.cbRecall.setText(_translate("frmMAGPUSVM", "Recall"))
        self.cbF1.setText(_translate("frmMAGPUSVM", "f1 score"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMAGPUSVM", "Metrics"))
        self.label_37.setText(_translate("frmMAGPUSVM", "Similarity results"))
        self.btnOutSim.setText(_translate("frmMAGPUSVM", "..."))
        self.cbSimDend.setText(_translate("frmMAGPUSVM", "Dendrogram"))
        self.cbSimMatrix.setText(_translate("frmMAGPUSVM", "Similarity Marix"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("frmMAGPUSVM", "Similarity"))
        self.label_27.setText(_translate("frmMAGPUSVM", "Font Size"))
        self.label_28.setText(_translate("frmMAGPUSVM", "Figure Title: Sim Mat (Null = Auto)"))
        self.label_30.setText(_translate("frmMAGPUSVM", "Figure Title: Den (Null = Auto)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("frmMAGPUSVM", "Options"))
        self.label_12.setText(_translate("frmMAGPUSVM", "$FOLD$ will be replaced by fold number."))
        self.btnOutModel.setText(_translate("frmMAGPUSVM", "..."))
        self.label_36.setText(_translate("frmMAGPUSVM", "Models (per fold/opt)"))
        self.btnRedraw.setText(_translate("frmMAGPUSVM", "Redraw"))

