# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMAMLPGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMAMLP(object):
    def setupUi(self, frmMAMLP):
        frmMAMLP.setObjectName("frmMAMLP")
        frmMAMLP.resize(851, 774)
        self.btnInFile = QtWidgets.QPushButton(frmMAMLP)
        self.btnInFile.setGeometry(QtCore.QRect(780, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMAMLP)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.btnOutFile = QtWidgets.QPushButton(frmMAMLP)
        self.btnOutFile.setGeometry(QtCore.QRect(780, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.txtInFile = QtWidgets.QLineEdit(frmMAMLP)
        self.txtInFile.setGeometry(QtCore.QRect(210, 20, 561, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMAMLP)
        self.btnConvert.setGeometry(QtCore.QRect(690, 725, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label_35 = QtWidgets.QLabel(frmMAMLP)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 211, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMAMLP)
        self.txtOutFile.setGeometry(QtCore.QRect(210, 60, 561, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnClose = QtWidgets.QPushButton(frmMAMLP)
        self.btnClose.setGeometry(QtCore.QRect(30, 725, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMAMLP)
        self.tabWidget.setGeometry(QtCore.QRect(30, 150, 801, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(390, 10, 61, 16))
        self.label.setObjectName("label")
        self.txtITrLabel = QtWidgets.QComboBox(self.tab)
        self.txtITrLabel.setGeometry(QtCore.QRect(270, 110, 121, 26))
        self.txtITrLabel.setEditable(True)
        self.txtITrLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrLabel.setObjectName("txtITrLabel")
        self.txtITrData = QtWidgets.QComboBox(self.tab)
        self.txtITrData.setGeometry(QtCore.QRect(270, 70, 121, 26))
        self.txtITrData.setEditable(True)
        self.txtITrData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrData.setObjectName("txtITrData")
        self.txtITeLabel = QtWidgets.QComboBox(self.tab)
        self.txtITeLabel.setGeometry(QtCore.QRect(420, 110, 121, 26))
        self.txtITeLabel.setEditable(True)
        self.txtITeLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeLabel.setObjectName("txtITeLabel")
        self.txtITeData = QtWidgets.QComboBox(self.tab)
        self.txtITeData.setGeometry(QtCore.QRect(420, 70, 121, 26))
        self.txtITeData.setEditable(True)
        self.txtITeData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeData.setObjectName("txtITeData")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(315, 40, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(460, 40, 81, 16))
        self.label_8.setObjectName("label_8")
        self.txtFoldID = QtWidgets.QComboBox(self.tab)
        self.txtFoldID.setGeometry(QtCore.QRect(270, 150, 121, 26))
        self.txtFoldID.setEditable(True)
        self.txtFoldID.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFoldID.setObjectName("txtFoldID")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 121, 16))
        self.label_9.setObjectName("label_9")
        self.lbFoldID = QtWidgets.QLabel(self.tab)
        self.lbFoldID.setGeometry(QtCore.QRect(420, 150, 251, 16))
        self.lbFoldID.setObjectName("lbFoldID")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 751, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 721, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.txtBatchSize = QtWidgets.QLineEdit(self.tab_2)
        self.txtBatchSize.setGeometry(QtCore.QRect(230, 240, 160, 21))
        self.txtBatchSize.setObjectName("txtBatchSize")
        self.cbSolver = QtWidgets.QComboBox(self.tab_2)
        self.cbSolver.setGeometry(QtCore.QRect(610, 120, 161, 26))
        self.cbSolver.setObjectName("cbSolver")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(30, 240, 191, 16))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(420, 120, 181, 16))
        self.label_13.setObjectName("label_13")
        self.cbActivation = QtWidgets.QComboBox(self.tab_2)
        self.cbActivation.setGeometry(QtCore.QRect(230, 120, 161, 26))
        self.cbActivation.setObjectName("cbActivation")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(30, 120, 191, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(420, 160, 181, 16))
        self.label_20.setObjectName("label_20")
        self.txtHiddenLayers = QtWidgets.QLineEdit(self.tab_2)
        self.txtHiddenLayers.setGeometry(QtCore.QRect(610, 160, 160, 21))
        self.txtHiddenLayers.setObjectName("txtHiddenLayers")
        self.cbShuffle = QtWidgets.QCheckBox(self.tab_2)
        self.cbShuffle.setGeometry(QtCore.QRect(420, 400, 351, 20))
        self.cbShuffle.setChecked(True)
        self.cbShuffle.setObjectName("cbShuffle")
        self.cbVerbose = QtWidgets.QCheckBox(self.tab_2)
        self.cbVerbose.setGeometry(QtCore.QRect(20, 440, 371, 20))
        self.cbVerbose.setChecked(False)
        self.cbVerbose.setObjectName("cbVerbose")
        self.cbLearningRate = QtWidgets.QComboBox(self.tab_2)
        self.cbLearningRate.setGeometry(QtCore.QRect(230, 160, 161, 26))
        self.cbLearningRate.setObjectName("cbLearningRate")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(30, 160, 191, 16))
        self.label_21.setObjectName("label_21")
        self.txtAlpha = QtWidgets.QLineEdit(self.tab_2)
        self.txtAlpha.setGeometry(QtCore.QRect(610, 240, 160, 21))
        self.txtAlpha.setObjectName("txtAlpha")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(420, 240, 181, 16))
        self.label_22.setObjectName("label_22")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 200, 191, 16))
        self.label_15.setObjectName("label_15")
        self.txtPowert = QtWidgets.QLineEdit(self.tab_2)
        self.txtPowert.setGeometry(QtCore.QRect(610, 200, 160, 21))
        self.txtPowert.setObjectName("txtPowert")
        self.txtLearningRate = QtWidgets.QLineEdit(self.tab_2)
        self.txtLearningRate.setGeometry(QtCore.QRect(230, 200, 160, 21))
        self.txtLearningRate.setObjectName("txtLearningRate")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(420, 200, 181, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(30, 280, 191, 16))
        self.label_24.setObjectName("label_24")
        self.txtTol = QtWidgets.QLineEdit(self.tab_2)
        self.txtTol.setGeometry(QtCore.QRect(610, 280, 160, 21))
        self.txtTol.setObjectName("txtTol")
        self.txtMaxIter = QtWidgets.QLineEdit(self.tab_2)
        self.txtMaxIter.setGeometry(QtCore.QRect(230, 280, 160, 21))
        self.txtMaxIter.setObjectName("txtMaxIter")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(420, 280, 181, 16))
        self.label_25.setObjectName("label_25")
        self.txtValidationFraction = QtWidgets.QLineEdit(self.tab_2)
        self.txtValidationFraction.setGeometry(QtCore.QRect(610, 320, 160, 21))
        self.txtValidationFraction.setObjectName("txtValidationFraction")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(420, 320, 181, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(30, 320, 191, 16))
        self.label_27.setObjectName("label_27")
        self.txtMomentum = QtWidgets.QLineEdit(self.tab_2)
        self.txtMomentum.setGeometry(QtCore.QRect(230, 320, 160, 21))
        self.txtMomentum.setObjectName("txtMomentum")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(30, 360, 191, 16))
        self.label_28.setObjectName("label_28")
        self.txtBeta1 = QtWidgets.QLineEdit(self.tab_2)
        self.txtBeta1.setGeometry(QtCore.QRect(230, 360, 160, 21))
        self.txtBeta1.setObjectName("txtBeta1")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(420, 360, 181, 16))
        self.label_29.setObjectName("label_29")
        self.txtBeta2 = QtWidgets.QLineEdit(self.tab_2)
        self.txtBeta2.setGeometry(QtCore.QRect(610, 360, 160, 21))
        self.txtBeta2.setObjectName("txtBeta2")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(30, 400, 191, 16))
        self.label_30.setObjectName("label_30")
        self.txtEpsilon = QtWidgets.QLineEdit(self.tab_2)
        self.txtEpsilon.setGeometry(QtCore.QRect(230, 400, 160, 21))
        self.txtEpsilon.setObjectName("txtEpsilon")
        self.cbWarmStart = QtWidgets.QCheckBox(self.tab_2)
        self.cbWarmStart.setGeometry(QtCore.QRect(420, 440, 351, 20))
        self.cbWarmStart.setChecked(False)
        self.cbWarmStart.setObjectName("cbWarmStart")
        self.cbNesterovsMomentum = QtWidgets.QCheckBox(self.tab_2)
        self.cbNesterovsMomentum.setGeometry(QtCore.QRect(20, 480, 371, 20))
        self.cbNesterovsMomentum.setChecked(True)
        self.cbNesterovsMomentum.setObjectName("cbNesterovsMomentum")
        self.cbEarlyStopping = QtWidgets.QCheckBox(self.tab_2)
        self.cbEarlyStopping.setGeometry(QtCore.QRect(420, 480, 351, 20))
        self.cbEarlyStopping.setChecked(False)
        self.cbEarlyStopping.setObjectName("cbEarlyStopping")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.txtFoldFrom = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldFrom.setGeometry(QtCore.QRect(100, 30, 80, 24))
        self.txtFoldFrom.setMaximum(100000)
        self.txtFoldFrom.setProperty("value", 1)
        self.txtFoldFrom.setObjectName("txtFoldFrom")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(40, 30, 60, 16))
        self.label_17.setObjectName("label_17")
        self.txtFoldTo = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldTo.setGeometry(QtCore.QRect(320, 30, 80, 24))
        self.txtFoldTo.setMaximum(100000)
        self.txtFoldTo.setProperty("value", 1)
        self.txtFoldTo.setObjectName("txtFoldTo")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(260, 30, 60, 16))
        self.label_44.setObjectName("label_44")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 321, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(530, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 431))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbAverage = QtWidgets.QCheckBox(self.tab_5)
        self.cbAverage.setGeometry(QtCore.QRect(20, 30, 181, 20))
        self.cbAverage.setChecked(True)
        self.cbAverage.setObjectName("cbAverage")
        self.cbPrecision = QtWidgets.QCheckBox(self.tab_5)
        self.cbPrecision.setGeometry(QtCore.QRect(20, 70, 181, 20))
        self.cbPrecision.setChecked(True)
        self.cbPrecision.setObjectName("cbPrecision")
        self.cbPrecisionAvg = QtWidgets.QComboBox(self.tab_5)
        self.cbPrecisionAvg.setGeometry(QtCore.QRect(270, 70, 321, 26))
        self.cbPrecisionAvg.setObjectName("cbPrecisionAvg")
        self.cbAPrecisionAvg = QtWidgets.QComboBox(self.tab_5)
        self.cbAPrecisionAvg.setGeometry(QtCore.QRect(270, 110, 321, 26))
        self.cbAPrecisionAvg.setObjectName("cbAPrecisionAvg")
        self.cbAPrecision = QtWidgets.QCheckBox(self.tab_5)
        self.cbAPrecision.setGeometry(QtCore.QRect(20, 110, 231, 20))
        self.cbAPrecision.setChecked(False)
        self.cbAPrecision.setObjectName("cbAPrecision")
        self.cbRecallAvg = QtWidgets.QComboBox(self.tab_5)
        self.cbRecallAvg.setGeometry(QtCore.QRect(270, 150, 321, 26))
        self.cbRecallAvg.setObjectName("cbRecallAvg")
        self.cbRecall = QtWidgets.QCheckBox(self.tab_5)
        self.cbRecall.setGeometry(QtCore.QRect(20, 150, 181, 20))
        self.cbRecall.setChecked(True)
        self.cbRecall.setObjectName("cbRecall")
        self.cbF1 = QtWidgets.QCheckBox(self.tab_5)
        self.cbF1.setGeometry(QtCore.QRect(20, 190, 181, 20))
        self.cbF1.setChecked(True)
        self.cbF1.setObjectName("cbF1")
        self.cbF1Avg = QtWidgets.QComboBox(self.tab_5)
        self.cbF1Avg.setGeometry(QtCore.QRect(270, 190, 321, 26))
        self.cbF1Avg.setObjectName("cbF1Avg")
        self.tabWidget.addTab(self.tab_5, "")
        self.label_12 = QtWidgets.QLabel(frmMAMLP)
        self.label_12.setGeometry(QtCore.QRect(185, 730, 501, 20))
        self.label_12.setObjectName("label_12")
        self.btnOutModel = QtWidgets.QPushButton(frmMAMLP)
        self.btnOutModel.setGeometry(QtCore.QRect(780, 100, 51, 32))
        self.btnOutModel.setObjectName("btnOutModel")
        self.label_36 = QtWidgets.QLabel(frmMAMLP)
        self.label_36.setGeometry(QtCore.QRect(30, 100, 231, 16))
        self.label_36.setObjectName("label_36")
        self.txtOutModel = QtWidgets.QLineEdit(frmMAMLP)
        self.txtOutModel.setGeometry(QtCore.QRect(210, 100, 561, 21))
        self.txtOutModel.setText("")
        self.txtOutModel.setObjectName("txtOutModel")

        self.retranslateUi(frmMAMLP)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMAMLP)
        frmMAMLP.setTabOrder(self.txtInFile, self.btnInFile)
        frmMAMLP.setTabOrder(self.btnInFile, self.txtOutFile)
        frmMAMLP.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmMAMLP.setTabOrder(self.btnOutFile, self.tabWidget)
        frmMAMLP.setTabOrder(self.tabWidget, self.txtITrData)
        frmMAMLP.setTabOrder(self.txtITrData, self.txtITrLabel)
        frmMAMLP.setTabOrder(self.txtITrLabel, self.btnConvert)
        frmMAMLP.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMAMLP):
        _translate = QtCore.QCoreApplication.translate
        frmMAMLP.setWindowTitle(_translate("frmMAMLP", "Multi-layer Perceptron Classifier"))
        self.btnInFile.setText(_translate("frmMAMLP", "..."))
        self.label_33.setText(_translate("frmMAMLP", "Input Data (per fold)"))
        self.btnOutFile.setText(_translate("frmMAMLP", "..."))
        self.btnConvert.setText(_translate("frmMAMLP", "Analyze"))
        self.label_35.setText(_translate("frmMAMLP", "Analysis Results"))
        self.btnClose.setText(_translate("frmMAMLP", "Close"))
        self.label_2.setText(_translate("frmMAMLP", "Data"))
        self.label_3.setText(_translate("frmMAMLP", "Label"))
        self.label.setText(_translate("frmMAMLP", "Input"))
        self.label_7.setText(_translate("frmMAMLP", "Train"))
        self.label_8.setText(_translate("frmMAMLP", "Test"))
        self.label_9.setText(_translate("frmMAMLP", "FoldID"))
        self.lbFoldID.setText(_translate("frmMAMLP", "ID=None"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMAMLP", "Data"))
        self.groupBox.setTitle(_translate("frmMAMLP", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMAMLP", "Scale Data Train~N(0,1) and Test~N(0,1)"))
        self.txtBatchSize.setText(_translate("frmMAMLP", "0"))
        self.label_11.setText(_translate("frmMAMLP", "Batch Size (Auto=0)"))
        self.label_13.setText(_translate("frmMAMLP", "Solver"))
        self.label_19.setText(_translate("frmMAMLP", "Activation"))
        self.label_20.setText(_translate("frmMAMLP", "Hidden Layers"))
        self.txtHiddenLayers.setText(_translate("frmMAMLP", "[100,]"))
        self.cbShuffle.setText(_translate("frmMAMLP", "Shuffle"))
        self.cbVerbose.setText(_translate("frmMAMLP", "Verbose"))
        self.label_21.setText(_translate("frmMAMLP", "Learning Rate"))
        self.txtAlpha.setText(_translate("frmMAMLP", "0.0001"))
        self.label_22.setText(_translate("frmMAMLP", "Alpha"))
        self.label_15.setText(_translate("frmMAMLP", "Learning Rate (init)"))
        self.txtPowert.setText(_translate("frmMAMLP", "0.5"))
        self.txtLearningRate.setText(_translate("frmMAMLP", "0.001"))
        self.label_23.setText(_translate("frmMAMLP", "power_t"))
        self.label_24.setText(_translate("frmMAMLP", "Maximum Iterations"))
        self.txtTol.setText(_translate("frmMAMLP", "0.0001"))
        self.txtMaxIter.setText(_translate("frmMAMLP", "200"))
        self.label_25.setText(_translate("frmMAMLP", "Tolerance"))
        self.txtValidationFraction.setText(_translate("frmMAMLP", "0.1"))
        self.label_26.setText(_translate("frmMAMLP", "Validation Fraction"))
        self.label_27.setText(_translate("frmMAMLP", "Momentum"))
        self.txtMomentum.setText(_translate("frmMAMLP", "0.9"))
        self.label_28.setText(_translate("frmMAMLP", "beta_1 "))
        self.txtBeta1.setText(_translate("frmMAMLP", "0.9"))
        self.label_29.setText(_translate("frmMAMLP", "beta_2"))
        self.txtBeta2.setText(_translate("frmMAMLP", "0.999"))
        self.label_30.setText(_translate("frmMAMLP", "Epsilon"))
        self.txtEpsilon.setText(_translate("frmMAMLP", "1e-8"))
        self.cbWarmStart.setText(_translate("frmMAMLP", "Warm Start"))
        self.cbNesterovsMomentum.setText(_translate("frmMAMLP", "Nesterovs Momentum"))
        self.cbEarlyStopping.setText(_translate("frmMAMLP", "Early Stopping"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMAMLP", "Parameters"))
        self.label_17.setText(_translate("frmMAMLP", "From:"))
        self.label_44.setText(_translate("frmMAMLP", "To:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmMAMLP", "Fold"))
        self.label_4.setText(_translate("frmMAMLP", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMAMLP", "0"))
        self.label_5.setText(_translate("frmMAMLP", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMAMLP", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMAMLP", "Filter Class ID"))
        self.cbAverage.setText(_translate("frmMAMLP", "Average"))
        self.cbPrecision.setText(_translate("frmMAMLP", "Precision"))
        self.cbAPrecision.setText(_translate("frmMAMLP", "Average of Precision"))
        self.cbRecall.setText(_translate("frmMAMLP", "Recall"))
        self.cbF1.setText(_translate("frmMAMLP", "f1 score"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMAMLP", "Metrics"))
        self.label_12.setText(_translate("frmMAMLP", "$FOLD$ will be replaced by fold number."))
        self.btnOutModel.setText(_translate("frmMAMLP", "..."))
        self.label_36.setText(_translate("frmMAMLP", "Models (per fold/opt)"))

