# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMAAtlasEnsembleGUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMAAtlasEnsemble(object):
    def setupUi(self, frmMAAtlasEnsemble):
        frmMAAtlasEnsemble.setObjectName("frmMAAtlasEnsemble")
        frmMAAtlasEnsemble.resize(853, 690)
        self.btnInFile = QtWidgets.QPushButton(frmMAAtlasEnsemble)
        self.btnInFile.setGeometry(QtCore.QRect(770, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMAAtlasEnsemble)
        self.label_33.setGeometry(QtCore.QRect(20, 20, 131, 16))
        self.label_33.setObjectName("label_33")
        self.btnOutFile = QtWidgets.QPushButton(frmMAAtlasEnsemble)
        self.btnOutFile.setGeometry(QtCore.QRect(770, 100, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.txtInFile = QtWidgets.QLineEdit(frmMAAtlasEnsemble)
        self.txtInFile.setGeometry(QtCore.QRect(180, 20, 571, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMAAtlasEnsemble)
        self.btnConvert.setGeometry(QtCore.QRect(680, 640, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label_35 = QtWidgets.QLabel(frmMAAtlasEnsemble)
        self.label_35.setGeometry(QtCore.QRect(20, 100, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMAAtlasEnsemble)
        self.txtOutFile.setGeometry(QtCore.QRect(180, 100, 571, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnClose = QtWidgets.QPushButton(frmMAAtlasEnsemble)
        self.btnClose.setGeometry(QtCore.QRect(30, 640, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMAAtlasEnsemble)
        self.tabWidget.setGeometry(QtCore.QRect(20, 150, 811, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(140, 90, 60, 16))
        self.label_3.setObjectName("label_3")
        self.txtCol = QtWidgets.QComboBox(self.tab)
        self.txtCol.setGeometry(QtCore.QRect(260, 130, 121, 26))
        self.txtCol.setEditable(True)
        self.txtCol.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCol.setObjectName("txtCol")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(300, 20, 61, 16))
        self.label.setObjectName("label")
        self.txtITrLabel = QtWidgets.QComboBox(self.tab)
        self.txtITrLabel.setGeometry(QtCore.QRect(260, 90, 121, 26))
        self.txtITrLabel.setEditable(True)
        self.txtITrLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrLabel.setObjectName("txtITrLabel")
        self.txtITrData = QtWidgets.QComboBox(self.tab)
        self.txtITrData.setGeometry(QtCore.QRect(260, 50, 121, 26))
        self.txtITrData.setEditable(True)
        self.txtITrData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrData.setObjectName("txtITrData")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(140, 130, 101, 16))
        self.label_6.setObjectName("label_6")
        self.txtImg = QtWidgets.QComboBox(self.tab)
        self.txtImg.setGeometry(QtCore.QRect(260, 170, 121, 26))
        self.txtImg.setEditable(True)
        self.txtImg.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtImg.setObjectName("txtImg")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(140, 170, 101, 16))
        self.label_7.setObjectName("label_7")
        self.txtITeLabel = QtWidgets.QComboBox(self.tab)
        self.txtITeLabel.setGeometry(QtCore.QRect(420, 90, 121, 26))
        self.txtITeLabel.setEditable(True)
        self.txtITeLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeLabel.setObjectName("txtITeLabel")
        self.txtITeData = QtWidgets.QComboBox(self.tab)
        self.txtITeData.setGeometry(QtCore.QRect(420, 50, 121, 26))
        self.txtITeData.setEditable(True)
        self.txtITeData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeData.setObjectName("txtITeData")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(460, 20, 61, 16))
        self.label_4.setObjectName("label_4")
        self.lbFoldID = QtWidgets.QLabel(self.tab)
        self.lbFoldID.setGeometry(QtCore.QRect(410, 210, 251, 16))
        self.lbFoldID.setObjectName("lbFoldID")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(140, 210, 111, 16))
        self.label_11.setObjectName("label_11")
        self.txtFoldID = QtWidgets.QComboBox(self.tab)
        self.txtFoldID.setGeometry(QtCore.QRect(260, 210, 121, 26))
        self.txtFoldID.setEditable(True)
        self.txtFoldID.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFoldID.setObjectName("txtFoldID")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 751, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(40, 40, 191, 20))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(30, 30, 60, 16))
        self.label_17.setObjectName("label_17")
        self.txtFoldTo = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldTo.setGeometry(QtCore.QRect(260, 30, 80, 24))
        self.txtFoldTo.setMaximum(100000)
        self.txtFoldTo.setProperty("value", 1)
        self.txtFoldTo.setObjectName("txtFoldTo")
        self.txtFoldFrom = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldFrom.setGeometry(QtCore.QRect(90, 30, 80, 24))
        self.txtFoldFrom.setMaximum(100000)
        self.txtFoldFrom.setProperty("value", 1)
        self.txtFoldFrom.setObjectName("txtFoldFrom")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(200, 30, 60, 16))
        self.label_44.setObjectName("label_44")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 220, 771, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cbFilterTrID = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbFilterTrID.setGeometry(QtCore.QRect(20, 40, 191, 21))
        self.cbFilterTrID.setObjectName("cbFilterTrID")
        self.txtFilterTrID = QtWidgets.QComboBox(self.groupBox_3)
        self.txtFilterTrID.setGeometry(QtCore.QRect(190, 40, 231, 26))
        self.txtFilterTrID.setEditable(True)
        self.txtFilterTrID.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFilterTrID.setObjectName("txtFilterTrID")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 80, 201, 16))
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(640, 80, 111, 16))
        self.label_13.setObjectName("label_13")
        self.txtFilterTrContent = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtFilterTrContent.setGeometry(QtCore.QRect(190, 80, 441, 21))
        self.txtFilterTrContent.setText("")
        self.txtFilterTrContent.setObjectName("txtFilterTrContent")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(640, 160, 111, 16))
        self.label_14.setObjectName("label_14")
        self.cbFilterTeID = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbFilterTeID.setGeometry(QtCore.QRect(20, 120, 191, 21))
        self.cbFilterTeID.setObjectName("cbFilterTeID")
        self.txtFilterTeContent = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtFilterTeContent.setGeometry(QtCore.QRect(190, 160, 441, 21))
        self.txtFilterTeContent.setText("")
        self.txtFilterTeContent.setObjectName("txtFilterTeContent")
        self.txtFilterTeID = QtWidgets.QComboBox(self.groupBox_3)
        self.txtFilterTeID.setGeometry(QtCore.QRect(190, 120, 231, 26))
        self.txtFilterTeID.setEditable(True)
        self.txtFilterTeID.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFilterTeID.setObjectName("txtFilterTeID")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(20, 160, 201, 16))
        self.label_16.setObjectName("label_16")
        self.btnShowFilterContent = QtWidgets.QPushButton(self.groupBox_3)
        self.btnShowFilterContent.setGeometry(QtCore.QRect(620, 40, 141, 23))
        self.btnShowFilterContent.setObjectName("btnShowFilterContent")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 771, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 201, 16))
        self.label_5.setObjectName("label_5")
        self.txtFilter = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtFilter.setGeometry(QtCore.QRect(190, 40, 441, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(640, 40, 111, 16))
        self.label_9.setObjectName("label_9")
        self.txtClass = QtWidgets.QTextEdit(self.groupBox_2)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 231, 121))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.cbAverage = QtWidgets.QCheckBox(self.tab_6)
        self.cbAverage.setGeometry(QtCore.QRect(30, 40, 181, 20))
        self.cbAverage.setChecked(True)
        self.cbAverage.setObjectName("cbAverage")
        self.cbAPrecisionAvg = QtWidgets.QComboBox(self.tab_6)
        self.cbAPrecisionAvg.setGeometry(QtCore.QRect(250, 120, 321, 26))
        self.cbAPrecisionAvg.setObjectName("cbAPrecisionAvg")
        self.cbPrecision = QtWidgets.QCheckBox(self.tab_6)
        self.cbPrecision.setGeometry(QtCore.QRect(30, 80, 181, 20))
        self.cbPrecision.setChecked(True)
        self.cbPrecision.setObjectName("cbPrecision")
        self.cbAPrecision = QtWidgets.QCheckBox(self.tab_6)
        self.cbAPrecision.setGeometry(QtCore.QRect(30, 120, 231, 20))
        self.cbAPrecision.setChecked(False)
        self.cbAPrecision.setObjectName("cbAPrecision")
        self.cbRecall = QtWidgets.QCheckBox(self.tab_6)
        self.cbRecall.setGeometry(QtCore.QRect(30, 160, 181, 20))
        self.cbRecall.setChecked(True)
        self.cbRecall.setObjectName("cbRecall")
        self.cbF1Avg = QtWidgets.QComboBox(self.tab_6)
        self.cbF1Avg.setGeometry(QtCore.QRect(250, 200, 321, 26))
        self.cbF1Avg.setObjectName("cbF1Avg")
        self.cbF1 = QtWidgets.QCheckBox(self.tab_6)
        self.cbF1.setGeometry(QtCore.QRect(30, 200, 181, 20))
        self.cbF1.setChecked(True)
        self.cbF1.setObjectName("cbF1")
        self.cbPrecisionAvg = QtWidgets.QComboBox(self.tab_6)
        self.cbPrecisionAvg.setGeometry(QtCore.QRect(250, 80, 321, 26))
        self.cbPrecisionAvg.setObjectName("cbPrecisionAvg")
        self.cbRecallAvg = QtWidgets.QComboBox(self.tab_6)
        self.cbRecallAvg.setGeometry(QtCore.QRect(250, 160, 321, 26))
        self.cbRecallAvg.setObjectName("cbRecallAvg")
        self.tabWidget.addTab(self.tab_6, "")
        self.txtAtlas = QtWidgets.QLineEdit(frmMAAtlasEnsemble)
        self.txtAtlas.setGeometry(QtCore.QRect(180, 60, 571, 21))
        self.txtAtlas.setText("")
        self.txtAtlas.setObjectName("txtAtlas")
        self.btnAtlas = QtWidgets.QPushButton(frmMAAtlasEnsemble)
        self.btnAtlas.setGeometry(QtCore.QRect(770, 60, 51, 32))
        self.btnAtlas.setObjectName("btnAtlas")
        self.label_34 = QtWidgets.QLabel(frmMAAtlasEnsemble)
        self.label_34.setGeometry(QtCore.QRect(20, 60, 131, 16))
        self.label_34.setObjectName("label_34")
        self.label_12 = QtWidgets.QLabel(frmMAAtlasEnsemble)
        self.label_12.setGeometry(QtCore.QRect(190, 640, 481, 20))
        self.label_12.setObjectName("label_12")

        self.retranslateUi(frmMAAtlasEnsemble)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMAAtlasEnsemble)
        frmMAAtlasEnsemble.setTabOrder(self.txtInFile, self.btnInFile)
        frmMAAtlasEnsemble.setTabOrder(self.btnInFile, self.txtOutFile)
        frmMAAtlasEnsemble.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmMAAtlasEnsemble.setTabOrder(self.btnOutFile, self.tabWidget)
        frmMAAtlasEnsemble.setTabOrder(self.tabWidget, self.txtITrData)
        frmMAAtlasEnsemble.setTabOrder(self.txtITrData, self.txtITrLabel)
        frmMAAtlasEnsemble.setTabOrder(self.txtITrLabel, self.txtCol)
        frmMAAtlasEnsemble.setTabOrder(self.txtCol, self.btnConvert)
        frmMAAtlasEnsemble.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMAAtlasEnsemble):
        _translate = QtCore.QCoreApplication.translate
        frmMAAtlasEnsemble.setWindowTitle(_translate("frmMAAtlasEnsemble", "Incremental Principal Component Analysis (PCA)"))
        self.btnInFile.setText(_translate("frmMAAtlasEnsemble", "..."))
        self.label_33.setText(_translate("frmMAAtlasEnsemble", "Input Data"))
        self.btnOutFile.setText(_translate("frmMAAtlasEnsemble", "..."))
        self.btnConvert.setText(_translate("frmMAAtlasEnsemble", "Report"))
        self.label_35.setText(_translate("frmMAAtlasEnsemble", "Output"))
        self.btnClose.setText(_translate("frmMAAtlasEnsemble", "Close"))
        self.label_2.setText(_translate("frmMAAtlasEnsemble", "Data"))
        self.label_3.setText(_translate("frmMAAtlasEnsemble", "Label"))
        self.label.setText(_translate("frmMAAtlasEnsemble", "Train"))
        self.label_6.setText(_translate("frmMAAtlasEnsemble", "Coordinate"))
        self.label_7.setText(_translate("frmMAAtlasEnsemble", "Image Shape"))
        self.label_4.setText(_translate("frmMAAtlasEnsemble", "Test"))
        self.lbFoldID.setText(_translate("frmMAAtlasEnsemble", "ID=None"))
        self.label_11.setText(_translate("frmMAAtlasEnsemble", "FoldID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMAAtlasEnsemble", "Data"))
        self.groupBox.setTitle(_translate("frmMAAtlasEnsemble", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMAAtlasEnsemble", "Scale Data X~N(0,1)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMAAtlasEnsemble", "Parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMAAtlasEnsemble", "Base Algorithm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("frmMAAtlasEnsemble", "Ensemble Model"))
        self.label_17.setText(_translate("frmMAAtlasEnsemble", "From:"))
        self.label_44.setText(_translate("frmMAAtlasEnsemble", "To:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmMAAtlasEnsemble", "Fold"))
        self.groupBox_3.setTitle(_translate("frmMAAtlasEnsemble", "<Based on a reference>"))
        self.cbFilterTrID.setText(_translate("frmMAAtlasEnsemble", "Filter training based on"))
        self.label_8.setText(_translate("frmMAAtlasEnsemble", "Remove training contents"))
        self.label_13.setText(_translate("frmMAAtlasEnsemble", "e.g. 0 or [1,2]"))
        self.label_14.setText(_translate("frmMAAtlasEnsemble", "e.g. 0 or [1,2]"))
        self.cbFilterTeID.setText(_translate("frmMAAtlasEnsemble", "Filter testing based on"))
        self.label_16.setText(_translate("frmMAAtlasEnsemble", "Remove testing contents"))
        self.btnShowFilterContent.setText(_translate("frmMAAtlasEnsemble", "Show Content"))
        self.groupBox_2.setTitle(_translate("frmMAAtlasEnsemble", "<Filter based on Class ID>"))
        self.label_10.setText(_translate("frmMAAtlasEnsemble", "Existed Classes"))
        self.label_5.setText(_translate("frmMAAtlasEnsemble", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMAAtlasEnsemble", "0"))
        self.label_9.setText(_translate("frmMAAtlasEnsemble", "e.g. 0 or [1,2]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMAAtlasEnsemble", "Filter"))
        self.cbAverage.setText(_translate("frmMAAtlasEnsemble", "Average"))
        self.cbPrecision.setText(_translate("frmMAAtlasEnsemble", "Precision"))
        self.cbAPrecision.setText(_translate("frmMAAtlasEnsemble", "Average of Precision"))
        self.cbRecall.setText(_translate("frmMAAtlasEnsemble", "Recall"))
        self.cbF1.setText(_translate("frmMAAtlasEnsemble", "f1 score"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("frmMAAtlasEnsemble", "Metrics"))
        self.btnAtlas.setText(_translate("frmMAAtlasEnsemble", "..."))
        self.label_34.setText(_translate("frmMAAtlasEnsemble", "Atlas"))
        self.label_12.setText(_translate("frmMAAtlasEnsemble", "$FOLD$ will be replaced by fold number."))

