# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMAKMeansGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMAKMeans(object):
    def setupUi(self, frmMAKMeans):
        frmMAKMeans.setObjectName("frmMAKMeans")
        frmMAKMeans.resize(782, 764)
        self.btnInFile = QtWidgets.QPushButton(frmMAKMeans)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMAKMeans)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.btnOutFile = QtWidgets.QPushButton(frmMAKMeans)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.txtInFile = QtWidgets.QLineEdit(frmMAKMeans)
        self.txtInFile.setGeometry(QtCore.QRect(180, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMAKMeans)
        self.btnConvert.setGeometry(QtCore.QRect(620, 715, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label_35 = QtWidgets.QLabel(frmMAKMeans)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 211, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMAKMeans)
        self.txtOutFile.setGeometry(QtCore.QRect(180, 60, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnClose = QtWidgets.QPushButton(frmMAKMeans)
        self.btnClose.setGeometry(QtCore.QRect(30, 715, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMAKMeans)
        self.tabWidget.setGeometry(QtCore.QRect(30, 150, 731, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 60, 16))
        self.label_3.setObjectName("label_3")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(180, 60, 181, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(180, 20, 181, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 671, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 641, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.txtNCluster = QtWidgets.QLineEdit(self.tab_2)
        self.txtNCluster.setGeometry(QtCore.QRect(300, 230, 160, 21))
        self.txtNCluster.setObjectName("txtNCluster")
        self.txtMaxIter = QtWidgets.QLineEdit(self.tab_2)
        self.txtMaxIter.setGeometry(QtCore.QRect(300, 390, 160, 21))
        self.txtMaxIter.setObjectName("txtMaxIter")
        self.txtTole = QtWidgets.QLineEdit(self.tab_2)
        self.txtTole.setGeometry(QtCore.QRect(300, 350, 160, 21))
        self.txtTole.setObjectName("txtTole")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(30, 350, 221, 16))
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(30, 310, 231, 16))
        self.label_18.setObjectName("label_18")
        self.cbAlgorithm = QtWidgets.QComboBox(self.tab_2)
        self.cbAlgorithm.setGeometry(QtCore.QRect(300, 150, 161, 26))
        self.cbAlgorithm.setObjectName("cbAlgorithm")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(30, 230, 221, 16))
        self.label_11.setObjectName("label_11")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 270, 231, 16))
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(30, 150, 231, 16))
        self.label_13.setObjectName("label_13")
        self.txtVerbose = QtWidgets.QLineEdit(self.tab_2)
        self.txtVerbose.setGeometry(QtCore.QRect(300, 310, 160, 21))
        self.txtVerbose.setObjectName("txtVerbose")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(30, 390, 251, 16))
        self.label_16.setObjectName("label_16")
        self.txtNInit = QtWidgets.QLineEdit(self.tab_2)
        self.txtNInit.setGeometry(QtCore.QRect(300, 270, 160, 21))
        self.txtNInit.setObjectName("txtNInit")
        self.cbInit = QtWidgets.QComboBox(self.tab_2)
        self.cbInit.setGeometry(QtCore.QRect(300, 110, 161, 26))
        self.cbInit.setObjectName("cbInit")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(30, 110, 231, 16))
        self.label_19.setObjectName("label_19")
        self.cbCopyX = QtWidgets.QCheckBox(self.tab_2)
        self.cbCopyX.setGeometry(QtCore.QRect(30, 470, 401, 20))
        self.cbCopyX.setChecked(True)
        self.cbCopyX.setObjectName("cbCopyX")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(30, 190, 231, 16))
        self.label_20.setObjectName("label_20")
        self.cbPrecompute = QtWidgets.QComboBox(self.tab_2)
        self.cbPrecompute.setGeometry(QtCore.QRect(300, 190, 161, 26))
        self.cbPrecompute.setObjectName("cbPrecompute")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(30, 430, 251, 16))
        self.label_21.setObjectName("label_21")
        self.txtNJobs = QtWidgets.QLineEdit(self.tab_2)
        self.txtNJobs.setGeometry(QtCore.QRect(300, 430, 160, 21))
        self.txtNJobs.setObjectName("txtNJobs")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 431))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbAverage = QtWidgets.QCheckBox(self.tab_5)
        self.cbAverage.setGeometry(QtCore.QRect(20, 30, 391, 20))
        self.cbAverage.setChecked(True)
        self.cbAverage.setObjectName("cbAverage")
        self.cbNMI = QtWidgets.QCheckBox(self.tab_5)
        self.cbNMI.setGeometry(QtCore.QRect(20, 70, 391, 20))
        self.cbNMI.setChecked(True)
        self.cbNMI.setObjectName("cbNMI")
        self.cbAMI = QtWidgets.QCheckBox(self.tab_5)
        self.cbAMI.setGeometry(QtCore.QRect(20, 110, 401, 20))
        self.cbAMI.setChecked(True)
        self.cbAMI.setObjectName("cbAMI")
        self.cbRIA = QtWidgets.QCheckBox(self.tab_5)
        self.cbRIA.setGeometry(QtCore.QRect(20, 150, 381, 20))
        self.cbRIA.setChecked(True)
        self.cbRIA.setObjectName("cbRIA")
        self.tabWidget.addTab(self.tab_5, "")
        self.btnOutModel = QtWidgets.QPushButton(frmMAKMeans)
        self.btnOutModel.setGeometry(QtCore.QRect(710, 100, 51, 32))
        self.btnOutModel.setObjectName("btnOutModel")
        self.label_36 = QtWidgets.QLabel(frmMAKMeans)
        self.label_36.setGeometry(QtCore.QRect(30, 100, 231, 16))
        self.label_36.setObjectName("label_36")
        self.txtOutModel = QtWidgets.QLineEdit(frmMAKMeans)
        self.txtOutModel.setGeometry(QtCore.QRect(180, 100, 521, 21))
        self.txtOutModel.setText("")
        self.txtOutModel.setObjectName("txtOutModel")

        self.retranslateUi(frmMAKMeans)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMAKMeans)
        frmMAKMeans.setTabOrder(self.txtInFile, self.btnInFile)
        frmMAKMeans.setTabOrder(self.btnInFile, self.txtOutFile)
        frmMAKMeans.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmMAKMeans.setTabOrder(self.btnOutFile, self.tabWidget)
        frmMAKMeans.setTabOrder(self.tabWidget, self.txtData)
        frmMAKMeans.setTabOrder(self.txtData, self.txtLabel)
        frmMAKMeans.setTabOrder(self.txtLabel, self.btnConvert)
        frmMAKMeans.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMAKMeans):
        _translate = QtCore.QCoreApplication.translate
        frmMAKMeans.setWindowTitle(_translate("frmMAKMeans", "KMeans"))
        self.btnInFile.setText(_translate("frmMAKMeans", "..."))
        self.label_33.setText(_translate("frmMAKMeans", "Input Data "))
        self.btnOutFile.setText(_translate("frmMAKMeans", "..."))
        self.btnConvert.setText(_translate("frmMAKMeans", "Analyze"))
        self.label_35.setText(_translate("frmMAKMeans", "Analysis Results"))
        self.btnClose.setText(_translate("frmMAKMeans", "Close"))
        self.label_2.setText(_translate("frmMAKMeans", "Data"))
        self.label_3.setText(_translate("frmMAKMeans", "Label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMAKMeans", "Data"))
        self.groupBox.setTitle(_translate("frmMAKMeans", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMAKMeans", "Scale Data~N(0,1)"))
        self.txtNCluster.setText(_translate("frmMAKMeans", "8"))
        self.txtMaxIter.setText(_translate("frmMAKMeans", "300"))
        self.txtTole.setText(_translate("frmMAKMeans", "0.0001"))
        self.label_14.setText(_translate("frmMAKMeans", "Tolerance"))
        self.label_18.setText(_translate("frmMAKMeans", "Verbose"))
        self.label_11.setText(_translate("frmMAKMeans", "Num of Clusters"))
        self.label_15.setText(_translate("frmMAKMeans", "Num of Init"))
        self.label_13.setText(_translate("frmMAKMeans", "Algorithm"))
        self.txtVerbose.setText(_translate("frmMAKMeans", "0"))
        self.label_16.setText(_translate("frmMAKMeans", "Maximum Iterations"))
        self.txtNInit.setText(_translate("frmMAKMeans", "10"))
        self.label_19.setText(_translate("frmMAKMeans", "Init"))
        self.cbCopyX.setText(_translate("frmMAKMeans", "copy_x"))
        self.label_20.setText(_translate("frmMAKMeans", "Precompute Distances"))
        self.label_21.setText(_translate("frmMAKMeans", "Num of Jobs"))
        self.txtNJobs.setText(_translate("frmMAKMeans", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMAKMeans", "Parameters"))
        self.label_4.setText(_translate("frmMAKMeans", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMAKMeans", "0"))
        self.label_5.setText(_translate("frmMAKMeans", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMAKMeans", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMAKMeans", "Filter Class ID"))
        self.cbAverage.setText(_translate("frmMAKMeans", "Average"))
        self.cbNMI.setText(_translate("frmMAKMeans", "Normalized Mutual Information"))
        self.cbAMI.setText(_translate("frmMAKMeans", "Adjusted Mutual Information"))
        self.cbRIA.setText(_translate("frmMAKMeans", "Rand Index Adjusted "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMAKMeans", "Metrics"))
        self.btnOutModel.setText(_translate("frmMAKMeans", "..."))
        self.label_36.setText(_translate("frmMAKMeans", "Models "))

