# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMASKRSAGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMASKRSA(object):
    def setupUi(self, frmMASKRSA):
        frmMASKRSA.setObjectName("frmMASKRSA")
        frmMASKRSA.resize(782, 709)
        self.btnInFile = QtWidgets.QPushButton(frmMASKRSA)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMASKRSA)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.txtInFile = QtWidgets.QLineEdit(frmMASKRSA)
        self.txtInFile.setGeometry(QtCore.QRect(180, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMASKRSA)
        self.btnConvert.setGeometry(QtCore.QRect(620, 660, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.btnClose = QtWidgets.QPushButton(frmMASKRSA)
        self.btnClose.setGeometry(QtCore.QRect(30, 660, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMASKRSA)
        self.tabWidget.setGeometry(QtCore.QRect(30, 150, 731, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.label_3.setObjectName("label_3")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(180, 90, 181, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(180, 50, 181, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.txtSubject = QtWidgets.QComboBox(self.tab)
        self.txtSubject.setGeometry(QtCore.QRect(180, 170, 181, 26))
        self.txtSubject.setEditable(True)
        self.txtSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubject.setObjectName("txtSubject")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 111, 16))
        self.label_6.setObjectName("label_6")
        self.txtRun = QtWidgets.QComboBox(self.tab)
        self.txtRun.setGeometry(QtCore.QRect(180, 210, 181, 26))
        self.txtRun.setEditable(True)
        self.txtRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRun.setObjectName("txtRun")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 60, 16))
        self.label_7.setObjectName("label_7")
        self.txtCounter = QtWidgets.QComboBox(self.tab)
        self.txtCounter.setGeometry(QtCore.QRect(180, 250, 181, 26))
        self.txtCounter.setEditable(True)
        self.txtCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounter.setObjectName("txtCounter")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 131, 16))
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 10, 51, 17))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 290, 131, 16))
        self.label_9.setObjectName("label_9")
        self.txtTask = QtWidgets.QComboBox(self.tab)
        self.txtTask.setGeometry(QtCore.QRect(180, 290, 181, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTask.setObjectName("txtTask")
        self.txtRunVal = QtWidgets.QComboBox(self.tab)
        self.txtRunVal.setGeometry(QtCore.QRect(400, 210, 181, 26))
        self.txtRunVal.setEditable(True)
        self.txtRunVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRunVal.setObjectName("txtRunVal")
        self.txtTaskVal = QtWidgets.QComboBox(self.tab)
        self.txtTaskVal.setGeometry(QtCore.QRect(400, 290, 181, 26))
        self.txtTaskVal.setEditable(True)
        self.txtTaskVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTaskVal.setObjectName("txtTaskVal")
        self.txtSubjectVal = QtWidgets.QComboBox(self.tab)
        self.txtSubjectVal.setGeometry(QtCore.QRect(400, 170, 181, 26))
        self.txtSubjectVal.setEditable(True)
        self.txtSubjectVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubjectVal.setObjectName("txtSubjectVal")
        self.txtCounterVal = QtWidgets.QComboBox(self.tab)
        self.txtCounterVal.setGeometry(QtCore.QRect(400, 250, 181, 26))
        self.txtCounterVal.setEditable(True)
        self.txtCounterVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounterVal.setObjectName("txtCounterVal")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(470, 10, 111, 17))
        self.label_11.setObjectName("label_11")
        self.btnRef = QtWidgets.QPushButton(self.tab)
        self.btnRef.setGeometry(QtCore.QRect(520, 410, 181, 29))
        self.btnRef.setObjectName("btnRef")
        self.txtDesign = QtWidgets.QComboBox(self.tab)
        self.txtDesign.setGeometry(QtCore.QRect(180, 130, 181, 26))
        self.txtDesign.setEditable(True)
        self.txtDesign.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtDesign.setObjectName("txtDesign")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 141, 16))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 671, 71))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 35, 641, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(30, 300, 391, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(30, 220, 401, 16))
        self.label_14.setObjectName("label_14")
        self.txtAlpha = QtWidgets.QLineEdit(self.tab_2)
        self.txtAlpha.setGeometry(QtCore.QRect(460, 180, 160, 21))
        self.txtAlpha.setObjectName("txtAlpha")
        self.txtL1 = QtWidgets.QLineEdit(self.tab_2)
        self.txtL1.setGeometry(QtCore.QRect(460, 300, 160, 21))
        self.txtL1.setObjectName("txtL1")
        self.txtTole = QtWidgets.QLineEdit(self.tab_2)
        self.txtTole.setGeometry(QtCore.QRect(460, 260, 160, 21))
        self.txtTole.setObjectName("txtTole")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 140, 411, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(30, 180, 411, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(30, 260, 401, 16))
        self.label_17.setObjectName("label_17")
        self.txtMaxIter = QtWidgets.QLineEdit(self.tab_2)
        self.txtMaxIter.setGeometry(QtCore.QRect(460, 220, 160, 21))
        self.txtMaxIter.setObjectName("txtMaxIter")
        self.txtJobs = QtWidgets.QLineEdit(self.tab_2)
        self.txtJobs.setGeometry(QtCore.QRect(460, 140, 160, 21))
        self.txtJobs.setObjectName("txtJobs")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(30, 100, 421, 16))
        self.label_18.setObjectName("label_18")
        self.cbMethod = QtWidgets.QComboBox(self.tab_2)
        self.cbMethod.setGeometry(QtCore.QRect(460, 100, 160, 26))
        self.cbMethod.setObjectName("cbMethod")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(30, 340, 391, 16))
        self.label_19.setObjectName("label_19")
        self.cbSelection = QtWidgets.QComboBox(self.tab_2)
        self.cbSelection.setGeometry(QtCore.QRect(460, 340, 160, 26))
        self.cbSelection.setObjectName("cbSelection")
        self.cbSolver = QtWidgets.QComboBox(self.tab_2)
        self.cbSolver.setGeometry(QtCore.QRect(460, 380, 160, 26))
        self.cbSolver.setObjectName("cbSolver")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(30, 380, 391, 16))
        self.label_20.setObjectName("label_20")
        self.cbFit = QtWidgets.QCheckBox(self.tab_2)
        self.cbFit.setGeometry(QtCore.QRect(30, 420, 191, 20))
        self.cbFit.setChecked(True)
        self.cbFit.setObjectName("cbFit")
        self.cbNormalize = QtWidgets.QCheckBox(self.tab_2)
        self.cbNormalize.setGeometry(QtCore.QRect(220, 420, 251, 20))
        self.cbNormalize.setChecked(True)
        self.cbNormalize.setObjectName("cbNormalize")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 371))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbCov = QtWidgets.QCheckBox(self.tab_5)
        self.cbCov.setGeometry(QtCore.QRect(20, 30, 391, 20))
        self.cbCov.setChecked(True)
        self.cbCov.setObjectName("cbCov")
        self.cbCorr = QtWidgets.QCheckBox(self.tab_5)
        self.cbCorr.setGeometry(QtCore.QRect(20, 70, 391, 20))
        self.cbCorr.setChecked(True)
        self.cbCorr.setObjectName("cbCorr")
        self.tabWidget.addTab(self.tab_5, "")
        self.label_35 = QtWidgets.QLabel(frmMASKRSA)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMASKRSA)
        self.txtOutFile.setGeometry(QtCore.QRect(180, 60, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnOutFile = QtWidgets.QPushButton(frmMASKRSA)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.cbDiagram = QtWidgets.QCheckBox(frmMASKRSA)
        self.cbDiagram.setGeometry(QtCore.QRect(30, 100, 341, 22))
        self.cbDiagram.setChecked(True)
        self.cbDiagram.setObjectName("cbDiagram")
        self.cbBeta = QtWidgets.QCheckBox(frmMASKRSA)
        self.cbBeta.setGeometry(QtCore.QRect(250, 100, 341, 22))
        self.cbBeta.setChecked(True)
        self.cbBeta.setObjectName("cbBeta")
        self.btnRedraw = QtWidgets.QPushButton(frmMASKRSA)
        self.btnRedraw.setGeometry(QtCore.QRect(460, 660, 141, 32))
        self.btnRedraw.setObjectName("btnRedraw")

        self.retranslateUi(frmMASKRSA)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(frmMASKRSA)
        frmMASKRSA.setTabOrder(self.txtInFile, self.btnInFile)
        frmMASKRSA.setTabOrder(self.btnInFile, self.tabWidget)
        frmMASKRSA.setTabOrder(self.tabWidget, self.txtData)
        frmMASKRSA.setTabOrder(self.txtData, self.txtLabel)
        frmMASKRSA.setTabOrder(self.txtLabel, self.btnConvert)
        frmMASKRSA.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMASKRSA):
        _translate = QtCore.QCoreApplication.translate
        frmMASKRSA.setWindowTitle(_translate("frmMASKRSA", "RAS"))
        self.btnInFile.setText(_translate("frmMASKRSA", "..."))
        self.label_33.setText(_translate("frmMASKRSA", "Input Data "))
        self.btnConvert.setText(_translate("frmMASKRSA", "Analyze"))
        self.btnClose.setText(_translate("frmMASKRSA", "Close"))
        self.label_2.setText(_translate("frmMASKRSA", "Data"))
        self.label_3.setText(_translate("frmMASKRSA", "Label"))
        self.label_6.setText(_translate("frmMASKRSA", "Subject"))
        self.label_7.setText(_translate("frmMASKRSA", "Run"))
        self.label_8.setText(_translate("frmMASKRSA", "Counter"))
        self.label.setText(_translate("frmMASKRSA", "ID"))
        self.label_9.setText(_translate("frmMASKRSA", "Task"))
        self.label_11.setText(_translate("frmMASKRSA", "Value"))
        self.btnRef.setText(_translate("frmMASKRSA", "Referesh"))
        self.label_12.setText(_translate("frmMASKRSA", "Design"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMASKRSA", "Data"))
        self.groupBox.setTitle(_translate("frmMASKRSA", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMASKRSA", "Scale Data~N(0,1)"))
        self.label_13.setText(_translate("frmMASKRSA", "L1 (ElasticNet)"))
        self.label_14.setText(_translate("frmMASKRSA", "Max Iteration (Ridge, LASSO, ElasticNet)"))
        self.txtAlpha.setText(_translate("frmMASKRSA", "1.0"))
        self.txtL1.setText(_translate("frmMASKRSA", "0.5"))
        self.txtTole.setText(_translate("frmMASKRSA", "0.0001"))
        self.label_15.setText(_translate("frmMASKRSA", "Number of parallel jobs (OLS)"))
        self.label_16.setText(_translate("frmMASKRSA", "Alpha (Ridge, LASSO, ElasticNet)"))
        self.label_17.setText(_translate("frmMASKRSA", "Tolerance (Ridge=0.001, LASSO or ElasticNet=0.0001)"))
        self.txtMaxIter.setText(_translate("frmMASKRSA", "1000"))
        self.txtJobs.setText(_translate("frmMASKRSA", "1"))
        self.label_18.setText(_translate("frmMASKRSA", "Method"))
        self.label_19.setText(_translate("frmMASKRSA", "Selection (LASSO, ElasticNet)"))
        self.label_20.setText(_translate("frmMASKRSA", "Solver (Ridge)"))
        self.cbFit.setText(_translate("frmMASKRSA", "Fit Intercept"))
        self.cbNormalize.setText(_translate("frmMASKRSA", "Normalize"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMASKRSA", "Parameters"))
        self.label_4.setText(_translate("frmMASKRSA", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMASKRSA", "0"))
        self.label_5.setText(_translate("frmMASKRSA", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMASKRSA", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMASKRSA", "Filter Class ID"))
        self.cbCov.setText(_translate("frmMASKRSA", "Covariance"))
        self.cbCorr.setText(_translate("frmMASKRSA", "Correlation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMASKRSA", "Metrics"))
        self.label_35.setText(_translate("frmMASKRSA", "Output Data"))
        self.btnOutFile.setText(_translate("frmMASKRSA", "..."))
        self.cbDiagram.setText(_translate("frmMASKRSA", "Show Diagrams"))
        self.cbBeta.setText(_translate("frmMASKRSA", "Save Beta Values"))
        self.btnRedraw.setText(_translate("frmMASKRSA", "Redraw"))

