# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMAGRSAGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMAGRSA(object):
    def setupUi(self, frmMAGRSA):
        frmMAGRSA.setObjectName("frmMAGRSA")
        frmMAGRSA.resize(782, 636)
        self.btnInFile = QtWidgets.QPushButton(frmMAGRSA)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMAGRSA)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.txtInFile = QtWidgets.QLineEdit(frmMAGRSA)
        self.txtInFile.setGeometry(QtCore.QRect(180, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMAGRSA)
        self.btnConvert.setGeometry(QtCore.QRect(620, 580, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.btnClose = QtWidgets.QPushButton(frmMAGRSA)
        self.btnClose.setGeometry(QtCore.QRect(30, 580, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMAGRSA)
        self.tabWidget.setGeometry(QtCore.QRect(30, 150, 731, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.label_3.setObjectName("label_3")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(180, 90, 181, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(180, 50, 181, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.txtSubject = QtWidgets.QComboBox(self.tab)
        self.txtSubject.setGeometry(QtCore.QRect(180, 170, 181, 26))
        self.txtSubject.setEditable(True)
        self.txtSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubject.setObjectName("txtSubject")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 111, 16))
        self.label_6.setObjectName("label_6")
        self.txtRun = QtWidgets.QComboBox(self.tab)
        self.txtRun.setGeometry(QtCore.QRect(180, 210, 181, 26))
        self.txtRun.setEditable(True)
        self.txtRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRun.setObjectName("txtRun")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 60, 16))
        self.label_7.setObjectName("label_7")
        self.txtCounter = QtWidgets.QComboBox(self.tab)
        self.txtCounter.setGeometry(QtCore.QRect(180, 250, 181, 26))
        self.txtCounter.setEditable(True)
        self.txtCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounter.setObjectName("txtCounter")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 131, 16))
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 10, 51, 17))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 290, 131, 16))
        self.label_9.setObjectName("label_9")
        self.txtTask = QtWidgets.QComboBox(self.tab)
        self.txtTask.setGeometry(QtCore.QRect(180, 290, 181, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTask.setObjectName("txtTask")
        self.txtDesign = QtWidgets.QComboBox(self.tab)
        self.txtDesign.setGeometry(QtCore.QRect(180, 130, 181, 26))
        self.txtDesign.setEditable(True)
        self.txtDesign.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtDesign.setObjectName("txtDesign")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 141, 16))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 30, 451, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cbFSubject = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbFSubject.setGeometry(QtCore.QRect(10, 30, 130, 20))
        self.cbFSubject.setChecked(True)
        self.cbFSubject.setObjectName("cbFSubject")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(10, 60, 201, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.rbFRun = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbFRun.setGeometry(QtCore.QRect(220, 60, 221, 20))
        self.rbFRun.setObjectName("rbFRun")
        self.cbFTask = QtWidgets.QCheckBox(self.tab_3)
        self.cbFTask.setGeometry(QtCore.QRect(510, 60, 161, 20))
        self.cbFTask.setObjectName("cbFTask")
        self.cbFCounter = QtWidgets.QCheckBox(self.tab_3)
        self.cbFCounter.setGeometry(QtCore.QRect(510, 100, 161, 20))
        self.cbFCounter.setObjectName("cbFCounter")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(40, 160, 121, 16))
        self.label_11.setObjectName("label_11")
        self.txtUnit = QtWidgets.QSpinBox(self.tab_3)
        self.txtUnit.setGeometry(QtCore.QRect(160, 160, 181, 24))
        self.txtUnit.setMinimum(1)
        self.txtUnit.setMaximum(1000000000)
        self.txtUnit.setObjectName("txtUnit")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 671, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 161, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.rbScale = QtWidgets.QRadioButton(self.groupBox)
        self.rbScale.setGeometry(QtCore.QRect(190, 40, 161, 20))
        self.rbScale.setChecked(True)
        self.rbScale.setObjectName("rbScale")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(350, 40, 131, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 120, 671, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rbAvg = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbAvg.setGeometry(QtCore.QRect(20, 30, 116, 22))
        self.rbAvg.setChecked(True)
        self.rbAvg.setObjectName("rbAvg")
        self.rbMax = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbMax.setGeometry(QtCore.QRect(170, 30, 116, 22))
        self.rbMax.setObjectName("rbMax")
        self.rbMin = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbMin.setGeometry(QtCore.QRect(330, 30, 116, 22))
        self.rbMin.setObjectName("rbMin")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 221))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbCov = QtWidgets.QCheckBox(self.tab_5)
        self.cbCov.setGeometry(QtCore.QRect(20, 30, 391, 20))
        self.cbCov.setChecked(True)
        self.cbCov.setObjectName("cbCov")
        self.cbCorr = QtWidgets.QCheckBox(self.tab_5)
        self.cbCorr.setGeometry(QtCore.QRect(20, 70, 391, 20))
        self.cbCorr.setChecked(True)
        self.cbCorr.setObjectName("cbCorr")
        self.tabWidget.addTab(self.tab_5, "")
        self.label_35 = QtWidgets.QLabel(frmMAGRSA)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMAGRSA)
        self.txtOutFile.setGeometry(QtCore.QRect(180, 60, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnOutFile = QtWidgets.QPushButton(frmMAGRSA)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.cbDiagram = QtWidgets.QCheckBox(frmMAGRSA)
        self.cbDiagram.setGeometry(QtCore.QRect(30, 100, 341, 22))
        self.cbDiagram.setChecked(True)
        self.cbDiagram.setObjectName("cbDiagram")
        self.cbBeta = QtWidgets.QCheckBox(frmMAGRSA)
        self.cbBeta.setGeometry(QtCore.QRect(250, 100, 341, 22))
        self.cbBeta.setChecked(True)
        self.cbBeta.setObjectName("cbBeta")
        self.btnRedraw = QtWidgets.QPushButton(frmMAGRSA)
        self.btnRedraw.setGeometry(QtCore.QRect(460, 580, 141, 32))
        self.btnRedraw.setObjectName("btnRedraw")

        self.retranslateUi(frmMAGRSA)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMAGRSA)
        frmMAGRSA.setTabOrder(self.txtInFile, self.btnInFile)
        frmMAGRSA.setTabOrder(self.btnInFile, self.tabWidget)
        frmMAGRSA.setTabOrder(self.tabWidget, self.txtData)
        frmMAGRSA.setTabOrder(self.txtData, self.txtLabel)
        frmMAGRSA.setTabOrder(self.txtLabel, self.btnConvert)
        frmMAGRSA.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMAGRSA):
        _translate = QtCore.QCoreApplication.translate
        frmMAGRSA.setWindowTitle(_translate("frmMAGRSA", "RAS"))
        self.btnInFile.setText(_translate("frmMAGRSA", "..."))
        self.label_33.setText(_translate("frmMAGRSA", "Input Data "))
        self.btnConvert.setText(_translate("frmMAGRSA", "Analyze"))
        self.btnClose.setText(_translate("frmMAGRSA", "Close"))
        self.label_2.setText(_translate("frmMAGRSA", "Data"))
        self.label_3.setText(_translate("frmMAGRSA", "Label"))
        self.label_6.setText(_translate("frmMAGRSA", "Subject"))
        self.label_7.setText(_translate("frmMAGRSA", "Run"))
        self.label_8.setText(_translate("frmMAGRSA", "Counter"))
        self.label.setText(_translate("frmMAGRSA", "ID"))
        self.label_9.setText(_translate("frmMAGRSA", "Task"))
        self.label_12.setText(_translate("frmMAGRSA", "Design"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMAGRSA", "Data"))
        self.groupBox_3.setTitle(_translate("frmMAGRSA", "<Subject Level>"))
        self.cbFSubject.setText(_translate("frmMAGRSA", "Subject"))
        self.radioButton.setText(_translate("frmMAGRSA", "Without Run"))
        self.rbFRun.setText(_translate("frmMAGRSA", "With Run"))
        self.cbFTask.setText(_translate("frmMAGRSA", "Task"))
        self.cbFCounter.setText(_translate("frmMAGRSA", "Counter"))
        self.label_11.setText(_translate("frmMAGRSA", "Unit number"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmMAGRSA", "Level"))
        self.groupBox.setTitle(_translate("frmMAGRSA", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMAGRSA", "Scale Data~N(0,1)"))
        self.rbScale.setText(_translate("frmMAGRSA", "Session Level"))
        self.radioButton_2.setText(_translate("frmMAGRSA", "Whole Data"))
        self.groupBox_2.setTitle(_translate("frmMAGRSA", "<Integration Metric>"))
        self.rbAvg.setText(_translate("frmMAGRSA", "Average"))
        self.rbMax.setText(_translate("frmMAGRSA", "Max"))
        self.rbMin.setText(_translate("frmMAGRSA", "Min"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMAGRSA", "Parameters"))
        self.label_4.setText(_translate("frmMAGRSA", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMAGRSA", "0"))
        self.label_5.setText(_translate("frmMAGRSA", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMAGRSA", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMAGRSA", "Filter Class ID"))
        self.cbCov.setText(_translate("frmMAGRSA", "Covariance"))
        self.cbCorr.setText(_translate("frmMAGRSA", "Correlation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMAGRSA", "Metrics"))
        self.label_35.setText(_translate("frmMAGRSA", "Output Data"))
        self.btnOutFile.setText(_translate("frmMAGRSA", "..."))
        self.cbDiagram.setText(_translate("frmMAGRSA", "Show Diagrams"))
        self.cbBeta.setText(_translate("frmMAGRSA", "Save Beta Values"))
        self.btnRedraw.setText(_translate("frmMAGRSA", "Redraw"))

