# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMABayesianRSAGUI.ui'
#
# Created by: PyQt6 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_frmMABayesianRSA(object):
    def setupUi(self, frmMABayesianRSA):
        frmMABayesianRSA.setObjectName("frmMABayesianRSA")
        frmMABayesianRSA.resize(780, 837)
        self.btnInFile = QtWidgets.QPushButton(frmMABayesianRSA)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMABayesianRSA)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.txtInFile = QtWidgets.QLineEdit(frmMABayesianRSA)
        self.txtInFile.setGeometry(QtCore.QRect(180, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMABayesianRSA)
        self.btnConvert.setGeometry(QtCore.QRect(620, 790, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.btnClose = QtWidgets.QPushButton(frmMABayesianRSA)
        self.btnClose.setGeometry(QtCore.QRect(30, 790, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMABayesianRSA)
        self.tabWidget.setGeometry(QtCore.QRect(30, 130, 731, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.label_3.setObjectName("label_3")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(180, 90, 181, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(180, 50, 181, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.txtSubject = QtWidgets.QComboBox(self.tab)
        self.txtSubject.setGeometry(QtCore.QRect(180, 170, 181, 26))
        self.txtSubject.setEditable(True)
        self.txtSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubject.setObjectName("txtSubject")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 111, 16))
        self.label_6.setObjectName("label_6")
        self.txtRun = QtWidgets.QComboBox(self.tab)
        self.txtRun.setGeometry(QtCore.QRect(180, 210, 181, 26))
        self.txtRun.setEditable(True)
        self.txtRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRun.setObjectName("txtRun")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 60, 16))
        self.label_7.setObjectName("label_7")
        self.txtCounter = QtWidgets.QComboBox(self.tab)
        self.txtCounter.setGeometry(QtCore.QRect(180, 250, 181, 26))
        self.txtCounter.setEditable(True)
        self.txtCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounter.setObjectName("txtCounter")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 131, 16))
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 10, 51, 17))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 290, 131, 16))
        self.label_9.setObjectName("label_9")
        self.txtTask = QtWidgets.QComboBox(self.tab)
        self.txtTask.setGeometry(QtCore.QRect(180, 290, 181, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTask.setObjectName("txtTask")
        self.txtDesign = QtWidgets.QComboBox(self.tab)
        self.txtDesign.setGeometry(QtCore.QRect(180, 130, 181, 26))
        self.txtDesign.setEditable(True)
        self.txtDesign.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtDesign.setObjectName("txtDesign")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 141, 16))
        self.label_12.setObjectName("label_12")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(20, 330, 131, 16))
        self.label_31.setObjectName("label_31")
        self.txtCond = QtWidgets.QComboBox(self.tab)
        self.txtCond.setGeometry(QtCore.QRect(180, 330, 181, 26))
        self.txtCond.setEditable(True)
        self.txtCond.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCond.setObjectName("txtCond")
        self.txtCoord = QtWidgets.QComboBox(self.tab)
        self.txtCoord.setGeometry(QtCore.QRect(180, 370, 181, 26))
        self.txtCoord.setEditable(True)
        self.txtCoord.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCoord.setObjectName("txtCoord")
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(20, 370, 131, 16))
        self.label_32.setObjectName("label_32")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 30, 451, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cbFSubject = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbFSubject.setGeometry(QtCore.QRect(10, 30, 130, 20))
        self.cbFSubject.setChecked(False)
        self.cbFSubject.setObjectName("cbFSubject")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(10, 60, 201, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.rbFRun = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbFRun.setGeometry(QtCore.QRect(220, 60, 221, 20))
        self.rbFRun.setObjectName("rbFRun")
        self.cbFTask = QtWidgets.QCheckBox(self.tab_3)
        self.cbFTask.setGeometry(QtCore.QRect(510, 60, 161, 20))
        self.cbFTask.setObjectName("cbFTask")
        self.cbFCounter = QtWidgets.QCheckBox(self.tab_3)
        self.cbFCounter.setGeometry(QtCore.QRect(510, 100, 161, 20))
        self.cbFCounter.setObjectName("cbFCounter")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(40, 160, 121, 16))
        self.label_11.setObjectName("label_11")
        self.txtUnit = QtWidgets.QSpinBox(self.tab_3)
        self.txtUnit.setGeometry(QtCore.QRect(160, 160, 181, 24))
        self.txtUnit.setMinimum(1)
        self.txtUnit.setMaximum(1000000000)
        self.txtUnit.setObjectName("txtUnit")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 671, 71))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 32, 161, 21))
        self.cbScale.setChecked(False)
        self.cbScale.setObjectName("cbScale")
        self.rbScale = QtWidgets.QRadioButton(self.groupBox)
        self.rbScale.setGeometry(QtCore.QRect(190, 32, 161, 20))
        self.rbScale.setChecked(True)
        self.rbScale.setObjectName("rbScale")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(350, 32, 131, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 90, 671, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rbAvg = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbAvg.setGeometry(QtCore.QRect(20, 33, 116, 22))
        self.rbAvg.setChecked(True)
        self.rbAvg.setObjectName("rbAvg")
        self.rbMax = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbMax.setGeometry(QtCore.QRect(170, 33, 116, 22))
        self.rbMax.setObjectName("rbMax")
        self.rbMin = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbMin.setGeometry(QtCore.QRect(330, 33, 116, 22))
        self.rbMin.setObjectName("rbMin")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(30, 420, 141, 16))
        self.label_16.setObjectName("label_16")
        self.cbTau2Prior = QtWidgets.QComboBox(self.tab_2)
        self.cbTau2Prior.setGeometry(QtCore.QRect(180, 260, 160, 26))
        self.cbTau2Prior.setObjectName("cbTau2Prior")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(30, 180, 151, 16))
        self.label_18.setObjectName("label_18")
        self.cbGBS = QtWidgets.QCheckBox(self.tab_2)
        self.cbGBS.setGeometry(QtCore.QRect(390, 180, 311, 20))
        self.cbGBS.setChecked(True)
        self.cbGBS.setObjectName("cbGBS")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(30, 380, 141, 16))
        self.label_14.setObjectName("label_14")
        self.txtRank = QtWidgets.QLineEdit(self.tab_2)
        self.txtRank.setGeometry(QtCore.QRect(180, 420, 160, 21))
        self.txtRank.setObjectName("txtRank")
        self.txtMaxIter = QtWidgets.QLineEdit(self.tab_2)
        self.txtMaxIter.setGeometry(QtCore.QRect(180, 380, 160, 21))
        self.txtMaxIter.setObjectName("txtMaxIter")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 340, 141, 16))
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(30, 460, 151, 16))
        self.label_13.setObjectName("label_13")
        self.txtInitIter = QtWidgets.QLineEdit(self.tab_2)
        self.txtInitIter.setGeometry(QtCore.QRect(180, 340, 160, 21))
        self.txtInitIter.setObjectName("txtInitIter")
        self.cbNuregMethod = QtWidgets.QComboBox(self.tab_2)
        self.cbNuregMethod.setGeometry(QtCore.QRect(180, 220, 160, 26))
        self.cbNuregMethod.setObjectName("cbNuregMethod")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(30, 220, 151, 16))
        self.label_19.setObjectName("label_19")
        self.txtNumReg = QtWidgets.QLineEdit(self.tab_2)
        self.txtNumReg.setGeometry(QtCore.QRect(180, 460, 160, 21))
        self.txtNumReg.setObjectName("txtNumReg")
        self.txtTole = QtWidgets.QLineEdit(self.tab_2)
        self.txtTole.setGeometry(QtCore.QRect(180, 500, 160, 21))
        self.txtTole.setObjectName("txtTole")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(30, 500, 141, 16))
        self.label_17.setObjectName("label_17")
        self.cbMethod = QtWidgets.QComboBox(self.tab_2)
        self.cbMethod.setGeometry(QtCore.QRect(180, 180, 160, 26))
        self.cbMethod.setObjectName("cbMethod")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(30, 260, 151, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(390, 340, 141, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(390, 420, 151, 16))
        self.label_22.setObjectName("label_22")
        self.txtSpaceSmoothRange = QtWidgets.QLineEdit(self.tab_2)
        self.txtSpaceSmoothRange.setGeometry(QtCore.QRect(540, 300, 160, 21))
        self.txtSpaceSmoothRange.setObjectName("txtSpaceSmoothRange")
        self.txtIntenSmoothRange = QtWidgets.QLineEdit(self.tab_2)
        self.txtIntenSmoothRange.setGeometry(QtCore.QRect(540, 340, 160, 21))
        self.txtIntenSmoothRange.setObjectName("txtIntenSmoothRange")
        self.txtAnnealSpeed = QtWidgets.QLineEdit(self.tab_2)
        self.txtAnnealSpeed.setGeometry(QtCore.QRect(540, 420, 160, 21))
        self.txtAnnealSpeed.setObjectName("txtAnnealSpeed")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(390, 380, 141, 16))
        self.label_23.setObjectName("label_23")
        self.txtTauRange = QtWidgets.QLineEdit(self.tab_2)
        self.txtTauRange.setGeometry(QtCore.QRect(540, 380, 160, 21))
        self.txtTauRange.setObjectName("txtTauRange")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(390, 300, 141, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(390, 460, 141, 16))
        self.label_25.setObjectName("label_25")
        self.txtEta = QtWidgets.QLineEdit(self.tab_2)
        self.txtEta.setGeometry(QtCore.QRect(540, 460, 160, 21))
        self.txtEta.setObjectName("txtEta")
        self.cbGPI = QtWidgets.QCheckBox(self.tab_2)
        self.cbGPI.setGeometry(QtCore.QRect(390, 220, 311, 20))
        self.cbGPI.setChecked(True)
        self.cbGPI.setObjectName("cbGPI")
        self.cbBaselineSingle = QtWidgets.QCheckBox(self.tab_2)
        self.cbBaselineSingle.setGeometry(QtCore.QRect(390, 260, 311, 20))
        self.cbBaselineSingle.setChecked(True)
        self.cbBaselineSingle.setObjectName("cbBaselineSingle")
        self.cbAutoNuisance = QtWidgets.QCheckBox(self.tab_2)
        self.cbAutoNuisance.setGeometry(QtCore.QRect(30, 580, 311, 20))
        self.cbAutoNuisance.setChecked(True)
        self.cbAutoNuisance.setObjectName("cbAutoNuisance")
        self.cbNuregZscore = QtWidgets.QCheckBox(self.tab_2)
        self.cbNuregZscore.setGeometry(QtCore.QRect(390, 580, 311, 20))
        self.cbNuregZscore.setChecked(True)
        self.cbNuregZscore.setObjectName("cbNuregZscore")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(30, 300, 151, 16))
        self.label_26.setObjectName("label_26")
        self.cbSNRPrior = QtWidgets.QComboBox(self.tab_2)
        self.cbSNRPrior.setGeometry(QtCore.QRect(180, 300, 160, 26))
        self.cbSNRPrior.setObjectName("cbSNRPrior")
        self.txtLogSRange = QtWidgets.QLineEdit(self.tab_2)
        self.txtLogSRange.setGeometry(QtCore.QRect(180, 540, 160, 21))
        self.txtLogSRange.setObjectName("txtLogSRange")
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        self.label_37.setGeometry(QtCore.QRect(30, 540, 141, 16))
        self.label_37.setObjectName("label_37")
        self.txtRhoBins = QtWidgets.QLineEdit(self.tab_2)
        self.txtRhoBins.setGeometry(QtCore.QRect(540, 540, 160, 21))
        self.txtRhoBins.setObjectName("txtRhoBins")
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        self.label_38.setGeometry(QtCore.QRect(390, 540, 141, 16))
        self.label_38.setObjectName("label_38")
        self.txtSNRBins = QtWidgets.QLineEdit(self.tab_2)
        self.txtSNRBins.setGeometry(QtCore.QRect(540, 500, 160, 21))
        self.txtSNRBins.setObjectName("txtSNRBins")
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        self.label_39.setGeometry(QtCore.QRect(390, 500, 141, 16))
        self.label_39.setObjectName("label_39")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 221))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbCov = QtWidgets.QCheckBox(self.tab_5)
        self.cbCov.setGeometry(QtCore.QRect(20, 30, 391, 20))
        self.cbCov.setChecked(True)
        self.cbCov.setObjectName("cbCov")
        self.cbCorr = QtWidgets.QCheckBox(self.tab_5)
        self.cbCorr.setGeometry(QtCore.QRect(20, 70, 391, 20))
        self.cbCorr.setChecked(True)
        self.cbCorr.setObjectName("cbCorr")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(20, 39, 71, 16))
        self.label_27.setObjectName("label_27")
        self.txtTitleCorr = QtWidgets.QLineEdit(self.tab_6)
        self.txtTitleCorr.setGeometry(QtCore.QRect(240, 133, 461, 35))
        self.txtTitleCorr.setObjectName("txtTitleCorr")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(20, 90, 221, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(20, 139, 221, 20))
        self.label_29.setObjectName("label_29")
        self.txtTitleCov = QtWidgets.QLineEdit(self.tab_6)
        self.txtTitleCov.setGeometry(QtCore.QRect(240, 83, 461, 35))
        self.txtTitleCov.setObjectName("txtTitleCov")
        self.txtTitleDen = QtWidgets.QLineEdit(self.tab_6)
        self.txtTitleDen.setGeometry(QtCore.QRect(240, 184, 461, 35))
        self.txtTitleDen.setObjectName("txtTitleDen")
        self.label_30 = QtWidgets.QLabel(self.tab_6)
        self.label_30.setGeometry(QtCore.QRect(20, 190, 221, 20))
        self.label_30.setObjectName("label_30")
        self.txtFontSize = QtWidgets.QSpinBox(self.tab_6)
        self.txtFontSize.setGeometry(QtCore.QRect(240, 33, 171, 35))
        self.txtFontSize.setMinimum(1)
        self.txtFontSize.setMaximum(1000)
        self.txtFontSize.setProperty("value", 14)
        self.txtFontSize.setObjectName("txtFontSize")
        self.txtYRotation = QtWidgets.QSpinBox(self.tab_6)
        self.txtYRotation.setGeometry(QtCore.QRect(240, 283, 171, 35))
        self.txtYRotation.setMinimum(0)
        self.txtYRotation.setMaximum(359)
        self.txtYRotation.setProperty("value", 0)
        self.txtYRotation.setObjectName("txtYRotation")
        self.txtXRotation = QtWidgets.QSpinBox(self.tab_6)
        self.txtXRotation.setGeometry(QtCore.QRect(240, 235, 171, 35))
        self.txtXRotation.setMinimum(0)
        self.txtXRotation.setMaximum(359)
        self.txtXRotation.setProperty("value", 45)
        self.txtXRotation.setObjectName("txtXRotation")
        self.label_34 = QtWidgets.QLabel(self.tab_6)
        self.label_34.setGeometry(QtCore.QRect(20, 242, 71, 16))
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.tab_6)
        self.label_36.setGeometry(QtCore.QRect(20, 290, 71, 16))
        self.label_36.setObjectName("label_36")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.txtLic = QtWidgets.QTextEdit(self.tab_8)
        self.txtLic.setGeometry(QtCore.QRect(10, 10, 711, 591))
        self.txtLic.setReadOnly(True)
        self.txtLic.setObjectName("txtLic")
        self.tabWidget.addTab(self.tab_8, "")
        self.label_35 = QtWidgets.QLabel(frmMABayesianRSA)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMABayesianRSA)
        self.txtOutFile.setGeometry(QtCore.QRect(180, 60, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnOutFile = QtWidgets.QPushButton(frmMABayesianRSA)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.cbDiagram = QtWidgets.QCheckBox(frmMABayesianRSA)
        self.cbDiagram.setGeometry(QtCore.QRect(30, 94, 341, 22))
        self.cbDiagram.setChecked(True)
        self.cbDiagram.setObjectName("cbDiagram")
        self.cbBeta = QtWidgets.QCheckBox(frmMABayesianRSA)
        self.cbBeta.setGeometry(QtCore.QRect(250, 94, 341, 22))
        self.cbBeta.setChecked(True)
        self.cbBeta.setObjectName("cbBeta")
        self.btnRedraw = QtWidgets.QPushButton(frmMABayesianRSA)
        self.btnRedraw.setGeometry(QtCore.QRect(460, 790, 141, 32))
        self.btnRedraw.setObjectName("btnRedraw")

        self.retranslateUi(frmMABayesianRSA)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMABayesianRSA)
        frmMABayesianRSA.setTabOrder(self.txtInFile, self.btnInFile)
        frmMABayesianRSA.setTabOrder(self.btnInFile, self.tabWidget)
        frmMABayesianRSA.setTabOrder(self.tabWidget, self.txtData)
        frmMABayesianRSA.setTabOrder(self.txtData, self.txtLabel)
        frmMABayesianRSA.setTabOrder(self.txtLabel, self.btnConvert)
        frmMABayesianRSA.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMABayesianRSA):
        _translate = QtCore.QCoreApplication.translate
        frmMABayesianRSA.setWindowTitle(_translate("frmMABayesianRSA", "RAS"))
        self.btnInFile.setText(_translate("frmMABayesianRSA", "..."))
        self.label_33.setText(_translate("frmMABayesianRSA", "Input Data "))
        self.btnConvert.setText(_translate("frmMABayesianRSA", "Analyze"))
        self.btnClose.setText(_translate("frmMABayesianRSA", "Close"))
        self.label_2.setText(_translate("frmMABayesianRSA", "Data"))
        self.label_3.setText(_translate("frmMABayesianRSA", "Label"))
        self.label_6.setText(_translate("frmMABayesianRSA", "Subject"))
        self.label_7.setText(_translate("frmMABayesianRSA", "Run"))
        self.label_8.setText(_translate("frmMABayesianRSA", "Counter"))
        self.label.setText(_translate("frmMABayesianRSA", "ID"))
        self.label_9.setText(_translate("frmMABayesianRSA", "Task"))
        self.label_12.setText(_translate("frmMABayesianRSA", "Design"))
        self.label_31.setText(_translate("frmMABayesianRSA", "Condition"))
        self.label_32.setText(_translate("frmMABayesianRSA", "Coordinate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMABayesianRSA", "Data"))
        self.groupBox_3.setTitle(_translate("frmMABayesianRSA", "<Subject Level>"))
        self.cbFSubject.setText(_translate("frmMABayesianRSA", "Subject"))
        self.radioButton.setText(_translate("frmMABayesianRSA", "Without Run"))
        self.rbFRun.setText(_translate("frmMABayesianRSA", "With Run"))
        self.cbFTask.setText(_translate("frmMABayesianRSA", "Task"))
        self.cbFCounter.setText(_translate("frmMABayesianRSA", "Counter"))
        self.label_11.setText(_translate("frmMABayesianRSA", "Unit number"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmMABayesianRSA", "Level"))
        self.groupBox.setTitle(_translate("frmMABayesianRSA", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMABayesianRSA", "Scale Data~N(0,1)"))
        self.rbScale.setText(_translate("frmMABayesianRSA", "Session Level"))
        self.radioButton_2.setText(_translate("frmMABayesianRSA", "Whole Data"))
        self.groupBox_2.setTitle(_translate("frmMABayesianRSA", "<Integration Metric>"))
        self.rbAvg.setText(_translate("frmMABayesianRSA", "Average"))
        self.rbMax.setText(_translate("frmMABayesianRSA", "Max"))
        self.rbMin.setText(_translate("frmMABayesianRSA", "Min"))
        self.label_16.setText(_translate("frmMABayesianRSA", "Rank (Full=0)"))
        self.label_18.setText(_translate("frmMABayesianRSA", "Method"))
        self.cbGBS.setText(_translate("frmMABayesianRSA", "Gaussion Process (GP) Space"))
        self.label_14.setText(_translate("frmMABayesianRSA", "Max Iteration"))
        self.txtRank.setText(_translate("frmMABayesianRSA", "0"))
        self.txtMaxIter.setText(_translate("frmMABayesianRSA", "1000"))
        self.label_15.setText(_translate("frmMABayesianRSA", "Init of Iteration"))
        self.label_13.setText(_translate("frmMABayesianRSA", "Number of nuisance"))
        self.txtInitIter.setText(_translate("frmMABayesianRSA", "20"))
        self.label_19.setText(_translate("frmMABayesianRSA", "nureg_method"))
        self.txtNumReg.setText(_translate("frmMABayesianRSA", "0"))
        self.txtTole.setText(_translate("frmMABayesianRSA", "0.0001"))
        self.label_17.setText(_translate("frmMABayesianRSA", "Tolerance"))
        self.label_20.setText(_translate("frmMABayesianRSA", "tau2_prior"))
        self.label_21.setText(_translate("frmMABayesianRSA", "inten_smooth_range"))
        self.label_22.setText(_translate("frmMABayesianRSA", "anneal_speed"))
        self.txtSpaceSmoothRange.setText(_translate("frmMABayesianRSA", "0"))
        self.txtIntenSmoothRange.setText(_translate("frmMABayesianRSA", "0"))
        self.txtAnnealSpeed.setText(_translate("frmMABayesianRSA", "10"))
        self.label_23.setText(_translate("frmMABayesianRSA", "tau_range"))
        self.txtTauRange.setText(_translate("frmMABayesianRSA", "5.0"))
        self.label_24.setText(_translate("frmMABayesianRSA", "space_smooth_range"))
        self.label_25.setText(_translate("frmMABayesianRSA", "eta"))
        self.txtEta.setText(_translate("frmMABayesianRSA", "0.0001"))
        self.cbGPI.setText(_translate("frmMABayesianRSA", "Gaussion Process (GP) Inten"))
        self.cbBaselineSingle.setText(_translate("frmMABayesianRSA", "Baseline Single"))
        self.cbAutoNuisance.setText(_translate("frmMABayesianRSA", "Auto Nuisance"))
        self.cbNuregZscore.setText(_translate("frmMABayesianRSA", "Nureg Zscore"))
        self.label_26.setText(_translate("frmMABayesianRSA", "SNR_prior"))
        self.txtLogSRange.setText(_translate("frmMABayesianRSA", "1.0"))
        self.label_37.setText(_translate("frmMABayesianRSA", "logS_range"))
        self.txtRhoBins.setText(_translate("frmMABayesianRSA", "20"))
        self.label_38.setText(_translate("frmMABayesianRSA", "rho_bins"))
        self.txtSNRBins.setText(_translate("frmMABayesianRSA", "21"))
        self.label_39.setText(_translate("frmMABayesianRSA", "SNR_bins"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMABayesianRSA", "Parameters"))
        self.label_4.setText(_translate("frmMABayesianRSA", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMABayesianRSA", "0"))
        self.label_5.setText(_translate("frmMABayesianRSA", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMABayesianRSA", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMABayesianRSA", "Filter Class ID"))
        self.cbCov.setText(_translate("frmMABayesianRSA", "Covariance"))
        self.cbCorr.setText(_translate("frmMABayesianRSA", "Correlation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMABayesianRSA", "Metrics"))
        self.label_27.setText(_translate("frmMABayesianRSA", "Font Size"))
        self.label_28.setText(_translate("frmMABayesianRSA", "Figure Title: Cov (Null = Auto)"))
        self.label_29.setText(_translate("frmMABayesianRSA", "Figure Title: Corr (Null = Auto)"))
        self.label_30.setText(_translate("frmMABayesianRSA", "Figure Title: Den (Null = Auto)"))
        self.label_34.setText(_translate("frmMABayesianRSA", "X Rotation"))
        self.label_36.setText(_translate("frmMABayesianRSA", "Y Rotation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("frmMABayesianRSA", "Options"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("frmMABayesianRSA", "Optimizer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("frmMABayesianRSA", "License"))
        self.label_35.setText(_translate("frmMABayesianRSA", "Output Data"))
        self.btnOutFile.setText(_translate("frmMABayesianRSA", "..."))
        self.cbDiagram.setText(_translate("frmMABayesianRSA", "Show Diagrams"))
        self.cbBeta.setText(_translate("frmMABayesianRSA", "Save Beta Values"))
        self.btnRedraw.setText(_translate("frmMABayesianRSA", "Redraw"))

