# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMANetworkGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMANetwork(object):
    def setupUi(self, frmMANetwork):
        frmMANetwork.setObjectName("frmMANetwork")
        frmMANetwork.resize(782, 636)
        self.btnInFile = QtWidgets.QPushButton(frmMANetwork)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMANetwork)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.txtInFile = QtWidgets.QLineEdit(frmMANetwork)
        self.txtInFile.setGeometry(QtCore.QRect(180, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMANetwork)
        self.btnConvert.setGeometry(QtCore.QRect(620, 590, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.btnClose = QtWidgets.QPushButton(frmMANetwork)
        self.btnClose.setGeometry(QtCore.QRect(30, 590, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMANetwork)
        self.tabWidget.setGeometry(QtCore.QRect(30, 170, 731, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.label_3.setObjectName("label_3")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(180, 90, 181, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(180, 50, 181, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 10, 51, 17))
        self.label.setObjectName("label")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(20, 130, 131, 16))
        self.label_31.setObjectName("label_31")
        self.txtCond = QtWidgets.QComboBox(self.tab)
        self.txtCond.setGeometry(QtCore.QRect(180, 130, 181, 26))
        self.txtCond.setEditable(True)
        self.txtCond.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCond.setObjectName("txtCond")
        self.lblImgShape = QtWidgets.QLabel(self.tab)
        self.lblImgShape.setGeometry(QtCore.QRect(440, 50, 271, 20))
        self.lblImgShape.setObjectName("lblImgShape")
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(20, 170, 131, 16))
        self.label_32.setObjectName("label_32")
        self.txtCoord = QtWidgets.QComboBox(self.tab)
        self.txtCoord.setGeometry(QtCore.QRect(180, 170, 181, 26))
        self.txtCoord.setEditable(True)
        self.txtCoord.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCoord.setObjectName("txtCoord")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 671, 71))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 32, 161, 21))
        self.cbScale.setChecked(False)
        self.cbScale.setObjectName("cbScale")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 100, 181, 16))
        self.label_15.setObjectName("label_15")
        self.txtThre = QtWidgets.QLineEdit(self.tab_2)
        self.txtThre.setGeometry(QtCore.QRect(220, 100, 160, 21))
        self.txtThre.setObjectName("txtThre")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 281))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(20, 39, 71, 16))
        self.label_27.setObjectName("label_27")
        self.txtTitleCorr = QtWidgets.QLineEdit(self.tab_6)
        self.txtTitleCorr.setGeometry(QtCore.QRect(240, 133, 461, 35))
        self.txtTitleCorr.setObjectName("txtTitleCorr")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(20, 90, 221, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(20, 139, 221, 20))
        self.label_29.setObjectName("label_29")
        self.txtTitleCov = QtWidgets.QLineEdit(self.tab_6)
        self.txtTitleCov.setGeometry(QtCore.QRect(240, 83, 461, 35))
        self.txtTitleCov.setObjectName("txtTitleCov")
        self.txtTitleDen = QtWidgets.QLineEdit(self.tab_6)
        self.txtTitleDen.setGeometry(QtCore.QRect(240, 184, 461, 35))
        self.txtTitleDen.setObjectName("txtTitleDen")
        self.label_30 = QtWidgets.QLabel(self.tab_6)
        self.label_30.setGeometry(QtCore.QRect(20, 190, 221, 20))
        self.label_30.setObjectName("label_30")
        self.txtFontSize = QtWidgets.QSpinBox(self.tab_6)
        self.txtFontSize.setGeometry(QtCore.QRect(240, 33, 171, 35))
        self.txtFontSize.setMinimum(1)
        self.txtFontSize.setMaximum(1000)
        self.txtFontSize.setProperty("value", 14)
        self.txtFontSize.setObjectName("txtFontSize")
        self.txtYRotation = QtWidgets.QSpinBox(self.tab_6)
        self.txtYRotation.setGeometry(QtCore.QRect(240, 283, 171, 35))
        self.txtYRotation.setMinimum(0)
        self.txtYRotation.setMaximum(359)
        self.txtYRotation.setProperty("value", 0)
        self.txtYRotation.setObjectName("txtYRotation")
        self.txtXRotation = QtWidgets.QSpinBox(self.tab_6)
        self.txtXRotation.setGeometry(QtCore.QRect(240, 235, 171, 35))
        self.txtXRotation.setMinimum(0)
        self.txtXRotation.setMaximum(359)
        self.txtXRotation.setProperty("value", 45)
        self.txtXRotation.setObjectName("txtXRotation")
        self.label_34 = QtWidgets.QLabel(self.tab_6)
        self.label_34.setGeometry(QtCore.QRect(20, 242, 71, 16))
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.tab_6)
        self.label_36.setGeometry(QtCore.QRect(20, 290, 71, 16))
        self.label_36.setObjectName("label_36")
        self.tabWidget.addTab(self.tab_6, "")
        self.label_35 = QtWidgets.QLabel(frmMANetwork)
        self.label_35.setGeometry(QtCore.QRect(30, 100, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMANetwork)
        self.txtOutFile.setGeometry(QtCore.QRect(180, 100, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnOutFile = QtWidgets.QPushButton(frmMANetwork)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 100, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.cbDiagram = QtWidgets.QCheckBox(frmMANetwork)
        self.cbDiagram.setGeometry(QtCore.QRect(30, 140, 341, 22))
        self.cbDiagram.setChecked(True)
        self.cbDiagram.setObjectName("cbDiagram")
        self.btnRedraw = QtWidgets.QPushButton(frmMANetwork)
        self.btnRedraw.setGeometry(QtCore.QRect(460, 590, 141, 32))
        self.btnRedraw.setObjectName("btnRedraw")
        self.btnAtlasFile = QtWidgets.QPushButton(frmMANetwork)
        self.btnAtlasFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnAtlasFile.setObjectName("btnAtlasFile")
        self.label_37 = QtWidgets.QLabel(frmMANetwork)
        self.label_37.setGeometry(QtCore.QRect(30, 60, 211, 16))
        self.label_37.setObjectName("label_37")
        self.txtAtlasFile = QtWidgets.QLineEdit(frmMANetwork)
        self.txtAtlasFile.setGeometry(QtCore.QRect(180, 60, 521, 21))
        self.txtAtlasFile.setText("")
        self.txtAtlasFile.setObjectName("txtAtlasFile")

        self.retranslateUi(frmMANetwork)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMANetwork)
        frmMANetwork.setTabOrder(self.txtInFile, self.btnInFile)
        frmMANetwork.setTabOrder(self.btnInFile, self.tabWidget)
        frmMANetwork.setTabOrder(self.tabWidget, self.txtData)
        frmMANetwork.setTabOrder(self.txtData, self.txtLabel)
        frmMANetwork.setTabOrder(self.txtLabel, self.btnConvert)
        frmMANetwork.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMANetwork):
        _translate = QtCore.QCoreApplication.translate
        frmMANetwork.setWindowTitle(_translate("frmMANetwork", "RAS"))
        self.btnInFile.setText(_translate("frmMANetwork", "..."))
        self.label_33.setText(_translate("frmMANetwork", "Input Data "))
        self.btnConvert.setText(_translate("frmMANetwork", "Analyze"))
        self.btnClose.setText(_translate("frmMANetwork", "Close"))
        self.label_2.setText(_translate("frmMANetwork", "Data"))
        self.label_3.setText(_translate("frmMANetwork", "Label"))
        self.label.setText(_translate("frmMANetwork", "ID"))
        self.label_31.setText(_translate("frmMANetwork", "Condition"))
        self.lblImgShape.setText(_translate("frmMANetwork", "imgShape"))
        self.label_32.setText(_translate("frmMANetwork", "Coordinate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMANetwork", "Data"))
        self.groupBox.setTitle(_translate("frmMANetwork", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMANetwork", "Scale Data~N(0,1)"))
        self.label_15.setText(_translate("frmMANetwork", "Thresholding (of max)"))
        self.txtThre.setText(_translate("frmMANetwork", "0.9"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMANetwork", "Parameters"))
        self.label_4.setText(_translate("frmMANetwork", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMANetwork", "0"))
        self.label_5.setText(_translate("frmMANetwork", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMANetwork", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMANetwork", "Filter Class ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmMANetwork", "Integration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMANetwork", "Metric"))
        self.label_27.setText(_translate("frmMANetwork", "Font Size"))
        self.label_28.setText(_translate("frmMANetwork", "Figure Title: Cov (Null = Auto)"))
        self.label_29.setText(_translate("frmMANetwork", "Figure Title: Corr (Null = Auto)"))
        self.label_30.setText(_translate("frmMANetwork", "Figure Title: Den (Null = Auto)"))
        self.label_34.setText(_translate("frmMANetwork", "X Rotation"))
        self.label_36.setText(_translate("frmMANetwork", "Y Rotation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("frmMANetwork", "Options"))
        self.label_35.setText(_translate("frmMANetwork", "Output Data"))
        self.btnOutFile.setText(_translate("frmMANetwork", "..."))
        self.cbDiagram.setText(_translate("frmMANetwork", "Show Diagrams"))
        self.btnRedraw.setText(_translate("frmMANetwork", "Redraw"))
        self.btnAtlasFile.setText(_translate("frmMANetwork", "..."))
        self.label_37.setText(_translate("frmMANetwork", "Atlas"))

