# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMADeepRSAGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMADeepRSA(object):
    def setupUi(self, frmMADeepRSA):
        frmMADeepRSA.setObjectName("frmMADeepRSA")
        frmMADeepRSA.resize(838, 580)
        self.btnInFile = QtWidgets.QPushButton(frmMADeepRSA)
        self.btnInFile.setGeometry(QtCore.QRect(770, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMADeepRSA)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.txtInFile = QtWidgets.QLineEdit(frmMADeepRSA)
        self.txtInFile.setGeometry(QtCore.QRect(180, 20, 581, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMADeepRSA)
        self.btnConvert.setGeometry(QtCore.QRect(680, 530, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.btnClose = QtWidgets.QPushButton(frmMADeepRSA)
        self.btnClose.setGeometry(QtCore.QRect(30, 530, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMADeepRSA)
        self.tabWidget.setGeometry(QtCore.QRect(30, 150, 791, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.label_3.setObjectName("label_3")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(180, 90, 181, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(180, 50, 181, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.txtSubject = QtWidgets.QComboBox(self.tab)
        self.txtSubject.setGeometry(QtCore.QRect(180, 170, 181, 26))
        self.txtSubject.setEditable(True)
        self.txtSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubject.setObjectName("txtSubject")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 111, 16))
        self.label_6.setObjectName("label_6")
        self.txtRun = QtWidgets.QComboBox(self.tab)
        self.txtRun.setGeometry(QtCore.QRect(180, 210, 181, 26))
        self.txtRun.setEditable(True)
        self.txtRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRun.setObjectName("txtRun")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 60, 16))
        self.label_7.setObjectName("label_7")
        self.txtCounter = QtWidgets.QComboBox(self.tab)
        self.txtCounter.setGeometry(QtCore.QRect(180, 250, 181, 26))
        self.txtCounter.setEditable(True)
        self.txtCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounter.setObjectName("txtCounter")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 131, 16))
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 10, 51, 17))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 290, 131, 16))
        self.label_9.setObjectName("label_9")
        self.txtTask = QtWidgets.QComboBox(self.tab)
        self.txtTask.setGeometry(QtCore.QRect(180, 290, 181, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTask.setObjectName("txtTask")
        self.txtRunVal = QtWidgets.QComboBox(self.tab)
        self.txtRunVal.setGeometry(QtCore.QRect(400, 210, 181, 26))
        self.txtRunVal.setEditable(True)
        self.txtRunVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRunVal.setObjectName("txtRunVal")
        self.txtTaskVal = QtWidgets.QComboBox(self.tab)
        self.txtTaskVal.setGeometry(QtCore.QRect(400, 290, 181, 26))
        self.txtTaskVal.setEditable(True)
        self.txtTaskVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTaskVal.setObjectName("txtTaskVal")
        self.txtSubjectVal = QtWidgets.QComboBox(self.tab)
        self.txtSubjectVal.setGeometry(QtCore.QRect(400, 170, 181, 26))
        self.txtSubjectVal.setEditable(True)
        self.txtSubjectVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubjectVal.setObjectName("txtSubjectVal")
        self.txtCounterVal = QtWidgets.QComboBox(self.tab)
        self.txtCounterVal.setGeometry(QtCore.QRect(400, 250, 181, 26))
        self.txtCounterVal.setEditable(True)
        self.txtCounterVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounterVal.setObjectName("txtCounterVal")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(470, 10, 111, 17))
        self.label_11.setObjectName("label_11")
        self.btnRef = QtWidgets.QPushButton(self.tab)
        self.btnRef.setGeometry(QtCore.QRect(630, 370, 131, 29))
        self.btnRef.setObjectName("btnRef")
        self.txtDesign = QtWidgets.QComboBox(self.tab)
        self.txtDesign.setGeometry(QtCore.QRect(180, 130, 181, 26))
        self.txtDesign.setEditable(True)
        self.txtDesign.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtDesign.setObjectName("txtDesign")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 141, 16))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 751, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 641, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(20, 210, 201, 16))
        self.label_16.setObjectName("label_16")
        self.txtIter = QtWidgets.QLineEdit(self.tab_2)
        self.txtIter.setGeometry(QtCore.QRect(220, 210, 160, 21))
        self.txtIter.setObjectName("txtIter")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(20, 250, 201, 16))
        self.label_17.setObjectName("label_17")
        self.txtBatch = QtWidgets.QLineEdit(self.tab_2)
        self.txtBatch.setGeometry(QtCore.QRect(220, 250, 160, 21))
        self.txtBatch.setObjectName("txtBatch")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(400, 210, 201, 16))
        self.label_18.setObjectName("label_18")
        self.txtReportStep = QtWidgets.QLineEdit(self.tab_2)
        self.txtReportStep.setGeometry(QtCore.QRect(600, 210, 160, 21))
        self.txtReportStep.setObjectName("txtReportStep")
        self.txtRate = QtWidgets.QLineEdit(self.tab_2)
        self.txtRate.setGeometry(QtCore.QRect(600, 250, 160, 21))
        self.txtRate.setObjectName("txtRate")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(400, 250, 201, 16))
        self.label_19.setObjectName("label_19")
        self.txtLayers = QtWidgets.QLineEdit(self.tab_2)
        self.txtLayers.setGeometry(QtCore.QRect(220, 130, 160, 21))
        self.txtLayers.setObjectName("txtLayers")
        self.cbVerbose = QtWidgets.QCheckBox(self.tab_2)
        self.cbVerbose.setGeometry(QtCore.QRect(20, 290, 371, 20))
        self.cbVerbose.setChecked(True)
        self.cbVerbose.setObjectName("cbVerbose")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(20, 130, 201, 16))
        self.label_13.setObjectName("label_13")
        self.cbActivation = QtWidgets.QComboBox(self.tab_2)
        self.cbActivation.setGeometry(QtCore.QRect(220, 170, 161, 26))
        self.cbActivation.setObjectName("cbActivation")
        self.cbLossNorm = QtWidgets.QComboBox(self.tab_2)
        self.cbLossNorm.setGeometry(QtCore.QRect(600, 170, 161, 26))
        self.cbLossNorm.setObjectName("cbLossNorm")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(20, 170, 201, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(400, 170, 201, 16))
        self.label_15.setObjectName("label_15")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(400, 130, 371, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(400, 290, 201, 16))
        self.label_21.setObjectName("label_21")
        self.txtAlpha = QtWidgets.QLineEdit(self.tab_2)
        self.txtAlpha.setGeometry(QtCore.QRect(600, 290, 160, 21))
        self.txtAlpha.setObjectName("txtAlpha")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 221))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbCov = QtWidgets.QCheckBox(self.tab_5)
        self.cbCov.setGeometry(QtCore.QRect(20, 30, 391, 20))
        self.cbCov.setChecked(True)
        self.cbCov.setObjectName("cbCov")
        self.cbCorr = QtWidgets.QCheckBox(self.tab_5)
        self.cbCorr.setGeometry(QtCore.QRect(20, 70, 391, 20))
        self.cbCorr.setChecked(True)
        self.cbCorr.setObjectName("cbCorr")
        self.tabWidget.addTab(self.tab_5, "")
        self.label_35 = QtWidgets.QLabel(frmMADeepRSA)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMADeepRSA)
        self.txtOutFile.setGeometry(QtCore.QRect(180, 60, 581, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnOutFile = QtWidgets.QPushButton(frmMADeepRSA)
        self.btnOutFile.setGeometry(QtCore.QRect(770, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.cbDiagram = QtWidgets.QCheckBox(frmMADeepRSA)
        self.cbDiagram.setGeometry(QtCore.QRect(30, 100, 341, 22))
        self.cbDiagram.setChecked(True)
        self.cbDiagram.setObjectName("cbDiagram")
        self.cbBeta = QtWidgets.QCheckBox(frmMADeepRSA)
        self.cbBeta.setGeometry(QtCore.QRect(200, 100, 341, 22))
        self.cbBeta.setChecked(True)
        self.cbBeta.setObjectName("cbBeta")
        self.btnRedraw = QtWidgets.QPushButton(frmMADeepRSA)
        self.btnRedraw.setGeometry(QtCore.QRect(520, 530, 141, 32))
        self.btnRedraw.setObjectName("btnRedraw")
        self.cbDevice = QtWidgets.QComboBox(frmMADeepRSA)
        self.cbDevice.setGeometry(QtCore.QRect(590, 100, 171, 26))
        self.cbDevice.setObjectName("cbDevice")
        self.label_26 = QtWidgets.QLabel(frmMADeepRSA)
        self.label_26.setGeometry(QtCore.QRect(510, 100, 81, 16))
        self.label_26.setObjectName("label_26")

        self.retranslateUi(frmMADeepRSA)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(frmMADeepRSA)
        frmMADeepRSA.setTabOrder(self.txtInFile, self.btnInFile)
        frmMADeepRSA.setTabOrder(self.btnInFile, self.tabWidget)
        frmMADeepRSA.setTabOrder(self.tabWidget, self.txtData)
        frmMADeepRSA.setTabOrder(self.txtData, self.txtLabel)
        frmMADeepRSA.setTabOrder(self.txtLabel, self.btnConvert)
        frmMADeepRSA.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMADeepRSA):
        _translate = QtCore.QCoreApplication.translate
        frmMADeepRSA.setWindowTitle(_translate("frmMADeepRSA", "Deep RAS"))
        self.btnInFile.setText(_translate("frmMADeepRSA", "..."))
        self.label_33.setText(_translate("frmMADeepRSA", "Input Data "))
        self.btnConvert.setText(_translate("frmMADeepRSA", "Analyze"))
        self.btnClose.setText(_translate("frmMADeepRSA", "Close"))
        self.label_2.setText(_translate("frmMADeepRSA", "Data"))
        self.label_3.setText(_translate("frmMADeepRSA", "Label"))
        self.label_6.setText(_translate("frmMADeepRSA", "Subject"))
        self.label_7.setText(_translate("frmMADeepRSA", "Run"))
        self.label_8.setText(_translate("frmMADeepRSA", "Counter"))
        self.label.setText(_translate("frmMADeepRSA", "ID"))
        self.label_9.setText(_translate("frmMADeepRSA", "Task"))
        self.label_11.setText(_translate("frmMADeepRSA", "Value"))
        self.btnRef.setText(_translate("frmMADeepRSA", "Referesh"))
        self.label_12.setText(_translate("frmMADeepRSA", "Design"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMADeepRSA", "Data"))
        self.groupBox.setTitle(_translate("frmMADeepRSA", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMADeepRSA", "Scale Data~N(0,1)"))
        self.label_16.setText(_translate("frmMADeepRSA", "Iteration"))
        self.txtIter.setText(_translate("frmMADeepRSA", "1000"))
        self.label_17.setText(_translate("frmMADeepRSA", "Batch Size"))
        self.txtBatch.setText(_translate("frmMADeepRSA", "50"))
        self.label_18.setText(_translate("frmMADeepRSA", "Report Step every"))
        self.txtReportStep.setText(_translate("frmMADeepRSA", "300"))
        self.txtRate.setText(_translate("frmMADeepRSA", "0.001"))
        self.label_19.setText(_translate("frmMADeepRSA", "Learning Rate"))
        self.txtLayers.setText(_translate("frmMADeepRSA", "[1000, 700, 500]"))
        self.cbVerbose.setText(_translate("frmMADeepRSA", "Show Report"))
        self.label_13.setText(_translate("frmMADeepRSA", "Layers"))
        self.label_14.setText(_translate("frmMADeepRSA", "Activation"))
        self.label_15.setText(_translate("frmMADeepRSA", "Loss Metric"))
        self.label_20.setText(_translate("frmMADeepRSA", "[Hidden Layer 1, HL2, HL3, ..., Out Layer]"))
        self.label_21.setText(_translate("frmMADeepRSA", "Alpha > 0"))
        self.txtAlpha.setText(_translate("frmMADeepRSA", "10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMADeepRSA", "Parameters"))
        self.label_4.setText(_translate("frmMADeepRSA", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMADeepRSA", "0"))
        self.label_5.setText(_translate("frmMADeepRSA", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMADeepRSA", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMADeepRSA", "Filter Class ID"))
        self.cbCov.setText(_translate("frmMADeepRSA", "Covariance"))
        self.cbCorr.setText(_translate("frmMADeepRSA", "Correlation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMADeepRSA", "Metrics"))
        self.label_35.setText(_translate("frmMADeepRSA", "Output Data"))
        self.btnOutFile.setText(_translate("frmMADeepRSA", "..."))
        self.cbDiagram.setText(_translate("frmMADeepRSA", "Show Diagrams"))
        self.cbBeta.setText(_translate("frmMADeepRSA", "Save Beta, and Network Parameters"))
        self.btnRedraw.setText(_translate("frmMADeepRSA", "Redraw"))
        self.label_26.setText(_translate("frmMADeepRSA", "Device"))

