# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMABirchGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMABirch(object):
    def setupUi(self, frmMABirch):
        frmMABirch.setObjectName("frmMABirch")
        frmMABirch.resize(782, 595)
        self.btnInFile = QtWidgets.QPushButton(frmMABirch)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMABirch)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.btnOutFile = QtWidgets.QPushButton(frmMABirch)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.txtInFile = QtWidgets.QLineEdit(frmMABirch)
        self.txtInFile.setGeometry(QtCore.QRect(180, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMABirch)
        self.btnConvert.setGeometry(QtCore.QRect(620, 550, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label_35 = QtWidgets.QLabel(frmMABirch)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 211, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMABirch)
        self.txtOutFile.setGeometry(QtCore.QRect(180, 60, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnClose = QtWidgets.QPushButton(frmMABirch)
        self.btnClose.setGeometry(QtCore.QRect(30, 550, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMABirch)
        self.tabWidget.setGeometry(QtCore.QRect(30, 150, 731, 381))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 60, 16))
        self.label_3.setObjectName("label_3")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(180, 60, 181, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(180, 20, 181, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 671, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 641, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.txtNCluster = QtWidgets.QLineEdit(self.tab_2)
        self.txtNCluster.setGeometry(QtCore.QRect(270, 110, 160, 21))
        self.txtNCluster.setObjectName("txtNCluster")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(30, 190, 231, 16))
        self.label_18.setObjectName("label_18")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(30, 110, 221, 16))
        self.label_11.setObjectName("label_11")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 150, 231, 16))
        self.label_15.setObjectName("label_15")
        self.txtBranchingFactor = QtWidgets.QLineEdit(self.tab_2)
        self.txtBranchingFactor.setGeometry(QtCore.QRect(270, 190, 160, 21))
        self.txtBranchingFactor.setObjectName("txtBranchingFactor")
        self.txtThreshold = QtWidgets.QLineEdit(self.tab_2)
        self.txtThreshold.setGeometry(QtCore.QRect(270, 150, 160, 21))
        self.txtThreshold.setObjectName("txtThreshold")
        self.cbComputeLabels = QtWidgets.QCheckBox(self.tab_2)
        self.cbComputeLabels.setGeometry(QtCore.QRect(30, 230, 401, 20))
        self.cbComputeLabels.setChecked(True)
        self.cbComputeLabels.setObjectName("cbComputeLabels")
        self.cbCopy = QtWidgets.QCheckBox(self.tab_2)
        self.cbCopy.setGeometry(QtCore.QRect(30, 270, 401, 20))
        self.cbCopy.setChecked(True)
        self.cbCopy.setObjectName("cbCopy")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 261))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbAverage = QtWidgets.QCheckBox(self.tab_5)
        self.cbAverage.setGeometry(QtCore.QRect(20, 30, 391, 20))
        self.cbAverage.setChecked(True)
        self.cbAverage.setObjectName("cbAverage")
        self.cbNMI = QtWidgets.QCheckBox(self.tab_5)
        self.cbNMI.setGeometry(QtCore.QRect(20, 70, 391, 20))
        self.cbNMI.setChecked(True)
        self.cbNMI.setObjectName("cbNMI")
        self.cbAMI = QtWidgets.QCheckBox(self.tab_5)
        self.cbAMI.setGeometry(QtCore.QRect(20, 110, 401, 20))
        self.cbAMI.setChecked(True)
        self.cbAMI.setObjectName("cbAMI")
        self.cbRIA = QtWidgets.QCheckBox(self.tab_5)
        self.cbRIA.setGeometry(QtCore.QRect(20, 150, 381, 20))
        self.cbRIA.setChecked(True)
        self.cbRIA.setObjectName("cbRIA")
        self.tabWidget.addTab(self.tab_5, "")
        self.btnOutModel = QtWidgets.QPushButton(frmMABirch)
        self.btnOutModel.setGeometry(QtCore.QRect(710, 100, 51, 32))
        self.btnOutModel.setObjectName("btnOutModel")
        self.label_36 = QtWidgets.QLabel(frmMABirch)
        self.label_36.setGeometry(QtCore.QRect(30, 100, 231, 16))
        self.label_36.setObjectName("label_36")
        self.txtOutModel = QtWidgets.QLineEdit(frmMABirch)
        self.txtOutModel.setGeometry(QtCore.QRect(180, 100, 521, 21))
        self.txtOutModel.setText("")
        self.txtOutModel.setObjectName("txtOutModel")

        self.retranslateUi(frmMABirch)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMABirch)
        frmMABirch.setTabOrder(self.txtInFile, self.btnInFile)
        frmMABirch.setTabOrder(self.btnInFile, self.txtOutFile)
        frmMABirch.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmMABirch.setTabOrder(self.btnOutFile, self.tabWidget)
        frmMABirch.setTabOrder(self.tabWidget, self.txtData)
        frmMABirch.setTabOrder(self.txtData, self.txtLabel)
        frmMABirch.setTabOrder(self.txtLabel, self.btnConvert)
        frmMABirch.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMABirch):
        _translate = QtCore.QCoreApplication.translate
        frmMABirch.setWindowTitle(_translate("frmMABirch", "Birch"))
        self.btnInFile.setText(_translate("frmMABirch", "..."))
        self.label_33.setText(_translate("frmMABirch", "Input Data "))
        self.btnOutFile.setText(_translate("frmMABirch", "..."))
        self.btnConvert.setText(_translate("frmMABirch", "Analyze"))
        self.label_35.setText(_translate("frmMABirch", "Analysis Results"))
        self.btnClose.setText(_translate("frmMABirch", "Close"))
        self.label_2.setText(_translate("frmMABirch", "Data"))
        self.label_3.setText(_translate("frmMABirch", "Label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMABirch", "Data"))
        self.groupBox.setTitle(_translate("frmMABirch", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMABirch", "Scale Data~N(0,1)"))
        self.txtNCluster.setText(_translate("frmMABirch", "3"))
        self.label_18.setText(_translate("frmMABirch", "Branching Factor"))
        self.label_11.setText(_translate("frmMABirch", "Num of Clusters"))
        self.label_15.setText(_translate("frmMABirch", "Threshold"))
        self.txtBranchingFactor.setText(_translate("frmMABirch", "50"))
        self.txtThreshold.setText(_translate("frmMABirch", "0.5"))
        self.cbComputeLabels.setText(_translate("frmMABirch", "Compute Labels"))
        self.cbCopy.setText(_translate("frmMABirch", "Copy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMABirch", "Parameters"))
        self.label_4.setText(_translate("frmMABirch", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMABirch", "0"))
        self.label_5.setText(_translate("frmMABirch", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMABirch", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMABirch", "Filter Class ID"))
        self.cbAverage.setText(_translate("frmMABirch", "Average"))
        self.cbNMI.setText(_translate("frmMABirch", "Normalized Mutual Information"))
        self.cbAMI.setText(_translate("frmMABirch", "Adjusted Mutual Information"))
        self.cbRIA.setText(_translate("frmMABirch", "Rand Index Adjusted "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMABirch", "Metrics"))
        self.btnOutModel.setText(_translate("frmMABirch", "..."))
        self.label_36.setText(_translate("frmMABirch", "Models "))

