# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMASKGRSAGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMASKGRSA(object):
    def setupUi(self, frmMASKGRSA):
        frmMASKGRSA.setObjectName("frmMASKGRSA")
        frmMASKGRSA.resize(782, 749)
        self.btnInFile = QtWidgets.QPushButton(frmMASKGRSA)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMASKGRSA)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.txtInFile = QtWidgets.QLineEdit(frmMASKGRSA)
        self.txtInFile.setGeometry(QtCore.QRect(180, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMASKGRSA)
        self.btnConvert.setGeometry(QtCore.QRect(620, 700, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.btnClose = QtWidgets.QPushButton(frmMASKGRSA)
        self.btnClose.setGeometry(QtCore.QRect(30, 700, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMASKGRSA)
        self.tabWidget.setGeometry(QtCore.QRect(30, 130, 731, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.label_3.setObjectName("label_3")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(180, 90, 181, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(180, 50, 181, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.txtSubject = QtWidgets.QComboBox(self.tab)
        self.txtSubject.setGeometry(QtCore.QRect(180, 170, 181, 26))
        self.txtSubject.setEditable(True)
        self.txtSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubject.setObjectName("txtSubject")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 111, 16))
        self.label_6.setObjectName("label_6")
        self.txtRun = QtWidgets.QComboBox(self.tab)
        self.txtRun.setGeometry(QtCore.QRect(180, 210, 181, 26))
        self.txtRun.setEditable(True)
        self.txtRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRun.setObjectName("txtRun")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 60, 16))
        self.label_7.setObjectName("label_7")
        self.txtCounter = QtWidgets.QComboBox(self.tab)
        self.txtCounter.setGeometry(QtCore.QRect(180, 250, 181, 26))
        self.txtCounter.setEditable(True)
        self.txtCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounter.setObjectName("txtCounter")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 131, 16))
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 10, 51, 17))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 290, 131, 16))
        self.label_9.setObjectName("label_9")
        self.txtTask = QtWidgets.QComboBox(self.tab)
        self.txtTask.setGeometry(QtCore.QRect(180, 290, 181, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTask.setObjectName("txtTask")
        self.txtDesign = QtWidgets.QComboBox(self.tab)
        self.txtDesign.setGeometry(QtCore.QRect(180, 130, 181, 26))
        self.txtDesign.setEditable(True)
        self.txtDesign.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtDesign.setObjectName("txtDesign")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 141, 16))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 30, 451, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cbFSubject = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbFSubject.setGeometry(QtCore.QRect(10, 30, 130, 20))
        self.cbFSubject.setChecked(True)
        self.cbFSubject.setObjectName("cbFSubject")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(10, 60, 201, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.rbFRun = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbFRun.setGeometry(QtCore.QRect(220, 60, 221, 20))
        self.rbFRun.setObjectName("rbFRun")
        self.cbFTask = QtWidgets.QCheckBox(self.tab_3)
        self.cbFTask.setGeometry(QtCore.QRect(510, 60, 161, 20))
        self.cbFTask.setObjectName("cbFTask")
        self.cbFCounter = QtWidgets.QCheckBox(self.tab_3)
        self.cbFCounter.setGeometry(QtCore.QRect(510, 100, 161, 20))
        self.cbFCounter.setObjectName("cbFCounter")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(40, 160, 121, 16))
        self.label_11.setObjectName("label_11")
        self.txtUnit = QtWidgets.QSpinBox(self.tab_3)
        self.txtUnit.setGeometry(QtCore.QRect(160, 160, 181, 24))
        self.txtUnit.setMinimum(1)
        self.txtUnit.setMaximum(1000000000)
        self.txtUnit.setObjectName("txtUnit")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 671, 71))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 32, 161, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.rbScale = QtWidgets.QRadioButton(self.groupBox)
        self.rbScale.setGeometry(QtCore.QRect(190, 32, 161, 20))
        self.rbScale.setChecked(True)
        self.rbScale.setObjectName("rbScale")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(350, 32, 131, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 90, 671, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rbAvg = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbAvg.setGeometry(QtCore.QRect(20, 33, 116, 22))
        self.rbAvg.setChecked(True)
        self.rbAvg.setObjectName("rbAvg")
        self.rbMax = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbMax.setGeometry(QtCore.QRect(170, 33, 116, 22))
        self.rbMax.setObjectName("rbMax")
        self.rbMin = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbMin.setGeometry(QtCore.QRect(330, 33, 116, 22))
        self.rbMin.setObjectName("rbMin")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(30, 250, 411, 16))
        self.label_16.setObjectName("label_16")
        self.cbSolver = QtWidgets.QComboBox(self.tab_2)
        self.cbSolver.setGeometry(QtCore.QRect(460, 450, 160, 26))
        self.cbSolver.setObjectName("cbSolver")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(30, 170, 421, 16))
        self.label_18.setObjectName("label_18")
        self.cbFit = QtWidgets.QCheckBox(self.tab_2)
        self.cbFit.setGeometry(QtCore.QRect(30, 490, 191, 20))
        self.cbFit.setChecked(True)
        self.cbFit.setObjectName("cbFit")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(30, 290, 401, 16))
        self.label_14.setObjectName("label_14")
        self.txtAlpha = QtWidgets.QLineEdit(self.tab_2)
        self.txtAlpha.setGeometry(QtCore.QRect(460, 250, 160, 21))
        self.txtAlpha.setObjectName("txtAlpha")
        self.txtMaxIter = QtWidgets.QLineEdit(self.tab_2)
        self.txtMaxIter.setGeometry(QtCore.QRect(460, 290, 160, 21))
        self.txtMaxIter.setObjectName("txtMaxIter")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 210, 411, 16))
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(30, 370, 391, 16))
        self.label_13.setObjectName("label_13")
        self.txtJobs = QtWidgets.QLineEdit(self.tab_2)
        self.txtJobs.setGeometry(QtCore.QRect(460, 210, 160, 21))
        self.txtJobs.setObjectName("txtJobs")
        self.cbSelection = QtWidgets.QComboBox(self.tab_2)
        self.cbSelection.setGeometry(QtCore.QRect(460, 410, 160, 26))
        self.cbSelection.setObjectName("cbSelection")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(30, 410, 391, 16))
        self.label_19.setObjectName("label_19")
        self.txtL1 = QtWidgets.QLineEdit(self.tab_2)
        self.txtL1.setGeometry(QtCore.QRect(460, 370, 160, 21))
        self.txtL1.setObjectName("txtL1")
        self.txtTole = QtWidgets.QLineEdit(self.tab_2)
        self.txtTole.setGeometry(QtCore.QRect(460, 330, 160, 21))
        self.txtTole.setObjectName("txtTole")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(30, 330, 401, 16))
        self.label_17.setObjectName("label_17")
        self.cbMethod = QtWidgets.QComboBox(self.tab_2)
        self.cbMethod.setGeometry(QtCore.QRect(460, 170, 160, 26))
        self.cbMethod.setObjectName("cbMethod")
        self.cbNormalize = QtWidgets.QCheckBox(self.tab_2)
        self.cbNormalize.setGeometry(QtCore.QRect(220, 490, 251, 20))
        self.cbNormalize.setChecked(True)
        self.cbNormalize.setObjectName("cbNormalize")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(30, 450, 391, 16))
        self.label_20.setObjectName("label_20")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 221))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbCov = QtWidgets.QCheckBox(self.tab_5)
        self.cbCov.setGeometry(QtCore.QRect(20, 30, 391, 20))
        self.cbCov.setChecked(True)
        self.cbCov.setObjectName("cbCov")
        self.cbCorr = QtWidgets.QCheckBox(self.tab_5)
        self.cbCorr.setGeometry(QtCore.QRect(20, 70, 391, 20))
        self.cbCorr.setChecked(True)
        self.cbCorr.setObjectName("cbCorr")
        self.tabWidget.addTab(self.tab_5, "")
        self.label_35 = QtWidgets.QLabel(frmMASKGRSA)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMASKGRSA)
        self.txtOutFile.setGeometry(QtCore.QRect(180, 60, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnOutFile = QtWidgets.QPushButton(frmMASKGRSA)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.cbDiagram = QtWidgets.QCheckBox(frmMASKGRSA)
        self.cbDiagram.setGeometry(QtCore.QRect(30, 94, 341, 22))
        self.cbDiagram.setChecked(True)
        self.cbDiagram.setObjectName("cbDiagram")
        self.cbBeta = QtWidgets.QCheckBox(frmMASKGRSA)
        self.cbBeta.setGeometry(QtCore.QRect(250, 94, 341, 22))
        self.cbBeta.setChecked(True)
        self.cbBeta.setObjectName("cbBeta")
        self.btnRedraw = QtWidgets.QPushButton(frmMASKGRSA)
        self.btnRedraw.setGeometry(QtCore.QRect(460, 700, 141, 32))
        self.btnRedraw.setObjectName("btnRedraw")

        self.retranslateUi(frmMASKGRSA)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(frmMASKGRSA)
        frmMASKGRSA.setTabOrder(self.txtInFile, self.btnInFile)
        frmMASKGRSA.setTabOrder(self.btnInFile, self.tabWidget)
        frmMASKGRSA.setTabOrder(self.tabWidget, self.txtData)
        frmMASKGRSA.setTabOrder(self.txtData, self.txtLabel)
        frmMASKGRSA.setTabOrder(self.txtLabel, self.btnConvert)
        frmMASKGRSA.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMASKGRSA):
        _translate = QtCore.QCoreApplication.translate
        frmMASKGRSA.setWindowTitle(_translate("frmMASKGRSA", "RAS"))
        self.btnInFile.setText(_translate("frmMASKGRSA", "..."))
        self.label_33.setText(_translate("frmMASKGRSA", "Input Data "))
        self.btnConvert.setText(_translate("frmMASKGRSA", "Analyze"))
        self.btnClose.setText(_translate("frmMASKGRSA", "Close"))
        self.label_2.setText(_translate("frmMASKGRSA", "Data"))
        self.label_3.setText(_translate("frmMASKGRSA", "Label"))
        self.label_6.setText(_translate("frmMASKGRSA", "Subject"))
        self.label_7.setText(_translate("frmMASKGRSA", "Run"))
        self.label_8.setText(_translate("frmMASKGRSA", "Counter"))
        self.label.setText(_translate("frmMASKGRSA", "ID"))
        self.label_9.setText(_translate("frmMASKGRSA", "Task"))
        self.label_12.setText(_translate("frmMASKGRSA", "Design"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMASKGRSA", "Data"))
        self.groupBox_3.setTitle(_translate("frmMASKGRSA", "<Subject Level>"))
        self.cbFSubject.setText(_translate("frmMASKGRSA", "Subject"))
        self.radioButton.setText(_translate("frmMASKGRSA", "Without Run"))
        self.rbFRun.setText(_translate("frmMASKGRSA", "With Run"))
        self.cbFTask.setText(_translate("frmMASKGRSA", "Task"))
        self.cbFCounter.setText(_translate("frmMASKGRSA", "Counter"))
        self.label_11.setText(_translate("frmMASKGRSA", "Unit number"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmMASKGRSA", "Level"))
        self.groupBox.setTitle(_translate("frmMASKGRSA", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMASKGRSA", "Scale Data~N(0,1)"))
        self.rbScale.setText(_translate("frmMASKGRSA", "Session Level"))
        self.radioButton_2.setText(_translate("frmMASKGRSA", "Whole Data"))
        self.groupBox_2.setTitle(_translate("frmMASKGRSA", "<Integration Metric>"))
        self.rbAvg.setText(_translate("frmMASKGRSA", "Average"))
        self.rbMax.setText(_translate("frmMASKGRSA", "Max"))
        self.rbMin.setText(_translate("frmMASKGRSA", "Min"))
        self.label_16.setText(_translate("frmMASKGRSA", "Alpha (Ridge, LASSO, ElasticNet)"))
        self.label_18.setText(_translate("frmMASKGRSA", "Method"))
        self.cbFit.setText(_translate("frmMASKGRSA", "Fit Intercept"))
        self.label_14.setText(_translate("frmMASKGRSA", "Max Iteration (Ridge, LASSO, ElasticNet)"))
        self.txtAlpha.setText(_translate("frmMASKGRSA", "1.0"))
        self.txtMaxIter.setText(_translate("frmMASKGRSA", "1000"))
        self.label_15.setText(_translate("frmMASKGRSA", "Number of parallel jobs (OLS)"))
        self.label_13.setText(_translate("frmMASKGRSA", "L1 (ElasticNet)"))
        self.txtJobs.setText(_translate("frmMASKGRSA", "1"))
        self.label_19.setText(_translate("frmMASKGRSA", "Selection (LASSO, ElasticNet)"))
        self.txtL1.setText(_translate("frmMASKGRSA", "0.5"))
        self.txtTole.setText(_translate("frmMASKGRSA", "0.0001"))
        self.label_17.setText(_translate("frmMASKGRSA", "Tolerance (Ridge=0.001, LASSO or ElasticNet=0.0001)"))
        self.cbNormalize.setText(_translate("frmMASKGRSA", "Normalize"))
        self.label_20.setText(_translate("frmMASKGRSA", "Solver (Ridge)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMASKGRSA", "Parameters"))
        self.label_4.setText(_translate("frmMASKGRSA", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMASKGRSA", "0"))
        self.label_5.setText(_translate("frmMASKGRSA", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMASKGRSA", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMASKGRSA", "Filter Class ID"))
        self.cbCov.setText(_translate("frmMASKGRSA", "Covariance"))
        self.cbCorr.setText(_translate("frmMASKGRSA", "Correlation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMASKGRSA", "Metrics"))
        self.label_35.setText(_translate("frmMASKGRSA", "Output Data"))
        self.btnOutFile.setText(_translate("frmMASKGRSA", "..."))
        self.cbDiagram.setText(_translate("frmMASKGRSA", "Show Diagrams"))
        self.cbBeta.setText(_translate("frmMASKGRSA", "Save Beta Values"))
        self.btnRedraw.setText(_translate("frmMASKGRSA", "Redraw"))

