# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMASpectralGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMASpectral(object):
    def setupUi(self, frmMASpectral):
        frmMASpectral.setObjectName("frmMASpectral")
        frmMASpectral.resize(782, 595)
        self.btnInFile = QtWidgets.QPushButton(frmMASpectral)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMASpectral)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.btnOutFile = QtWidgets.QPushButton(frmMASpectral)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.txtInFile = QtWidgets.QLineEdit(frmMASpectral)
        self.txtInFile.setGeometry(QtCore.QRect(180, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMASpectral)
        self.btnConvert.setGeometry(QtCore.QRect(620, 550, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label_35 = QtWidgets.QLabel(frmMASpectral)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 211, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMASpectral)
        self.txtOutFile.setGeometry(QtCore.QRect(180, 60, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnClose = QtWidgets.QPushButton(frmMASpectral)
        self.btnClose.setGeometry(QtCore.QRect(30, 550, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMASpectral)
        self.tabWidget.setGeometry(QtCore.QRect(30, 150, 731, 381))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 60, 16))
        self.label_3.setObjectName("label_3")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(180, 60, 181, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(180, 20, 181, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 671, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 641, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.txtNCluster = QtWidgets.QLineEdit(self.tab_2)
        self.txtNCluster.setGeometry(QtCore.QRect(540, 150, 160, 21))
        self.txtNCluster.setObjectName("txtNCluster")
        self.txtDegree = QtWidgets.QLineEdit(self.tab_2)
        self.txtDegree.setGeometry(QtCore.QRect(540, 230, 160, 21))
        self.txtDegree.setObjectName("txtDegree")
        self.txtTole = QtWidgets.QLineEdit(self.tab_2)
        self.txtTole.setGeometry(QtCore.QRect(190, 230, 160, 21))
        self.txtTole.setObjectName("txtTole")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(30, 230, 221, 16))
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(380, 190, 231, 16))
        self.label_18.setObjectName("label_18")
        self.cbAffinity = QtWidgets.QComboBox(self.tab_2)
        self.cbAffinity.setGeometry(QtCore.QRect(190, 150, 161, 26))
        self.cbAffinity.setObjectName("cbAffinity")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(380, 150, 221, 16))
        self.label_11.setObjectName("label_11")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(30, 190, 231, 16))
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(30, 150, 231, 16))
        self.label_13.setObjectName("label_13")
        self.txtGamma = QtWidgets.QLineEdit(self.tab_2)
        self.txtGamma.setGeometry(QtCore.QRect(540, 190, 160, 21))
        self.txtGamma.setObjectName("txtGamma")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(380, 230, 251, 16))
        self.label_16.setObjectName("label_16")
        self.txtNInit = QtWidgets.QLineEdit(self.tab_2)
        self.txtNInit.setGeometry(QtCore.QRect(190, 190, 160, 21))
        self.txtNInit.setObjectName("txtNInit")
        self.cbESolver = QtWidgets.QComboBox(self.tab_2)
        self.cbESolver.setGeometry(QtCore.QRect(190, 110, 161, 26))
        self.cbESolver.setObjectName("cbESolver")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(30, 110, 231, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(380, 110, 231, 16))
        self.label_20.setObjectName("label_20")
        self.cbAssignLabels = QtWidgets.QComboBox(self.tab_2)
        self.cbAssignLabels.setGeometry(QtCore.QRect(540, 110, 161, 26))
        self.cbAssignLabels.setObjectName("cbAssignLabels")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(30, 270, 251, 16))
        self.label_21.setObjectName("label_21")
        self.txtNJobs = QtWidgets.QLineEdit(self.tab_2)
        self.txtNJobs.setGeometry(QtCore.QRect(190, 270, 160, 21))
        self.txtNJobs.setObjectName("txtNJobs")
        self.txtNNeighbors = QtWidgets.QLineEdit(self.tab_2)
        self.txtNNeighbors.setGeometry(QtCore.QRect(540, 270, 160, 21))
        self.txtNNeighbors.setObjectName("txtNNeighbors")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(380, 270, 251, 16))
        self.label_22.setObjectName("label_22")
        self.txtCoef0 = QtWidgets.QLineEdit(self.tab_2)
        self.txtCoef0.setGeometry(QtCore.QRect(190, 310, 160, 21))
        self.txtCoef0.setObjectName("txtCoef0")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(30, 310, 251, 16))
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 261))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbAverage = QtWidgets.QCheckBox(self.tab_5)
        self.cbAverage.setGeometry(QtCore.QRect(20, 30, 391, 20))
        self.cbAverage.setChecked(True)
        self.cbAverage.setObjectName("cbAverage")
        self.cbNMI = QtWidgets.QCheckBox(self.tab_5)
        self.cbNMI.setGeometry(QtCore.QRect(20, 70, 391, 20))
        self.cbNMI.setChecked(True)
        self.cbNMI.setObjectName("cbNMI")
        self.cbAMI = QtWidgets.QCheckBox(self.tab_5)
        self.cbAMI.setGeometry(QtCore.QRect(20, 110, 401, 20))
        self.cbAMI.setChecked(True)
        self.cbAMI.setObjectName("cbAMI")
        self.cbRIA = QtWidgets.QCheckBox(self.tab_5)
        self.cbRIA.setGeometry(QtCore.QRect(20, 150, 381, 20))
        self.cbRIA.setChecked(True)
        self.cbRIA.setObjectName("cbRIA")
        self.tabWidget.addTab(self.tab_5, "")
        self.btnOutModel = QtWidgets.QPushButton(frmMASpectral)
        self.btnOutModel.setGeometry(QtCore.QRect(710, 100, 51, 32))
        self.btnOutModel.setObjectName("btnOutModel")
        self.label_36 = QtWidgets.QLabel(frmMASpectral)
        self.label_36.setGeometry(QtCore.QRect(30, 100, 231, 16))
        self.label_36.setObjectName("label_36")
        self.txtOutModel = QtWidgets.QLineEdit(frmMASpectral)
        self.txtOutModel.setGeometry(QtCore.QRect(180, 100, 521, 21))
        self.txtOutModel.setText("")
        self.txtOutModel.setObjectName("txtOutModel")

        self.retranslateUi(frmMASpectral)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMASpectral)
        frmMASpectral.setTabOrder(self.txtInFile, self.btnInFile)
        frmMASpectral.setTabOrder(self.btnInFile, self.txtOutFile)
        frmMASpectral.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmMASpectral.setTabOrder(self.btnOutFile, self.tabWidget)
        frmMASpectral.setTabOrder(self.tabWidget, self.txtData)
        frmMASpectral.setTabOrder(self.txtData, self.txtLabel)
        frmMASpectral.setTabOrder(self.txtLabel, self.btnConvert)
        frmMASpectral.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMASpectral):
        _translate = QtCore.QCoreApplication.translate
        frmMASpectral.setWindowTitle(_translate("frmMASpectral", "Spectral"))
        self.btnInFile.setText(_translate("frmMASpectral", "..."))
        self.label_33.setText(_translate("frmMASpectral", "Input Data "))
        self.btnOutFile.setText(_translate("frmMASpectral", "..."))
        self.btnConvert.setText(_translate("frmMASpectral", "Analyze"))
        self.label_35.setText(_translate("frmMASpectral", "Analysis Results"))
        self.btnClose.setText(_translate("frmMASpectral", "Close"))
        self.label_2.setText(_translate("frmMASpectral", "Data"))
        self.label_3.setText(_translate("frmMASpectral", "Label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMASpectral", "Data"))
        self.groupBox.setTitle(_translate("frmMASpectral", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMASpectral", "Scale Data~N(0,1)"))
        self.txtNCluster.setText(_translate("frmMASpectral", "8"))
        self.txtDegree.setText(_translate("frmMASpectral", "3"))
        self.txtTole.setText(_translate("frmMASpectral", "0"))
        self.label_14.setText(_translate("frmMASpectral", "Eigen Tolerance"))
        self.label_18.setText(_translate("frmMASpectral", "Gamma"))
        self.label_11.setText(_translate("frmMASpectral", "Num of Clusters"))
        self.label_15.setText(_translate("frmMASpectral", "Num of Init"))
        self.label_13.setText(_translate("frmMASpectral", "Affinity"))
        self.txtGamma.setText(_translate("frmMASpectral", "1"))
        self.label_16.setText(_translate("frmMASpectral", "Degree"))
        self.txtNInit.setText(_translate("frmMASpectral", "10"))
        self.label_19.setText(_translate("frmMASpectral", "Eigen Solver"))
        self.label_20.setText(_translate("frmMASpectral", "Assign Labels"))
        self.label_21.setText(_translate("frmMASpectral", "Num of Jobs"))
        self.txtNJobs.setText(_translate("frmMASpectral", "1"))
        self.txtNNeighbors.setText(_translate("frmMASpectral", "10"))
        self.label_22.setText(_translate("frmMASpectral", "Num of Neighbors "))
        self.txtCoef0.setText(_translate("frmMASpectral", "1"))
        self.label_23.setText(_translate("frmMASpectral", "Coef0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMASpectral", "Parameters"))
        self.label_4.setText(_translate("frmMASpectral", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMASpectral", "0"))
        self.label_5.setText(_translate("frmMASpectral", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMASpectral", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMASpectral", "Filter Class ID"))
        self.cbAverage.setText(_translate("frmMASpectral", "Average"))
        self.cbNMI.setText(_translate("frmMASpectral", "Normalized Mutual Information"))
        self.cbAMI.setText(_translate("frmMASpectral", "Adjusted Mutual Information"))
        self.cbRIA.setText(_translate("frmMASpectral", "Rand Index Adjusted "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMASpectral", "Metrics"))
        self.btnOutModel.setText(_translate("frmMASpectral", "..."))
        self.label_36.setText(_translate("frmMASpectral", "Models "))

