# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMARSAGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMARSA(object):
    def setupUi(self, frmMARSA):
        frmMARSA.setObjectName("frmMARSA")
        frmMARSA.resize(782, 636)
        self.btnInFile = QtWidgets.QPushButton(frmMARSA)
        self.btnInFile.setGeometry(QtCore.QRect(710, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMARSA)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.txtInFile = QtWidgets.QLineEdit(frmMARSA)
        self.txtInFile.setGeometry(QtCore.QRect(180, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMARSA)
        self.btnConvert.setGeometry(QtCore.QRect(620, 580, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.btnClose = QtWidgets.QPushButton(frmMARSA)
        self.btnClose.setGeometry(QtCore.QRect(30, 580, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMARSA)
        self.tabWidget.setGeometry(QtCore.QRect(30, 150, 731, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.label_3.setObjectName("label_3")
        self.txtLabel = QtWidgets.QComboBox(self.tab)
        self.txtLabel.setGeometry(QtCore.QRect(180, 90, 181, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtData = QtWidgets.QComboBox(self.tab)
        self.txtData.setGeometry(QtCore.QRect(180, 50, 181, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.txtSubject = QtWidgets.QComboBox(self.tab)
        self.txtSubject.setGeometry(QtCore.QRect(180, 170, 181, 26))
        self.txtSubject.setEditable(True)
        self.txtSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubject.setObjectName("txtSubject")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 111, 16))
        self.label_6.setObjectName("label_6")
        self.txtRun = QtWidgets.QComboBox(self.tab)
        self.txtRun.setGeometry(QtCore.QRect(180, 210, 181, 26))
        self.txtRun.setEditable(True)
        self.txtRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRun.setObjectName("txtRun")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 60, 16))
        self.label_7.setObjectName("label_7")
        self.txtCounter = QtWidgets.QComboBox(self.tab)
        self.txtCounter.setGeometry(QtCore.QRect(180, 250, 181, 26))
        self.txtCounter.setEditable(True)
        self.txtCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounter.setObjectName("txtCounter")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 131, 16))
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 10, 51, 17))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 290, 131, 16))
        self.label_9.setObjectName("label_9")
        self.txtTask = QtWidgets.QComboBox(self.tab)
        self.txtTask.setGeometry(QtCore.QRect(180, 290, 181, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTask.setObjectName("txtTask")
        self.txtRunVal = QtWidgets.QComboBox(self.tab)
        self.txtRunVal.setGeometry(QtCore.QRect(400, 210, 181, 26))
        self.txtRunVal.setEditable(True)
        self.txtRunVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRunVal.setObjectName("txtRunVal")
        self.txtTaskVal = QtWidgets.QComboBox(self.tab)
        self.txtTaskVal.setGeometry(QtCore.QRect(400, 290, 181, 26))
        self.txtTaskVal.setEditable(True)
        self.txtTaskVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTaskVal.setObjectName("txtTaskVal")
        self.txtSubjectVal = QtWidgets.QComboBox(self.tab)
        self.txtSubjectVal.setGeometry(QtCore.QRect(400, 170, 181, 26))
        self.txtSubjectVal.setEditable(True)
        self.txtSubjectVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubjectVal.setObjectName("txtSubjectVal")
        self.txtCounterVal = QtWidgets.QComboBox(self.tab)
        self.txtCounterVal.setGeometry(QtCore.QRect(400, 250, 181, 26))
        self.txtCounterVal.setEditable(True)
        self.txtCounterVal.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounterVal.setObjectName("txtCounterVal")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(470, 10, 111, 17))
        self.label_11.setObjectName("label_11")
        self.btnRef = QtWidgets.QPushButton(self.tab)
        self.btnRef.setGeometry(QtCore.QRect(530, 330, 181, 29))
        self.btnRef.setObjectName("btnRef")
        self.txtDesign = QtWidgets.QComboBox(self.tab)
        self.txtDesign.setGeometry(QtCore.QRect(180, 130, 181, 26))
        self.txtDesign.setEditable(True)
        self.txtDesign.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtDesign.setObjectName("txtDesign")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 141, 16))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 671, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 641, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 221))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbCov = QtWidgets.QCheckBox(self.tab_5)
        self.cbCov.setGeometry(QtCore.QRect(20, 30, 391, 20))
        self.cbCov.setChecked(True)
        self.cbCov.setObjectName("cbCov")
        self.cbCorr = QtWidgets.QCheckBox(self.tab_5)
        self.cbCorr.setGeometry(QtCore.QRect(20, 70, 391, 20))
        self.cbCorr.setChecked(True)
        self.cbCorr.setObjectName("cbCorr")
        self.tabWidget.addTab(self.tab_5, "")
        self.label_35 = QtWidgets.QLabel(frmMARSA)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 111, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMARSA)
        self.txtOutFile.setGeometry(QtCore.QRect(180, 60, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnOutFile = QtWidgets.QPushButton(frmMARSA)
        self.btnOutFile.setGeometry(QtCore.QRect(710, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.cbDiagram = QtWidgets.QCheckBox(frmMARSA)
        self.cbDiagram.setGeometry(QtCore.QRect(30, 100, 341, 22))
        self.cbDiagram.setChecked(True)
        self.cbDiagram.setObjectName("cbDiagram")
        self.cbBeta = QtWidgets.QCheckBox(frmMARSA)
        self.cbBeta.setGeometry(QtCore.QRect(250, 100, 341, 22))
        self.cbBeta.setChecked(True)
        self.cbBeta.setObjectName("cbBeta")
        self.btnRedraw = QtWidgets.QPushButton(frmMARSA)
        self.btnRedraw.setGeometry(QtCore.QRect(460, 580, 141, 32))
        self.btnRedraw.setObjectName("btnRedraw")

        self.retranslateUi(frmMARSA)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMARSA)
        frmMARSA.setTabOrder(self.txtInFile, self.btnInFile)
        frmMARSA.setTabOrder(self.btnInFile, self.tabWidget)
        frmMARSA.setTabOrder(self.tabWidget, self.txtData)
        frmMARSA.setTabOrder(self.txtData, self.txtLabel)
        frmMARSA.setTabOrder(self.txtLabel, self.btnConvert)
        frmMARSA.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMARSA):
        _translate = QtCore.QCoreApplication.translate
        frmMARSA.setWindowTitle(_translate("frmMARSA", "RAS"))
        self.btnInFile.setText(_translate("frmMARSA", "..."))
        self.label_33.setText(_translate("frmMARSA", "Input Data "))
        self.btnConvert.setText(_translate("frmMARSA", "Analyze"))
        self.btnClose.setText(_translate("frmMARSA", "Close"))
        self.label_2.setText(_translate("frmMARSA", "Data"))
        self.label_3.setText(_translate("frmMARSA", "Label"))
        self.label_6.setText(_translate("frmMARSA", "Subject"))
        self.label_7.setText(_translate("frmMARSA", "Run"))
        self.label_8.setText(_translate("frmMARSA", "Counter"))
        self.label.setText(_translate("frmMARSA", "ID"))
        self.label_9.setText(_translate("frmMARSA", "Task"))
        self.label_11.setText(_translate("frmMARSA", "Value"))
        self.btnRef.setText(_translate("frmMARSA", "Referesh"))
        self.label_12.setText(_translate("frmMARSA", "Design"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMARSA", "Data"))
        self.groupBox.setTitle(_translate("frmMARSA", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMARSA", "Scale Data~N(0,1)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMARSA", "Parameters"))
        self.label_4.setText(_translate("frmMARSA", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMARSA", "0"))
        self.label_5.setText(_translate("frmMARSA", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMARSA", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMARSA", "Filter Class ID"))
        self.cbCov.setText(_translate("frmMARSA", "Covariance"))
        self.cbCorr.setText(_translate("frmMARSA", "Correlation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMARSA", "Metrics"))
        self.label_35.setText(_translate("frmMARSA", "Output Data"))
        self.btnOutFile.setText(_translate("frmMARSA", "..."))
        self.cbDiagram.setText(_translate("frmMARSA", "Show Diagrams"))
        self.cbBeta.setText(_translate("frmMARSA", "Save Beta Values"))
        self.btnRedraw.setText(_translate("frmMARSA", "Redraw"))

