# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMainMenuGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMainMenuGUI(object):
    def setupUi(self, frmMainMenuGUI):
        frmMainMenuGUI.setObjectName("frmMainMenuGUI")
        frmMainMenuGUI.resize(723, 494)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/icons8-brain-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMainMenuGUI.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(frmMainMenuGUI)
        self.label.setGeometry(QtCore.QRect(100, 14, 611, 80))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(frmMainMenuGUI)
        self.tabWidget.setGeometry(QtCore.QRect(10, 120, 701, 201))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btnPreprocess = QtWidgets.QToolButton(self.tab)
        self.btnPreprocess.setGeometry(QtCore.QRect(10, 10, 160, 150))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/402612-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPreprocess.setIcon(icon1)
        self.btnPreprocess.setIconSize(QtCore.QSize(100, 100))
        self.btnPreprocess.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPreprocess.setObjectName("btnPreprocess")
        self.btnFeatureAnalysis = QtWidgets.QToolButton(self.tab)
        self.btnFeatureAnalysis.setGeometry(QtCore.QRect(350, 10, 160, 150))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/icons8-scatter-plot-filled-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFeatureAnalysis.setIcon(icon2)
        self.btnFeatureAnalysis.setIconSize(QtCore.QSize(100, 100))
        self.btnFeatureAnalysis.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnFeatureAnalysis.setObjectName("btnFeatureAnalysis")
        self.btnModelAnalysis = QtWidgets.QToolButton(self.tab)
        self.btnModelAnalysis.setGeometry(QtCore.QRect(180, 10, 160, 150))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/noun_mind_1705433.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModelAnalysis.setIcon(icon3)
        self.btnModelAnalysis.setIconSize(QtCore.QSize(100, 100))
        self.btnModelAnalysis.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnModelAnalysis.setObjectName("btnModelAnalysis")
        self.btnVisualization = QtWidgets.QToolButton(self.tab)
        self.btnVisualization.setGeometry(QtCore.QRect(520, 10, 160, 150))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/noun_Brain_7784.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVisualization.setIcon(icon4)
        self.btnVisualization.setIconSize(QtCore.QSize(100, 100))
        self.btnVisualization.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnVisualization.setObjectName("btnVisualization")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cbTools = QtWidgets.QComboBox(self.tab_2)
        self.cbTools.setGeometry(QtCore.QRect(10, 40, 491, 121))
        self.cbTools.setObjectName("cbTools")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 471, 20))
        self.label_2.setObjectName("label_2")
        self.btnTools = QtWidgets.QToolButton(self.tab_2)
        self.btnTools.setGeometry(QtCore.QRect(520, 10, 160, 150))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons/icons8-play-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTools.setIcon(icon5)
        self.btnTools.setIconSize(QtCore.QSize(100, 100))
        self.btnTools.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnTools.setObjectName("btnTools")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 471, 20))
        self.label_3.setObjectName("label_3")
        self.txtEZDIR = QtWidgets.QLineEdit(self.tab_3)
        self.txtEZDIR.setGeometry(QtCore.QRect(10, 47, 321, 111))
        self.txtEZDIR.setReadOnly(True)
        self.txtEZDIR.setObjectName("txtEZDIR")
        self.btnStable = QtWidgets.QToolButton(self.tab_3)
        self.btnStable.setGeometry(QtCore.QRect(350, 10, 160, 150))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons/icons8-administrative-tools-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStable.setIcon(icon6)
        self.btnStable.setIconSize(QtCore.QSize(100, 100))
        self.btnStable.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnStable.setObjectName("btnStable")
        self.btnDev = QtWidgets.QToolButton(self.tab_3)
        self.btnDev.setGeometry(QtCore.QRect(520, 10, 160, 150))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icons/icons8-settings-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDev.setIcon(icon7)
        self.btnDev.setIconSize(QtCore.QSize(100, 100))
        self.btnDev.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnDev.setObjectName("btnDev")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.cbSource = QtWidgets.QComboBox(self.tab_4)
        self.cbSource.setGeometry(QtCore.QRect(10, 40, 491, 121))
        self.cbSource.setObjectName("cbSource")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 471, 20))
        self.label_4.setObjectName("label_4")
        self.btnUpdate = QtWidgets.QToolButton(self.tab_4)
        self.btnUpdate.setGeometry(QtCore.QRect(520, 10, 160, 150))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Icons/icons8-installing-updates-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpdate.setIcon(icon8)
        self.btnUpdate.setIconSize(QtCore.QSize(100, 100))
        self.btnUpdate.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btnUpdate.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnUpdate.setObjectName("btnUpdate")
        self.tabWidget.addTab(self.tab_4, "")
        self.label_5 = QtWidgets.QLabel(frmMainMenuGUI)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 91, 91))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/Icons/icons8-brain-128.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.btnExit = QtWidgets.QToolButton(frmMainMenuGUI)
        self.btnExit.setGeometry(QtCore.QRect(550, 330, 160, 150))
        self.btnExit.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Icons/icons8-shutdown-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon9)
        self.btnExit.setIconSize(QtCore.QSize(100, 100))
        self.btnExit.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btnExit.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnExit.setObjectName("btnExit")
        self.btnAbout = QtWidgets.QToolButton(frmMainMenuGUI)
        self.btnAbout.setGeometry(QtCore.QRect(10, 330, 160, 150))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Icons/icons8-whatsapp-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAbout.setIcon(icon10)
        self.btnAbout.setIconSize(QtCore.QSize(100, 100))
        self.btnAbout.setObjectName("btnAbout")

        self.retranslateUi(frmMainMenuGUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMainMenuGUI)

    def retranslateUi(self, frmMainMenuGUI):
        _translate = QtCore.QCoreApplication.translate
        frmMainMenuGUI.setWindowTitle(_translate("frmMainMenuGUI", "easy fMRI (2.0)"))
        self.label.setText(_translate("frmMainMenuGUI", "easy fMRI"))
        self.btnPreprocess.setText(_translate("frmMainMenuGUI", "Preprocessing (FSL)"))
        self.btnFeatureAnalysis.setText(_translate("frmMainMenuGUI", "Feature Analysis"))
        self.btnModelAnalysis.setText(_translate("frmMainMenuGUI", "Model Analysis"))
        self.btnVisualization.setText(_translate("frmMainMenuGUI", "Visualization (AFNI)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMainMenuGUI", "Main"))
        self.label_2.setText(_translate("frmMainMenuGUI", "Select a tool:"))
        self.btnTools.setText(_translate("frmMainMenuGUI", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMainMenuGUI", "Tools"))
        self.label_3.setText(_translate("frmMainMenuGUI", "Easy fMRI DIR (set from $EASYFMRI):"))
        self.btnStable.setText(_translate("frmMainMenuGUI", "Stable"))
        self.btnDev.setText(_translate("frmMainMenuGUI", "Developing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmMainMenuGUI", "Mode"))
        self.label_4.setText(_translate("frmMainMenuGUI", "Source:"))
        self.btnUpdate.setText(_translate("frmMainMenuGUI", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMainMenuGUI", "Update"))
        self.btnAbout.setText(_translate("frmMainMenuGUI", "Contact Us"))

import icon_rc
