# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMARFCGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMARFC(object):
    def setupUi(self, frmMARFC):
        frmMARFC.setObjectName("frmMARFC")
        frmMARFC.resize(860, 670)
        self.btnInFile = QtWidgets.QPushButton(frmMARFC)
        self.btnInFile.setGeometry(QtCore.QRect(790, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmMARFC)
        self.label_33.setGeometry(QtCore.QRect(30, 20, 161, 16))
        self.label_33.setObjectName("label_33")
        self.btnOutFile = QtWidgets.QPushButton(frmMARFC)
        self.btnOutFile.setGeometry(QtCore.QRect(790, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.txtInFile = QtWidgets.QLineEdit(frmMARFC)
        self.txtInFile.setGeometry(QtCore.QRect(200, 20, 581, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnConvert = QtWidgets.QPushButton(frmMARFC)
        self.btnConvert.setGeometry(QtCore.QRect(690, 625, 141, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label_35 = QtWidgets.QLabel(frmMARFC)
        self.label_35.setGeometry(QtCore.QRect(30, 60, 161, 16))
        self.label_35.setObjectName("label_35")
        self.txtOutFile = QtWidgets.QLineEdit(frmMARFC)
        self.txtOutFile.setGeometry(QtCore.QRect(200, 60, 581, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnClose = QtWidgets.QPushButton(frmMARFC)
        self.btnClose.setGeometry(QtCore.QRect(30, 625, 141, 32))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmMARFC)
        self.tabWidget.setGeometry(QtCore.QRect(30, 150, 811, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(360, 10, 61, 16))
        self.label.setObjectName("label")
        self.txtITrLabel = QtWidgets.QComboBox(self.tab)
        self.txtITrLabel.setGeometry(QtCore.QRect(240, 110, 121, 26))
        self.txtITrLabel.setEditable(True)
        self.txtITrLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrLabel.setObjectName("txtITrLabel")
        self.txtITrData = QtWidgets.QComboBox(self.tab)
        self.txtITrData.setGeometry(QtCore.QRect(240, 70, 121, 26))
        self.txtITrData.setEditable(True)
        self.txtITrData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITrData.setObjectName("txtITrData")
        self.txtITeLabel = QtWidgets.QComboBox(self.tab)
        self.txtITeLabel.setGeometry(QtCore.QRect(390, 110, 121, 26))
        self.txtITeLabel.setEditable(True)
        self.txtITeLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeLabel.setObjectName("txtITeLabel")
        self.txtITeData = QtWidgets.QComboBox(self.tab)
        self.txtITeData.setGeometry(QtCore.QRect(390, 70, 121, 26))
        self.txtITeData.setEditable(True)
        self.txtITeData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeData.setObjectName("txtITeData")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(285, 40, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(430, 40, 81, 16))
        self.label_8.setObjectName("label_8")
        self.txtFoldID = QtWidgets.QComboBox(self.tab)
        self.txtFoldID.setGeometry(QtCore.QRect(240, 150, 121, 26))
        self.txtFoldID.setEditable(True)
        self.txtFoldID.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFoldID.setObjectName("txtFoldID")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 121, 16))
        self.label_9.setObjectName("label_9")
        self.lbFoldID = QtWidgets.QLabel(self.tab)
        self.lbFoldID.setGeometry(QtCore.QRect(390, 150, 251, 16))
        self.lbFoldID.setObjectName("lbFoldID")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 761, 80))
        self.groupBox.setObjectName("groupBox")
        self.cbScale = QtWidgets.QCheckBox(self.groupBox)
        self.cbScale.setGeometry(QtCore.QRect(20, 40, 721, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.txtMinSamplesSplit = QtWidgets.QLineEdit(self.tab_2)
        self.txtMinSamplesSplit.setGeometry(QtCore.QRect(230, 190, 160, 21))
        self.txtMinSamplesSplit.setObjectName("txtMinSamplesSplit")
        self.txtMaxLeafNodes = QtWidgets.QLineEdit(self.tab_2)
        self.txtMaxLeafNodes.setGeometry(QtCore.QRect(230, 270, 160, 21))
        self.txtMaxLeafNodes.setObjectName("txtMaxLeafNodes")
        self.txtMaxFeatures = QtWidgets.QLineEdit(self.tab_2)
        self.txtMaxFeatures.setGeometry(QtCore.QRect(620, 310, 160, 21))
        self.txtMaxFeatures.setText("")
        self.txtMaxFeatures.setObjectName("txtMaxFeatures")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(20, 310, 221, 16))
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(20, 230, 231, 16))
        self.label_18.setObjectName("label_18")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 190, 221, 16))
        self.label_11.setObjectName("label_11")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(410, 190, 231, 16))
        self.label_15.setObjectName("label_15")
        self.txtMinWeightFractionLeaf = QtWidgets.QLineEdit(self.tab_2)
        self.txtMinWeightFractionLeaf.setGeometry(QtCore.QRect(230, 230, 160, 21))
        self.txtMinWeightFractionLeaf.setObjectName("txtMinWeightFractionLeaf")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(20, 270, 251, 16))
        self.label_16.setObjectName("label_16")
        self.txtMinSamplesLeaf = QtWidgets.QLineEdit(self.tab_2)
        self.txtMinSamplesLeaf.setGeometry(QtCore.QRect(620, 190, 160, 21))
        self.txtMinSamplesLeaf.setObjectName("txtMinSamplesLeaf")
        self.cbCriterion = QtWidgets.QComboBox(self.tab_2)
        self.cbCriterion.setGeometry(QtCore.QRect(230, 110, 161, 26))
        self.cbCriterion.setObjectName("cbCriterion")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(20, 110, 231, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(410, 150, 221, 16))
        self.label_20.setObjectName("label_20")
        self.txtMaxDepth = QtWidgets.QLineEdit(self.tab_2)
        self.txtMaxDepth.setGeometry(QtCore.QRect(620, 150, 160, 21))
        self.txtMaxDepth.setObjectName("txtMaxDepth")
        self.cbBootstrap = QtWidgets.QCheckBox(self.tab_2)
        self.cbBootstrap.setGeometry(QtCore.QRect(20, 390, 201, 20))
        self.cbBootstrap.setChecked(True)
        self.cbBootstrap.setObjectName("cbBootstrap")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(410, 230, 251, 16))
        self.label_21.setObjectName("label_21")
        self.txtMinImpurityDecrease = QtWidgets.QLineEdit(self.tab_2)
        self.txtMinImpurityDecrease.setGeometry(QtCore.QRect(620, 230, 160, 21))
        self.txtMinImpurityDecrease.setObjectName("txtMinImpurityDecrease")
        self.txtMinImpuritySplit = QtWidgets.QLineEdit(self.tab_2)
        self.txtMinImpuritySplit.setGeometry(QtCore.QRect(620, 270, 160, 21))
        self.txtMinImpuritySplit.setObjectName("txtMinImpuritySplit")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(410, 270, 251, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(410, 310, 221, 16))
        self.label_23.setObjectName("label_23")
        self.cbMaxFeatures = QtWidgets.QComboBox(self.tab_2)
        self.cbMaxFeatures.setGeometry(QtCore.QRect(230, 310, 161, 26))
        self.cbMaxFeatures.setObjectName("cbMaxFeatures")
        self.txtNEstimators = QtWidgets.QLineEdit(self.tab_2)
        self.txtNEstimators.setGeometry(QtCore.QRect(230, 150, 160, 21))
        self.txtNEstimators.setObjectName("txtNEstimators")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(20, 150, 221, 16))
        self.label_24.setObjectName("label_24")
        self.txtNJobs = QtWidgets.QLineEdit(self.tab_2)
        self.txtNJobs.setGeometry(QtCore.QRect(620, 110, 160, 21))
        self.txtNJobs.setObjectName("txtNJobs")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(410, 110, 221, 16))
        self.label_25.setObjectName("label_25")
        self.cbOobScore = QtWidgets.QCheckBox(self.tab_2)
        self.cbOobScore.setGeometry(QtCore.QRect(230, 390, 201, 20))
        self.cbOobScore.setChecked(False)
        self.cbOobScore.setObjectName("cbOobScore")
        self.txtVerbose = QtWidgets.QLineEdit(self.tab_2)
        self.txtVerbose.setGeometry(QtCore.QRect(230, 350, 160, 21))
        self.txtVerbose.setObjectName("txtVerbose")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(20, 350, 251, 16))
        self.label_26.setObjectName("label_26")
        self.cbWarmStart = QtWidgets.QCheckBox(self.tab_2)
        self.cbWarmStart.setGeometry(QtCore.QRect(440, 390, 201, 20))
        self.cbWarmStart.setChecked(False)
        self.cbWarmStart.setObjectName("cbWarmStart")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.txtFoldFrom = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldFrom.setGeometry(QtCore.QRect(100, 30, 80, 24))
        self.txtFoldFrom.setMaximum(100000)
        self.txtFoldFrom.setProperty("value", 1)
        self.txtFoldFrom.setObjectName("txtFoldFrom")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(40, 30, 60, 16))
        self.label_17.setObjectName("label_17")
        self.txtFoldTo = QtWidgets.QSpinBox(self.tab_3)
        self.txtFoldTo.setGeometry(QtCore.QRect(270, 30, 80, 24))
        self.txtFoldTo.setMaximum(100000)
        self.txtFoldTo.setProperty("value", 1)
        self.txtFoldTo.setObjectName("txtFoldTo")
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(210, 30, 60, 16))
        self.label_44.setObjectName("label_44")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label_4.setObjectName("label_4")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_4)
        self.txtFilter.setGeometry(QtCore.QRect(190, 30, 291, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(490, 30, 211, 16))
        self.label_5.setObjectName("label_5")
        self.txtClass = QtWidgets.QTextEdit(self.tab_4)
        self.txtClass.setGeometry(QtCore.QRect(190, 70, 91, 341))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.cbAverage = QtWidgets.QCheckBox(self.tab_5)
        self.cbAverage.setGeometry(QtCore.QRect(20, 30, 181, 20))
        self.cbAverage.setChecked(True)
        self.cbAverage.setObjectName("cbAverage")
        self.cbPrecision = QtWidgets.QCheckBox(self.tab_5)
        self.cbPrecision.setGeometry(QtCore.QRect(20, 70, 181, 20))
        self.cbPrecision.setChecked(True)
        self.cbPrecision.setObjectName("cbPrecision")
        self.cbPrecisionAvg = QtWidgets.QComboBox(self.tab_5)
        self.cbPrecisionAvg.setGeometry(QtCore.QRect(240, 70, 321, 26))
        self.cbPrecisionAvg.setObjectName("cbPrecisionAvg")
        self.cbAPrecisionAvg = QtWidgets.QComboBox(self.tab_5)
        self.cbAPrecisionAvg.setGeometry(QtCore.QRect(240, 110, 321, 26))
        self.cbAPrecisionAvg.setObjectName("cbAPrecisionAvg")
        self.cbAPrecision = QtWidgets.QCheckBox(self.tab_5)
        self.cbAPrecision.setGeometry(QtCore.QRect(20, 110, 231, 20))
        self.cbAPrecision.setChecked(False)
        self.cbAPrecision.setObjectName("cbAPrecision")
        self.cbRecallAvg = QtWidgets.QComboBox(self.tab_5)
        self.cbRecallAvg.setGeometry(QtCore.QRect(240, 150, 321, 26))
        self.cbRecallAvg.setObjectName("cbRecallAvg")
        self.cbRecall = QtWidgets.QCheckBox(self.tab_5)
        self.cbRecall.setGeometry(QtCore.QRect(20, 150, 181, 20))
        self.cbRecall.setChecked(True)
        self.cbRecall.setObjectName("cbRecall")
        self.cbF1 = QtWidgets.QCheckBox(self.tab_5)
        self.cbF1.setGeometry(QtCore.QRect(20, 190, 181, 20))
        self.cbF1.setChecked(True)
        self.cbF1.setObjectName("cbF1")
        self.cbF1Avg = QtWidgets.QComboBox(self.tab_5)
        self.cbF1Avg.setGeometry(QtCore.QRect(240, 190, 321, 26))
        self.cbF1Avg.setObjectName("cbF1Avg")
        self.tabWidget.addTab(self.tab_5, "")
        self.label_12 = QtWidgets.QLabel(frmMARFC)
        self.label_12.setGeometry(QtCore.QRect(185, 630, 491, 20))
        self.label_12.setObjectName("label_12")
        self.btnOutModel = QtWidgets.QPushButton(frmMARFC)
        self.btnOutModel.setGeometry(QtCore.QRect(790, 100, 51, 32))
        self.btnOutModel.setObjectName("btnOutModel")
        self.label_36 = QtWidgets.QLabel(frmMARFC)
        self.label_36.setGeometry(QtCore.QRect(30, 100, 171, 16))
        self.label_36.setObjectName("label_36")
        self.txtOutModel = QtWidgets.QLineEdit(frmMARFC)
        self.txtOutModel.setGeometry(QtCore.QRect(200, 100, 581, 21))
        self.txtOutModel.setText("")
        self.txtOutModel.setObjectName("txtOutModel")

        self.retranslateUi(frmMARFC)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMARFC)
        frmMARFC.setTabOrder(self.txtInFile, self.btnInFile)
        frmMARFC.setTabOrder(self.btnInFile, self.txtOutFile)
        frmMARFC.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmMARFC.setTabOrder(self.btnOutFile, self.tabWidget)
        frmMARFC.setTabOrder(self.tabWidget, self.txtITrData)
        frmMARFC.setTabOrder(self.txtITrData, self.txtITrLabel)
        frmMARFC.setTabOrder(self.txtITrLabel, self.btnConvert)
        frmMARFC.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmMARFC):
        _translate = QtCore.QCoreApplication.translate
        frmMARFC.setWindowTitle(_translate("frmMARFC", "Random Forest"))
        self.btnInFile.setText(_translate("frmMARFC", "..."))
        self.label_33.setText(_translate("frmMARFC", "Input Data (per fold)"))
        self.btnOutFile.setText(_translate("frmMARFC", "..."))
        self.btnConvert.setText(_translate("frmMARFC", "Analyze"))
        self.label_35.setText(_translate("frmMARFC", "Analysis"))
        self.btnClose.setText(_translate("frmMARFC", "Close"))
        self.label_2.setText(_translate("frmMARFC", "Data"))
        self.label_3.setText(_translate("frmMARFC", "Label"))
        self.label.setText(_translate("frmMARFC", "Input"))
        self.label_7.setText(_translate("frmMARFC", "Train"))
        self.label_8.setText(_translate("frmMARFC", "Test"))
        self.label_9.setText(_translate("frmMARFC", "FoldID"))
        self.lbFoldID.setText(_translate("frmMARFC", "ID=None"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmMARFC", "Data"))
        self.groupBox.setTitle(_translate("frmMARFC", "<Input Data Normalization>"))
        self.cbScale.setText(_translate("frmMARFC", "Scale Data Train~N(0,1) and Test~N(0,1)"))
        self.txtMinSamplesSplit.setText(_translate("frmMARFC", "2"))
        self.txtMaxLeafNodes.setText(_translate("frmMARFC", "0"))
        self.label_14.setText(_translate("frmMARFC", "Max Features"))
        self.label_18.setText(_translate("frmMARFC", "Min Weight Fraction Leaf "))
        self.label_11.setText(_translate("frmMARFC", "Min Samples Split "))
        self.label_15.setText(_translate("frmMARFC", "Min Samples Leaf"))
        self.txtMinWeightFractionLeaf.setText(_translate("frmMARFC", "0"))
        self.label_16.setText(_translate("frmMARFC", "Max Leaf Nodes (None=0)"))
        self.txtMinSamplesLeaf.setText(_translate("frmMARFC", "1"))
        self.label_19.setText(_translate("frmMARFC", "Criterion"))
        self.label_20.setText(_translate("frmMARFC", "Max Depth (None=0)"))
        self.txtMaxDepth.setText(_translate("frmMARFC", "0"))
        self.cbBootstrap.setText(_translate("frmMARFC", "Bootstrap"))
        self.label_21.setText(_translate("frmMARFC", "Min Impurity Decrease"))
        self.txtMinImpurityDecrease.setText(_translate("frmMARFC", "0"))
        self.txtMinImpuritySplit.setText(_translate("frmMARFC", "0"))
        self.label_22.setText(_translate("frmMARFC", "Min Impurity Split (None=0)"))
        self.label_23.setText(_translate("frmMARFC", "Max Features Value"))
        self.txtNEstimators.setText(_translate("frmMARFC", "10"))
        self.label_24.setText(_translate("frmMARFC", "Num Estimators"))
        self.txtNJobs.setText(_translate("frmMARFC", "1"))
        self.label_25.setText(_translate("frmMARFC", "Num Jobs"))
        self.cbOobScore.setText(_translate("frmMARFC", "Out-of-bag samples"))
        self.txtVerbose.setText(_translate("frmMARFC", "0"))
        self.label_26.setText(_translate("frmMARFC", "Verbose"))
        self.cbWarmStart.setText(_translate("frmMARFC", "Warm Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmMARFC", "Parameters"))
        self.label_17.setText(_translate("frmMARFC", "From:"))
        self.label_44.setText(_translate("frmMARFC", "To:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmMARFC", "Fold"))
        self.label_4.setText(_translate("frmMARFC", "Remove Class IDs"))
        self.txtFilter.setText(_translate("frmMARFC", "0"))
        self.label_5.setText(_translate("frmMARFC", "e.g. 0 or [1,2]"))
        self.label_10.setText(_translate("frmMARFC", "Existed Classes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmMARFC", "Filter Class ID"))
        self.cbAverage.setText(_translate("frmMARFC", "Average"))
        self.cbPrecision.setText(_translate("frmMARFC", "Precision"))
        self.cbAPrecision.setText(_translate("frmMARFC", "Average of Precision"))
        self.cbRecall.setText(_translate("frmMARFC", "Recall"))
        self.cbF1.setText(_translate("frmMARFC", "f1 score"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmMARFC", "Metrics"))
        self.label_12.setText(_translate("frmMARFC", "$FOLD$ will be replaced by fold number."))
        self.btnOutModel.setText(_translate("frmMARFC", "..."))
        self.label_36.setText(_translate("frmMARFC", "Models (per fold)"))

