# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmProbabilisticROIGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmProbabilisticROI(object):
    def setupUi(self, frmProbabilisticROI):
        frmProbabilisticROI.setObjectName("frmProbabilisticROI")
        frmProbabilisticROI.resize(802, 476)
        self.label_6 = QtWidgets.QLabel(frmProbabilisticROI)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.label_6.setObjectName("label_6")
        self.btnSSSetting = QtWidgets.QPushButton(frmProbabilisticROI)
        self.btnSSSetting.setGeometry(QtCore.QRect(740, 20, 51, 32))
        self.btnSSSetting.setObjectName("btnSSSetting")
        self.txtSSSetting = QtWidgets.QComboBox(frmProbabilisticROI)
        self.txtSSSetting.setGeometry(QtCore.QRect(98, 20, 541, 26))
        self.txtSSSetting.setEditable(True)
        self.txtSSSetting.setObjectName("txtSSSetting")
        self.btnSSSettingReload = QtWidgets.QPushButton(frmProbabilisticROI)
        self.btnSSSettingReload.setGeometry(QtCore.QRect(650, 20, 81, 32))
        self.btnSSSettingReload.setObjectName("btnSSSettingReload")
        self.tabWidget_2 = QtWidgets.QTabWidget(frmProbabilisticROI)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 150, 761, 211))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.txtSSDIR = QtWidgets.QLineEdit(self.tab_9)
        self.txtSSDIR.setGeometry(QtCore.QRect(140, 26, 601, 21))
        self.txtSSDIR.setStatusTip("")
        self.txtSSDIR.setText("")
        self.txtSSDIR.setObjectName("txtSSDIR")
        self.label_4 = QtWidgets.QLabel(self.tab_9)
        self.label_4.setGeometry(QtCore.QRect(10, 26, 131, 16))
        self.label_4.setToolTip("")
        self.label_4.setToolTipDuration(-1)
        self.label_4.setStatusTip("")
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.tab_9)
        self.label_9.setGeometry(QtCore.QRect(11, 60, 131, 16))
        self.label_9.setObjectName("label_9")
        self.txtSSTask = QtWidgets.QLineEdit(self.tab_9)
        self.txtSSTask.setGeometry(QtCore.QRect(140, 60, 601, 21))
        self.txtSSTask.setStatusTip("")
        self.txtSSTask.setText("")
        self.txtSSTask.setObjectName("txtSSTask")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_12 = QtWidgets.QLabel(self.tab_8)
        self.label_12.setGeometry(QtCore.QRect(550, 20, 60, 16))
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.tab_8)
        self.label_11.setGeometry(QtCore.QRect(370, 20, 60, 21))
        self.label_11.setObjectName("label_11")
        self.txtSSSubPer = QtWidgets.QLineEdit(self.tab_8)
        self.txtSSSubPer.setGeometry(QtCore.QRect(600, 20, 80, 21))
        self.txtSSSubPer.setObjectName("txtSSSubPer")
        self.txtSSSubLen = QtWidgets.QSpinBox(self.tab_8)
        self.txtSSSubLen.setGeometry(QtCore.QRect(440, 20, 80, 24))
        self.txtSSSubLen.setMinimum(1)
        self.txtSSSubLen.setMaximum(999999999)
        self.txtSSSubLen.setSingleStep(1)
        self.txtSSSubLen.setProperty("value", 2)
        self.txtSSSubLen.setObjectName("txtSSSubLen")
        self.txtSSSubRange = QtWidgets.QLineEdit(self.tab_8)
        self.txtSSSubRange.setGeometry(QtCore.QRect(130, 20, 211, 21))
        self.txtSSSubRange.setObjectName("txtSSSubRange")
        self.label_10 = QtWidgets.QLabel(self.tab_8)
        self.label_10.setGeometry(QtCore.QRect(60, 20, 71, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.txtSSRunLen = QtWidgets.QSpinBox(self.tab_10)
        self.txtSSRunLen.setGeometry(QtCore.QRect(440, 20, 80, 24))
        self.txtSSRunLen.setMinimum(1)
        self.txtSSRunLen.setMaximum(999999999)
        self.txtSSRunLen.setProperty("value", 2)
        self.txtSSRunLen.setObjectName("txtSSRunLen")
        self.txtSSRunPer = QtWidgets.QLineEdit(self.tab_10)
        self.txtSSRunPer.setGeometry(QtCore.QRect(600, 20, 80, 21))
        self.txtSSRunPer.setObjectName("txtSSRunPer")
        self.label_18 = QtWidgets.QLabel(self.tab_10)
        self.label_18.setGeometry(QtCore.QRect(370, 20, 60, 21))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.tab_10)
        self.label_21.setGeometry(QtCore.QRect(550, 20, 60, 16))
        self.label_21.setObjectName("label_21")
        self.txtSSRunRange = QtWidgets.QLineEdit(self.tab_10)
        self.txtSSRunRange.setGeometry(QtCore.QRect(135, 20, 211, 21))
        self.txtSSRunRange.setObjectName("txtSSRunRange")
        self.label_24 = QtWidgets.QLabel(self.tab_10)
        self.label_24.setGeometry(QtCore.QRect(70, 20, 71, 16))
        self.label_24.setObjectName("label_24")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.txtSSConLen = QtWidgets.QSpinBox(self.tab_11)
        self.txtSSConLen.setGeometry(QtCore.QRect(440, 20, 80, 24))
        self.txtSSConLen.setMaximum(100000)
        self.txtSSConLen.setSingleStep(1)
        self.txtSSConLen.setProperty("value", 2)
        self.txtSSConLen.setObjectName("txtSSConLen")
        self.label_43 = QtWidgets.QLabel(self.tab_11)
        self.label_43.setGeometry(QtCore.QRect(370, 20, 60, 21))
        self.label_43.setObjectName("label_43")
        self.label_42 = QtWidgets.QLabel(self.tab_11)
        self.label_42.setGeometry(QtCore.QRect(540, 20, 60, 16))
        self.label_42.setObjectName("label_42")
        self.txtSSConPer = QtWidgets.QLineEdit(self.tab_11)
        self.txtSSConPer.setGeometry(QtCore.QRect(590, 20, 80, 21))
        self.txtSSConPer.setObjectName("txtSSConPer")
        self.label_20 = QtWidgets.QLabel(self.tab_11)
        self.label_20.setGeometry(QtCore.QRect(80, 20, 61, 16))
        self.label_20.setObjectName("label_20")
        self.txtSSConRange = QtWidgets.QLineEdit(self.tab_11)
        self.txtSSConRange.setGeometry(QtCore.QRect(150, 20, 201, 21))
        self.txtSSConRange.setObjectName("txtSSConRange")
        self.tabWidget_2.addTab(self.tab_11, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.txtSSCondLen = QtWidgets.QSpinBox(self.tab_2)
        self.txtSSCondLen.setGeometry(QtCore.QRect(440, 20, 80, 24))
        self.txtSSCondLen.setMinimum(1)
        self.txtSSCondLen.setMaximum(999999999)
        self.txtSSCondLen.setSingleStep(1)
        self.txtSSCondLen.setProperty("value", 1)
        self.txtSSCondLen.setObjectName("txtSSCondLen")
        self.txtSSCondPer = QtWidgets.QLineEdit(self.tab_2)
        self.txtSSCondPer.setGeometry(QtCore.QRect(610, 20, 80, 21))
        self.txtSSCondPer.setText("")
        self.txtSSCondPer.setObjectName("txtSSCondPer")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(550, 20, 60, 16))
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(370, 20, 71, 21))
        self.label_19.setObjectName("label_19")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 49, 731, 121))
        self.groupBox.setObjectName("groupBox")
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setGeometry(QtCore.QRect(11, 40, 201, 16))
        self.label_27.setObjectName("label_27")
        self.txtCondPre = QtWidgets.QLineEdit(self.groupBox)
        self.txtCondPre.setGeometry(QtCore.QRect(160, 80, 431, 21))
        self.txtCondPre.setObjectName("txtCondPre")
        self.txtEventDIR = QtWidgets.QLineEdit(self.groupBox)
        self.txtEventDIR.setGeometry(QtCore.QRect(211, 40, 501, 21))
        self.txtEventDIR.setObjectName("txtEventDIR")
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setGeometry(QtCore.QRect(9, 80, 201, 16))
        self.label_28.setObjectName("label_28")
        self.btnLoadEvent = QtWidgets.QPushButton(self.groupBox)
        self.btnLoadEvent.setGeometry(QtCore.QRect(604, 74, 113, 32))
        self.btnLoadEvent.setObjectName("btnLoadEvent")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(230, 20, 60, 16))
        self.label_25.setObjectName("label_25")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(80, 20, 60, 16))
        self.label_14.setObjectName("label_14")
        self.txtSSCondFrom = QtWidgets.QSpinBox(self.tab_2)
        self.txtSSCondFrom.setGeometry(QtCore.QRect(130, 20, 80, 24))
        self.txtSSCondFrom.setMaximum(999999999)
        self.txtSSCondFrom.setProperty("value", 1)
        self.txtSSCondFrom.setObjectName("txtSSCondFrom")
        self.txtSSCondTo = QtWidgets.QSpinBox(self.tab_2)
        self.txtSSCondTo.setGeometry(QtCore.QRect(270, 20, 80, 24))
        self.txtSSCondTo.setMaximum(999999999)
        self.txtSSCondTo.setProperty("value", 2)
        self.txtSSCondTo.setObjectName("txtSSCondTo")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label.setObjectName("label")
        self.cbMetric = QtWidgets.QComboBox(self.tab)
        self.cbMetric.setGeometry(QtCore.QRect(100, 20, 331, 26))
        self.cbMetric.setObjectName("cbMetric")
        self.txtSSSpace = QtWidgets.QComboBox(self.tab)
        self.txtSSSpace.setGeometry(QtCore.QRect(100, 60, 581, 26))
        self.txtSSSpace.setEditable(True)
        self.txtSSSpace.setObjectName("txtSSSpace")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_5.setObjectName("label_5")
        self.btnSSSpace = QtWidgets.QPushButton(self.tab)
        self.btnSSSpace.setGeometry(QtCore.QRect(690, 60, 51, 32))
        self.btnSSSpace.setObjectName("btnSSSpace")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label_7.setObjectName("label_7")
        self.cbThType = QtWidgets.QComboBox(self.tab_3)
        self.cbThType.setGeometry(QtCore.QRect(90, 20, 361, 26))
        self.cbThType.setObjectName("cbThType")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 63, 71, 16))
        self.label_8.setObjectName("label_8")
        self.txtThMin = QtWidgets.QLineEdit(self.tab_3)
        self.txtThMin.setEnabled(False)
        self.txtThMin.setGeometry(QtCore.QRect(90, 63, 113, 21))
        self.txtThMin.setObjectName("txtThMin")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(20, 100, 71, 16))
        self.label_22.setObjectName("label_22")
        self.txtThMax = QtWidgets.QLineEdit(self.tab_3)
        self.txtThMax.setEnabled(False)
        self.txtThMax.setGeometry(QtCore.QRect(90, 100, 113, 21))
        self.txtThMax.setObjectName("txtThMax")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.btnClose = QtWidgets.QPushButton(frmProbabilisticROI)
        self.btnClose.setGeometry(QtCore.QRect(20, 430, 113, 32))
        self.btnClose.setObjectName("btnClose")
        self.btnRUN = QtWidgets.QPushButton(frmProbabilisticROI)
        self.btnRUN.setGeometry(QtCore.QRect(670, 430, 113, 32))
        self.btnRUN.setObjectName("btnRUN")
        self.label_2 = QtWidgets.QLabel(frmProbabilisticROI)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 131, 16))
        self.label_2.setObjectName("label_2")
        self.txtSSInFile = QtWidgets.QComboBox(frmProbabilisticROI)
        self.txtSSInFile.setGeometry(QtCore.QRect(150, 60, 631, 26))
        self.txtSSInFile.setEditable(True)
        self.txtSSInFile.setObjectName("txtSSInFile")
        self.label_23 = QtWidgets.QLabel(frmProbabilisticROI)
        self.label_23.setGeometry(QtCore.QRect(20, 380, 771, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_23.setObjectName("label_23")
        self.btnOutROI = QtWidgets.QPushButton(frmProbabilisticROI)
        self.btnOutROI.setGeometry(QtCore.QRect(740, 100, 51, 32))
        self.btnOutROI.setObjectName("btnOutROI")
        self.label_3 = QtWidgets.QLabel(frmProbabilisticROI)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 101, 16))
        self.label_3.setObjectName("label_3")
        self.txtOutROI = QtWidgets.QLineEdit(frmProbabilisticROI)
        self.txtOutROI.setGeometry(QtCore.QRect(120, 100, 611, 21))
        self.txtOutROI.setText("")
        self.txtOutROI.setObjectName("txtOutROI")

        self.retranslateUi(frmProbabilisticROI)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmProbabilisticROI)
        frmProbabilisticROI.setTabOrder(self.txtSSSetting, self.btnSSSettingReload)
        frmProbabilisticROI.setTabOrder(self.btnSSSettingReload, self.btnSSSetting)
        frmProbabilisticROI.setTabOrder(self.btnSSSetting, self.txtSSInFile)
        frmProbabilisticROI.setTabOrder(self.txtSSInFile, self.txtOutROI)
        frmProbabilisticROI.setTabOrder(self.txtOutROI, self.btnOutROI)
        frmProbabilisticROI.setTabOrder(self.btnOutROI, self.tabWidget_2)
        frmProbabilisticROI.setTabOrder(self.tabWidget_2, self.txtSSDIR)
        frmProbabilisticROI.setTabOrder(self.txtSSDIR, self.txtSSTask)
        frmProbabilisticROI.setTabOrder(self.txtSSTask, self.txtSSSubLen)
        frmProbabilisticROI.setTabOrder(self.txtSSSubLen, self.txtSSSubPer)
        frmProbabilisticROI.setTabOrder(self.txtSSSubPer, self.txtSSRunLen)
        frmProbabilisticROI.setTabOrder(self.txtSSRunLen, self.txtSSRunPer)
        frmProbabilisticROI.setTabOrder(self.txtSSRunPer, self.txtSSCondLen)
        frmProbabilisticROI.setTabOrder(self.txtSSCondLen, self.txtSSCondPer)
        frmProbabilisticROI.setTabOrder(self.txtSSCondPer, self.txtEventDIR)
        frmProbabilisticROI.setTabOrder(self.txtEventDIR, self.txtCondPre)
        frmProbabilisticROI.setTabOrder(self.txtCondPre, self.btnLoadEvent)
        frmProbabilisticROI.setTabOrder(self.btnLoadEvent, self.txtSSConLen)
        frmProbabilisticROI.setTabOrder(self.txtSSConLen, self.txtSSConPer)
        frmProbabilisticROI.setTabOrder(self.txtSSConPer, self.cbMetric)
        frmProbabilisticROI.setTabOrder(self.cbMetric, self.txtSSSpace)
        frmProbabilisticROI.setTabOrder(self.txtSSSpace, self.btnSSSpace)
        frmProbabilisticROI.setTabOrder(self.btnSSSpace, self.cbThType)
        frmProbabilisticROI.setTabOrder(self.cbThType, self.txtThMin)
        frmProbabilisticROI.setTabOrder(self.txtThMin, self.txtThMax)
        frmProbabilisticROI.setTabOrder(self.txtThMax, self.btnRUN)
        frmProbabilisticROI.setTabOrder(self.btnRUN, self.btnClose)

    def retranslateUi(self, frmProbabilisticROI):
        _translate = QtCore.QCoreApplication.translate
        frmProbabilisticROI.setWindowTitle(_translate("frmProbabilisticROI", "Probabilistic ROI"))
        self.label_6.setText(_translate("frmProbabilisticROI", "Setting"))
        self.btnSSSetting.setText(_translate("frmProbabilisticROI", "..."))
        self.btnSSSettingReload.setText(_translate("frmProbabilisticROI", "Reload"))
        self.txtSSDIR.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt;\">mainDIR: main folder that is included all dataset files, i.e. support BIDS format: </span><a href=\"https://www.nature.com/articles/sdata201644\"><span style=\" font-size:18pt; text-decoration: underline; color:#0000ff;\">https://www.nature.com/articles/sdata201644</span></a></p></body></html>"))
        self.label_4.setText(_translate("frmProbabilisticROI", "Main Directory:"))
        self.label_4.setProperty("setToolTip", _translate("frmProbabilisticROI", "Please enter the main directory of the fMRI dataset. Format of directory must be based on BIDS structure."))
        self.label_9.setText(_translate("frmProbabilisticROI", "Task Name:"))
        self.txtSSTask.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt;\">mainDIR: main folder that is included all dataset files, i.e. support BIDS format: </span><a href=\"https://www.nature.com/articles/sdata201644\"><span style=\" font-size:18pt; text-decoration: underline; color:#0000ff;\">https://www.nature.com/articles/sdata201644</span></a></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("frmProbabilisticROI", "General"))
        self.label_12.setText(_translate("frmProbabilisticROI", "Perfix:"))
        self.label_11.setText(_translate("frmProbabilisticROI", "Length:"))
        self.txtSSSubPer.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubPer: content of subject counter, e.g. SubPer = 0 -&gt; sub-001 OR SubPer = A -&gt; sub-AA1</span></p></body></html>"))
        self.txtSSSubPer.setText(_translate("frmProbabilisticROI", "0"))
        self.txtSSSubLen.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen: the length of subject counter, e.g. SubLen=3 -&gt; output sub-001, sub-002</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen &gt; 1</span></p></body></html>"))
        self.txtSSSubRange.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubRange: a unique range of integers, i.e. Range=[1, 4-8, 10, 12-14]</span></p></body></html>"))
        self.txtSSSubRange.setText(_translate("frmProbabilisticROI", "[1-1]"))
        self.label_10.setText(_translate("frmProbabilisticROI", "Range:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("frmProbabilisticROI", "Subjects"))
        self.txtSSRunLen.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunLen: the length of run counter, e.g. RunLen=3 -&gt; output run-001, rub-002</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">RunLen &gt; 1</span></p></body></html>"))
        self.txtSSRunPer.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunPer: content of subject counter, e.g. RunPer = 0 -&gt; run-001 OR RunPer = A -&gt; run-AA1</span></p></body></html>"))
        self.txtSSRunPer.setText(_translate("frmProbabilisticROI", "0"))
        self.label_18.setText(_translate("frmProbabilisticROI", "Length:"))
        self.label_21.setText(_translate("frmProbabilisticROI", "Perfix:"))
        self.txtSSRunRange.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunRange: sequence of ranges, i.e. If all 12 subjects have runs from 2 to 5 then Range=[12*2-5]; If 3 subjects have runs from 1 to 4 and 2 subjects have runs from 5 to 7 then Range=[3*1-4, 2*5-7]</span></p></body></html>"))
        self.txtSSRunRange.setText(_translate("frmProbabilisticROI", "[1*1-1]"))
        self.label_24.setText(_translate("frmProbabilisticROI", "Ranges:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("frmProbabilisticROI", "Run"))
        self.label_43.setText(_translate("frmProbabilisticROI", "Length:"))
        self.label_42.setText(_translate("frmProbabilisticROI", "Perfix:"))
        self.txtSSConPer.setText(_translate("frmProbabilisticROI", "0"))
        self.label_20.setText(_translate("frmProbabilisticROI", "Ranges:"))
        self.txtSSConRange.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">CounterRange: sequence of ranges, i.e. If all 12 subjects have runs from 2 to 5 then Range=[12*2-5]; If 3 subjects have runs from 1 to 4 and 2 subjects have runs from 5 to 7 then Range=[3*1-4, 2*5-7]</span></p></body></html>"))
        self.txtSSConRange.setText(_translate("frmProbabilisticROI", "[1*1-1]"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("frmProbabilisticROI", "Counter"))
        self.txtSSCondLen.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen: the length of subject counter, e.g. SubLen=3 -&gt; output sub-001, sub-002</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen &gt; 1</span></p></body></html>"))
        self.txtSSCondPer.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubPer: content of subject counter, e.g. SubPer = 0 -&gt; sub-001 OR SubPer = A -&gt; sub-AA1</span></p></body></html>"))
        self.label_15.setText(_translate("frmProbabilisticROI", "Perfix:"))
        self.label_19.setText(_translate("frmProbabilisticROI", "Length:"))
        self.groupBox.setTitle(_translate("frmProbabilisticROI", "<Generated Event>"))
        self.label_27.setText(_translate("frmProbabilisticROI", "Generated Event Folders:"))
        self.txtCondPre.setText(_translate("frmProbabilisticROI", "cond"))
        self.txtEventDIR.setText(_translate("frmProbabilisticROI", "$MAINDIR$/sub-$SUB$/func/sub-$SUB$_task-$TASK$_run-$RUN$_events/"))
        self.label_28.setText(_translate("frmProbabilisticROI", "Condition Prefix:"))
        self.btnLoadEvent.setText(_translate("frmProbabilisticROI", "Load"))
        self.label_25.setText(_translate("frmProbabilisticROI", "To:"))
        self.label_14.setText(_translate("frmProbabilisticROI", "From:"))
        self.txtSSCondFrom.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubFrom: subject counter will be started from this number</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">SubForm &gt; 0 &amp;&amp; SubFrom &lt;= SubTo</span></p></body></html>"))
        self.txtSSCondTo.setToolTip(_translate("frmProbabilisticROI", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubFrom: subject counter will be ended from this number</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">SubTo &gt; 0 &amp;&amp; SubFrom &lt;= SubTo</span></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("frmProbabilisticROI", "Condition"))
        self.label.setText(_translate("frmProbabilisticROI", "Metric"))
        self.label_5.setText(_translate("frmProbabilisticROI", "Affine file"))
        self.btnSSSpace.setText(_translate("frmProbabilisticROI", "..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("frmProbabilisticROI", "Parameters"))
        self.label_7.setText(_translate("frmProbabilisticROI", "Type:"))
        self.label_8.setText(_translate("frmProbabilisticROI", "Min:"))
        self.label_22.setText(_translate("frmProbabilisticROI", "Max:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("frmProbabilisticROI", "Thresholding"))
        self.btnClose.setText(_translate("frmProbabilisticROI", "Close"))
        self.btnRUN.setText(_translate("frmProbabilisticROI", "Run"))
        self.label_2.setText(_translate("frmProbabilisticROI", "Mask File Name"))
        self.label_23.setText(_translate("frmProbabilisticROI", "$MAINDIR$, $SUB$, $TASK$, $RUN$, $COND$, $COUNT$ will be replaced by the preprocessing parameters.\n"
"It\'s case sensitive."))
        self.btnOutROI.setText(_translate("frmProbabilisticROI", "..."))
        self.label_3.setText(_translate("frmProbabilisticROI", "Output ROI"))

