# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmPreprocessGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmPreprocess(object):
    def setupUi(self, frmPreprocess):
        frmPreprocess.setObjectName("frmPreprocess")
        frmPreprocess.resize(703, 649)
        frmPreprocess.setAcceptDrops(False)
        self.tabWidget = QtWidgets.QTabWidget(frmPreprocess)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 671, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 621, 80))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 35, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(300, 35, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(480, 35, 60, 16))
        self.label_4.setObjectName("label_4")
        self.txtSubPer = QtWidgets.QLineEdit(self.groupBox)
        self.txtSubPer.setGeometry(QtCore.QRect(530, 35, 80, 21))
        self.txtSubPer.setObjectName("txtSubPer")
        self.txtSubLen = QtWidgets.QSpinBox(self.groupBox)
        self.txtSubLen.setGeometry(QtCore.QRect(370, 35, 80, 24))
        self.txtSubLen.setMinimum(1)
        self.txtSubLen.setMaximum(999999999)
        self.txtSubLen.setSingleStep(1)
        self.txtSubLen.setProperty("value", 2)
        self.txtSubLen.setObjectName("txtSubLen")
        self.txtSubRange = QtWidgets.QLineEdit(self.groupBox)
        self.txtSubRange.setGeometry(QtCore.QRect(70, 35, 211, 21))
        self.txtSubRange.setObjectName("txtSubRange")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 190, 621, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(11, 69, 81, 16))
        self.label_5.setObjectName("label_5")
        self.btnDIR = QtWidgets.QPushButton(self.groupBox_4)
        self.btnDIR.setGeometry(QtCore.QRect(559, 26, 51, 32))
        self.btnDIR.setObjectName("btnDIR")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 31, 111, 16))
        self.label.setToolTip("")
        self.label.setToolTipDuration(-1)
        self.label.setStatusTip("")
        self.label.setObjectName("label")
        self.txtDIR = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtDIR.setGeometry(QtCore.QRect(118, 31, 431, 21))
        self.txtDIR.setStatusTip("")
        self.txtDIR.setText("")
        self.txtDIR.setObjectName("txtDIR")
        self.btnReadTask = QtWidgets.QPushButton(self.groupBox_4)
        self.btnReadTask.setGeometry(QtCore.QRect(529, 66, 81, 32))
        self.btnReadTask.setObjectName("btnReadTask")
        self.txtTask = QtWidgets.QComboBox(self.groupBox_4)
        self.txtTask.setGeometry(QtCore.QRect(100, 67, 421, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setObjectName("txtTask")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 98, 621, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 35, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(300, 35, 71, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(480, 35, 61, 16))
        self.label_10.setObjectName("label_10")
        self.txtRunPer = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtRunPer.setGeometry(QtCore.QRect(530, 35, 80, 21))
        self.txtRunPer.setObjectName("txtRunPer")
        self.txtRunLen = QtWidgets.QSpinBox(self.groupBox_3)
        self.txtRunLen.setGeometry(QtCore.QRect(370, 35, 80, 24))
        self.txtRunLen.setMinimum(1)
        self.txtRunLen.setMaximum(999999999)
        self.txtRunLen.setProperty("value", 2)
        self.txtRunLen.setObjectName("txtRunLen")
        self.txtRunRange = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtRunRange.setGeometry(QtCore.QRect(75, 35, 211, 21))
        self.txtRunRange.setObjectName("txtRunRange")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 310, 621, 151))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.txtBOLD = QtWidgets.QLineEdit(self.tab_8)
        self.txtBOLD.setGeometry(QtCore.QRect(120, 20, 481, 21))
        self.txtBOLD.setObjectName("txtBOLD")
        self.label_12 = QtWidgets.QLabel(self.tab_8)
        self.label_12.setGeometry(QtCore.QRect(17, 20, 121, 16))
        self.label_12.setObjectName("label_12")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_26 = QtWidgets.QLabel(self.tab_9)
        self.label_26.setGeometry(QtCore.QRect(12, 50, 231, 16))
        self.label_26.setObjectName("label_26")
        self.txtBET = QtWidgets.QLineEdit(self.tab_9)
        self.txtBET.setGeometry(QtCore.QRect(254, 50, 341, 21))
        self.txtBET.setObjectName("txtBET")
        self.label_29 = QtWidgets.QLabel(self.tab_9)
        self.label_29.setGeometry(QtCore.QRect(10, 124, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_9)
        self.label_30.setGeometry(QtCore.QRect(12, 90, 251, 16))
        self.label_30.setObjectName("label_30")
        self.txtBETPDF = QtWidgets.QLineEdit(self.tab_9)
        self.txtBETPDF.setGeometry(QtCore.QRect(263, 90, 331, 21))
        self.txtBETPDF.setObjectName("txtBETPDF")
        self.label_22 = QtWidgets.QLabel(self.tab_9)
        self.label_22.setGeometry(QtCore.QRect(14, 10, 141, 16))
        self.label_22.setObjectName("label_22")
        self.txtAnat = QtWidgets.QLineEdit(self.tab_9)
        self.txtAnat.setGeometry(QtCore.QRect(163, 10, 431, 21))
        self.txtAnat.setObjectName("txtAnat")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.Report = QtWidgets.QWidget()
        self.Report.setObjectName("Report")
        self.label_31 = QtWidgets.QLabel(self.Report)
        self.label_31.setGeometry(QtCore.QRect(10, 124, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_31.setObjectName("label_31")
        self.txtCondPre = QtWidgets.QLineEdit(self.Report)
        self.txtCondPre.setGeometry(QtCore.QRect(131, 90, 461, 21))
        self.txtCondPre.setObjectName("txtCondPre")
        self.txtEventDIR = QtWidgets.QLineEdit(self.Report)
        self.txtEventDIR.setGeometry(QtCore.QRect(202, 50, 391, 21))
        self.txtEventDIR.setObjectName("txtEventDIR")
        self.label_28 = QtWidgets.QLabel(self.Report)
        self.label_28.setGeometry(QtCore.QRect(10, 90, 201, 16))
        self.label_28.setObjectName("label_28")
        self.label_27 = QtWidgets.QLabel(self.Report)
        self.label_27.setGeometry(QtCore.QRect(12, 50, 201, 16))
        self.label_27.setObjectName("label_27")
        self.label_11 = QtWidgets.QLabel(self.Report)
        self.label_11.setGeometry(QtCore.QRect(13, 10, 121, 16))
        self.label_11.setObjectName("label_11")
        self.txtOnset = QtWidgets.QLineEdit(self.Report)
        self.txtOnset.setGeometry(QtCore.QRect(101, 9, 491, 21))
        self.txtOnset.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtOnset.setObjectName("txtOnset")
        self.tabWidget_2.addTab(self.Report, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_32 = QtWidgets.QLabel(self.tab_10)
        self.label_32.setGeometry(QtCore.QRect(10, 124, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_32.setObjectName("label_32")
        self.txtAnalysis = QtWidgets.QLineEdit(self.tab_10)
        self.txtAnalysis.setGeometry(QtCore.QRect(140, 60, 461, 21))
        self.txtAnalysis.setObjectName("txtAnalysis")
        self.label_33 = QtWidgets.QLabel(self.tab_10)
        self.label_33.setGeometry(QtCore.QRect(10, 60, 201, 16))
        self.label_33.setObjectName("label_33")
        self.txtScript = QtWidgets.QLineEdit(self.tab_10)
        self.txtScript.setGeometry(QtCore.QRect(120, 20, 481, 21))
        self.txtScript.setObjectName("txtScript")
        self.label_34 = QtWidgets.QLabel(self.tab_10)
        self.label_34.setGeometry(QtCore.QRect(10, 20, 201, 16))
        self.label_34.setObjectName("label_34")
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.label_41 = QtWidgets.QLabel(self.tab_11)
        self.label_41.setGeometry(QtCore.QRect(470, 30, 60, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_11)
        self.label_42.setGeometry(QtCore.QRect(300, 30, 60, 21))
        self.label_42.setObjectName("label_42")
        self.txtConPer = QtWidgets.QLineEdit(self.tab_11)
        self.txtConPer.setGeometry(QtCore.QRect(520, 30, 80, 21))
        self.txtConPer.setObjectName("txtConPer")
        self.txtConLen = QtWidgets.QSpinBox(self.tab_11)
        self.txtConLen.setGeometry(QtCore.QRect(370, 30, 80, 24))
        self.txtConLen.setMaximum(100000)
        self.txtConLen.setSingleStep(1)
        self.txtConLen.setProperty("value", 2)
        self.txtConLen.setObjectName("txtConLen")
        self.txtConRange = QtWidgets.QLineEdit(self.tab_11)
        self.txtConRange.setGeometry(QtCore.QRect(80, 30, 201, 21))
        self.txtConRange.setObjectName("txtConRange")
        self.label_7 = QtWidgets.QLabel(self.tab_11)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_7.setObjectName("label_7")
        self.tabWidget_2.addTab(self.tab_11, "")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(20, 470, 641, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 23, 71, 16))
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 231, 16))
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 221, 16))
        self.label_15.setObjectName("label_15")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(350, 110, 231, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(10, 154, 231, 16))
        self.label_21.setObjectName("label_21")
        self.cbSliceTime = QtWidgets.QComboBox(self.tab_2)
        self.cbSliceTime.setGeometry(QtCore.QRect(180, 150, 251, 26))
        self.cbSliceTime.setObjectName("cbSliceTime")
        self.txtVoxel = QtWidgets.QLabel(self.tab_2)
        self.txtVoxel.setGeometry(QtCore.QRect(230, 23, 401, 16))
        self.txtVoxel.setObjectName("txtVoxel")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(380, 60, 151, 16))
        self.label_14.setObjectName("label_14")
        self.cbRegAnat = QtWidgets.QCheckBox(self.tab_2)
        self.cbRegAnat.setEnabled(True)
        self.cbRegAnat.setGeometry(QtCore.QRect(180, 190, 271, 20))
        self.cbRegAnat.setChecked(False)
        self.cbRegAnat.setObjectName("cbRegAnat")
        self.cbMotionCorrection = QtWidgets.QCheckBox(self.tab_2)
        self.cbMotionCorrection.setGeometry(QtCore.QRect(10, 190, 160, 20))
        self.cbMotionCorrection.setChecked(True)
        self.cbMotionCorrection.setObjectName("cbMotionCorrection")
        self.txtTotalVol = QtWidgets.QSpinBox(self.tab_2)
        self.txtTotalVol.setGeometry(QtCore.QRect(230, 60, 121, 24))
        self.txtTotalVol.setMinimum(0)
        self.txtTotalVol.setMaximum(999999999)
        self.txtTotalVol.setProperty("value", 0)
        self.txtTotalVol.setObjectName("txtTotalVol")
        self.txtDeleteVol = QtWidgets.QSpinBox(self.tab_2)
        self.txtDeleteVol.setGeometry(QtCore.QRect(530, 60, 121, 24))
        self.txtDeleteVol.setMaximum(999999999)
        self.txtDeleteVol.setObjectName("txtDeleteVol")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 240, 631, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(10, 40, 231, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(200, 40, 231, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(450, 40, 231, 16))
        self.label_37.setObjectName("label_37")
        self.txtDENL = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtDENL.setGeometry(QtCore.QRect(110, 40, 80, 21))
        self.txtDENL.setObjectName("txtDENL")
        self.txtDETS = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtDETS.setGeometry(QtCore.QRect(360, 40, 80, 21))
        self.txtDETS.setObjectName("txtDETS")
        self.txtDEZT = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtDEZT.setGeometry(QtCore.QRect(536, 40, 80, 21))
        self.txtDEZT.setObjectName("txtDEZT")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(19, 350, 631, 80))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_38 = QtWidgets.QLabel(self.groupBox_6)
        self.label_38.setGeometry(QtCore.QRect(14, 39, 101, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(214, 40, 131, 16))
        self.label_39.setObjectName("label_39")
        self.txtCTZT = QtWidgets.QLineEdit(self.groupBox_6)
        self.txtCTZT.setGeometry(QtCore.QRect(104, 40, 80, 21))
        self.txtCTZT.setObjectName("txtCTZT")
        self.txtCTPT = QtWidgets.QLineEdit(self.groupBox_6)
        self.txtCTPT.setGeometry(QtCore.QRect(360, 40, 80, 21))
        self.txtCTPT.setObjectName("txtCTPT")
        self.txtTR = QtWidgets.QLineEdit(self.tab_2)
        self.txtTR.setGeometry(QtCore.QRect(90, 20, 100, 21))
        self.txtTR.setObjectName("txtTR")
        self.txtHighPass = QtWidgets.QLineEdit(self.tab_2)
        self.txtHighPass.setGeometry(QtCore.QRect(550, 108, 100, 21))
        self.txtHighPass.setObjectName("txtHighPass")
        self.txtFWHM = QtWidgets.QLineEdit(self.tab_2)
        self.txtFWHM.setGeometry(QtCore.QRect(230, 108, 100, 21))
        self.txtFWHM.setObjectName("txtFWHM")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.btnEventTest = QtWidgets.QPushButton(self.tab_3)
        self.btnEventTest.setGeometry(QtCore.QRect(432, 470, 221, 32))
        self.btnEventTest.setObjectName("btnEventTest")
        self.txtEvents = QtWidgets.QTextEdit(self.tab_3)
        self.txtEvents.setGeometry(QtCore.QRect(10, 10, 641, 451))
        self.txtEvents.setObjectName("txtEvents")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.btnEvent = QtWidgets.QPushButton(self.tab_4)
        self.btnEvent.setEnabled(True)
        self.btnEvent.setGeometry(QtCore.QRect(23, 20, 631, 40))
        self.btnEvent.setObjectName("btnEvent")
        self.btnExtractor = QtWidgets.QPushButton(self.tab_4)
        self.btnExtractor.setEnabled(False)
        self.btnExtractor.setGeometry(QtCore.QRect(23, 70, 631, 40))
        self.btnExtractor.setObjectName("btnExtractor")
        self.btnPreprocessScripts = QtWidgets.QPushButton(self.tab_4)
        self.btnPreprocessScripts.setEnabled(True)
        self.btnPreprocessScripts.setGeometry(QtCore.QRect(23, 120, 631, 40))
        self.btnPreprocessScripts.setObjectName("btnPreprocessScripts")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 170, 631, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.cbJustRun = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbJustRun.setGeometry(QtCore.QRect(30, 30, 201, 20))
        self.cbJustRun.setObjectName("cbJustRun")
        self.cbRemoveOlds = QtWidgets.QCheckBox(self.groupBox_5)
        self.cbRemoveOlds.setGeometry(QtCore.QRect(230, 30, 191, 20))
        self.cbRemoveOlds.setChecked(True)
        self.cbRemoveOlds.setObjectName("cbRemoveOlds")
        self.btnPreprocess = QtWidgets.QPushButton(self.groupBox_5)
        self.btnPreprocess.setEnabled(True)
        self.btnPreprocess.setGeometry(QtCore.QRect(20, 80, 591, 40))
        self.btnPreprocess.setObjectName("btnPreprocess")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 20, 631, 121))
        self.groupBox_7.setObjectName("groupBox_7")
        self.cbVImage = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbVImage.setGeometry(QtCore.QRect(20, 40, 231, 20))
        self.cbVImage.setChecked(True)
        self.cbVImage.setObjectName("cbVImage")
        self.cbVEvent = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbVEvent.setGeometry(QtCore.QRect(20, 80, 411, 20))
        self.cbVEvent.setChecked(True)
        self.cbVEvent.setObjectName("cbVEvent")
        self.cbVMRI = QtWidgets.QCheckBox(self.groupBox_7)
        self.cbVMRI.setGeometry(QtCore.QRect(260, 40, 351, 20))
        self.cbVMRI.setChecked(True)
        self.cbVMRI.setObjectName("cbVMRI")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 160, 631, 291))
        self.groupBox_8.setObjectName("groupBox_8")
        self.cbVExEvent = QtWidgets.QCheckBox(self.groupBox_8)
        self.cbVExEvent.setGeometry(QtCore.QRect(20, 40, 281, 20))
        self.cbVExEvent.setChecked(True)
        self.cbVExEvent.setObjectName("cbVExEvent")
        self.cbVBet = QtWidgets.QCheckBox(self.groupBox_8)
        self.cbVBet.setGeometry(QtCore.QRect(260, 40, 361, 20))
        self.cbVBet.setChecked(True)
        self.cbVBet.setObjectName("cbVBet")
        self.cbVScript = QtWidgets.QCheckBox(self.groupBox_8)
        self.cbVScript.setGeometry(QtCore.QRect(20, 80, 261, 20))
        self.cbVScript.setChecked(True)
        self.cbVScript.setObjectName("cbVScript")
        self.cbVOutput = QtWidgets.QCheckBox(self.groupBox_8)
        self.cbVOutput.setGeometry(QtCore.QRect(260, 80, 361, 20))
        self.cbVOutput.setChecked(True)
        self.cbVOutput.setObjectName("cbVOutput")
        self.txtVOutput = QtWidgets.QTextEdit(self.groupBox_8)
        self.txtVOutput.setGeometry(QtCore.QRect(20, 140, 591, 131))
        self.txtVOutput.setObjectName("txtVOutput")
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(20, 116, 591, 20))
        self.label_17.setObjectName("label_17")
        self.btnDelete = QtWidgets.QPushButton(self.tab_12)
        self.btnDelete.setGeometry(QtCore.QRect(22, 466, 301, 32))
        self.btnDelete.setObjectName("btnDelete")
        self.btnVerify = QtWidgets.QPushButton(self.tab_12)
        self.btnVerify.setGeometry(QtCore.QRect(350, 466, 301, 32))
        self.btnVerify.setObjectName("btnVerify")
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.btnLoadHistory = QtWidgets.QPushButton(self.tab_5)
        self.btnLoadHistory.setGeometry(QtCore.QRect(10, 470, 131, 29))
        self.btnLoadHistory.setObjectName("btnLoadHistory")
        self.lwHistory = QtWidgets.QListWidget(self.tab_5)
        self.lwHistory.setGeometry(QtCore.QRect(13, 10, 641, 441))
        self.lwHistory.setObjectName("lwHistory")
        self.btnRemoveHistory = QtWidgets.QPushButton(self.tab_5)
        self.btnRemoveHistory.setGeometry(QtCore.QRect(160, 470, 131, 29))
        self.btnRemoveHistory.setObjectName("btnRemoveHistory")
        self.btnClearAllHistory = QtWidgets.QPushButton(self.tab_5)
        self.btnClearAllHistory.setGeometry(QtCore.QRect(550, 470, 101, 29))
        self.btnClearAllHistory.setObjectName("btnClearAllHistory")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(21, 80, 121, 16))
        self.label_19.setObjectName("label_19")
        self.txtFSLDIR = QtWidgets.QLineEdit(self.tab_6)
        self.txtFSLDIR.setGeometry(QtCore.QRect(140, 80, 510, 21))
        self.txtFSLDIR.setToolTip("")
        self.txtFSLDIR.setToolTipDuration(-1)
        self.txtFSLDIR.setStatusTip("")
        self.txtFSLDIR.setObjectName("txtFSLDIR")
        self.txtFeat = QtWidgets.QLineEdit(self.tab_6)
        self.txtFeat.setGeometry(QtCore.QRect(140, 130, 510, 21))
        self.txtFeat.setToolTip("")
        self.txtFeat.setToolTipDuration(-1)
        self.txtFeat.setStatusTip("")
        self.txtFeat.setObjectName("txtFeat")
        self.label_24 = QtWidgets.QLabel(self.tab_6)
        self.label_24.setGeometry(QtCore.QRect(20, 130, 121, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(21, 180, 121, 16))
        self.label_25.setObjectName("label_25")
        self.txtFeat_gui = QtWidgets.QLineEdit(self.tab_6)
        self.txtFeat_gui.setGeometry(QtCore.QRect(140, 180, 510, 21))
        self.txtFeat_gui.setToolTip("")
        self.txtFeat_gui.setToolTipDuration(-1)
        self.txtFeat_gui.setStatusTip("")
        self.txtFeat_gui.setObjectName("txtFeat_gui")
        self.txtbetcmd = QtWidgets.QLineEdit(self.tab_6)
        self.txtbetcmd.setGeometry(QtCore.QRect(140, 230, 510, 21))
        self.txtbetcmd.setToolTip("")
        self.txtbetcmd.setToolTipDuration(-1)
        self.txtbetcmd.setStatusTip("")
        self.txtbetcmd.setObjectName("txtbetcmd")
        self.label_40 = QtWidgets.QLabel(self.tab_6)
        self.label_40.setGeometry(QtCore.QRect(21, 230, 121, 16))
        self.label_40.setObjectName("label_40")
        self.txtMNI = QtWidgets.QComboBox(self.tab_6)
        self.txtMNI.setGeometry(QtCore.QRect(140, 25, 510, 26))
        self.txtMNI.setObjectName("txtMNI")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.btnEstimate = QtWidgets.QPushButton(self.tab_7)
        self.btnEstimate.setGeometry(QtCore.QRect(20, 290, 630, 32))
        self.btnEstimate.setObjectName("btnEstimate")
        self.btnReportViewer = QtWidgets.QPushButton(self.tab_7)
        self.btnReportViewer.setGeometry(QtCore.QRect(20, 350, 630, 32))
        self.btnReportViewer.setObjectName("btnReportViewer")
        self.label_43 = QtWidgets.QLabel(self.tab_7)
        self.label_43.setGeometry(QtCore.QRect(20, 30, 471, 20))
        self.label_43.setObjectName("label_43")
        self.cbTools = QtWidgets.QComboBox(self.tab_7)
        self.cbTools.setGeometry(QtCore.QRect(20, 50, 630, 26))
        self.cbTools.setObjectName("cbTools")
        self.btnTools = QtWidgets.QPushButton(self.tab_7)
        self.btnTools.setGeometry(QtCore.QRect(20, 110, 630, 32))
        self.btnTools.setObjectName("btnTools")
        self.btnScriptEditor = QtWidgets.QPushButton(self.tab_7)
        self.btnScriptEditor.setGeometry(QtCore.QRect(20, 170, 630, 32))
        self.btnScriptEditor.setObjectName("btnScriptEditor")
        self.btnFilesRename = QtWidgets.QPushButton(self.tab_7)
        self.btnFilesRename.setGeometry(QtCore.QRect(20, 230, 630, 32))
        self.btnFilesRename.setObjectName("btnFilesRename")
        self.tabWidget.addTab(self.tab_7, "")
        self.btnTest = QtWidgets.QPushButton(frmPreprocess)
        self.btnTest.setGeometry(QtCore.QRect(280, 600, 113, 32))
        self.btnTest.setObjectName("btnTest")
        self.btnClose = QtWidgets.QPushButton(frmPreprocess)
        self.btnClose.setGeometry(QtCore.QRect(580, 600, 113, 32))
        self.btnClose.setObjectName("btnClose")
        self.btnSave = QtWidgets.QPushButton(frmPreprocess)
        self.btnSave.setGeometry(QtCore.QRect(150, 600, 113, 32))
        self.btnSave.setObjectName("btnSave")
        self.btnLoad = QtWidgets.QPushButton(frmPreprocess)
        self.btnLoad.setGeometry(QtCore.QRect(20, 600, 113, 32))
        self.btnLoad.setObjectName("btnLoad")
        self.label_6 = QtWidgets.QLabel(frmPreprocess)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 68, 21))
        self.label_6.setObjectName("label_6")
        self.txtSetting = QtWidgets.QLineEdit(frmPreprocess)
        self.txtSetting.setGeometry(QtCore.QRect(80, 7, 601, 29))
        self.txtSetting.setMinimumSize(QtCore.QSize(601, 0))
        self.txtSetting.setReadOnly(True)
        self.txtSetting.setObjectName("txtSetting")

        self.retranslateUi(frmPreprocess)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmPreprocess)
        frmPreprocess.setTabOrder(self.tabWidget, self.txtSubLen)
        frmPreprocess.setTabOrder(self.txtSubLen, self.txtSubPer)
        frmPreprocess.setTabOrder(self.txtSubPer, self.txtRunRange)
        frmPreprocess.setTabOrder(self.txtRunRange, self.txtRunLen)
        frmPreprocess.setTabOrder(self.txtRunLen, self.txtRunPer)
        frmPreprocess.setTabOrder(self.txtRunPer, self.txtDIR)
        frmPreprocess.setTabOrder(self.txtDIR, self.txtTask)
        frmPreprocess.setTabOrder(self.txtTask, self.btnDIR)
        frmPreprocess.setTabOrder(self.btnDIR, self.btnReadTask)
        frmPreprocess.setTabOrder(self.btnReadTask, self.tabWidget_2)
        frmPreprocess.setTabOrder(self.tabWidget_2, self.txtBOLD)
        frmPreprocess.setTabOrder(self.txtBOLD, self.txtAnat)
        frmPreprocess.setTabOrder(self.txtAnat, self.txtBET)
        frmPreprocess.setTabOrder(self.txtBET, self.txtBETPDF)
        frmPreprocess.setTabOrder(self.txtBETPDF, self.txtOnset)
        frmPreprocess.setTabOrder(self.txtOnset, self.txtEventDIR)
        frmPreprocess.setTabOrder(self.txtEventDIR, self.txtCondPre)
        frmPreprocess.setTabOrder(self.txtCondPre, self.txtTotalVol)
        frmPreprocess.setTabOrder(self.txtTotalVol, self.txtDeleteVol)
        frmPreprocess.setTabOrder(self.txtDeleteVol, self.cbSliceTime)
        frmPreprocess.setTabOrder(self.cbSliceTime, self.cbMotionCorrection)
        frmPreprocess.setTabOrder(self.cbMotionCorrection, self.cbRegAnat)
        frmPreprocess.setTabOrder(self.cbRegAnat, self.btnEvent)
        frmPreprocess.setTabOrder(self.btnEvent, self.btnExtractor)
        frmPreprocess.setTabOrder(self.btnExtractor, self.btnPreprocessScripts)
        frmPreprocess.setTabOrder(self.btnPreprocessScripts, self.cbJustRun)
        frmPreprocess.setTabOrder(self.cbJustRun, self.cbRemoveOlds)
        frmPreprocess.setTabOrder(self.cbRemoveOlds, self.btnPreprocess)
        frmPreprocess.setTabOrder(self.btnPreprocess, self.lwHistory)
        frmPreprocess.setTabOrder(self.lwHistory, self.btnLoadHistory)
        frmPreprocess.setTabOrder(self.btnLoadHistory, self.btnRemoveHistory)
        frmPreprocess.setTabOrder(self.btnRemoveHistory, self.btnClearAllHistory)
        frmPreprocess.setTabOrder(self.btnClearAllHistory, self.txtFSLDIR)
        frmPreprocess.setTabOrder(self.txtFSLDIR, self.txtFeat)
        frmPreprocess.setTabOrder(self.txtFeat, self.txtFeat_gui)
        frmPreprocess.setTabOrder(self.txtFeat_gui, self.btnEstimate)
        frmPreprocess.setTabOrder(self.btnEstimate, self.btnReportViewer)
        frmPreprocess.setTabOrder(self.btnReportViewer, self.btnEventTest)
        frmPreprocess.setTabOrder(self.btnEventTest, self.btnLoad)
        frmPreprocess.setTabOrder(self.btnLoad, self.btnSave)
        frmPreprocess.setTabOrder(self.btnSave, self.btnTest)
        frmPreprocess.setTabOrder(self.btnTest, self.btnClose)
        frmPreprocess.setTabOrder(self.btnClose, self.txtSetting)
        frmPreprocess.setTabOrder(self.txtSetting, self.txtEvents)
        frmPreprocess.setTabOrder(self.txtEvents, self.txtAnalysis)
        frmPreprocess.setTabOrder(self.txtAnalysis, self.txtScript)
        frmPreprocess.setTabOrder(self.txtScript, self.txtConPer)
        frmPreprocess.setTabOrder(self.txtConPer, self.txtConLen)
        frmPreprocess.setTabOrder(self.txtConLen, self.txtDENL)
        frmPreprocess.setTabOrder(self.txtDENL, self.txtDETS)
        frmPreprocess.setTabOrder(self.txtDETS, self.txtDEZT)
        frmPreprocess.setTabOrder(self.txtDEZT, self.txtCTZT)
        frmPreprocess.setTabOrder(self.txtCTZT, self.txtCTPT)
        frmPreprocess.setTabOrder(self.txtCTPT, self.txtbetcmd)
        frmPreprocess.setTabOrder(self.txtbetcmd, self.txtMNI)

    def retranslateUi(self, frmPreprocess):
        _translate = QtCore.QCoreApplication.translate
        frmPreprocess.setWindowTitle(_translate("frmPreprocess", "easy fMRI: Preprosessing - "))
        self.groupBox.setTitle(_translate("frmPreprocess", "<Subjects>"))
        self.label_2.setText(_translate("frmPreprocess", "Range:"))
        self.label_3.setText(_translate("frmPreprocess", "Length:"))
        self.label_4.setText(_translate("frmPreprocess", "Perfix:"))
        self.txtSubPer.setToolTip(_translate("frmPreprocess", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubPer: content of subject counter, e.g. SubPer = 0 -&gt; sub-001 OR SubPer = A -&gt; sub-AA1</span></p></body></html>"))
        self.txtSubPer.setText(_translate("frmPreprocess", "0"))
        self.txtSubLen.setToolTip(_translate("frmPreprocess", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen: the length of subject counter, e.g. SubLen=3 -&gt; output sub-001, sub-002</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">SubLen &gt; 1</span></p></body></html>"))
        self.txtSubRange.setToolTip(_translate("frmPreprocess", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">SubRange: a unique range of integers, i.e. Range=[1, 4-8, 10, 12-14]</span></p></body></html>"))
        self.txtSubRange.setText(_translate("frmPreprocess", "[1-1]"))
        self.groupBox_4.setTitle(_translate("frmPreprocess", "<General>"))
        self.label_5.setText(_translate("frmPreprocess", "Task Name:"))
        self.btnDIR.setText(_translate("frmPreprocess", "..."))
        self.label.setText(_translate("frmPreprocess", "Main Directory:"))
        self.label.setProperty("setToolTip", _translate("frmPreprocess", "Please enter the main directory of the fMRI dataset. Format of directory must be based on BIDS structure."))
        self.txtDIR.setToolTip(_translate("frmPreprocess", "<html><head/><body><p><span style=\" font-size:18pt;\">mainDIR: main folder that is included all dataset files, i.e. support BIDS format: </span><a href=\"https://www.nature.com/articles/sdata201644\"><span style=\" font-size:18pt; text-decoration: underline; color:#0000ff;\">https://www.nature.com/articles/sdata201644</span></a></p></body></html>"))
        self.btnReadTask.setText(_translate("frmPreprocess", "Read"))
        self.groupBox_3.setTitle(_translate("frmPreprocess", "<Runs>"))
        self.label_8.setText(_translate("frmPreprocess", "Ranges:"))
        self.label_9.setText(_translate("frmPreprocess", "Length:"))
        self.label_10.setText(_translate("frmPreprocess", "Perfix:"))
        self.txtRunPer.setToolTip(_translate("frmPreprocess", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunPer: content of subject counter, e.g. RunPer = 0 -&gt; run-001 OR RunPer = A -&gt; run-AA1</span></p></body></html>"))
        self.txtRunPer.setText(_translate("frmPreprocess", "0"))
        self.txtRunLen.setToolTip(_translate("frmPreprocess", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunLen: the length of run counter, e.g. RunLen=3 -&gt; output run-001, rub-002</span></p><p><span style=\" font-size:18pt; color:#0000ff;\">RunLen &gt; 1</span></p></body></html>"))
        self.txtRunRange.setToolTip(_translate("frmPreprocess", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">RunRange: sequence of ranges, i.e. If all 12 subjects have runs from 2 to 5 then Range=[12*2-5]; If 3 subjects have runs from 1 to 4 and 2 subjects have runs from 5 to 7 then Range=[3*1-4, 2*5-7]</span></p></body></html>"))
        self.txtRunRange.setText(_translate("frmPreprocess", "[1*1-1]"))
        self.txtBOLD.setText(_translate("frmPreprocess", "$MAINDIR$/sub-$SUB$/func/sub-$SUB$_task-$TASK$_run-$RUN$_bold.nii.gz"))
        self.label_12.setText(_translate("frmPreprocess", "BOLD Images:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("frmPreprocess", "fMRI"))
        self.label_26.setText(_translate("frmPreprocess", "Anatomical Extracted Brain File:"))
        self.txtBET.setText(_translate("frmPreprocess", "$MAINDIR$/sub-$SUB$/anat/sub-$SUB$_T1w_BET.nii.gz"))
        self.label_29.setText(_translate("frmPreprocess", "$SUB$, $TASK$, $RUN$, $COUNT$ will be replaced by the preprocessing parameters.\n"
"It\'s case sensitive."))
        self.label_30.setText(_translate("frmPreprocess", "Anatomical Extracted Brain Report:"))
        self.txtBETPDF.setText(_translate("frmPreprocess", "$MAINDIR$/sub-$SUB$/anat/sub-$SUB$_T1w_BET.pdf"))
        self.label_22.setText(_translate("frmPreprocess", "Anatomical Images:"))
        self.txtAnat.setText(_translate("frmPreprocess", "$MAINDIR$/sub-$SUB$/anat/sub-$SUB$_T1w.nii.gz"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("frmPreprocess", "MRI"))
        self.label_31.setText(_translate("frmPreprocess", "$SUB$, $TASK$, $RUN$, $COUNT$ will be replaced by the preprocessing parameters.\n"
"It\'s case sensitive."))
        self.txtCondPre.setText(_translate("frmPreprocess", "cond"))
        self.txtEventDIR.setText(_translate("frmPreprocess", "$MAINDIR$/sub-$SUB$/func/sub-$SUB$_task-$TASK$_run-$RUN$_events/"))
        self.label_28.setText(_translate("frmPreprocess", "Condition Prefix:"))
        self.label_27.setText(_translate("frmPreprocess", "Generated Event Folders:"))
        self.label_11.setText(_translate("frmPreprocess", "Event Files:"))
        self.txtOnset.setText(_translate("frmPreprocess", "$MAINDIR$/sub-$SUB$/func/sub-$SUB$_task-$TASK$_run-$RUN$_events.tsv"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Report), _translate("frmPreprocess", "Event"))
        self.label_32.setText(_translate("frmPreprocess", "$SUB$, $TASK$, $RUN$, $COUNT$ will be replaced by the preprocessing parameters.\n"
"It\'s case sensitive."))
        self.txtAnalysis.setText(_translate("frmPreprocess", "$MAINDIR$/sub-$SUB$/func/sub-$SUB$_task-$TASK$_run-$RUN$_analyze"))
        self.label_33.setText(_translate("frmPreprocess", "Analysis Folders:"))
        self.txtScript.setText(_translate("frmPreprocess", "$MAINDIR$/sub-$SUB$/func/sub-$SUB$_task-$TASK$_run-$RUN$_script.fsf"))
        self.label_34.setText(_translate("frmPreprocess", "Analysis Script:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("frmPreprocess", "Analysis"))
        self.label_41.setText(_translate("frmPreprocess", "Perfix:"))
        self.label_42.setText(_translate("frmPreprocess", "Length:"))
        self.txtConPer.setText(_translate("frmPreprocess", "0"))
        self.txtConRange.setToolTip(_translate("frmPreprocess", "<html><head/><body><p><span style=\" font-size:18pt; color:#0000ff;\">CounterRange: sequence of ranges, i.e. If all 12 subjects have runs from 2 to 5 then Range=[12*2-5]; If 3 subjects have runs from 1 to 4 and 2 subjects have runs from 5 to 7 then Range=[3*1-4, 2*5-7]</span></p></body></html>"))
        self.txtConRange.setText(_translate("frmPreprocess", "[1*1-1]"))
        self.label_7.setText(_translate("frmPreprocess", "Ranges:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("frmPreprocess", "Counter"))
        self.label_23.setText(_translate("frmPreprocess", "$MAINDIR$, $SUB$, $TASK$, $RUN$, $COUNT$ will be replaced by\n"
"the preprocessing parameters. It\'s case sensitive."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmPreprocess", "Directory"))
        self.label_13.setText(_translate("frmPreprocess", "TR (sec):"))
        self.label_16.setText(_translate("frmPreprocess", "Spatial Smoothing FWHM (mm):"))
        self.label_15.setText(_translate("frmPreprocess", "Total Volumes (Auto=0): "))
        self.label_20.setText(_translate("frmPreprocess", "High pass filter cutoff (sec):"))
        self.label_21.setText(_translate("frmPreprocess", "Slice timing correction:"))
        self.txtVoxel.setText(_translate("frmPreprocess", "Voxel Size: None"))
        self.label_14.setText(_translate("frmPreprocess", "Delete Volumes: "))
        self.cbRegAnat.setText(_translate("frmPreprocess", "Register to Anatomical Image"))
        self.cbMotionCorrection.setText(_translate("frmPreprocess", "Motion Correction"))
        self.groupBox_2.setTitle(_translate("frmPreprocess", "<Design Efficiency>"))
        self.label_35.setText(_translate("frmPreprocess", "Noise Level %"))
        self.label_36.setText(_translate("frmPreprocess", "Temporal Smoothness:"))
        self.label_37.setText(_translate("frmPreprocess", "Z threshold:"))
        self.txtDENL.setText(_translate("frmPreprocess", "0.66"))
        self.txtDETS.setText(_translate("frmPreprocess", "0.34"))
        self.txtDEZT.setText(_translate("frmPreprocess", "5.3"))
        self.groupBox_6.setTitle(_translate("frmPreprocess", "<Clustering Thresholding>"))
        self.label_38.setText(_translate("frmPreprocess", "Z threshold:"))
        self.label_39.setText(_translate("frmPreprocess", "Cluster P threshold:"))
        self.txtCTZT.setText(_translate("frmPreprocess", "2.3"))
        self.txtCTPT.setText(_translate("frmPreprocess", "0.05"))
        self.txtHighPass.setText(_translate("frmPreprocess", "100"))
        self.txtFWHM.setText(_translate("frmPreprocess", "5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmPreprocess", "Basic"))
        self.btnEventTest.setText(_translate("frmPreprocess", "Extract Events"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmPreprocess", "Event"))
        self.btnEvent.setText(_translate("frmPreprocess", "Generate Event Files"))
        self.btnExtractor.setText(_translate("frmPreprocess", "Brain Extractor"))
        self.btnPreprocessScripts.setText(_translate("frmPreprocess", "Generate Preprocessing Scripts"))
        self.groupBox_5.setTitle(_translate("frmPreprocess", "<Preprocessing>"))
        self.cbJustRun.setText(_translate("frmPreprocess", "Just Run One for test"))
        self.cbRemoveOlds.setText(_translate("frmPreprocess", "Remove Old Results"))
        self.btnPreprocess.setText(_translate("frmPreprocess", "Preprocessing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmPreprocess", "Run"))
        self.groupBox_7.setTitle(_translate("frmPreprocess", "<Input>"))
        self.cbVImage.setText(_translate("frmPreprocess", "fMRI images"))
        self.cbVEvent.setText(_translate("frmPreprocess", "Raw event files (tsv)"))
        self.cbVMRI.setText(_translate("frmPreprocess", "MRI (anatomical) images"))
        self.groupBox_8.setTitle(_translate("frmPreprocess", "<Output>"))
        self.cbVExEvent.setText(_translate("frmPreprocess", "Extracted events"))
        self.cbVBet.setText(_translate("frmPreprocess", "Extracted Brain images"))
        self.cbVScript.setText(_translate("frmPreprocess", "Extracted scripts"))
        self.cbVOutput.setText(_translate("frmPreprocess", "Preprocessed outputs"))
        self.txtVOutput.setHtml(_translate("frmPreprocess", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">filtered_func_data.nii.gz</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">mask.nii.gz</p></body></html>"))
        self.label_17.setText(_translate("frmPreprocess", "Verify following files in output folders (each file per line)"))
        self.btnDelete.setText(_translate("frmPreprocess", "Delete Ouputs"))
        self.btnVerify.setText(_translate("frmPreprocess", "Verify"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("frmPreprocess", "Verify"))
        self.btnLoadHistory.setText(_translate("frmPreprocess", "Load Selected"))
        self.btnRemoveHistory.setText(_translate("frmPreprocess", "Remove Selected"))
        self.btnClearAllHistory.setText(_translate("frmPreprocess", "Clear All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmPreprocess", "History"))
        self.label_18.setText(_translate("frmPreprocess", "MNI Space:"))
        self.label_19.setText(_translate("frmPreprocess", "$FSLDIR:"))
        self.txtFeat.setText(_translate("frmPreprocess", "/bin/feat"))
        self.label_24.setText(_translate("frmPreprocess", "feat cmd:"))
        self.label_25.setText(_translate("frmPreprocess", "Feat_gui cmd:"))
        self.txtFeat_gui.setText(_translate("frmPreprocess", "/bin/Feat_gui"))
        self.txtbetcmd.setText(_translate("frmPreprocess", "/bin/bet"))
        self.label_40.setText(_translate("frmPreprocess", "bet cmd:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("frmPreprocess", "System"))
        self.btnEstimate.setText(_translate("frmPreprocess", "View Parameters (Feat_gui)"))
        self.btnReportViewer.setText(_translate("frmPreprocess", "View Generated Report"))
        self.label_43.setText(_translate("frmPreprocess", "Select a tool:"))
        self.btnTools.setText(_translate("frmPreprocess", "Run"))
        self.btnScriptEditor.setText(_translate("frmPreprocess", "Group Script Editor"))
        self.btnFilesRename.setText(_translate("frmPreprocess", "Group Rename Files"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("frmPreprocess", "Tools"))
        self.btnTest.setText(_translate("frmPreprocess", "Test"))
        self.btnClose.setText(_translate("frmPreprocess", "Close"))
        self.btnSave.setText(_translate("frmPreprocess", "Save"))
        self.btnLoad.setText(_translate("frmPreprocess", "Load"))
        self.label_6.setText(_translate("frmPreprocess", "Setting:"))
        self.txtSetting.setToolTip(_translate("frmPreprocess", "<html><head/><body><p>This is current setting file address</p></body></html>"))

