# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmResultReportGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmResultReport(object):
    def setupUi(self, frmResultReport):
        frmResultReport.setObjectName("frmResultReport")
        frmResultReport.resize(794, 753)
        self.btnExit = QtWidgets.QPushButton(frmResultReport)
        self.btnExit.setGeometry(QtCore.QRect(10, 710, 130, 32))
        self.btnExit.setObjectName("btnExit")
        self.txtVars = QtWidgets.QLineEdit(frmResultReport)
        self.txtVars.setGeometry(QtCore.QRect(190, 15, 591, 21))
        self.txtVars.setObjectName("txtVars")
        self.label_2 = QtWidgets.QLabel(frmResultReport)
        self.label_2.setGeometry(QtCore.QRect(14, 15, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(frmResultReport)
        self.label.setGeometry(QtCore.QRect(14, 50, 38, 16))
        self.label.setObjectName("label")
        self.btnAdd = QtWidgets.QPushButton(frmResultReport)
        self.btnAdd.setGeometry(QtCore.QRect(730, 60, 51, 32))
        self.btnAdd.setObjectName("btnAdd")
        self.btnRemove = QtWidgets.QPushButton(frmResultReport)
        self.btnRemove.setGeometry(QtCore.QRect(730, 110, 51, 32))
        self.btnRemove.setObjectName("btnRemove")
        self.lvFile = QtWidgets.QListWidget(frmResultReport)
        self.lvFile.setGeometry(QtCore.QRect(60, 50, 661, 171))
        self.lvFile.setObjectName("lvFile")
        self.txtReport = QtWidgets.QTextBrowser(frmResultReport)
        self.txtReport.setGeometry(QtCore.QRect(10, 270, 771, 431))
        self.txtReport.setObjectName("txtReport")
        self.btnReport = QtWidgets.QPushButton(frmResultReport)
        self.btnReport.setGeometry(QtCore.QRect(650, 710, 130, 32))
        self.btnReport.setObjectName("btnReport")
        self.btnClear = QtWidgets.QPushButton(frmResultReport)
        self.btnClear.setGeometry(QtCore.QRect(510, 710, 130, 32))
        self.btnClear.setObjectName("btnClear")
        self.label_3 = QtWidgets.QLabel(frmResultReport)
        self.label_3.setGeometry(QtCore.QRect(20, 240, 60, 16))
        self.label_3.setObjectName("label_3")
        self.rbName = QtWidgets.QRadioButton(frmResultReport)
        self.rbName.setGeometry(QtCore.QRect(70, 238, 100, 20))
        self.rbName.setChecked(True)
        self.rbName.setObjectName("rbName")
        self.rbIndex = QtWidgets.QRadioButton(frmResultReport)
        self.rbIndex.setGeometry(QtCore.QRect(280, 238, 100, 20))
        self.rbIndex.setObjectName("rbIndex")
        self.rbNone = QtWidgets.QRadioButton(frmResultReport)
        self.rbNone.setGeometry(QtCore.QRect(390, 238, 100, 20))
        self.rbNone.setObjectName("rbNone")
        self.rbAddress = QtWidgets.QRadioButton(frmResultReport)
        self.rbAddress.setGeometry(QtCore.QRect(170, 238, 100, 20))
        self.rbAddress.setObjectName("rbAddress")
        self.btnSave = QtWidgets.QPushButton(frmResultReport)
        self.btnSave.setGeometry(QtCore.QRect(360, 710, 130, 32))
        self.btnSave.setObjectName("btnSave")
        self.label_4 = QtWidgets.QLabel(frmResultReport)
        self.label_4.setGeometry(QtCore.QRect(480, 240, 60, 16))
        self.label_4.setObjectName("label_4")
        self.txtChar = QtWidgets.QSpinBox(frmResultReport)
        self.txtChar.setGeometry(QtCore.QRect(550, 238, 121, 24))
        self.txtChar.setMinimum(1)
        self.txtChar.setMaximum(100000)
        self.txtChar.setProperty("value", 40)
        self.txtChar.setObjectName("txtChar")
        self.cbClear = QtWidgets.QCheckBox(frmResultReport)
        self.cbClear.setGeometry(QtCore.QRect(690, 240, 87, 20))
        self.cbClear.setChecked(True)
        self.cbClear.setObjectName("cbClear")

        self.retranslateUi(frmResultReport)
        QtCore.QMetaObject.connectSlotsByName(frmResultReport)

    def retranslateUi(self, frmResultReport):
        _translate = QtCore.QCoreApplication.translate
        frmResultReport.setWindowTitle(_translate("frmResultReport", "Result Report"))
        self.btnExit.setText(_translate("frmResultReport", "Close"))
        self.label_2.setText(_translate("frmResultReport", "Variables (Var1, Var2, ...)"))
        self.label.setText(_translate("frmResultReport", "File"))
        self.btnAdd.setText(_translate("frmResultReport", "+"))
        self.btnRemove.setText(_translate("frmResultReport", "-"))
        self.btnReport.setText(_translate("frmResultReport", "Report"))
        self.btnClear.setText(_translate("frmResultReport", "Clear"))
        self.label_3.setText(_translate("frmResultReport", "File"))
        self.rbName.setText(_translate("frmResultReport", "Name"))
        self.rbIndex.setText(_translate("frmResultReport", "Index"))
        self.rbNone.setText(_translate("frmResultReport", "None"))
        self.rbAddress.setText(_translate("frmResultReport", "Address"))
        self.btnSave.setText(_translate("frmResultReport", "Save"))
        self.label_4.setText(_translate("frmResultReport", "Length"))
        self.cbClear.setText(_translate("frmResultReport", "Clear"))

