# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmRemoveRestScanCrossGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmRemoveRestScanCross(object):
    def setupUi(self, frmRemoveRestScanCross):
        frmRemoveRestScanCross.setObjectName("frmRemoveRestScanCross")
        frmRemoveRestScanCross.resize(742, 662)
        self.cbNScan = QtWidgets.QCheckBox(frmRemoveRestScanCross)
        self.cbNScan.setGeometry(QtCore.QRect(20, 530, 91, 20))
        self.cbNScan.setChecked(False)
        self.cbNScan.setObjectName("cbNScan")
        self.cbCond = QtWidgets.QCheckBox(frmRemoveRestScanCross)
        self.cbCond.setGeometry(QtCore.QRect(20, 490, 101, 20))
        self.cbCond.setChecked(True)
        self.cbCond.setObjectName("cbCond")
        self.cbCounter = QtWidgets.QCheckBox(frmRemoveRestScanCross)
        self.cbCounter.setGeometry(QtCore.QRect(20, 450, 81, 20))
        self.cbCounter.setChecked(False)
        self.cbCounter.setObjectName("cbCounter")
        self.cbmLabel = QtWidgets.QCheckBox(frmRemoveRestScanCross)
        self.cbmLabel.setGeometry(QtCore.QRect(20, 210, 161, 20))
        self.cbmLabel.setObjectName("cbmLabel")
        self.cbCol = QtWidgets.QCheckBox(frmRemoveRestScanCross)
        self.cbCol.setGeometry(QtCore.QRect(20, 250, 111, 20))
        self.cbCol.setChecked(True)
        self.cbCol.setObjectName("cbCol")
        self.cbDM = QtWidgets.QCheckBox(frmRemoveRestScanCross)
        self.cbDM.setGeometry(QtCore.QRect(20, 290, 121, 20))
        self.cbDM.setChecked(False)
        self.cbDM.setObjectName("cbDM")
        self.cbTask = QtWidgets.QCheckBox(frmRemoveRestScanCross)
        self.cbTask.setGeometry(QtCore.QRect(20, 370, 81, 20))
        self.cbTask.setChecked(True)
        self.cbTask.setObjectName("cbTask")
        self.cbSubject = QtWidgets.QCheckBox(frmRemoveRestScanCross)
        self.cbSubject.setGeometry(QtCore.QRect(20, 330, 81, 20))
        self.cbSubject.setChecked(True)
        self.cbSubject.setObjectName("cbSubject")
        self.cbRun = QtWidgets.QCheckBox(frmRemoveRestScanCross)
        self.cbRun.setGeometry(QtCore.QRect(20, 410, 81, 20))
        self.cbRun.setChecked(True)
        self.cbRun.setObjectName("cbRun")
        self.label_33 = QtWidgets.QLabel(frmRemoveRestScanCross)
        self.label_33.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_33.setObjectName("label_33")
        self.btnInFile = QtWidgets.QPushButton(frmRemoveRestScanCross)
        self.btnInFile.setGeometry(QtCore.QRect(670, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.txtInFile = QtWidgets.QLineEdit(frmRemoveRestScanCross)
        self.txtInFile.setGeometry(QtCore.QRect(140, 20, 521, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.label_34 = QtWidgets.QLabel(frmRemoveRestScanCross)
        self.label_34.setGeometry(QtCore.QRect(20, 60, 111, 16))
        self.label_34.setObjectName("label_34")
        self.txtOutFile = QtWidgets.QLineEdit(frmRemoveRestScanCross)
        self.txtOutFile.setGeometry(QtCore.QRect(140, 60, 521, 21))
        self.txtOutFile.setText("")
        self.txtOutFile.setObjectName("txtOutFile")
        self.btnOutFile = QtWidgets.QPushButton(frmRemoveRestScanCross)
        self.btnOutFile.setGeometry(QtCore.QRect(670, 60, 51, 32))
        self.btnOutFile.setObjectName("btnOutFile")
        self.btnConvert = QtWidgets.QPushButton(frmRemoveRestScanCross)
        self.btnConvert.setGeometry(QtCore.QRect(480, 560, 241, 32))
        self.btnConvert.setObjectName("btnConvert")
        self.label = QtWidgets.QLabel(frmRemoveRestScanCross)
        self.label.setGeometry(QtCore.QRect(460, 140, 91, 16))
        self.label.setObjectName("label")
        self.txtClassID = QtWidgets.QLineEdit(frmRemoveRestScanCross)
        self.txtClassID.setGeometry(QtCore.QRect(603, 140, 113, 21))
        self.txtClassID.setObjectName("txtClassID")
        self.txtData = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtData.setGeometry(QtCore.QRect(170, 130, 121, 26))
        self.txtData.setEditable(True)
        self.txtData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtData.setObjectName("txtData")
        self.txtLabel = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtLabel.setGeometry(QtCore.QRect(170, 170, 121, 26))
        self.txtLabel.setEditable(True)
        self.txtLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtLabel.setObjectName("txtLabel")
        self.txtmLabel = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtmLabel.setGeometry(QtCore.QRect(170, 210, 121, 26))
        self.txtmLabel.setEditable(True)
        self.txtmLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtmLabel.setObjectName("txtmLabel")
        self.txtCol = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtCol.setGeometry(QtCore.QRect(170, 250, 121, 26))
        self.txtCol.setEditable(True)
        self.txtCol.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCol.setObjectName("txtCol")
        self.txtDM = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtDM.setGeometry(QtCore.QRect(170, 290, 121, 26))
        self.txtDM.setEditable(True)
        self.txtDM.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtDM.setObjectName("txtDM")
        self.txtSubject = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtSubject.setGeometry(QtCore.QRect(170, 330, 121, 26))
        self.txtSubject.setEditable(True)
        self.txtSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtSubject.setObjectName("txtSubject")
        self.txtTask = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtTask.setGeometry(QtCore.QRect(170, 370, 121, 26))
        self.txtTask.setEditable(True)
        self.txtTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTask.setObjectName("txtTask")
        self.txtRun = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtRun.setGeometry(QtCore.QRect(170, 410, 121, 26))
        self.txtRun.setEditable(True)
        self.txtRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtRun.setObjectName("txtRun")
        self.txtCounter = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtCounter.setGeometry(QtCore.QRect(170, 450, 121, 26))
        self.txtCounter.setEditable(True)
        self.txtCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCounter.setObjectName("txtCounter")
        self.txtCond = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtCond.setGeometry(QtCore.QRect(170, 490, 121, 26))
        self.txtCond.setEditable(True)
        self.txtCond.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtCond.setObjectName("txtCond")
        self.txtNScan = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtNScan.setGeometry(QtCore.QRect(170, 530, 121, 26))
        self.txtNScan.setEditable(True)
        self.txtNScan.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtNScan.setObjectName("txtNScan")
        self.btnClose = QtWidgets.QPushButton(frmRemoveRestScanCross)
        self.btnClose.setGeometry(QtCore.QRect(480, 610, 241, 32))
        self.btnClose.setObjectName("btnClose")
        self.label_2 = QtWidgets.QLabel(frmRemoveRestScanCross)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(frmRemoveRestScanCross)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(frmRemoveRestScanCross)
        self.label_4.setGeometry(QtCore.QRect(460, 180, 111, 16))
        self.label_4.setObjectName("label_4")
        self.txtClassName = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtClassName.setGeometry(QtCore.QRect(600, 180, 121, 26))
        self.txtClassName.setEditable(True)
        self.txtClassName.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtClassName.setObjectName("txtClassName")
        self.btnReadClassName = QtWidgets.QPushButton(frmRemoveRestScanCross)
        self.btnReadClassName.setGeometry(QtCore.QRect(480, 240, 241, 32))
        self.btnReadClassName.setObjectName("btnReadClassName")
        self.txtTSubject = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtTSubject.setGeometry(QtCore.QRect(320, 330, 121, 26))
        self.txtTSubject.setEditable(True)
        self.txtTSubject.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTSubject.setObjectName("txtTSubject")
        self.txtTData = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtTData.setGeometry(QtCore.QRect(320, 130, 121, 26))
        self.txtTData.setEditable(True)
        self.txtTData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTData.setObjectName("txtTData")
        self.txtTDM = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtTDM.setGeometry(QtCore.QRect(320, 290, 121, 26))
        self.txtTDM.setEditable(True)
        self.txtTDM.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTDM.setObjectName("txtTDM")
        self.txtTRun = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtTRun.setGeometry(QtCore.QRect(320, 410, 121, 26))
        self.txtTRun.setEditable(True)
        self.txtTRun.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTRun.setObjectName("txtTRun")
        self.txtTmLabel = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtTmLabel.setGeometry(QtCore.QRect(320, 210, 121, 26))
        self.txtTmLabel.setEditable(True)
        self.txtTmLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTmLabel.setObjectName("txtTmLabel")
        self.txtTLabel = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtTLabel.setGeometry(QtCore.QRect(320, 170, 121, 26))
        self.txtTLabel.setEditable(True)
        self.txtTLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTLabel.setObjectName("txtTLabel")
        self.txtTTask = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtTTask.setGeometry(QtCore.QRect(320, 370, 121, 26))
        self.txtTTask.setEditable(True)
        self.txtTTask.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTTask.setObjectName("txtTTask")
        self.txtTCounter = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtTCounter.setGeometry(QtCore.QRect(320, 450, 121, 26))
        self.txtTCounter.setEditable(True)
        self.txtTCounter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTCounter.setObjectName("txtTCounter")
        self.label_5 = QtWidgets.QLabel(frmRemoveRestScanCross)
        self.label_5.setGeometry(QtCore.QRect(210, 100, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(frmRemoveRestScanCross)
        self.label_6.setGeometry(QtCore.QRect(360, 100, 111, 16))
        self.label_6.setObjectName("label_6")
        self.txtTNScan = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtTNScan.setGeometry(QtCore.QRect(320, 530, 121, 26))
        self.txtTNScan.setEditable(True)
        self.txtTNScan.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtTNScan.setObjectName("txtTNScan")
        self.txtFoldInfo = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtFoldInfo.setGeometry(QtCore.QRect(170, 610, 121, 26))
        self.txtFoldInfo.setEditable(True)
        self.txtFoldInfo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFoldInfo.setObjectName("txtFoldInfo")
        self.cbFoldInfo = QtWidgets.QCheckBox(frmRemoveRestScanCross)
        self.cbFoldInfo.setGeometry(QtCore.QRect(20, 610, 101, 20))
        self.cbFoldInfo.setChecked(True)
        self.cbFoldInfo.setObjectName("cbFoldInfo")
        self.txtFoldID = QtWidgets.QComboBox(frmRemoveRestScanCross)
        self.txtFoldID.setGeometry(QtCore.QRect(170, 570, 121, 26))
        self.txtFoldID.setEditable(True)
        self.txtFoldID.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtFoldID.setObjectName("txtFoldID")
        self.cbFoldID = QtWidgets.QCheckBox(frmRemoveRestScanCross)
        self.cbFoldID.setGeometry(QtCore.QRect(20, 570, 101, 20))
        self.cbFoldID.setChecked(True)
        self.cbFoldID.setObjectName("cbFoldID")
        self.lbFoldID = QtWidgets.QLabel(frmRemoveRestScanCross)
        self.lbFoldID.setGeometry(QtCore.QRect(320, 570, 121, 16))
        self.lbFoldID.setObjectName("lbFoldID")

        self.retranslateUi(frmRemoveRestScanCross)
        QtCore.QMetaObject.connectSlotsByName(frmRemoveRestScanCross)
        frmRemoveRestScanCross.setTabOrder(self.txtInFile, self.btnInFile)
        frmRemoveRestScanCross.setTabOrder(self.btnInFile, self.txtOutFile)
        frmRemoveRestScanCross.setTabOrder(self.txtOutFile, self.btnOutFile)
        frmRemoveRestScanCross.setTabOrder(self.btnOutFile, self.txtData)
        frmRemoveRestScanCross.setTabOrder(self.txtData, self.txtLabel)
        frmRemoveRestScanCross.setTabOrder(self.txtLabel, self.cbmLabel)
        frmRemoveRestScanCross.setTabOrder(self.cbmLabel, self.txtmLabel)
        frmRemoveRestScanCross.setTabOrder(self.txtmLabel, self.cbCol)
        frmRemoveRestScanCross.setTabOrder(self.cbCol, self.txtCol)
        frmRemoveRestScanCross.setTabOrder(self.txtCol, self.cbDM)
        frmRemoveRestScanCross.setTabOrder(self.cbDM, self.txtDM)
        frmRemoveRestScanCross.setTabOrder(self.txtDM, self.cbSubject)
        frmRemoveRestScanCross.setTabOrder(self.cbSubject, self.txtSubject)
        frmRemoveRestScanCross.setTabOrder(self.txtSubject, self.cbTask)
        frmRemoveRestScanCross.setTabOrder(self.cbTask, self.txtTask)
        frmRemoveRestScanCross.setTabOrder(self.txtTask, self.cbRun)
        frmRemoveRestScanCross.setTabOrder(self.cbRun, self.txtRun)
        frmRemoveRestScanCross.setTabOrder(self.txtRun, self.cbCounter)
        frmRemoveRestScanCross.setTabOrder(self.cbCounter, self.txtCounter)
        frmRemoveRestScanCross.setTabOrder(self.txtCounter, self.cbCond)
        frmRemoveRestScanCross.setTabOrder(self.cbCond, self.txtCond)
        frmRemoveRestScanCross.setTabOrder(self.txtCond, self.cbNScan)
        frmRemoveRestScanCross.setTabOrder(self.cbNScan, self.txtNScan)
        frmRemoveRestScanCross.setTabOrder(self.txtNScan, self.txtClassID)
        frmRemoveRestScanCross.setTabOrder(self.txtClassID, self.btnConvert)
        frmRemoveRestScanCross.setTabOrder(self.btnConvert, self.btnClose)

    def retranslateUi(self, frmRemoveRestScanCross):
        _translate = QtCore.QCoreApplication.translate
        frmRemoveRestScanCross.setWindowTitle(_translate("frmRemoveRestScanCross", "Remove Rest Scan (after cross validation)"))
        self.cbNScan.setText(_translate("frmRemoveRestScanCross", "NScan"))
        self.cbCond.setText(_translate("frmRemoveRestScanCross", "Condition"))
        self.cbCounter.setText(_translate("frmRemoveRestScanCross", "Counter"))
        self.cbmLabel.setText(_translate("frmRemoveRestScanCross", "Label (matrix)"))
        self.cbCol.setText(_translate("frmRemoveRestScanCross", "Coordinate"))
        self.cbDM.setText(_translate("frmRemoveRestScanCross", "Design Matrix"))
        self.cbTask.setText(_translate("frmRemoveRestScanCross", "Task"))
        self.cbSubject.setText(_translate("frmRemoveRestScanCross", "Subject"))
        self.cbRun.setText(_translate("frmRemoveRestScanCross", "Run"))
        self.label_33.setText(_translate("frmRemoveRestScanCross", "Input Data File"))
        self.btnInFile.setText(_translate("frmRemoveRestScanCross", "..."))
        self.label_34.setText(_translate("frmRemoveRestScanCross", "Output Data File"))
        self.btnOutFile.setText(_translate("frmRemoveRestScanCross", "..."))
        self.btnConvert.setText(_translate("frmRemoveRestScanCross", "Convert"))
        self.label.setText(_translate("frmRemoveRestScanCross", "Rest Class ID"))
        self.txtClassID.setText(_translate("frmRemoveRestScanCross", "0"))
        self.btnClose.setText(_translate("frmRemoveRestScanCross", "Close"))
        self.label_2.setText(_translate("frmRemoveRestScanCross", "Data"))
        self.label_3.setText(_translate("frmRemoveRestScanCross", "Label"))
        self.label_4.setText(_translate("frmRemoveRestScanCross", "Rest Class Name"))
        self.btnReadClassName.setText(_translate("frmRemoveRestScanCross", "Reload Class Name"))
        self.label_5.setText(_translate("frmRemoveRestScanCross", "Train"))
        self.label_6.setText(_translate("frmRemoveRestScanCross", "Test"))
        self.cbFoldInfo.setText(_translate("frmRemoveRestScanCross", "FoldInfo"))
        self.cbFoldID.setText(_translate("frmRemoveRestScanCross", "FoldID"))
        self.lbFoldID.setText(_translate("frmRemoveRestScanCross", "ID=None"))

