# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmSKCModelEditorGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmSKCModelEditor(object):
    def setupUi(self, frmSKCModelEditor):
        frmSKCModelEditor.setObjectName("frmSKCModelEditor")
        frmSKCModelEditor.resize(872, 632)
        self.txtInFile = QtWidgets.QLineEdit(frmSKCModelEditor)
        self.txtInFile.setGeometry(QtCore.QRect(140, 20, 661, 21))
        self.txtInFile.setText("")
        self.txtInFile.setObjectName("txtInFile")
        self.btnInFile = QtWidgets.QPushButton(frmSKCModelEditor)
        self.btnInFile.setGeometry(QtCore.QRect(810, 20, 51, 32))
        self.btnInFile.setObjectName("btnInFile")
        self.label_33 = QtWidgets.QLabel(frmSKCModelEditor)
        self.label_33.setGeometry(QtCore.QRect(20, 20, 211, 16))
        self.label_33.setObjectName("label_33")
        self.btnClose = QtWidgets.QPushButton(frmSKCModelEditor)
        self.btnClose.setGeometry(QtCore.QRect(690, 590, 161, 29))
        self.btnClose.setObjectName("btnClose")
        self.tabWidget = QtWidgets.QTabWidget(frmSKCModelEditor)
        self.tabWidget.setGeometry(QtCore.QRect(20, 60, 831, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lwData = QtWidgets.QTreeWidget(self.tab)
        self.lwData.setGeometry(QtCore.QRect(13, 10, 801, 431))
        self.lwData.setObjectName("lwData")
        self.lwData.headerItem().setText(0, "1")
        self.btnValue = QtWidgets.QPushButton(self.tab)
        self.btnValue.setGeometry(QtCore.QRect(10, 450, 801, 32))
        self.btnValue.setObjectName("btnValue")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btnTest = QtWidgets.QPushButton(self.tab_2)
        self.btnTest.setGeometry(QtCore.QRect(10, 450, 801, 32))
        self.btnTest.setObjectName("btnTest")
        self.btnInData = QtWidgets.QPushButton(self.tab_2)
        self.btnInData.setGeometry(QtCore.QRect(760, 20, 51, 32))
        self.btnInData.setObjectName("btnInData")
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(20, 20, 211, 16))
        self.label_34.setObjectName("label_34")
        self.txtInData = QtWidgets.QLineEdit(self.tab_2)
        self.txtInData.setGeometry(QtCore.QRect(140, 20, 611, 21))
        self.txtInData.setText("")
        self.txtInData.setObjectName("txtInData")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 181, 16))
        self.label_3.setObjectName("label_3")
        self.txtITeLabel = QtWidgets.QComboBox(self.tab_2)
        self.txtITeLabel.setGeometry(QtCore.QRect(190, 100, 431, 26))
        self.txtITeLabel.setEditable(True)
        self.txtITeLabel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeLabel.setObjectName("txtITeLabel")
        self.txtITeData = QtWidgets.QComboBox(self.tab_2)
        self.txtITeData.setGeometry(QtCore.QRect(190, 60, 431, 26))
        self.txtITeData.setEditable(True)
        self.txtITeData.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.txtITeData.setObjectName("txtITeData")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 181, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(20, 230, 791, 201))
        self.groupBox.setObjectName("groupBox")
        self.cbAverage = QtWidgets.QCheckBox(self.groupBox)
        self.cbAverage.setGeometry(QtCore.QRect(20, 40, 181, 20))
        self.cbAverage.setChecked(True)
        self.cbAverage.setObjectName("cbAverage")
        self.cbNMI = QtWidgets.QCheckBox(self.groupBox)
        self.cbNMI.setGeometry(QtCore.QRect(20, 80, 391, 20))
        self.cbNMI.setChecked(True)
        self.cbNMI.setObjectName("cbNMI")
        self.cbRIA = QtWidgets.QCheckBox(self.groupBox)
        self.cbRIA.setGeometry(QtCore.QRect(20, 160, 381, 20))
        self.cbRIA.setChecked(True)
        self.cbRIA.setObjectName("cbRIA")
        self.cbAMI = QtWidgets.QCheckBox(self.groupBox)
        self.cbAMI.setGeometry(QtCore.QRect(20, 120, 401, 20))
        self.cbAMI.setChecked(True)
        self.cbAMI.setObjectName("cbAMI")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(630, 140, 181, 20))
        self.label_5.setObjectName("label_5")
        self.txtFilter = QtWidgets.QLineEdit(self.tab_2)
        self.txtFilter.setGeometry(QtCore.QRect(190, 140, 431, 21))
        self.txtFilter.setObjectName("txtFilter")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 201, 16))
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(20, 180, 201, 16))
        self.label_10.setObjectName("label_10")
        self.txtClass = QtWidgets.QTextEdit(self.tab_2)
        self.txtClass.setGeometry(QtCore.QRect(190, 180, 611, 50))
        self.txtClass.setReadOnly(True)
        self.txtClass.setObjectName("txtClass")
        self.cbScale = QtWidgets.QCheckBox(self.tab_2)
        self.cbScale.setGeometry(QtCore.QRect(633, 60, 360, 21))
        self.cbScale.setChecked(True)
        self.cbScale.setObjectName("cbScale")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(frmSKCModelEditor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmSKCModelEditor)
        frmSKCModelEditor.setTabOrder(self.txtInFile, self.btnInFile)
        frmSKCModelEditor.setTabOrder(self.btnInFile, self.btnClose)

    def retranslateUi(self, frmSKCModelEditor):
        _translate = QtCore.QCoreApplication.translate
        frmSKCModelEditor.setWindowTitle(_translate("frmSKCModelEditor", "SK Learn Model Editor"))
        self.btnInFile.setText(_translate("frmSKCModelEditor", "..."))
        self.label_33.setText(_translate("frmSKCModelEditor", "Model File "))
        self.btnClose.setText(_translate("frmSKCModelEditor", "Close"))
        self.lwData.setSortingEnabled(True)
        self.btnValue.setText(_translate("frmSKCModelEditor", "View Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmSKCModelEditor", "Parameters"))
        self.btnTest.setText(_translate("frmSKCModelEditor", "Run Test Data"))
        self.btnInData.setText(_translate("frmSKCModelEditor", "..."))
        self.label_34.setText(_translate("frmSKCModelEditor", "Input Data "))
        self.label_3.setText(_translate("frmSKCModelEditor", "Label"))
        self.label_2.setText(_translate("frmSKCModelEditor", "Data"))
        self.groupBox.setTitle(_translate("frmSKCModelEditor", "<Metrics>"))
        self.cbAverage.setText(_translate("frmSKCModelEditor", "Average"))
        self.cbNMI.setText(_translate("frmSKCModelEditor", "Normalized Mutual Information"))
        self.cbRIA.setText(_translate("frmSKCModelEditor", "Rand Index Adjusted "))
        self.cbAMI.setText(_translate("frmSKCModelEditor", "Adjusted Mutual Information"))
        self.label_5.setText(_translate("frmSKCModelEditor", "e.g. 0 or [1,2]"))
        self.txtFilter.setText(_translate("frmSKCModelEditor", "0"))
        self.label_4.setText(_translate("frmSKCModelEditor", "Remove Class IDs"))
        self.label_10.setText(_translate("frmSKCModelEditor", "Existed Classes"))
        self.cbScale.setText(_translate("frmSKCModelEditor", "Scale Data N(0,1)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmSKCModelEditor", "Data Clustering"))

