# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmTransformationMatrixGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmTansformationMatrix(object):
    def setupUi(self, frmTansformationMatrix):
        frmTansformationMatrix.setObjectName("frmTansformationMatrix")
        frmTansformationMatrix.resize(844, 511)
        self.label_5 = QtWidgets.QLabel(frmTansformationMatrix)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 111, 16))
        self.label_5.setObjectName("label_5")
        self.txtMatFile = QtWidgets.QLineEdit(frmTansformationMatrix)
        self.txtMatFile.setGeometry(QtCore.QRect(200, 120, 571, 21))
        self.txtMatFile.setText("")
        self.txtMatFile.setObjectName("txtMatFile")
        self.btnSpace = QtWidgets.QPushButton(frmTansformationMatrix)
        self.btnSpace.setGeometry(QtCore.QRect(780, 70, 51, 32))
        self.btnSpace.setObjectName("btnSpace")
        self.label = QtWidgets.QLabel(frmTansformationMatrix)
        self.label.setGeometry(QtCore.QRect(20, 20, 201, 16))
        self.label.setObjectName("label")
        self.txtSpace = QtWidgets.QComboBox(frmTansformationMatrix)
        self.txtSpace.setGeometry(QtCore.QRect(130, 70, 641, 26))
        self.txtSpace.setEditable(True)
        self.txtSpace.setObjectName("txtSpace")
        self.label_2 = QtWidgets.QLabel(frmTansformationMatrix)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 161, 16))
        self.label_2.setObjectName("label_2")
        self.btnMatFile = QtWidgets.QPushButton(frmTansformationMatrix)
        self.btnMatFile.setGeometry(QtCore.QRect(780, 120, 51, 32))
        self.btnMatFile.setObjectName("btnMatFile")
        self.txtImgFile = QtWidgets.QLineEdit(frmTansformationMatrix)
        self.txtImgFile.setGeometry(QtCore.QRect(220, 20, 551, 21))
        self.txtImgFile.setText("")
        self.txtImgFile.setObjectName("txtImgFile")
        self.btnImgFile = QtWidgets.QPushButton(frmTansformationMatrix)
        self.btnImgFile.setGeometry(QtCore.QRect(780, 20, 51, 32))
        self.btnImgFile.setObjectName("btnImgFile")
        self.tabWidget = QtWidgets.QTabWidget(frmTansformationMatrix)
        self.tabWidget.setGeometry(QtCore.QRect(20, 220, 801, 221))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 151, 16))
        self.label_3.setObjectName("label_3")
        self.txtXmin = QtWidgets.QDoubleSpinBox(self.tab)
        self.txtXmin.setGeometry(QtCore.QRect(190, 60, 100, 24))
        self.txtXmin.setMinimum(-180.0)
        self.txtXmin.setMaximum(180.0)
        self.txtXmin.setSingleStep(1.0)
        self.txtXmin.setProperty("value", -90.0)
        self.txtXmin.setObjectName("txtXmin")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(310, 60, 51, 16))
        self.label_4.setObjectName("label_4")
        self.txtXmax = QtWidgets.QDoubleSpinBox(self.tab)
        self.txtXmax.setGeometry(QtCore.QRect(360, 60, 100, 24))
        self.txtXmax.setMinimum(-180.0)
        self.txtXmax.setMaximum(180.0)
        self.txtXmax.setSingleStep(1.0)
        self.txtXmax.setProperty("value", 90.0)
        self.txtXmax.setObjectName("txtXmax")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(40, 100, 151, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(310, 100, 51, 16))
        self.label_7.setObjectName("label_7")
        self.txtYmin = QtWidgets.QDoubleSpinBox(self.tab)
        self.txtYmin.setGeometry(QtCore.QRect(190, 100, 100, 24))
        self.txtYmin.setMinimum(-180.0)
        self.txtYmin.setMaximum(180.0)
        self.txtYmin.setSingleStep(1.0)
        self.txtYmin.setProperty("value", -90.0)
        self.txtYmin.setObjectName("txtYmin")
        self.txtYmax = QtWidgets.QDoubleSpinBox(self.tab)
        self.txtYmax.setGeometry(QtCore.QRect(360, 100, 100, 24))
        self.txtYmax.setMinimum(-180.0)
        self.txtYmax.setMaximum(180.0)
        self.txtYmax.setSingleStep(1.0)
        self.txtYmax.setProperty("value", 90.0)
        self.txtYmax.setObjectName("txtYmax")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(40, 140, 151, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(310, 140, 51, 16))
        self.label_9.setObjectName("label_9")
        self.txtZmin = QtWidgets.QDoubleSpinBox(self.tab)
        self.txtZmin.setGeometry(QtCore.QRect(190, 140, 100, 24))
        self.txtZmin.setMinimum(-180.0)
        self.txtZmin.setMaximum(180.0)
        self.txtZmin.setSingleStep(1.0)
        self.txtZmin.setProperty("value", -90.0)
        self.txtZmin.setObjectName("txtZmin")
        self.txtZmax = QtWidgets.QDoubleSpinBox(self.tab)
        self.txtZmax.setGeometry(QtCore.QRect(360, 140, 100, 24))
        self.txtZmax.setMinimum(-180.0)
        self.txtZmax.setMaximum(180.0)
        self.txtZmax.setSingleStep(1.0)
        self.txtZmax.setProperty("value", 90.0)
        self.txtZmax.setObjectName("txtZmax")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(40, 20, 60, 16))
        self.label_10.setObjectName("label_10")
        self.cbSearch = QtWidgets.QComboBox(self.tab)
        self.cbSearch.setGeometry(QtCore.QRect(100, 20, 361, 26))
        self.cbSearch.setObjectName("cbSearch")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_11.setObjectName("label_11")
        self.cbCostFunction = QtWidgets.QComboBox(self.tab_3)
        self.cbCostFunction.setGeometry(QtCore.QRect(120, 20, 371, 26))
        self.cbCostFunction.setObjectName("cbCostFunction")
        self.txtBins = QtWidgets.QSpinBox(self.tab_3)
        self.txtBins.setGeometry(QtCore.QRect(190, 60, 161, 24))
        self.txtBins.setMinimum(1)
        self.txtBins.setMaximum(1000000000)
        self.txtBins.setProperty("value", 256)
        self.txtBins.setObjectName("txtBins")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(20, 60, 171, 16))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 291, 16))
        self.label_13.setObjectName("label_13")
        self.cbInter = QtWidgets.QComboBox(self.tab_2)
        self.cbInter.setGeometry(QtCore.QRect(280, 20, 201, 26))
        self.cbInter.setObjectName("cbInter")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.txtFSLDIR = QtWidgets.QLineEdit(self.tab_4)
        self.txtFSLDIR.setGeometry(QtCore.QRect(120, 20, 651, 21))
        self.txtFSLDIR.setToolTip("")
        self.txtFSLDIR.setToolTipDuration(-1)
        self.txtFSLDIR.setStatusTip("")
        self.txtFSLDIR.setObjectName("txtFSLDIR")
        self.txtFlirt = QtWidgets.QLineEdit(self.tab_4)
        self.txtFlirt.setGeometry(QtCore.QRect(120, 70, 651, 21))
        self.txtFlirt.setToolTip("")
        self.txtFlirt.setToolTipDuration(-1)
        self.txtFlirt.setStatusTip("")
        self.txtFlirt.setObjectName("txtFlirt")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(11, 120, 121, 16))
        self.label_25.setObjectName("label_25")
        self.txtFlirtGUI = QtWidgets.QLineEdit(self.tab_4)
        self.txtFlirtGUI.setGeometry(QtCore.QRect(120, 120, 651, 21))
        self.txtFlirtGUI.setToolTip("")
        self.txtFlirtGUI.setToolTipDuration(-1)
        self.txtFlirtGUI.setStatusTip("")
        self.txtFlirtGUI.setObjectName("txtFlirtGUI")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(11, 20, 121, 16))
        self.label_19.setObjectName("label_19")
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(10, 70, 121, 16))
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.btnFlirtGUI = QtWidgets.QPushButton(self.tab_5)
        self.btnFlirtGUI.setGeometry(QtCore.QRect(10, 20, 771, 32))
        self.btnFlirtGUI.setObjectName("btnFlirtGUI")
        self.tabWidget.addTab(self.tab_5, "")
        self.btnRun = QtWidgets.QPushButton(frmTansformationMatrix)
        self.btnRun.setGeometry(QtCore.QRect(710, 460, 113, 32))
        self.btnRun.setObjectName("btnRun")
        self.btnClose = QtWidgets.QPushButton(frmTansformationMatrix)
        self.btnClose.setGeometry(QtCore.QRect(20, 460, 113, 32))
        self.btnClose.setObjectName("btnClose")
        self.btnExaFile = QtWidgets.QPushButton(frmTansformationMatrix)
        self.btnExaFile.setGeometry(QtCore.QRect(780, 170, 51, 32))
        self.btnExaFile.setObjectName("btnExaFile")
        self.txtExaFile = QtWidgets.QLineEdit(frmTansformationMatrix)
        self.txtExaFile.setGeometry(QtCore.QRect(200, 170, 571, 21))
        self.txtExaFile.setText("")
        self.txtExaFile.setObjectName("txtExaFile")
        self.label_14 = QtWidgets.QLabel(frmTansformationMatrix)
        self.label_14.setGeometry(QtCore.QRect(20, 170, 181, 16))
        self.label_14.setObjectName("label_14")

        self.retranslateUi(frmTansformationMatrix)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmTansformationMatrix)
        frmTansformationMatrix.setTabOrder(self.txtImgFile, self.btnImgFile)
        frmTansformationMatrix.setTabOrder(self.btnImgFile, self.txtSpace)
        frmTansformationMatrix.setTabOrder(self.txtSpace, self.btnSpace)
        frmTansformationMatrix.setTabOrder(self.btnSpace, self.txtMatFile)
        frmTansformationMatrix.setTabOrder(self.txtMatFile, self.btnMatFile)
        frmTansformationMatrix.setTabOrder(self.btnMatFile, self.tabWidget)
        frmTansformationMatrix.setTabOrder(self.tabWidget, self.cbSearch)
        frmTansformationMatrix.setTabOrder(self.cbSearch, self.txtXmin)
        frmTansformationMatrix.setTabOrder(self.txtXmin, self.txtXmax)
        frmTansformationMatrix.setTabOrder(self.txtXmax, self.txtYmin)
        frmTansformationMatrix.setTabOrder(self.txtYmin, self.txtYmax)
        frmTansformationMatrix.setTabOrder(self.txtYmax, self.txtZmin)
        frmTansformationMatrix.setTabOrder(self.txtZmin, self.txtZmax)
        frmTansformationMatrix.setTabOrder(self.txtZmax, self.cbCostFunction)
        frmTansformationMatrix.setTabOrder(self.cbCostFunction, self.txtBins)
        frmTansformationMatrix.setTabOrder(self.txtBins, self.cbInter)
        frmTansformationMatrix.setTabOrder(self.cbInter, self.txtFSLDIR)
        frmTansformationMatrix.setTabOrder(self.txtFSLDIR, self.txtFlirt)
        frmTansformationMatrix.setTabOrder(self.txtFlirt, self.txtFlirtGUI)
        frmTansformationMatrix.setTabOrder(self.txtFlirtGUI, self.btnFlirtGUI)
        frmTansformationMatrix.setTabOrder(self.btnFlirtGUI, self.btnRun)
        frmTansformationMatrix.setTabOrder(self.btnRun, self.btnClose)

    def retranslateUi(self, frmTansformationMatrix):
        _translate = QtCore.QCoreApplication.translate
        frmTansformationMatrix.setWindowTitle(_translate("frmTansformationMatrix", "Transformation Matrix"))
        self.label_5.setText(_translate("frmTansformationMatrix", "Standard Space"))
        self.btnSpace.setText(_translate("frmTansformationMatrix", "..."))
        self.label.setText(_translate("frmTansformationMatrix", "Original Image (3D or 4D fMRI)"))
        self.label_2.setText(_translate("frmTansformationMatrix", "Tranformation Matrix"))
        self.btnMatFile.setText(_translate("frmTansformationMatrix", "..."))
        self.btnImgFile.setText(_translate("frmTansformationMatrix", "..."))
        self.label_3.setText(_translate("frmTansformationMatrix", "X-axis (degrees): min"))
        self.label_4.setText(_translate("frmTansformationMatrix", "max"))
        self.label_6.setText(_translate("frmTansformationMatrix", "Y-axis (degrees): min"))
        self.label_7.setText(_translate("frmTansformationMatrix", "max"))
        self.label_8.setText(_translate("frmTansformationMatrix", "Z-axis (degrees): min"))
        self.label_9.setText(_translate("frmTansformationMatrix", "max"))
        self.label_10.setText(_translate("frmTansformationMatrix", "Images"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmTansformationMatrix", "Search"))
        self.label_11.setText(_translate("frmTansformationMatrix", "Cost Function"))
        self.label_12.setText(_translate("frmTansformationMatrix", "Number of Histogram Bins"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("frmTansformationMatrix", "Cost Function"))
        self.label_13.setText(_translate("frmTansformationMatrix", "Final Interpolation Method (Reslice Only)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmTansformationMatrix", "Interpolation"))
        self.txtFlirt.setText(_translate("frmTansformationMatrix", "/bin/flirt"))
        self.label_25.setText(_translate("frmTansformationMatrix", "Flirt_gui cmd:"))
        self.txtFlirtGUI.setText(_translate("frmTansformationMatrix", "/bin/Flirt_gui"))
        self.label_19.setText(_translate("frmTansformationMatrix", "$FSLDIR:"))
        self.label_24.setText(_translate("frmTansformationMatrix", "flirt cmd:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("frmTansformationMatrix", "System"))
        self.btnFlirtGUI.setText(_translate("frmTansformationMatrix", "Flirt_gui"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("frmTansformationMatrix", "Tools"))
        self.btnRun.setText(_translate("frmTansformationMatrix", "Run"))
        self.btnClose.setText(_translate("frmTansformationMatrix", "Close"))
        self.btnExaFile.setText(_translate("frmTansformationMatrix", "..."))
        self.label_14.setText(_translate("frmTansformationMatrix", "Example Output (Optional)"))

