#!/bin/bash
source $HOME/.startupscript
export QT_SCALE_FACTOR=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCREEN_SCALE_FACTORS=$SCREEN_SCALE
conda activate $EV_EZFMRI
cd $EASYFMRI
python main.py &
